In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import numpy as np

from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

from transformers import AutoTokenizer
from datasets import load_dataset, DatasetDict, ClassLabel

import multiprocessing

from functools import partial

from tqdm import tqdm
from collections import Counter

In [ ]:
data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/data.csv"
max_token_length = 512
batch_size_train = 64
num_workers = 4
batch_size_val = 64
batch_size_test = 64
val_num_workers = 4
start_idx = 64100
end_idx = 1
padding_idx = 0
unk_idx = 2
seed = 42

In [ ]:
class Loaders():
    def __init__(
            self,
            data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/data.csv",
            max_token_length = 512,
            batch_size_train = 8,
            num_workers = 4,
            batch_size_val = 4,
            batch_size_test = 4,
            val_num_workers = 4,
            start_idx = 64100, 
            end_idx = 1, 
            padding_idx = 0, 
            unk_idx = 2,
            seed = 42,
    ):
        self.start_idx = start_idx
        self.end_idx = end_idx
        self.padding_idx = padding_idx
        self.unk_idx = unk_idx

        # 1) 데이터셋 로드
        dataset = load_dataset("csv", data_files=data_path)['train']
        # AI hub 한국어-영어 번역(병렬) 말뭉치 데이터셋
        # kor, en, cat 3개의 칼럼으로 구성

        # 2) 카테고리 컬럼의 고유 클래스 찾아서 ClassLabel 객체 생성
        unique_classes = dataset.unique('cat')  
        # 'cat' 열에 문장 분류 
        # 0: 구어체
        # 1: 대화체
        # 2: 문어체_뉴스
        # 3: 문어체_한국문화
        # 4: 문어체_조례
        # 5: 문어체_지자체웹사이트

        print(f"==>> unique_classes: {unique_classes}")
        class_label = ClassLabel(names=unique_classes)

        # 3) 기존 컬럼 타입 변경 (캐스팅)
        dataset = dataset.cast_column('cat', class_label)

        # 4) stratify_by_column으로 분할
        train_validtest = dataset.train_test_split(test_size=0.2, seed=seed, stratify_by_column='cat')
        valid_test = train_validtest['test'].train_test_split(test_size=0.1, seed=seed, stratify_by_column='cat')

        dataset_dict = DatasetDict({
            'train': train_validtest['train'],
            'validation': valid_test['train'],
            'test': valid_test['test']
        })

        # print(dataset_dict)

        NUM_CPU = multiprocessing.cpu_count()
        # print(f"==>> NUM_CPU: {NUM_CPU}")

        # self.tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-ko-en")
        # @@@ 점포, 만료 등의 단어가 <unk>인 문제 발견 => 다른 토크나이저 사용?
        self.tokenizer = AutoTokenizer.from_pretrained("KETI-AIR/ke-t5-base")

        special_tokens_dict = {'bos_token': '<s>'}
        self.tokenizer.add_special_tokens(special_tokens_dict)

        print(self.tokenizer.all_special_ids)
        print(self.tokenizer.all_special_tokens)

        print(f"==>> self.tokenizer.model_max_length: {self.tokenizer.model_max_length}")

        print(f"==>> len(self.tokenizer): {len(self.tokenizer)}")

        self.max_token_length = min(max_token_length, self.tokenizer.model_max_length)

        # partial을 이용해 tokenizer, max_token_length 인자 고정
        cetf = partial(convert_examples_to_features, tokenizer=self.tokenizer, max_token_length=self.max_token_length)
        # @@@ convert_examples_to_features함수에서 examples가 첫번쨰 인자가 아니면 
        # @@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서 
        # @@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러 발생

        self.datasets = dataset_dict.map(
                                cetf,
                                # lambda examples: convert_examples_to_features(examples, tokenizer=self.tokenizer, max_token_length=self.max_token_length),
                                batched=True,
                                # 원 데이터 'en', 'kor', 'cat' 등의 칼럼을 지우려면
                                # remove_columns 인자 사용
                                # remove_columns=dataset_dict["train"].column_names,
                                num_proc=NUM_CPU)

        print(f"==>> self.datasets: {self.datasets}")

        self.train_set = self.datasets['train']
        self.val_set = self.datasets['validation']
        self.test_set = self.datasets['test']

        c_fn = partial(collate_fn, start_idx=self.start_idx, end_idx=self.end_idx, padding_idx=self.padding_idx, unk_idx=self.unk_idx)

        self.loader_train = DataLoader(self.train_set, batch_size=batch_size_train, collate_fn=c_fn, shuffle=True, num_workers=num_workers, pin_memory=True)
        # 학습시에만 shuffle=True
        self.loader_val = DataLoader(self.val_set, batch_size=batch_size_val, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)
        self.loader_test = DataLoader(self.test_set, batch_size=batch_size_test, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)

# def convert_examples_to_features(tokenizer, max_token_length, examples):
# @@@@@@@@@ examples가 첫번쨰 인자가 아니면 
# @@@@@@@@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서
# @@@@@@@@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러가 발생한다
def convert_examples_to_features(examples, tokenizer, max_token_length):
    model_inputs = tokenizer(examples['kor'],
                             text_target=examples['en'],
                             max_length=max_token_length, truncation=True)
    # 여기서 첫번째 인자와 두번째 인자의 순서를 바꾸면 한영 번역 대신 영한 번역용으로 인풋과 타겟이 토큰화된다
    return model_inputs


def collate_fn(batch, start_idx, end_idx, padding_idx, unk_idx):
    # print('Original:\n', batch)
    # print("".center(50, "-"))
    # batch는 [{'kor':..., 'en':..., 'cat':숫자, 'input_ids':[...], 'attention_mask':[1, ...], 'labels': [...]}, ...] 형태
    
    # keys = batch[0].keys()
    keys = ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels']
    # print(f"==>> keys: {keys}")
    # print("".center(50, "-"))
    
    # new_batch = {k:[] for k in keys}
    # new_batch['decoder_inputs'] = []
    
    # for b in batch:
    #     for k,v in b.items():
    #         if k == 'input_ids' or k == 'attention_mask':
    #             new_batch[k].append(torch.LongTensor(v))
    #         elif k == 'labels':
    #             new_batch[k].append(torch.LongTensor(v))
    #             new_batch['decoder_inputs'].append(torch.LongTensor([65001] + v[:-1]))
    #         else:
    #             new_batch[k].append(v)

    # key값별로 value 다 모으기
    new_batch = {k:[b[k] for b in batch] for k in keys}

    # list들 LongTensor로 변환
    new_batch['decoder_inputs'] = [torch.LongTensor([start_idx] + label[:-1]) for label in new_batch['labels']]
    # print(f"==>> new_batch['decoder_inputs']: {new_batch['decoder_inputs']}")
    new_batch['input_ids'] = [torch.LongTensor(inp) for inp in new_batch['input_ids']]
    new_batch['labels'] = [torch.LongTensor(label) for label in new_batch['labels']]
    new_batch['attention_mask'] = [torch.LongTensor(mask) for mask in new_batch['attention_mask']]

    new_batch['ntokens'] = sum([l.numel() for l in new_batch['labels']])

    # decoder input의 attention mask 생성
    new_batch['decoder_mask'] = [torch.ones_like(d_inp, dtype=torch.long) for d_inp in new_batch['decoder_inputs']]


    # 각 input과 target 텐서를 패딩
    padded_inputs = pad_sequence(new_batch['input_ids'], batch_first=True, padding_value=padding_idx)
    new_batch['input_ids'] = padded_inputs
    padded_decoder_inputs = pad_sequence(new_batch['decoder_inputs'], batch_first=True, padding_value=padding_idx)
    new_batch['decoder_inputs'] = padded_decoder_inputs
    padded_targets = pad_sequence(new_batch['labels'], batch_first=True, padding_value=padding_idx)
    new_batch['labels'] = padded_targets

    # attention 마스크는 패딩(padding_idx) 대신 False(0)을 입력
    padded_masks = pad_sequence(new_batch['attention_mask'], batch_first=True, padding_value=0)
    new_batch['attention_mask'] = padded_masks

    padded_d_masks = pad_sequence(new_batch['decoder_mask'], batch_first=True, padding_value=0)
    new_batch['decoder_mask'] = padded_d_masks
    
    return new_batch

In [ ]:
loaders = Loaders(
    data_path=data_path,
    max_token_length=max_token_length,
    batch_size_train=batch_size_train,
    num_workers=num_workers,
    batch_size_val=batch_size_val,
    batch_size_test=batch_size_test,
    val_num_workers=val_num_workers,
    start_idx=start_idx,
    end_idx=end_idx,
    padding_idx=padding_idx,
    unk_idx=unk_idx,
    seed=seed,
)

==>> unique_classes: [2, 4, 1, 0, 3, 5]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

[64100, 1, 2, 0, 64099, 64098, 64097, 64096, 64095, 64094, 64093, 64092, 64091, 64090, 64089, 64088, 64087, 64086, 64085, 64084, 64083, 64082, 64081, 64080, 64079, 64078, 64077, 64076, 64075, 64074, 64073, 64072, 64071, 64070, 64069, 64068, 64067, 64066, 64065, 64064, 64063, 64062, 64061, 64060, 64059, 64058, 64057, 64056, 64055, 64054, 64053, 64052, 64051, 64050, 64049, 64048, 64047, 64046, 64045, 64044, 64043, 64042, 64041, 64040, 64039, 64038, 64037, 64036, 64035, 64034, 64033, 64032, 64031, 64030, 64029, 64028, 64027, 64026, 64025, 64024, 64023, 64022, 64021, 64020, 64019, 64018, 64017, 64016, 64015, 64014, 64013, 64012, 64011, 64010, 64009, 64008, 64007, 64006, 64005, 64004, 64003, 64002, 64001, 64000]
['<s>', '</s>', '<unk>', '<pad>', '<extra_id_0>', '<extra_id_1>', '<extra_id_2>', '<extra_id_3>', '<extra_id_4>', '<extra_id_5>', '<extra_id_6>', '<extra_id_7>', '<extra_id_8>', '<extra_id_9>', '<extra_id_10>', '<extra_id_11>', '<extra_id_12>', '<extra_id_13>', '<extra_id_14>', '<extra_id_15>', '<extra_id_16>', '<extra_id_17>', '<extra_id_18>', '<extra_id_19>', '<extra_id_20>', '<extra_id_21>', '<extra_id_22>', '<extra_id_23>', '<extra_id_24>', '<extra_id_25>', '<extra_id_26>', '<extra_id_27>', '<extra_id_28>', '<extra_id_29>', '<extra_id_30>', '<extra_id_31>', '<extra_id_32>', '<extra_id_33>', '<extra_id_34>', '<extra_id_35>', '<extra_id_36>', '<extra_id_37>', '<extra_id_38>', '<extra_id_39>', '<extra_id_40>', '<extra_id_41>', '<extra_id_42>', '<extra_id_43>', '<extra_id_44>', '<extra_id_45>', '<extra_id_46>', '<extra_id_47>', '<extra_id_48>', '<extra_id_49>', '<extra_id_50>', '<extra_id_51>', '<extra_id_52>', '<extra_id_53>', '<extra_id_54>', '<extra_id_55>', '<extra_id_56>', '<extra_id_57>', '<extra_id_58>', '<extra_id_59>', '<extra_id_60>', '<extra_id_61>', '<extra_id_62>', '<extra_id_63>', '<extra_id_64>', '<extra_id_65>', '<extra_id_66>', '<extra_id_67>', '<extra_id_68>', '<extra_id_69>', '<extra_id_70>', '<extra_id_71>', '<extra_id_72>', '<extra_id_73>', '<extra_id_74>', '<extra_id_75>', '<extra_id_76>', '<extra_id_77>', '<extra_id_78>', '<extra_id_79>', '<extra_id_80>', '<extra_id_81>', '<extra_id_82>', '<extra_id_83>', '<extra_id_84>', '<extra_id_85>', '<extra_id_86>', '<extra_id_87>', '<extra_id_88>', '<extra_id_89>', '<extra_id_90>', '<extra_id_91>', '<extra_id_92>', '<extra_id_93>', '<extra_id_94>', '<extra_id_95>', '<extra_id_96>', '<extra_id_97>', '<extra_id_98>', '<extra_id_99>']
==>> self.tokenizer.model_max_length: 512
==>> len(self.tokenizer): 64101
==>> self.datasets: DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1281934
    })
    validation: Dataset({
        features: ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 288435
    })
    test: Dataset({
        features: ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 32049
    })
})

In [ ]:
print(f"==>> unk_idx: {unk_idx}")

input_total = Counter([])
target_total = Counter([])
# total

num_batches_train = len(loaders.loader_train)

for step, batch in tqdm(
    enumerate(loaders.loader_train),
    total=num_batches_train,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total += input_count
    target_total += target_count

    # if step == 10:
    #     break

print(f"==>> input_total: {input_total}")
print(f"==>> target_total: {target_total}")

print(f"==>> input_total[unk_idx]: {input_total[unk_idx]}")
print(f"==>> target_total[unk_idx]: {target_total[unk_idx]}")

input_total_val = Counter([])
target_total_val = Counter([])
# total

num_batches_val = len(loaders.loader_val)

for step, batch in tqdm(
    enumerate(loaders.loader_val),
    total=num_batches_val,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_val += input_count
    target_total_val += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_val: {input_total_val}")
print(f"==>> target_total_val: {target_total_val}")
print(f"==>> input_total_val[unk_idx]: {input_total_val[unk_idx]}")
print(f"==>> target_total_val[unk_idx]: {target_total_val[unk_idx]}")

input_total_test = Counter([])
target_total_test = Counter([])
# total

num_batches_test = len(loaders.loader_test)

for step, batch in tqdm(
    enumerate(loaders.loader_test),
    total=num_batches_test,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_test += input_count
    target_total_test += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_test: {input_total_test}")
print(f"==>> target_total_test: {target_total_test}")
print(f"==>> input_total_test[unk_idx]: {input_total_test[unk_idx]}")
print(f"==>> target_total_test[unk_idx]: {target_total_test[unk_idx]}")

==>> unk_idx: 2

100%|██████████| 20031/20031 [01:45<00:00, 190.18it/s]

==>> input_total: Counter({0: 38628904, 1: 1281934, 3: 1231055, 4: 427959, 6: 313487, 15: 292084, 9: 272351, 11: 247959, 22: 227423, 12: 209259, 21: 172451, 35: 160825, 19: 143782, 32: 136435, 31: 126844, 25: 115514, 7: 109451, 42: 107337, 34: 105288, 30: 105192, 27: 102854, 18: 102613, 37: 99941, 24: 96661, 36: 94822, 41: 94217, 26: 92455, 56: 91259, 39: 86645, 53: 81602, 45: 80818, 47: 80376, 49: 74250, 50: 68885, 85: 66187, 44: 61816, 129: 59945, 52: 59210, 48: 58087, 59: 55220, 190: 52205, 88: 51717, 78: 50705, 79: 50356, 51: 49748, 74: 47617, 72: 46428, 70: 46107, 63: 45927, 57: 44254, 86: 43414, 58: 43001, 76: 41692, 80: 40317, 75: 37144, 105: 37027, 82: 33088, 121: 31609, 77: 31494, 66: 31338, 68: 31211, 208: 30686, 145: 30501, 125: 29147, 164: 29105, 99: 29080, 124: 29025, 95: 28116, 100: 27495, 98: 27376, 196: 27223, 600: 27209, 220: 26669, 123: 26205, 94: 25919, 61: 25905, 108: 25838, 156: 25168, 328: 25057, 127: 24623, 153: 24401, 132: 24160, 178: 24116, 119: 23869, 479: 23767, 163: 23567, 109: 23350, 160: 23282, 202: 23172, 327: 22956, 12027: 22828, 179: 22268, 162: 22238, 253: 22077, 182: 22075, 104: 21902, 181: 21898, 172: 21727, 189: 21548, 116: 21159, 251: 21056, 1449: 20999, 1928: 20890, 206: 20759, 234: 20708, 101: 20477, 150: 20395, 198: 19984, 141: 19906, 114: 19854, 168: 19649, 152: 19501, 120: 19303, 107: 19139, 151: 19058, 167: 19054, 233: 18891, 335: 18730, 240: 18613, 131: 18572, 115: 18569, 180: 18539, 200: 18263, 242: 18229, 148: 18195, 218: 18152, 161: 18123, 687: 18110, 216: 17970, 274: 17744, 133: 17520, 739: 17460, 794: 16940, 313: 16891, 237: 16730, 967: 16665, 213: 16396, 288: 16385, 188: 16357, 203: 16276, 169: 16274, 183: 16210, 140: 16181, 239: 16179, 209: 16104, 295: 16091, 389: 15955, 247: 15952, 410: 15663, 306: 15632, 222: 15514, 416: 15435, 158: 14925, 354: 14877, 207: 14736, 2: 14653, 725: 14640, 184: 14608, 230: 14496, 337: 14316, 224: 14212, 137: 14139, 323: 14101, 303: 14082, 408: 14016, 204: 13897, 258: 13882, 221: 13843, 212: 13708, 197: 13667, 255: 13577, 1445: 13544, 201: 13531, 293: 13515, 264: 13453, 28: 13427, 287: 13368, 385: 13202, 712: 13173, 280: 13158, 192: 13077, 195: 13053, 157: 13020, 1008: 12923, 254: 12794, 261: 12586, 33368: 12581, 276: 12530, 444: 12387, 347: 12310, 405: 12239, 289: 12214, 457: 12189, 350: 12163, 364: 12152, 432: 12146, 263: 12146, 194: 12141, 235: 12058, 6264: 12052, 362: 12043, 186: 12000, 290: 11979, 260: 11821, 378: 11794, 299: 11756, 279: 11727, 199: 11684, 286: 11670, 407: 11578, 29: 11444, 2328: 11442, 143: 11355, 441: 11352, 1499: 11291, 1867: 11242, 257: 11225, 311: 11177, 459: 11040, 601: 10984, 214: 10975, 308: 10947, 232: 10942, 317: 10763, 370: 10700, 547: 10688, 309: 10681, 351: 10671, 1380: 10642, 278: 10590, 426: 10571, 5866: 10563, 252: 10555, 772: 10528, 285: 10515, 1620: 10486, 10825: 10459, 291: 10433, 298: 10343, 1614: 10326, 488: 10264, 953: 10241, 3058: 10216, 302: 10157, 118: 10111, 433: 10059, 294: 10026, 332: 10024, 369: 10013, 501: 9974, 185: 9969, 305: 9966, 281: 9944, 386: 9935, 1139: 9907, 626: 9902, 395: 9859, 404: 9851, 210: 9848, 326: 9834, 690: 9803, 270: 9802, 381: 9778, 304: 9776, 439: 9760, 472: 9760, 522: 9751, 418: 9726, 361: 9675, 661: 9667, 357: 9664, 374: 9650, 579: 9648, 346: 9625, 219: 9585, 450: 9538, 1279: 9469, 316: 9404, 436: 9398, 541: 9370, 423: 9368, 284: 9353, 338: 9277, 400: 9260, 719: 9257, 11267: 9229, 314: 9182, 863: 9153, 383: 9152, 344: 9148, 1247: 9091, 922: 9078, 449: 9058, 8259: 8951, 950: 8874, 434: 8871, 415: 8868, 500: 8862, 130: 8692, 685: 8676, 319: 8671, 393: 8656, 512: 8624, 329: 8589, 563: 8579, 310: 8577, 853: 8566, 431: 8509, 468: 8485, 3751: 8473, 428: 8468, 784: 8464, 17: 8451, 1071: 8360, 375: 8358, 487: 8326, 402: 8307, 245: 8283, 396: 8283, 521: 8263, 463: 8251, 611: 8247, 642: 8222, 440: 8209, 475: 8198, 320: 8188, 773: 8166, 296: 8161, 29024: 8159, 446: 8134, 417: 8068, 561: 8066, 546: 8056, 1045: 8034, 892: 8018, 419: 8012, 598: 8009, 455: 7993, 1099: 7972, 379: 7970, 1591: 7953, 307: 7930, 427: 7904, 382: 7879, 392: 7866, 714: 7860, 569: 7852, 372: 7844, 471: 7838, 265: 7825, 542: 7823, 525: 7822, 435: 7817, 1097: 7787, 2469: 7744, 664: 7743, 268: 7713, 411: 7646, 506: 7642, 409: 7614, 356: 7594, 358: 7572, 716: 7572, 454: 7543, 895: 7540, 562: 7448, 1104: 7442, 456: 7432, 663: 7391, 639: 7372, 701: 7370, 875: 7364, 438: 7347, 831: 7325, 333: 7320, 584: 7293, 646: 7267, 855: 7196, 22648: 7128, 580: 7108, 1115: 7096, 820: 7062, 422: 7059, 668: 7044, 345: 7020, 665: 7010, 934: 6998, 447: 6955, 605: 6925, 869: 6917, 430: 6915, 301: 6908, 705: 6857, 859: 6848, 549: 6842, 951: 6832, 647: 6783, 1738: 6769, 533: 6769, 977: 6743, 586: 6737, 18708: 6722, 623: 6720, 1034: 6711, 602: 6694, 577: 6694, 673: 6679, 2594: 6675, 732: 6663, 821: 6644, 625: 6629, 677: 6627, 9919: 6612, 324: 6576, 352: 6560, 587: 6556, 1911: 6551, 1229: 6504, 9147: 6481, 363: 6480, 1670: 6478, 669: 6439, 568: 6417, 1472: 6389, 780: 6360, 609: 6351, 737: 6335, 360: 6317, 380: 6306, 954: 6297, 536: 6295, 678: 6291, 507: 6281, 113: 6278, 657: 6262, 757: 6262, 613: 6219, 391: 6211, 671: 6208, 45404: 6156, 588: 6153, 460: 6132, 803: 6129, 583: 6129, 633: 6107, 952: 6099, 1011: 6083, 524: 6075, 2074: 6064, 819: 6060, 377: 6056, 759: 6046, 1297: 6035, 698: 6025, 518: 6015, 29592: 6015, 15479: 6011, 551: 6008, 503: 6003, 1486: 5995, 491: 5983, 717: 5979, 13799: 5969, 1391: 5965, 591: 5955, 489: 5945, 462: 5917, 559: 5911, 576: 5909, 679: 5897, 2676: 5869, 901: 5852, 564: 5841, 906: 5828, 582: 5827, 607: 5822, 702: 5822, 560: 5819, 734: 5813, 401: 5809, 692: 5808, 940: 5790, 398: 5778, 9142: 5749, 761: 5748, 594: 5730, 660: 5725, 555: 5720, 517: 5716, 824: 5702, 528: 5695, 397: 5690, 499: 5664, 498: 5650, 1170: 5644, 570: 5639, 804: 5638, 996: 5635, 478: 5625, 2014: 5621, 850: 5606, 538: 5586, 504: 5581, 550: 5581, 756: 5567, 399: 5559, 889: 5536, 2029: 5525, 938: 5519, 9813: 5514, 972: 5505, 412: 5505, 1201: 5498, 421: 5491, 442: 5467, 445: 5463, 33976: 5436, 6448: 5435, 800: 5430, 1492: 5419, 1629: 5418, 211: 5414, 1053: 5412, 1254: 5408, 1795: 5396, 837: 5374, 630: 5365, 6751: 5364, 537: 5364, 1633: 5361, 1435: 5355, 1337: 5350, 919: 5330, 1122: 5320, 138: 5317, 631: 5307, 466: 5287, 983: 5286, 1022: 5282, 810: 5282, 567: 5274, 1002: 5271, 1772: 5271, 452: 5270, 728: 5261, 1003: 5241, 1439: 5237, 3194: 5226, 776: 5226, 453: 5223, 543: 5222, 1211: 5214, 1921: 5208, 706: 5200, 629: 5198, 469: 5193, 1400: 5188, 751: 5184, 2344: 5176, 998: 5173, 638: 5169, 1573: 5168, 715: 5167, 652: 5166, 530: 5158, 771: 5158, 849: 5151, 997: 5150, 578: 5149, 1524: 5149, 722: 5133, 793: 5129, 966: 5128, 1459: 5127, 1037: 5127, 1092: 5106, 1005: 5099, 802: 5098, 914: 5088, 795: 5087, 852: 5084, 511: 5080, 1169: 5076, 606: 5062, 689: 5053, 659: 5047, 632: 5036, 1837: 5027, 514: 5026, 3790: 5025, 1041: 5014, 470: 5013, 1188: 5007, 1347: 5003, 1198: 4998, 535: 4993, 878: 4983, 553: 4977, 508: 4975, 1067: 4941, 939: 4925, 2273: 4923, 981: 4917, 1712: 4907, 1755: 4901, 648: 4898, 932: 4897, 7399: 4889, 801: 4866, 1064: 4865, 1031: 4865, 343: 4853, 2217: 4844, 6865: 4842, 846: 4841, 816: 4836, 987: 4798, 1052: 4796, 747: 4783, 5455: 4773, 884: 4768, 935: 4767, 666: 4765, 839: 4764, 493: 4763, 5435: 4761, 1137: 4758, 599: 4749, 1220: 4742, 490: 4738, 670: 4736, 1818: 4733, 2404: 4721, 1109: 4721, 544: 4711, 783: 4706, 1216: 4705, 552: 4700, 1595: 4694, 3606: 4693, 686: 4691, 1128: 4691, 540: 4690, 894: 4678, 833: 4674, 782: 4671, 5579: 4668, 818: 4666, 710: 4665, 809: 4664, 1147: 4663, 448: 4661, 1026: 4658, 12671: 4656, 2339: 4655, 917: 4653, 619: 4646, 1036: 4643, 595: 4625, 1079: 4623, 675: 4622, 636: 4618, 8002: 4615, 1018: 4615, 1531: 4607, 805: 4607, 887: 4604, 1290: 4600, 1506: 4596, 900: 4582, 902: 4578, 10493: 4578, 662: 4575, 14750: 4573, 1505: 4570, 2867: 4563, 5659: 4561, 707: 4560, 1166: 4543, 11157: 4539, 1016: 4535, 1192: 4535, 970: 4525, 6271: 4524, 1523: 4523, 1528: 4511, 890: 4500, 3343: 4499, 1149: 4493, 495: 4482, 945: 4474, 2437: 4471, 1489: 4462, 1074: 4459, 779: 4458, 965: 4456, 1020: 4454, 1495: 4452, 4293: 4451, 1145: 4442, 2322: 4438, 964: 4434, 1543: 4434, 4095: 4430, 955: 4413, 1148: 4410, 510: 4410, 1132: 4403, 1039: 4403, 1281: 4402, 89: 4401, 1007: 4400, 797: 4388, 1336: 4378, 876: 4365, 2379: 4364, 1496: 4363, 627: 4361, 3635: 4351, 865: 4350, 862: 4343, 1013: 4340, 1131: 4322, 1125: 4321, 4930: 4319, 1103: 4315, 1873: 4309, 480: 4309, 558: 4294, 1086: 4293, 898: 4289, 573: 4282, 545: 4257, 1107: 4254, 1219: 4253, 921: 4250, 718: 4247, 1043: 4242, 1396: 4240, 637: 4238, 708: 4237, 1417: 4235, 1317: 4229, 1852: 4220, 769: 4214, 838: 4202, 1282: 4202, 1434: 4201, 1747: 4188, 841: 4184, 1233: 4181, 1446: 4177, 2087: 4175, 1150: 4160, 12447: 4153, 1954: 4145, 731: 4144, 1030: 4143, 786: 4139, 982: 4136, 2043: 4132, 2104: 4130, 931: 4122, 554: 4112, 1152: 4109, 2682: 4104, 872: 4100, 3973: 4097, 2887: 4097, 2822: 4095, 1559: 4077, 1739: 4076, 903: 4074, 904: 4073, 1344: 4062, 3455: 4058, 1298: 4055, 1699: 4053, 8872: 4053, 1890: 4053, 960: 4048, 2184: 4047, 1578: 4046, 4030: 4043, 645: 4033, 881: 4027, 2670: 4021, 1313: 4020, 1766: 4017, 1255: 4014, 1704: 4010, 785: 4008, 1217: 4007, 4768: 4003, 641: 4002, 1460: 4001, 777: 4000, 1932: 3996, 2090: 3993, 3448: 3981, 513: 3962, 1006: 3962, 1287: 3958, 1480: 3956, 7876: 3954, 1184: 3953, 1362: 3953, 2547: 3945, 1087: 3943, 1209: 3935, 956: 3931, 1406: 3927, 1468: 3925, 910: 3923, 1021: 3917, 16233: 3911, 1538: 3899, 1214: 3892, 1582: 3889, 384: 3888, 3012: 3883, 790: 3882, 1059: 3880, 857: 3879, 1085: 3878, 752: 3877, 1238: 3873, 3433: 3872, 942: 3861, 2969: 3859, 6400: 3857, 1251: 3857, 1253: 3857, 1323: 3856, 1186: 3849, 1179: 3848, 1544: 3848, 1907: 3844, 699: 3837, 1162: 3835, 814: 3829, 896: 3828, 760: 3827, 1473: 3824, 3619: 3819, 911: 3816, 1017: 3814, 1720: 3805, 873: 3805, 1378: 3802, 883: 3794, 711: 3793, 529: 3792, 1376: 3791, 1130: 3787, 16084: 3786, 1165: 3783, 614: 3775, 1422: 3770, 995: 3769, 1168: 3761, 1230: 3760, 864: 3749, 817: 3741, 755: 3740, 5175: 3736, 1012: 3733, 1646: 3733, 1118: 3729, 1190: 3725, 1101: 3716, 1827: 3715, 556: 3709, 628: 3707, 1357: 3706, 886: 3702, 1643: 3701, 1151: 3700, 1177: 3700, 973: 3687, 2432: 3686, 1205: 3682, 949: 3676, 860: 3674, 980: 3666, 1397: 3666, 1069: 3664, 990: 3661, 1285: 3660, 1164: 3657, 5787: 3657, 25455: 3656, 778: 3655, 1821: 3654, 9297: 3654, 1196: 3649, 1129: 3648, 1748: 3642, 7809: 3641, 1197: 3638, 3885: 3636, 1635: 3634, 1420: 3626, 1476: 3626, 16065: 3625, 2254: 3623, 1507: 3614, 1770: 3610, 1056: 3610, 1341: 3608, 813: 3605, 1542: 3603, 1893: 3602, 1419: 3601, 3314: 3597, 1572: 3588, 1078: 3588, 1116: 3588, 2301: 3586, 1269: 3583, 1324: 3581, 4278: 3581, 1088: 3577, 1140: 3576, 1816: 3572, 1246: 3571, 1263: 3569, 1274: 3566, 684: 3559, 2430: 3557, 1352: 3555, 3430: 3552, 1464: 3544, 1509: 3541, 1557: 3538, 640: 3538, 1075: 3534, 1404: 3517, 12784: 3517, 1292: 3516, 1070: 3514, 1208: 3513, 1776: 3511, 1656: 3508, 597: 3501, 1604: 3499, 1592: 3495, 937: 3493, 1587: 3492, 1883: 3489, 1268: 3487, 880: 3486, 12978: 3483, 1267: 3478, 877: 3475, 848: 3474, 1478: 3473, 1143: 3472, 789: 3470, 2143: 3468, 984: 3467, 1511: 3467, 7909: 3460, 1829: 3459, 1334: 3459, 1574: 3451, 2303: 3451, 727: 3449, 1845: 3447, 1550: 3444, 891: 3444, 1102: 3444, 2331: 3437, 1027: 3432, 1135: 3428, 1106: 3428, 1328: 3419, 868: 3419, 1063: 3413, 2999: 3413, 1715: 3412, 2296: 3412, 1866: 3410, 741: 3406, 1552: 3403, 1181: 3397, 2175: 3396, 1611: 3395, 2932: 3393, 1696: 3388, 946: 3385, 2678: 3382, 1412: 3378, 2710: 3377, 1405: 3375, 1178: 3375, 1976: 3371, 1688: 3360, 764: 3360, 2537: 3355, 592: 3352, 2118: 3340, 2367: 3337, 2194: 3335, 879: 3334, 2823: 3333, 962: 3331, 944: 3330, 1736: 3326, 5641: 3323, 1392: 3323, 1807: 3318, 1311: 3317, 986: 3313, 1227: 3309, 6058: 3302, 1423: 3300, 3849: 3294, 2881: 3293, 1332: 3288, 1155: 3287, 815: 3286, 1555: 3284, 2063: 3284, 7804: 3283, 1306: 3280, 1359: 3276, 1598: 3273, 923: 3273, 2477: 3265, 1239: 3258, 3267: 3255, 2541: 3253, 1316: 3252, 2307: 3250, 1136: 3249, 1418: 3244, 2279: 3243, 1895: 3241, 3571: 3240, 2285: 3238, 1195: 3236, 1265: 3236, 3279: 3235, 1260: 3234, 2557: 3228, 1402: 3223, 1199: 3223, 1610: 3222, 3470: 3212, 1717: 3208, 1288: 3208, 1194: 3204, 766: 3203, 1955: 3200, 1563: 3197, 2319: 3191, 907: 3190, 3764: 3185, 1156: 3182, 1399: 3180, 2539: 3175, 1108: 3173, 1049: 3169, 1751: 3169, 1120: 3168, 1508: 3168, 1701: 3167, 743: 3163, 1437: 3162, 492: 3162, 1741: 3160, 9644: 3159, 1305: 3158, 723: 3154, 3013: 3154, 1609: 3152, 1138: 3151, 1784: 3150, 1068: 3147, 976: 3136, 1831: 3131, 856: 3130, 1836: 3125, 1083: 3125, 1515: 3124, 1744: 3123, 2993: 3120, 3744: 3117, 1682: 3115, 10335: 3115, 1315: 3114, 6382: 3112, 2386: 3112, 2112: 3109, 912: 3109, 975: 3106, 16169: 3106, 531: 3103, 3035: 3099, 1675: 3096, 4444: 3093, 2310: 3088, 968: 3086, 832: 3084, 3134: 3081, 1117: 3080, 6460: 3074, 2644: 3072, 1338: 3070, 1502: 3065, 1640: 3063, 1746: 3055, 1273: 3055, 1726: 3055, 1490: 3055, 1801: 3050, 2801: 3047, 1381: 3046, 842: 3044, 3235: 3044, 2166: 3044, 1203: 3043, 2041: 3042, 5341: 3041, 1657: 3040, 1919: 3040, 893: 3037, 1218: 3033, 2785: 3031, 1624: 3030, 1564: 3028, 3208: 3024, 205: 3022, 1813: 3022, 1681: 3019, 1182: 3018, 365: 3017, 974: 3016, 1545: 3014, 1038: 3013, 1834: 3011, 3178: 3010, 2290: 3009, 3520: 3008, 3306: 3006, 1822: 3002, 1370: 3002, 2983: 3002, 961: 3002, 11154: 3001, 2226: 2999, 1180: 2998, 3034: 2996, 1663: 2994, 2399: 2991, 2186: 2987, 1769: 2986, 2453: 2984, 3454: 2982, 930: 2979, 2947: 2979, 1119: 2979, 1606: 2978, 1243: 2976, 1731: 2976, 4597: 2975, 7378: 2975, 1382: 2974, 1312: 2974, 39287: 2973, 1250: 2973, 1534: 2972, 649: 2971, 3464: 2969, 1309: 2968, 3715: 2964, 1046: 2963, 1623: 2960, 1389: 2959, 1354: 2957, 781: 2955, 829: 2954, 2148: 2954, 1213: 2954, 1314: 2951, 1501: 2939, 1259: 2939, 1521: 2938, 2132: 2934, 1659: 2932, 10048: 2931, 1228: 2929, 4787: 2928, 4575: 2928, 1301: 2928, 2510: 2923, 1931: 2916, 1176: 2914, 2183: 2914, 1193: 2913, 2860: 2906, 753: 2905, 2326: 2905, 300: 2904, 1094: 2901, 1698: 2900, 768: 2899, 394: 2899, 2274: 2898, 1588: 2895, 5085: 2894, 1700: 2885, 1066: 2884, 1961: 2883, 1299: 2881, 1025: 2879, 2101: 2875, 2872: 2870, 3539: 2869, 1410: 2867, 1280: 2867, 1256: 2866, 1871: 2861, 2488: 2857, 2774: 2854, 1114: 2853, 2619: 2853, 1047: 2853, 1796: 2853, 1892: 2852, 2056: 2851, 1278: 2850, 1189: 2850, 1811: 2849, 1146: 2848, 1514: 2848, 2412: 2847, 999: 2846, 3209: 2845, 4333: 2844, 1141: 2840, 695: 2839, 2833: 2839, 1560: 2838, 1975: 2837, 4505: 2834, 1411: 2826, 6718: 2824, 5277: 2823, 1466: 2821, 1237: 2815, 957: 2813, 3069: 2813, 249: 2810, 1958: 2807, 1518: 2807, 1289: 2805, 1432: 2805, 1364: 2805, 1009: 2805, 2023: 2803, 1339: 2803, 2615: 2803, 3269: 2799, 4500: 2798, 19942: 2797, 1343: 2797, 2000: 2796, 1485: 2796, 1691: 2795, 1971: 2794, 3382: 2790, 1375: 2787, 1939: 2784, 3092: 2783, 1124: 2783, 2534: 2777, 1440: 2776, 1568: 2774, 775: 2773, 1740: 2769, 1481: 2769, 2634: 2764, 3011: 2763, 2172: 2762, 1173: 2762, 2674: 2761, 3677: 2760, 1072: 2759, 1781: 2757, 3584: 2756, 2070: 2756, 3022: 2751, 5360: 2746, 2007: 2745, 2052: 2743, 27121: 2742, 2942: 2741, 928: 2741, 1488: 2740, 1427: 2735, 3087: 2735, 1847: 2730, 1799: 2725, 1308: 2725, 1451: 2724, 1868: 2722, 1942: 2722, 1513: 2721, 2149: 2720, 1616: 2716, 1549: 2712, 2116: 2707, 1694: 2707, 1665: 2704, 1491: 2703, 2258: 2703, 1401: 2701, 3193: 2700, 2201: 2695, 2981: 2695, 2295: 2692, 748: 2691, 3070: 2690, 2551: 2689, 3124: 2689, 6636: 2687, 6126: 2687, 1395: 2686, 2067: 2685, 2076: 2684, 1409: 2681, 1286: 2679, 2293: 2677, 2015: 2676, 3902: 2675, 2209: 2675, 1593: 2672, 1851: 2668, 2147: 2666, 1933: 2665, 7208: 2664, 1719: 2663, 1998: 2661, 1986: 2661, 1732: 2659, 3334: 2659, 2032: 2658, 827: 2655, 2953: 2648, 2351: 2647, 1935: 2646, 10236: 2644, 1015: 2643, 2665: 2638, 2542: 2637, 3231: 2635, 851: 2634, 1082: 2633, 1642: 2631, 1231: 2631, 2414: 2630, 1291: 2630, 2671: 2629, 2649: 2628, 1361: 2627, 1778: 2627, 1930: 2624, 2660: 2624, 2387: 2624, 2022: 2623, 2381: 2622, 3403: 2619, 4283: 2612, 1407: 2609, 1058: 2608, 1244: 2608, 882: 2607, 1638: 2606, 1631: 2600, 2031: 2596, 2380: 2596, 2466: 2595, 2427: 2595, 888: 2591, 1603: 2589, 2849: 2584, 4554: 2583, 1252: 2583, 2045: 2583, 2291: 2582, 1566: 2580, 985: 2580, 1322: 2579, 1224: 2575, 1977: 2573, 733: 2573, 2120: 2572, 1742: 2570, 1910: 2565, 3820: 2563, 858: 2563, 908: 2563, 2257: 2563, 1144: 2561, 2529: 2558, 1997: 2558, 2580: 2556, 2638: 2551, 2110: 2551, 2034: 2548, 2513: 2547, 2951: 2547, 8505: 2546, 31289: 2543, 1882: 2538, 14316: 2536, 2075: 2535, 4100: 2534, 1627: 2533, 936: 2532, 3287: 2531, 834: 2529, 2733: 2529, 2334: 2527, 3328: 2524, 3429: 2524, 1388: 2524, 1912: 2523, 1212: 2523, 2646: 2521, 1756: 2520, 2461: 2519, 5966: 2518, 1771: 2518, 1565: 2515, 1540: 2514, 3510: 2514, 1367: 2511, 3451: 2511, 2436: 2508, 1172: 2506, 2827: 2506, 1121: 2504, 1917: 2501, 1916: 2500, 1901: 2500, 1899: 2500, 2288: 2496, 1519: 2496, 4678: 2496, 3471: 2495, 17503: 2490, 1463: 2486, 2192: 2478, 1957: 2478, 3909: 2477, 1666: 2476, 1133: 2475, 2704: 2475, 2613: 2474, 30411: 2473, 3014: 2471, 1832: 2468, 1791: 2468, 1475: 2467, 1782: 2466, 1547: 2463, 2599: 2463, 13121: 2461, 2984: 2460, 13642: 2457, 3374: 2457, 1335: 2457, 4502: 2453, 2065: 2451, 1385: 2450, 2340: 2448, 4764: 2448, 830: 2447, 21151: 2447, 635: 2446, 2742: 2446, 1561: 2442, 8342: 2442, 2938: 2440, 2193: 2437, 2044: 2433, 3095: 2433, 10120: 2431, 1329: 2427, 1777: 2422, 2019: 2422, 2012: 2421, 2500: 2421, 3698: 2420, 2802: 2419, 2216: 2419, 1850: 2418, 2966: 2418, 2740: 2416, 1300: 2415, 1869: 2411, 1902: 2410, 2480: 2409, 1881: 2409, 2787: 2408, 2423: 2407, 26722: 2407, 2515: 2406, 2095: 2402, 2783: 2402, 1431: 2397, 3831: 2397, 2292: 2397, 2998: 2396, 2365: 2395, 2345: 2394, 1482: 2391, 2693: 2387, 1724: 2384, 2739: 2384, 3265: 2383, 3641: 2383, 2457: 2381, 2084: 2377, 1618: 2375, 2313: 2373, 3608: 2372, 1969: 2372, 1945: 2372, 1938: 2372, 1241: 2371, 1333: 2370, 1567: 2369, 1091: 2368, 3694: 2368, 2793: 2366, 4407: 2365, 2790: 2364, 1351: 2364, 413: 2361, 1923: 2358, 1909: 2356, 1789: 2355, 2748: 2355, 4741: 2353, 7102: 2353, 1820: 2351, 5284: 2349, 2961: 2349, 2039: 2348, 2409: 2343, 4101: 2342, 1527: 2338, 2845: 2338, 2606: 2338, 2493: 2337, 2601: 2336, 4529: 2333, 1377: 2332, 26869: 2332, 2584: 2330, 1393: 2326, 2085: 2325, 1223: 2325, 1048: 2325, 1806: 2323, 1985: 2322, 1858: 2322, 1906: 2321, 1457: 2321, 696: 2319, 2544: 2318, 2462: 2316, 2905: 2315, 4350: 2314, 3538: 2314, 2914: 2312, 770: 2308, 2662: 2305, 4104: 2300, 1425: 2300, 2002: 2299, 1862: 2293, 1535: 2292, 12450: 2290, 1685: 2289, 1843: 2288, 3424: 2287, 2253: 2285, 2441: 2284, 1926: 2283, 811: 2283, 2572: 2282, 3576: 2280, 2096: 2280, 1504: 2279, 2428: 2278, 1918: 2277, 4613: 2276, 1596: 2276, 29149: 2276, 2249: 2275, 1999: 2275, 1687: 2274, 3037: 2273, 27789: 2273, 3725: 2270, 3077: 2269, 1024: 2269, 2732: 2268, 21476: 2267, 1788: 2266, 5893: 2265, 3118: 2265, 2255: 2265, 2154: 2264, 4484: 2264, 2587: 2263, 1915: 2261, 2128: 2260, 6574: 2260, 1886: 2259, 2502: 2257, 4767: 2256, 2954: 2256, 1602: 2254, 2139: 2254, 3145: 2250, 958: 2250, 2011: 2249, 4094: 2247, 4686: 2246, 1283: 2246, 2141: 2242, 3516: 2242, 2841: 2241, 2360: 2240, 4039: 2240, 20237: 2239, 5429: 2238, 1581: 2238, 1721: 2238, 1856: 2238, 2975: 2237, 2189: 2237, 1500: 2236, 1859: 2235, 6074: 2235, 2271: 2234, 2083: 2234, 13215: 2234, 4067: 2233, 2487: 2233, 2555: 2231, 4071: 2228, 7796: 2226, 2385: 2225, 1950: 2222, 1793: 2221, 3748: 2220, 1876: 2217, 2030: 2215, 6770: 2214, 2440: 2214, 2165: 2214, 4618: 2213, 30281: 2212, 3795: 2211, 3970: 2207, 2586: 2206, 3039: 2205, 1004: 2204, 2956: 2202, 2082: 2200, 2764: 2200, 1833: 2200, 1645: 2199, 1790: 2199, 2641: 2195, 1649: 2194, 1416: 2193, 2092: 2193, 4275: 2192, 4235: 2192, 2514: 2191, 3955: 2189, 497: 2188, 2332: 2186, 6006: 2181, 1920: 2179, 2579: 2179, 2021: 2177, 1674: 2175, 3240: 2174, 2233: 2172, 5974: 2172, 2559: 2170, 4129: 2170, 1842: 

100%|██████████| 4507/4507 [00:22<00:00, 202.02it/s]

==>> input_total_val: Counter({0: 8648372, 1: 288435, 3: 277030, 4: 96234, 6: 70050, 15: 65312, 9: 61727, 11: 55818, 22: 51026, 12: 47156, 21: 38417, 35: 35816, 19: 32310, 32: 30509, 31: 28310, 25: 25998, 7: 24491, 42: 24238, 30: 23887, 34: 23834, 27: 23292, 18: 23196, 37: 22267, 24: 21839, 36: 21332, 41: 20999, 26: 20933, 56: 20582, 39: 19484, 53: 18318, 47: 18241, 45: 18187, 49: 17046, 50: 15490, 85: 14824, 44: 13970, 129: 13634, 52: 13223, 48: 13134, 59: 12428, 190: 11757, 78: 11578, 88: 11400, 79: 11314, 51: 11144, 70: 10611, 74: 10590, 72: 10382, 63: 10291, 57: 10197, 86: 9870, 58: 9588, 76: 9385, 80: 9175, 75: 8354, 105: 8261, 82: 7517, 145: 7031, 121: 7022, 77: 6950, 66: 6864, 68: 6806, 208: 6794, 164: 6644, 125: 6618, 95: 6529, 99: 6525, 124: 6467, 100: 6203, 196: 6139, 600: 6082, 98: 6059, 220: 5885, 94: 5835, 123: 5808, 61: 5750, 108: 5739, 127: 5633, 156: 5596, 328: 5575, 178: 5397, 153: 5381, 479: 5362, 160: 5333, 163: 5238, 119: 5228, 327: 5220, 109: 5196, 132: 5137, 202: 5103, 179: 5052, 12027: 5038, 181: 4990, 253: 4966, 172: 4949, 182: 4926, 104: 4920, 162: 4909, 251: 4801, 116: 4769, 234: 4688, 1449: 4685, 1928: 4672, 189: 4665, 206: 4642, 101: 4620, 198: 4574, 150: 4545, 141: 4540, 114: 4476, 152: 4402, 168: 4335, 687: 4313, 167: 4306, 151: 4258, 180: 4240, 233: 4235, 120: 4232, 107: 4230, 115: 4209, 131: 4199, 335: 4187, 148: 4160, 200: 4138, 242: 4137, 240: 4131, 218: 4029, 161: 4019, 274: 3958, 216: 3952, 188: 3859, 794: 3845, 739: 3811, 133: 3810, 213: 3799, 169: 3725, 967: 3723, 288: 3713, 389: 3701, 313: 3689, 247: 3674, 203: 3667, 237: 3660, 239: 3633, 295: 3569, 140: 3552, 183: 3535, 306: 3534, 222: 3509, 209: 3503, 410: 3436, 354: 3372, 725: 3344, 416: 3333, 207: 3310, 137: 3293, 2: 3290, 323: 3285, 158: 3246, 184: 3204, 337: 3201, 230: 3151, 221: 3150, 197: 3138, 255: 3137, 212: 3113, 224: 3111, 303: 3102, 264: 3100, 1445: 3063, 204: 3055, 28: 3032, 408: 3029, 201: 3002, 293: 2996, 258: 2987, 280: 2981, 712: 2980, 287: 2974, 157: 2925, 192: 2915, 385: 2899, 195: 2895, 1008: 2877, 254: 2857, 276: 2854, 261: 2813, 350: 2812, 263: 2802, 405: 2795, 33368: 2793, 457: 2768, 347: 2765, 279: 2763, 194: 2763, 289: 2745, 6264: 2741, 290: 2725, 444: 2724, 364: 2714, 260: 2695, 299: 2695, 362: 2684, 235: 2682, 186: 2681, 432: 2675, 1499: 2672, 199: 2664, 407: 2639, 378: 2634, 1867: 2600, 286: 2596, 214: 2579, 2328: 2579, 441: 2574, 29: 2566, 143: 2540, 257: 2522, 232: 2518, 459: 2513, 426: 2511, 317: 2495, 5866: 2477, 10825: 2456, 547: 2443, 488: 2425, 308: 2414, 370: 2411, 311: 2397, 601: 2395, 1380: 2380, 772: 2373, 351: 2368, 1620: 2360, 285: 2353, 252: 2352, 291: 2349, 309: 2346, 278: 2330, 1614: 2329, 1139: 2316, 953: 2312, 298: 2310, 501: 2309, 332: 2281, 386: 2273, 302: 2272, 626: 2268, 395: 2258, 3058: 2236, 305: 2225, 270: 2224, 369: 2224, 316: 2221, 210: 2215, 294: 2215, 404: 2214, 522: 2213, 304: 2209, 661: 2208, 118: 2208, 219: 2207, 433: 2203, 439: 2198, 361: 2196, 326: 2191, 418: 2191, 423: 2186, 346: 2169, 185: 2168, 281: 2159, 690: 2158, 579: 2148, 436: 2147, 381: 2146, 374: 2142, 472: 2131, 400: 2112, 1279: 2102, 450: 2100, 284: 2099, 950: 2082, 541: 2078, 11267: 2072, 1247: 2064, 719: 2059, 338: 2059, 434: 2055, 357: 2052, 383: 2045, 863: 2030, 415: 2026, 922: 2024, 344: 2021, 449: 2006, 3751: 2001, 685: 1990, 314: 1989, 375: 1970, 245: 1962, 8259: 1957, 500: 1952, 319: 1933, 563: 1924, 784: 1915, 393: 1913, 512: 1912, 853: 1894, 310: 1888, 17: 1888, 402: 1887, 431: 1885, 463: 1880, 471: 1879, 773: 1877, 396: 1875, 468: 1874, 329: 1870, 598: 1869, 307: 1865, 130: 1863, 320: 1859, 428: 1851, 1071: 1851, 475: 1846, 611: 1846, 419: 1844, 379: 1834, 296: 1833, 546: 1830, 29024: 1828, 521: 1825, 487: 1824, 642: 1824, 892: 1814, 455: 1808, 561: 1801, 446: 1796, 569: 1795, 417: 1792, 525: 1791, 382: 1790, 435: 1786, 392: 1780, 440: 1778, 542: 1760, 714: 1759, 1591: 1758, 1045: 1754, 716: 1750, 427: 1750, 506: 1738, 664: 1735, 1099: 1733, 1097: 1731, 265: 1729, 372: 1725, 409: 1703, 562: 1698, 701: 1698, 1104: 1697, 358: 1695, 454: 1684, 875: 1682, 411: 1681, 831: 1681, 895: 1676, 268: 1671, 646: 1666, 333: 1666, 356: 1654, 855: 1649, 456: 1640, 1115: 1635, 2469: 1635, 549: 1632, 345: 1622, 668: 1620, 934: 1617, 639: 1616, 1670: 1616, 422: 1603, 447: 1602, 951: 1601, 438: 1594, 580: 1593, 673: 1593, 22648: 1589, 605: 1584, 705: 1576, 18708: 1570, 869: 1566, 663: 1560, 584: 1556, 363: 1554, 577: 1548, 1738: 1547, 533: 1541, 665: 1533, 301: 1533, 430: 1530, 602: 1526, 820: 1517, 2594: 1514, 625: 1511, 1229: 1505, 977: 1501, 1034: 1493, 1911: 1490, 623: 1489, 859: 1489, 647: 1486, 657: 1485, 352: 1481, 677: 1466, 732: 1461, 821: 1461, 954: 1460, 9919: 1458, 669: 1453, 1472: 1451, 780: 1447, 324: 1447, 9147: 1447, 737: 1444, 587: 1444, 460: 1437, 952: 1434, 518: 1426, 803: 1420, 586: 1420, 360: 1417, 536: 1414, 613: 1408, 507: 1408, 678: 1407, 671: 1397, 757: 1395, 380: 1390, 609: 1389, 568: 1386, 570: 1382, 583: 1382, 45404: 1381, 819: 1376, 759: 1365, 633: 1364, 503: 1364, 850: 1362, 698: 1360, 901: 1360, 391: 1356, 2074: 1355, 551: 1351, 524: 1350, 491: 1350, 113: 1348, 1297: 1347, 594: 1346, 1011: 1341, 559: 1341, 499: 1340, 679: 1339, 591: 1337, 588: 1336, 377: 1329, 1391: 1325, 734: 1325, 489: 1321, 528: 1319, 582: 1317, 756: 1316, 555: 1314, 761: 1314, 13799: 1314, 2676: 1311, 398: 1310, 702: 1307, 517: 1298, 15479: 1296, 996: 1295, 576: 1293, 462: 1292, 660: 1285, 2014: 1282, 906: 1281, 804: 1281, 1486: 1279, 940: 1277, 889: 1274, 692: 1274, 401: 1273, 478: 1270, 442: 1270, 607: 1268, 560: 1266, 29592: 1262, 550: 1261, 824: 1259, 800: 1255, 717: 1254, 1122: 1252, 1400: 1251, 1053: 1249, 9142: 1249, 1795: 1245, 564: 1243, 919: 1243, 412: 1237, 6751: 1236, 211: 1236, 1170: 1235, 498: 1234, 504: 1231, 652: 1229, 6448: 1228, 1629: 1228, 453: 1227, 1492: 1221, 538: 1219, 543: 1213, 397: 1211, 2029: 1210, 1435: 1208, 1002: 1207, 722: 1206, 1524: 1204, 399: 1204, 837: 1201, 421: 1201, 445: 1198, 972: 1196, 466: 1194, 1837: 1191, 638: 1190, 630: 1190, 530: 1189, 1037: 1187, 849: 1186, 1439: 1185, 1201: 1184, 998: 1184, 648: 1182, 983: 1181, 1921: 1180, 793: 1179, 1337: 1178, 508: 1176, 9813: 1175, 1003: 1174, 728: 1166, 846: 1162, 452: 1162, 578: 1161, 1022: 1161, 469: 1158, 33976: 1158, 1005: 1156, 1211: 1156, 938: 1153, 631: 1153, 751: 1153, 3194: 1150, 514: 1149, 914: 1149, 537: 1148, 810: 1147, 632: 1146, 706: 1145, 1347: 1145, 981: 1144, 138: 1144, 567: 1139, 715: 1139, 776: 1139, 1254: 1137, 1573: 1136, 802: 1136, 1041: 1130, 1188: 1130, 470: 1128, 894: 1128, 553: 1127, 1198: 1126, 1459: 1125, 1772: 1123, 795: 1123, 884: 1123, 801: 1122, 659: 1122, 1031: 1119, 1633: 1118, 1755: 1117, 1064: 1113, 878: 1113, 1026: 1108, 2404: 1108, 3790: 1107, 1220: 1107, 987: 1106, 1092: 1106, 1169: 1104, 599: 1103, 2217: 1099, 5455: 1097, 935: 1097, 1712: 1096, 1137: 1093, 689: 1093, 809: 1092, 771: 1092, 966: 1091, 852: 1089, 1067: 1088, 511: 1087, 666: 1084, 670: 1082, 2344: 1082, 606: 1081, 6865: 1077, 816: 1077, 1109: 1074, 7399: 1073, 747: 1071, 710: 1071, 900: 1070, 1818: 1069, 839: 1066, 629: 1066, 14750: 1065, 5579: 1065, 5435: 1065, 448: 1064, 1216: 1063, 2339: 1063, 12671: 1060, 965: 1059, 2437: 1058, 1281: 1058, 10493: 1056, 945: 1056, 932: 1055, 939: 1054, 782: 1052, 535: 1051, 1290: 1050, 997: 1050, 343: 1048, 1039: 1048, 544: 1048, 1147: 1048, 902: 1047, 540: 1047, 1489: 1046, 490: 1046, 2273: 1045, 8002: 1045, 890: 1044, 805: 1043, 1543: 1040, 1523: 1039, 2379: 1039, 783: 1037, 1052: 1037, 1505: 1033, 595: 1033, 686: 1032, 2867: 1032, 5659: 1032, 558: 1031, 1506: 1030, 1074: 1030, 917: 1029, 11157: 1026, 707: 1026, 4293: 1025, 619: 1023, 1149: 1023, 3606: 1023, 887: 1023, 1166: 1018, 1018: 1017, 12447: 1017, 1531: 1017, 970: 1017, 552: 1012, 6271: 1011, 1125: 1010, 1036: 1010, 3343: 1009, 1128: 1008, 1528: 1007, 4930: 1007, 495: 1006, 662: 1006, 1336: 1006, 1317: 1002, 797: 1000, 1132: 997, 3635: 996, 636: 995, 4095: 994, 1043: 993, 89: 993, 1016: 993, 1103: 991, 493: 991, 675: 990, 510: 990, 955: 990, 573: 990, 865: 990, 2322: 988, 818: 988, 833: 987, 1013: 987, 1145: 987, 872: 985, 964: 985, 1595: 984, 881: 976, 708: 974, 545: 971, 1495: 968, 896: 966, 1030: 964, 921: 964, 1079: 964, 779: 963, 718: 961, 1362: 961, 1747: 960, 1233: 960, 1007: 956, 2087: 953, 1020: 950, 637: 949, 731: 949, 641: 948, 3448: 945, 480: 945, 769: 944, 1131: 943, 627: 942, 1148: 941, 1152: 938, 1219: 936, 513: 935, 931: 933, 2887: 933, 2043: 933, 1086: 932, 1739: 931, 1766: 930, 1852: 930, 16233: 929, 1217: 929, 876: 927, 1873: 927, 1192: 927, 1704: 926, 1699: 926, 1396: 925, 3012: 921, 3455: 920, 384: 920, 862: 918, 1107: 916, 1085: 916, 1434: 915, 1378: 912, 1417: 912, 2104: 912, 1298: 912, 1282: 911, 1230: 911, 1460: 911, 1150: 909, 956: 909, 1287: 909, 2822: 908, 841: 906, 2090: 906, 1255: 904, 3973: 904, 1251: 903, 2184: 903, 1214: 903, 1006: 901, 7876: 900, 790: 898, 554: 898, 1559: 897, 6400: 897, 1406: 896, 786: 895, 904: 894, 838: 894, 903: 892, 1578: 891, 1954: 891, 1446: 890, 1932: 890, 857: 889, 1542: 888, 1313: 887, 1344: 886, 2682: 886, 645: 886, 814: 885, 1238: 884, 1269: 884, 785: 882, 982: 881, 1069: 880, 2670: 880, 1496: 879, 1186: 879, 1480: 879, 711: 879, 1246: 878, 1165: 877, 1468: 877, 1253: 877, 1816: 877, 1376: 876, 1184: 876, 1572: 876, 1907: 875, 960: 875, 8872: 875, 898: 874, 990: 872, 16084: 869, 1646: 867, 1151: 864, 1209: 863, 1544: 862, 1422: 861, 752: 861, 1190: 861, 1179: 859, 2547: 859, 1021: 857, 5787: 857, 12784: 857, 699: 856, 3885: 856, 1538: 854, 1087: 853, 1890: 853, 1205: 853, 1196: 851, 4030: 851, 942: 850, 2969: 850, 1070: 850, 4278: 850, 1177: 849, 1285: 849, 777: 849, 1357: 849, 813: 848, 864: 847, 3619: 847, 2432: 846, 886: 846, 1635: 845, 873: 845, 556: 843, 4768: 842, 1420: 841, 628: 840, 860: 840, 1582: 840, 614: 840, 1017: 838, 883: 837, 1012: 836, 1323: 833, 911: 832, 1893: 831, 1118: 831, 1473: 830, 1162: 830, 910: 829, 1404: 828, 995: 828, 1168: 828, 3433: 827, 980: 827, 1059: 827, 1720: 826, 2301: 825, 12978: 824, 1397: 823, 755: 823, 760: 821, 9297: 821, 1143: 821, 529: 819, 1419: 819, 1352: 818, 16065: 818, 1776: 817, 949: 817, 1106: 816, 1101: 814, 778: 814, 1332: 813, 1821: 811, 764: 810, 2143: 809, 877: 808, 1688: 808, 1164: 807, 1341: 806, 1509: 806, 2296: 805, 1845: 805, 973: 805, 1552: 805, 1056: 805, 1557: 803, 7909: 803, 1770: 803, 5175: 803, 2430: 802, 817: 802, 1129: 800, 2254: 800, 1274: 798, 1078: 798, 923: 798, 1116: 797, 1075: 793, 597: 793, 25455: 793, 1412: 791, 880: 790, 1316: 790, 1130: 789, 1827: 789, 1748: 786, 1227: 786, 1715: 786, 1405: 786, 1478: 785, 2307: 785, 1476: 785, 1063: 783, 1587: 783, 1135: 783, 2537: 783, 727: 782, 789: 780, 1334: 779, 1399: 779, 3267: 777, 848: 777, 2331: 777, 1604: 776, 1088: 775, 3571: 773, 1181: 773, 1866: 773, 946: 772, 1268: 771, 2303: 770, 1208: 770, 1829: 770, 968: 769, 3430: 769, 1550: 768, 684: 768, 2932: 768, 1592: 767, 2710: 765, 1464: 765, 1292: 765, 937: 764, 1140: 764, 1263: 763, 640: 763, 1643: 763, 741: 763, 1328: 762, 2175: 762, 7809: 761, 1883: 760, 1507: 760, 984: 758, 1178: 757, 1696: 757, 2367: 756, 1895: 755, 3849: 754, 1305: 754, 1136: 754, 868: 754, 1511: 753, 2881: 753, 1555: 753, 1610: 753, 1288: 752, 1574: 751, 2194: 751, 879: 751, 649: 750, 1611: 750, 1656: 749, 1083: 749, 1049: 748, 3279: 748, 1955: 748, 3470: 746, 1265: 746, 1267: 745, 1418: 745, 1598: 742, 1392: 742, 1490: 742, 1197: 742, 3314: 741, 815: 741, 592: 741, 3764: 741, 1784: 740, 1027: 740, 2063: 739, 1744: 737, 986: 737, 891: 736, 1260: 736, 9644: 735, 1746: 735, 2319: 735, 1239: 733, 2557: 733, 2477: 733, 1675: 732, 3464: 730, 2999: 730, 1306: 730, 1199: 729, 3013: 728, 1731: 728, 7804: 728, 1156: 728, 1624: 728, 1324: 727, 5641: 725, 1315: 725, 944: 724, 2279: 723, 2118: 723, 1564: 722, 1117: 722, 1545: 721, 1741: 721, 1508: 720, 1801: 719, 1259: 719, 2541: 718, 1228: 717, 2112: 717, 2310: 717, 1120: 716, 6058: 716, 11154: 716, 1195: 715, 1359: 715, 1194: 714, 856: 714, 1108: 714, 1609: 714, 3520: 713, 492: 713, 832: 713, 2285: 713, 1102: 712, 1682: 710, 974: 710, 1976: 710, 1736: 708, 912: 708, 205: 708, 3306: 707, 1717: 706, 1836: 706, 1701: 706, 4444: 705, 1155: 705, 1919: 705, 1751: 705, 766: 704, 1640: 704, 962: 703, 2801: 703, 2386: 702, 1138: 701, 2678: 701, 753: 700, 1180: 700, 1311: 699, 1423: 698, 1309: 697, 1213: 696, 1068: 696, 394: 695, 2644: 694, 1189: 694, 1502: 693, 16169: 692, 1534: 692, 1402: 692, 976: 692, 2774: 692, 1273: 691, 1381: 689, 781: 688, 1822: 687, 4575: 687, 2823: 686, 3209: 683, 1046: 683, 1038: 683, 1663: 683, 1119: 682, 365: 682, 743: 682, 1807: 682, 2226: 681, 5277: 681, 3744: 681, 531: 680, 3134: 680, 907: 679, 2615: 678, 1338: 678, 1437: 677, 1521: 677, 4597: 677, 3035: 676, 2488: 676, 2399: 676, 2101: 675, 1769: 674, 1141: 674, 1312: 673, 723: 673, 1218: 672, 1515: 672, 2785: 672, 3208: 672, 1389: 672, 6718: 671, 3178: 671, 1314: 670, 2983: 669, 1501: 669, 2619: 668, 6382: 668, 1451: 667, 1203: 667, 5341: 667, 3235: 667, 10048: 667, 2326: 666, 2993: 666, 3539: 665, 961: 664, 2872: 664, 2166: 664, 2453: 664, 842: 664, 3715: 662, 5085: 661, 2132: 661, 2860: 661, 2041: 661, 1411: 661, 10335: 661, 1698: 660, 1047: 659, 1831: 658, 1563: 657, 4505: 657, 1237: 654, 1681: 654, 768: 654, 975: 654, 829: 654, 2947: 654, 1256: 653, 2649: 653, 27121: 652, 1382: 652, 3069: 651, 1485: 651, 1971: 651, 4500: 651, 1466: 650, 1568: 650, 1250: 650, 1299: 649, 2186: 649, 2290: 648, 2674: 648, 2510: 648, 1834: 648, 1308: 647, 1176: 647, 1370: 647, 2634: 645, 3034: 645, 1606: 645, 2052: 644, 1025: 644, 3454: 643, 6460: 643, 4333: 643, 1871: 642, 1375: 642, 4787: 641, 1481: 641, 1094: 641, 1781: 640, 1892: 640, 1657: 640, 1066: 639, 1700: 639, 1939: 639, 300: 639, 1488: 638, 1958: 638, 2148: 638, 1638: 637, 1339: 637, 957: 636, 893: 635, 1931: 635, 930: 635, 2007: 635, 2070: 634, 1726: 633, 4554: 633, 2023: 632, 1072: 632, 2147: 632, 1182: 631, 2183: 631, 1560: 631, 2534: 630, 1114: 630, 999: 630, 1975: 630, 1301: 629, 3092: 628, 1813: 627, 1395: 627, 1278: 627, 695: 626, 2833: 625, 2539: 625, 2513: 625, 1518: 625, 1146: 624, 3269: 623, 2274: 623, 1361: 623, 2412: 623, 1280: 623, 1343: 622, 2022: 622, 1243: 622, 4100: 622, 2209: 622, 1796: 622, 39287: 621, 3382: 620, 1799: 620, 1882: 620, 1961: 619, 1631: 619, 1623: 619, 1354: 618, 2951: 618, 2295: 616, 3193: 616, 1732: 616, 775: 616, 748: 616, 1432: 615, 1977: 615, 1659: 615, 851: 614, 2201: 614, 1665: 613, 249: 613, 2172: 613, 2827: 612, 2056: 612, 2981: 611, 2149: 611, 1172: 610, 2942: 608, 3584: 608, 1410: 608, 1694: 608, 2387: 608, 1847: 608, 1364: 608, 5360: 608, 2032: 607, 2671: 607, 1427: 607, 2015: 606, 2075: 606, 1193: 606, 2351: 606, 3087: 605, 1124: 605, 2110: 605, 10236: 605, 1811: 605, 6636: 604, 2116: 604, 1549: 604, 2461: 604, 2067: 603, 985: 603, 1289: 602, 7378: 602, 1082: 602, 3070: 601, 2120: 601, 1666: 600, 1144: 600, 1058: 599, 2938: 599, 1009: 598, 1173: 598, 1912: 596, 2034: 596, 1588: 596, 1627: 595, 1642: 595, 2742: 595, 3022: 595, 1540: 595, 2257: 593, 3677: 593, 1616: 593, 2192: 593, 2000: 592, 1930: 591, 1133: 591, 1778: 591, 2849: 591, 1409: 591, 2258: 590, 1851: 589, 5966: 589, 928: 589, 1121: 589, 2380: 588, 2427: 588, 1933: 588, 1603: 586, 1015: 586, 2381: 585, 733: 585, 1740: 584, 1899: 584, 1514: 583, 2031: 583, 3820: 582, 827: 581, 1291: 580, 3902: 580, 3403: 580, 882: 580, 1832: 580, 1868: 580, 1491: 579, 3011: 579, 1244: 578, 3124: 578, 2139: 578, 1252: 578, 3287: 578, 4283: 577, 3510: 576, 4678: 576, 858: 575, 4764: 575, 1691: 575, 2345: 574, 17503: 574, 2551: 574, 1986: 574, 2293: 573, 2665: 573, 1917: 572, 1593: 572, 2414: 572, 2436: 572, 2365: 572, 1388: 571, 2529: 571, 2580: 571, 1504: 571, 1618: 570, 19942: 570, 2291: 569, 888: 569, 4484: 569, 1901: 569, 1224: 569, 3231: 569, 4101: 568, 1329: 568, 1547: 568, 8505: 568, 14316: 568, 2599: 568, 1742: 567, 2646: 566, 1997: 566, 830: 565, 635: 565, 2076: 565, 1942: 564, 2542: 564, 2704: 564, 6126: 563, 2288: 563, 10120: 563, 936: 563, 1998: 562, 1286: 562, 2733: 561, 2802: 561, 2953: 561, 2480: 561, 3014: 560, 1935: 560, 3334: 560, 2340: 560, 1910: 560, 1231: 559, 2216: 559, 2271: 559, 3265: 558, 1513: 558, 1212: 558, 2740: 558, 2660: 558, 2793: 557, 834: 557, 3374: 557, 2334: 557, 2693: 556, 4502: 556, 2998: 556, 2966: 555, 31289: 554, 2044: 554, 2012: 553, 2493: 553, 1241: 553, 13121: 553, 1719: 553, 4039: 552, 7208: 552, 3145: 552, 2095: 551, 2606: 551, 2065: 550, 2638: 550, 3328: 550, 1407: 550, 4529: 549, 1561: 548, 3451: 548, 3909: 548, 1401: 548, 3641: 548, 29149: 548, 1881: 547, 2409: 547, 1862: 547, 1567: 546, 1440: 546, 1475: 546, 13642: 546, 2249: 545, 1777: 545, 1859: 545, 413: 545, 1902: 545, 1519: 544, 2193: 544, 3831: 544, 1869: 544, 4741: 543, 2584: 543, 30411: 542, 2515: 542, 2466: 542, 3694: 542, 1856: 541, 2253: 541, 3725: 541, 1806: 541, 1876: 541, 12450: 540, 3118: 540, 3095: 540, 1333: 539, 2984: 539, 3608: 539, 2783: 538, 2084: 537, 3429: 537, 21151: 536, 2905: 536, 1789: 536, 908: 536, 1687: 536, 2128: 535, 1566: 535, 2790: 535, 2559: 535, 1385: 535, 2500: 535, 1782: 535, 1906: 535, 4767: 533, 3471: 532, 1024: 532, 3240: 531, 1500: 531, 2423: 531, 3698: 531, 1649: 531, 1565: 531, 1850: 531, 2841: 530, 1916: 530, 2092: 530, 3970: 530, 1335: 529, 1300: 529, 1596: 529, 1482: 529, 3576: 529, 1995: 528, 4618: 528, 1377: 528, 2292: 527, 2579: 526, 2662: 526, 2587: 526, 7796: 526, 3077: 525, 1791: 525, 1820: 525, 4613: 525, 1985: 524, 4686: 524, 2572: 524, 2082: 523, 2096: 523, 2002: 523, 1724: 523, 6006: 523, 4235: 522, 2227: 521, 1918: 520, 1843: 520, 1283: 520, 1223: 520, 2544: 520, 6074: 520, 2045: 519, 2154: 519, 1945: 519, 1367: 519, 1909: 518, 2630: 518, 2019: 518, 2441: 518, 2457: 518, 1322: 517, 1457: 516, 1938: 516, 1756: 516, 770: 516, 2975: 515, 1048: 515, 1771: 515, 1846: 515, 2255: 515, 8342: 514, 2462: 514, 1926: 514, 6574: 514, 2502: 513, 2895: 513, 2601: 513, 1004: 512, 2083: 512, 1431: 512, 2961: 512, 2514: 511, 4071: 511, 1842: 511, 2613: 511, 2313: 511, 4275: 511, 1857: 511, 2748: 511, 7182: 511, 1602: 510, 4067: 510, 3992: 509, 4407: 509, 2739: 509, 1833: 508, 2725: 508, 1398: 508, 1923: 508, 1788: 508, 1957: 507, 2821: 507, 2039: 507, 2393: 506, 5269: 506, 1393: 506, 13215: 506, 1793: 506, 4540: 506, 1463: 506, 2586: 505, 2385: 505, 2448: 505, 2845: 504, 1761: 504, 1858: 504, 26722: 504, 9675: 503, 2487: 502, 277: 502, 1685: 502, 1535: 502, 4094: 502, 2440: 502, 1527: 502, 3039: 502, 1941: 501, 1091: 501, 2085: 500, 30281: 500, 2494: 499, 1612: 499, 1351: 499, 3482: 498, 2838: 498, 1915: 498, 20237: 497, 2030: 496, 4350: 496, 2151: 495, 3516: 495, 2360: 495, 3424: 495, 4822: 495, 2189: 494, 1969: 493, 1790: 492, 5893: 492, 2233: 492, 3538: 492, 4438: 491, 2555: 491, 2914: 491, 3007: 491, 2372: 491, 3748: 490, 2100: 490, 5429: 490, 5418: 490, 1546: 490, 1645: 490, 2357: 489, 497: 489, 3300: 489, 22655: 489, 26869: 488, 6843: 488, 2428: 487, 3179: 487, 1674: 487, 5284: 486, 3955: 486, 28454: 486, 3467: 486, 3097: 486, 7102: 486, 2764: 486, 2729: 485, 2159: 485, 21476: 484, 2787: 484, 1886: 483, 1416: 482, 3795: 482, 2025: 481, 1721: 481, 969: 480, 2170: 480, 3794: 480, 1745: 480, 2245: 480, 2641: 479, 5272: 479, 4104: 478, 3055: 477, 1383: 477, 2954: 477, 2411: 476, 2134: 476, 2165: 476, 2196: 476, 2925: 476, 4525: 476, 3169: 475, 1581: 475, 1425: 475, 4399: 475, 3867: 475, 2549: 475, 3025: 474, 1626: 474, 2368: 474, 3040: 473, 27789: 473, 3044: 473, 2418: 473, 4007: 472, 4898: 472, 4140: 472, 2021: 471, 3141: 471, 3037: 471, 1877: 471, 5944: 471, 9203: 470, 1950: 470, 4202: 470, 6592: 470, 5974: 470, 1690: 470, 1889: 470, 2718: 469, 3672: 469, 19992: 469, 2944: 469, 1841: 469, 1262: 469, 989: 468, 2604: 468, 3093: 468, 696: 468, 958: 468, 13211: 468, 12184: 468, 2221: 467, 2332: 467, 2164: 467, 811: 467, 2369: 467, 2518: 466, 2732: 466, 2272: 466, 177: 466, 2839: 466, 2939: 466, 1815: 465, 2846: 465, 5930: 465, 1920: 465, 2309: 465, 1436: 464, 1936: 464, 2548: 463, 1887: 463, 9249: 463, 4129: 463, 6770: 463, 2059: 463, 3680: 462, 1497: 462, 3380: 462, 4783: 462, 2536: 462, 14618: 462, 2114: 461, 2081: 461, 2451: 461, 103

100%|██████████| 501/501 [00:02<00:00, 220.75it/s]

==>> input_total_test: Counter({0: 954386, 1: 32049, 3: 30865, 4: 10814, 6: 7593, 15: 7384, 9: 6733, 11: 6264, 22: 5635, 12: 5293, 21: 4359, 35: 4094, 19: 3595, 32: 3418, 31: 3169, 25: 2853, 42: 2802, 7: 2780, 34: 2675, 27: 2651, 30: 2640, 18: 2585, 24: 2522, 37: 2471, 41: 2388, 26: 2354, 36: 2349, 56: 2334, 39: 2160, 47: 2054, 53: 2033, 45: 2018, 49: 1812, 50: 1718, 85: 1622, 52: 1511, 44: 1501, 129: 1487, 48: 1443, 59: 1334, 88: 1317, 190: 1282, 78: 1262, 79: 1219, 74: 1216, 51: 1188, 72: 1162, 70: 1154, 86: 1123, 57: 1072, 63: 1071, 58: 1054, 76: 1025, 80: 995, 105: 921, 75: 890, 82: 832, 121: 818, 77: 809, 66: 788, 68: 761, 145: 754, 164: 746, 208: 735, 196: 709, 95: 707, 99: 696, 125: 695, 98: 683, 124: 683, 100: 681, 123: 679, 94: 650, 220: 649, 61: 642, 600: 635, 127: 631, 479: 625, 108: 625, 156: 620, 202: 608, 163: 603, 178: 598, 328: 594, 153: 591, 12027: 581, 253: 578, 132: 578, 109: 577, 160: 574, 181: 574, 119: 569, 172: 561, 251: 559, 162: 557, 327: 556, 182: 552, 234: 548, 179: 542, 104: 530, 116: 520, 1928: 519, 206: 512, 168: 506, 150: 504, 218: 500, 1449: 498, 167: 492, 101: 487, 242: 487, 115: 484, 189: 483, 114: 482, 198: 481, 151: 478, 180: 478, 200: 477, 107: 473, 131: 473, 233: 470, 239: 457, 161: 455, 120: 453, 183: 452, 141: 449, 335: 447, 133: 444, 152: 443, 188: 443, 274: 441, 169: 437, 213: 435, 240: 435, 313: 430, 222: 429, 687: 428, 967: 426, 148: 423, 216: 417, 237: 410, 2: 409, 306: 406, 410: 405, 140: 402, 416: 401, 739: 396, 209: 393, 389: 390, 794: 389, 203: 388, 295: 385, 158: 383, 725: 380, 408: 378, 258: 376, 337: 374, 354: 372, 323: 371, 247: 369, 184: 369, 28: 368, 221: 368, 230: 366, 207: 366, 288: 364, 264: 363, 255: 362, 224: 360, 287: 359, 137: 358, 303: 357, 197: 353, 201: 352, 385: 351, 204: 337, 192: 336, 276: 336, 712: 335, 457: 333, 280: 327, 254: 326, 1445: 326, 263: 325, 444: 322, 350: 320, 157: 319, 432: 319, 293: 317, 195: 314, 261: 308, 289: 308, 378: 303, 1867: 303, 1008: 303, 364: 302, 212: 301, 279: 301, 459: 301, 235: 300, 426: 300, 347: 300, 260: 300, 290: 297, 291: 291, 362: 291, 2328: 289, 194: 288, 441: 285, 311: 285, 370: 284, 186: 284, 257: 283, 1139: 282, 407: 282, 1620: 279, 302: 277, 953: 277, 232: 277, 298: 277, 199: 277, 299: 277, 33368: 276, 6264: 276, 143: 275, 1499: 273, 286: 272, 626: 272, 10825: 270, 118: 270, 547: 270, 308: 268, 386: 268, 501: 268, 472: 267, 252: 265, 351: 264, 278: 263, 1614: 263, 404: 263, 1380: 262, 29: 262, 3058: 260, 601: 259, 309: 258, 433: 257, 210: 256, 405: 255, 5866: 254, 346: 253, 317: 253, 488: 251, 294: 251, 285: 251, 185: 249, 357: 249, 338: 248, 304: 248, 439: 248, 772: 247, 418: 247, 690: 245, 374: 243, 316: 243, 395: 243, 219: 243, 1279: 243, 11267: 242, 950: 242, 369: 241, 270: 241, 214: 241, 400: 240, 332: 240, 326: 238, 310: 237, 383: 236, 436: 236, 450: 236, 415: 234, 305: 233, 130: 233, 661: 233, 381: 231, 434: 231, 8259: 229, 863: 228, 1247: 228, 522: 227, 487: 225, 423: 225, 319: 224, 3751: 224, 281: 223, 463: 223, 428: 221, 344: 221, 719: 221, 375: 220, 561: 218, 361: 218, 382: 217, 449: 216, 314: 216, 284: 216, 500: 215, 468: 215, 402: 215, 773: 214, 455: 214, 1071: 214, 563: 213, 427: 212, 639: 212, 685: 212, 546: 211, 875: 209, 320: 208, 17: 208, 419: 208, 1045: 207, 392: 205, 431: 204, 542: 203, 569: 202, 379: 202, 714: 202, 417: 202, 1097: 202, 611: 200, 446: 200, 1591: 200, 855: 200, 475: 200, 506: 200, 853: 200, 358: 200, 579: 199, 541: 199, 922: 199, 471: 199, 329: 198, 784: 197, 1104: 196, 701: 196, 454: 195, 307: 194, 296: 194, 435: 194, 512: 194, 265: 193, 598: 192, 562: 191, 372: 191, 892: 191, 647: 190, 2469: 190, 521: 189, 22648: 189, 396: 188, 663: 188, 934: 188, 584: 187, 642: 187, 1738: 185, 447: 184, 440: 183, 1099: 183, 716: 183, 673: 182, 895: 182, 533: 182, 869: 181, 393: 180, 438: 179, 525: 179, 559: 178, 665: 178, 664: 178, 409: 178, 29024: 177, 623: 176, 677: 176, 430: 176, 1115: 175, 668: 174, 705: 174, 2594: 174, 1472: 174, 732: 174, 301: 174, 831: 174, 9147: 173, 456: 173, 824: 172, 692: 172, 517: 171, 363: 171, 536: 171, 1911: 171, 583: 171, 646: 170, 580: 170, 45404: 170, 605: 170, 422: 169, 780: 168, 245: 168, 609: 168, 268: 168, 549: 168, 518: 167, 1170: 167, 671: 167, 586: 166, 633: 166, 951: 166, 678: 165, 324: 165, 411: 165, 356: 165, 821: 165, 577: 164, 952: 163, 560: 163, 1122: 163, 2074: 163, 564: 162, 333: 162, 345: 162, 507: 162, 613: 161, 906: 161, 761: 161, 391: 161, 1034: 161, 737: 161, 6751: 160, 582: 160, 759: 160, 625: 160, 9919: 159, 587: 159, 820: 159, 602: 159, 360: 159, 578: 159, 2676: 158, 499: 158, 503: 157, 1391: 157, 568: 157, 352: 156, 1297: 156, 679: 156, 380: 156, 551: 156, 669: 155, 591: 155, 859: 154, 901: 154, 555: 154, 15479: 154, 940: 154, 1011: 154, 804: 153, 588: 153, 13799: 153, 1772: 153, 715: 152, 977: 152, 18708: 151, 452: 151, 998: 150, 570: 150, 850: 150, 498: 150, 29592: 149, 607: 149, 1229: 149, 776: 149, 1633: 149, 889: 149, 1254: 148, 460: 148, 751: 147, 902: 147, 2014: 147, 722: 146, 3194: 146, 453: 145, 1201: 145, 631: 145, 657: 145, 478: 145, 576: 145, 819: 144, 1005: 144, 954: 143, 1064: 143, 919: 143, 660: 143, 689: 143, 1670: 143, 800: 143, 33976: 143, 698: 143, 972: 142, 938: 141, 398: 141, 2344: 141, 211: 141, 1712: 141, 401: 141, 421: 141, 996: 140, 377: 140, 939: 139, 734: 139, 900: 139, 1037: 139, 1629: 139, 1337: 139, 9813: 138, 524: 138, 756: 138, 728: 138, 757: 138, 530: 138, 466: 138, 442: 138, 567: 138, 489: 137, 805: 137, 803: 137, 1921: 137, 818: 136, 528: 136, 113: 136, 1795: 135, 1400: 135, 12671: 135, 1459: 135, 878: 134, 783: 134, 1022: 133, 983: 133, 887: 133, 491: 132, 469: 132, 801: 132, 652: 132, 670: 132, 1435: 131, 550: 131, 1486: 131, 2029: 131, 837: 131, 540: 131, 1492: 131, 810: 130, 1188: 130, 846: 129, 1092: 129, 397: 129, 1021: 128, 1192: 128, 399: 128, 2404: 128, 702: 128, 514: 128, 795: 127, 838: 127, 343: 127, 535: 127, 2217: 127, 1109: 127, 412: 127, 1211: 127, 1036: 127, 5659: 127, 629: 127, 1053: 126, 470: 126, 970: 126, 553: 126, 4095: 126, 9142: 126, 771: 126, 636: 126, 538: 126, 1531: 126, 686: 125, 2867: 125, 849: 125, 717: 125, 552: 125, 1439: 125, 6865: 125, 1147: 124, 894: 124, 921: 124, 1002: 124, 1595: 124, 448: 124, 1067: 123, 6448: 123, 1030: 123, 793: 123, 710: 123, 594: 123, 7399: 123, 1755: 123, 537: 123, 1003: 122, 1031: 122, 1166: 122, 462: 122, 1198: 122, 5435: 122, 1837: 122, 1528: 122, 707: 122, 1041: 121, 802: 121, 2273: 121, 3635: 121, 504: 121, 1018: 121, 1220: 121, 881: 121, 816: 121, 1216: 121, 659: 120, 490: 120, 3606: 120, 1573: 120, 917: 119, 852: 119, 1290: 119, 935: 119, 510: 119, 982: 118, 599: 118, 1506: 118, 632: 118, 4768: 118, 1169: 118, 3973: 118, 12978: 118, 1347: 117, 666: 117, 1103: 117, 987: 117, 1524: 117, 16065: 117, 493: 117, 556: 117, 508: 117, 706: 117, 1317: 117, 862: 117, 5579: 116, 14750: 115, 1137: 115, 1145: 115, 2043: 115, 779: 115, 1219: 115, 1039: 115, 138: 115, 997: 115, 809: 114, 914: 114, 1336: 114, 981: 114, 4030: 114, 619: 114, 1496: 114, 1747: 113, 1323: 113, 1255: 113, 3433: 113, 932: 113, 884: 113, 965: 112, 3343: 112, 1132: 112, 595: 112, 955: 112, 1052: 112, 511: 112, 1150: 111, 1468: 111, 554: 111, 2339: 111, 777: 111, 1538: 111, 1507: 111, 10493: 111, 641: 110, 1281: 110, 2437: 110, 1026: 110, 1074: 110, 2104: 110, 3790: 110, 747: 110, 876: 110, 1251: 110, 890: 109, 648: 109, 6271: 109, 833: 109, 1362: 109, 1699: 109, 8002: 109, 2379: 109, 16233: 109, 12447: 108, 627: 108, 1016: 108, 910: 108, 645: 108, 1739: 108, 445: 108, 1282: 108, 606: 108, 1128: 108, 2254: 107, 1125: 107, 1446: 107, 2322: 107, 1069: 107, 1873: 107, 1196: 107, 1509: 106, 1417: 106, 1821: 106, 1269: 106, 1816: 106, 2090: 106, 1007: 106, 904: 106, 1190: 106, 782: 106, 1079: 106, 1505: 105, 886: 105, 2430: 105, 573: 105, 1559: 105, 945: 105, 1131: 105, 1217: 105, 89: 105, 1954: 105, 2822: 105, 638: 105, 1287: 104, 7909: 104, 1489: 104, 544: 104, 973: 104, 1184: 104, 1168: 103, 480: 103, 839: 103, 630: 103, 785: 103, 1434: 103, 976: 103, 964: 103, 11157: 103, 1578: 103, 495: 103, 966: 103, 741: 102, 5455: 102, 1818: 102, 865: 102, 543: 102, 1604: 102, 3455: 102, 3448: 102, 1152: 101, 1085: 101, 675: 101, 769: 101, 1013: 101, 1214: 101, 1396: 101, 4930: 101, 790: 101, 1177: 101, 1285: 101, 8872: 101, 3012: 100, 857: 100, 1195: 100, 1420: 100, 1766: 100, 1086: 100, 1059: 100, 3885: 100, 1476: 100, 893: 100, 2969: 100, 662: 100, 1378: 100, 1238: 99, 1149: 99, 1129: 99, 1543: 99, 718: 99, 640: 98, 1209: 98, 731: 98, 2670: 98, 1523: 98, 1344: 98, 1102: 98, 911: 98, 1020: 98, 960: 98, 879: 97, 797: 97, 1406: 97, 1720: 97, 558: 97, 2087: 97, 1136: 97, 1078: 97, 1852: 97, 1741: 97, 1027: 97, 1399: 97, 1890: 97, 637: 97, 597: 96, 1542: 96, 1682: 96, 1181: 96, 1197: 96, 1587: 96, 1056: 96, 727: 96, 1075: 96, 2942: 96, 2999: 95, 708: 95, 1572: 95, 2063: 95, 1227: 95, 711: 95, 760: 95, 1495: 95, 2301: 95, 6400: 95, 7804: 95, 2983: 95, 814: 95, 766: 95, 1883: 95, 1557: 94, 2184: 94, 2307: 94, 1292: 94, 1895: 94, 2644: 94, 3013: 94, 786: 94, 1208: 94, 1265: 94, 12784: 94, 1866: 94, 1907: 94, 1155: 94, 1186: 94, 1550: 94, 1354: 93, 1087: 93, 1893: 93, 1108: 93, 1748: 93, 545: 93, 755: 93, 942: 93, 1165: 93, 1025: 93, 4293: 93, 2477: 92, 872: 92, 2432: 92, 841: 92, 1544: 92, 880: 92, 764: 92, 1397: 92, 883: 92, 1646: 92, 3134: 92, 931: 92, 16169: 92, 1233: 92, 1006: 92, 1043: 92, 1182: 92, 815: 92, 896: 91, 7876: 91, 860: 91, 2547: 91, 1501: 91, 3314: 91, 1460: 91, 2947: 91, 1179: 91, 3035: 91, 984: 91, 856: 91, 1143: 91, 2887: 91, 1834: 91, 775: 91, 1404: 91, 1070: 90, 903: 90, 1696: 90, 5175: 90, 817: 90, 1932: 90, 1156: 90, 7208: 90, 1955: 90, 956: 90, 3454: 90, 699: 89, 3619: 89, 1376: 89, 1831: 89, 1301: 89, 781: 89, 1230: 89, 1228: 89, 1083: 89, 1813: 89, 1552: 89, 832: 88, 923: 88, 1419: 88, 1357: 88, 5641: 88, 1012: 88, 2537: 88, 864: 88, 3279: 88, 1704: 88, 2823: 88, 1751: 88, 7378: 88, 1352: 88, 990: 88, 752: 88, 891: 87, 1769: 87, 2194: 87, 1164: 87, 16084: 87, 1717: 87, 1592: 87, 27121: 87, 898: 87, 1776: 87, 1107: 87, 3235: 87, 1324: 87, 1101: 87, 949: 87, 1508: 86, 1311: 86, 1314: 86, 1359: 86, 877: 86, 1106: 86, 1511: 86, 1151: 86, 1118: 86, 2331: 86, 1268: 86, 2118: 86, 813: 86, 937: 86, 873: 86, 628: 86, 2201: 86, 1313: 86, 1140: 85, 2132: 85, 3430: 85, 912: 85, 985: 85, 1744: 85, 2172: 85, 614: 85, 1298: 85, 384: 85, 7809: 85, 1827: 85, 2557: 85, 1162: 85, 2175: 85, 1009: 85, 868: 85, 1700: 85, 3539: 85, 1611: 84, 946: 84, 5277: 84, 1267: 84, 4278: 84, 1657: 84, 829: 84, 25455: 84, 2860: 84, 513: 83, 986: 83, 2682: 83, 1066: 83, 2052: 83, 1116: 83, 1574: 83, 1407: 83, 1656: 83, 3744: 83, 6718: 83, 2539: 83, 1205: 83, 1437: 82, 4787: 82, 768: 82, 1341: 82, 1038: 82, 1280: 82, 1259: 82, 2319: 82, 1305: 82, 1274: 82, 2932: 82, 205: 82, 1976: 82, 2801: 82, 1770: 81, 1412: 81, 733: 81, 1422: 81, 1289: 81, 1148: 81, 908: 81, 1598: 81, 11154: 81, 1047: 81, 6636: 81, 1784: 81, 2367: 81, 1048: 81, 684: 81, 1178: 81, 1405: 81, 529: 81, 1088: 81, 1564: 81, 2303: 80, 3306: 80, 789: 80, 300: 80, 249: 80, 1732: 80, 5787: 80, 1731: 80, 2143: 80, 1328: 80, 1799: 80, 1120: 80, 1017: 80, 1473: 80, 2510: 80, 1246: 80, 1237: 80, 1610: 80, 1623: 79, 778: 79, 1688: 79, 1146: 79, 1253: 79, 1199: 79, 1781: 79, 2296: 79, 848: 79, 1194: 79, 2070: 79, 2733: 79, 1545: 79, 1418: 79, 1942: 79, 1939: 79, 2056: 79, 10120: 79, 1409: 79, 3209: 79, 3677: 79, 743: 79, 1218: 79, 1701: 79, 3764: 79, 10335: 79, 3334: 79, 3571: 79, 4502: 79, 2541: 78, 1239: 78, 2774: 78, 1555: 78, 1635: 78, 1746: 78, 6460: 78, 2183: 78, 1811: 78, 2166: 78, 980: 78, 1306: 78, 3208: 78, 2881: 78, 31289: 78, 1288: 78, 2619: 78, 3902: 77, 999: 77, 5341: 77, 2613: 77, 1464: 77, 1117: 77, 1681: 77, 1046: 77, 2671: 77, 394: 77, 928: 77, 930: 77, 1263: 77, 1315: 77, 1392: 77, 492: 77, 1144: 76, 944: 76, 1642: 76, 1172: 76, 695: 76, 995: 76, 2427: 76, 842: 76, 1721: 76, 1049: 76, 1789: 76, 1068: 76, 1130: 76, 1309: 76, 2000: 76, 1478: 75, 6770: 75, 1203: 75, 1351: 75, 1278: 75, 4444: 75, 6058: 75, 4575: 75, 2993: 75, 2291: 75, 1480: 74, 3287: 74, 1138: 74, 4554: 74, 1892: 74, 1490: 74, 1829: 74, 2559: 74, 3382: 74, 1534: 74, 1124: 74, 1491: 74, 10048: 74, 2285: 74, 1466: 74, 1291: 74, 2288: 74, 1540: 74, 531: 74, 827: 74, 2641: 74, 1072: 74, 1063: 74, 1836: 74, 1740: 74, 1339: 74, 2216: 73, 2238: 73, 3069: 73, 1451: 73, 3034: 73, 1593: 73, 1316: 73, 1563: 73, 3269: 73, 1332: 73, 1918: 72, 2295: 72, 2634: 72, 1782: 72, 1521: 72, 2149: 72, 1726: 72, 2488: 72, 2290: 72, 19942: 72, 1640: 72, 1582: 72, 39287: 72, 2041: 72, 2412: 72, 1411: 72, 4333: 72, 1643: 72, 2487: 72, 2293: 72, 1141: 71, 2998: 71, 1180: 71, 3820: 71, 1626: 71, 6382: 71, 1338: 71, 1549: 71, 3374: 71, 1308: 71, 2022: 71, 3831: 71, 1624: 71, 1931: 71, 2461: 71, 1334: 71, 2279: 71, 365: 71, 2587: 71, 962: 71, 1502: 71, 2710: 71, 3909: 71, 1998: 71, 3267: 71, 1082: 71, 4597: 70, 858: 70, 1778: 70, 1015: 70, 1423: 70, 1389: 70, 2075: 70, 3274: 70, 649: 70, 1260: 70, 1933: 70, 1606: 70, 2436: 70, 1513: 70, 1698: 70, 2551: 70, 1950: 70, 5085: 70, 2414: 70, 2678: 69, 1514: 69, 1364: 69, 1930: 69, 1971: 69, 1381: 69, 1832: 69, 3014: 69, 1986: 69, 2529: 69, 21151: 69, 1665: 69, 2032: 69, 2785: 69, 2966: 69, 1410: 69, 8505: 69, 961: 69, 1868: 69, 1402: 69, 4529: 68, 1881: 68, 3849: 68, 1135: 68, 1663: 68, 1882: 68, 4100: 68, 1370: 68, 2186: 68, 907: 68, 2147: 68, 2148: 68, 1958: 68, 2740: 68, 2116: 68, 1649: 68, 1565: 68, 2534: 68, 2034: 68, 3516: 68, 3470: 68, 1250: 68, 1919: 68, 1213: 68, 1244: 68, 2386: 67, 723: 67, 1801: 67, 2096: 67, 2951: 67, 2292: 67, 1694: 67, 1440: 67, 3265: 67, 2518: 67, 3225: 67, 1609: 67, 1475: 67, 1742: 67, 1299: 67, 5360: 67, 2542: 67, 1977: 67, 3231: 67, 2410: 67, 2084: 67, 2827: 67, 1329: 67, 2065: 67, 1243: 67, 1675: 67, 2209: 67, 1659: 67, 8342: 67, 2310: 67, 2334: 67, 958: 66, 1488: 66, 2833: 66, 1807: 66, 4283: 66, 2326: 66, 1361: 66, 1938: 66, 14316: 66, 1616: 66, 968: 66, 3077: 66, 5966: 66, 2271: 66, 1286: 66, 2872: 66, 2630: 66, 1858: 66, 1948: 66, 2565: 66, 3124: 66, 1519: 65, 1058: 65, 1388: 65, 2196: 65, 936: 65, 1176: 65, 2387: 65, 1485: 65, 1820: 65, 2580: 65, 1691: 65, 592: 65, 1515: 65, 4505: 65, 1581: 65, 3451: 65, 20237: 65, 1273: 65, 1845: 65, 2599: 65, 4104: 65, 1119: 65, 2045: 65, 1482: 65, 1212: 65, 1997: 65, 1312: 65, 1715: 65, 2953: 65, 10236: 64, 2274: 64, 2975: 64, 1547: 64, 1796: 64, 1856: 64, 1382: 64, 2515: 64, 2257: 64, 2754: 64, 3641: 64, 2615: 64, 1612: 64, 3011: 64, 1588: 64, 2067: 64, 29149: 64, 1912: 64, 2513: 64, 2258: 64, 1724: 64, 2380: 64, 834: 63, 2249: 63, 748: 63, 2142: 63, 2195: 63, 1917: 63, 2110: 63, 2600: 63, 1262: 63, 3608: 63, 9297: 63, 979: 63, 3022: 63, 1687: 63, 2649: 63, 3178: 63, 2981: 63, 2453: 63, 1719: 63, 2399: 63, 2445: 63, 3328: 63, 4438: 63, 27789: 63, 1094: 63, 1736: 63, 2638: 63, 3698: 63, 4350: 63, 1638: 63, 1500: 62, 2961: 62, 3118: 62, 1843: 62, 2365: 62, 1936: 62, 5429: 62, 1877: 62, 3121: 62, 2381: 62, 2030: 62, 3490: 62, 3464: 62, 2193: 62, 1518: 62, 1685: 62, 1957: 62, 1535: 62, 2440: 62, 2253: 62, 1189: 62, 1567: 62, 1975: 62, 2764: 62, 753: 62, 3538: 62, 17503: 62, 1771: 62, 3087: 62, 1923: 62, 1631: 62, 1497: 62, 4500: 62, 1961: 62, 2956: 62, 3992: 62, 1395: 62, 3520: 62, 6574: 61, 2128: 61, 1504: 61, 1252: 61, 2023: 61, 1457: 61, 2665: 61, 851: 61, 635: 61, 3179: 61, 1114: 61, 9644: 61, 1494: 61, 957: 61, 2192: 61, 1822: 61, 1935: 61, 1566: 61, 2555: 61, 1847: 61, 6126: 61, 1756: 61, 2646: 61, 3148: 61, 1916: 61, 2007: 60, 1343: 60, 1603: 60, 4686: 60, 2139: 60, 2226: 60, 1945: 60, 3715: 60, 4039: 60, 497: 60, 1398: 60, 2360: 60, 2662: 60, 4741: 60, 2660: 60, 1481: 60, 4880: 60, 4071: 60, 4678: 60, 1375: 60, 975: 60, 9675: 60, 1886: 60, 2031: 60, 13642: 60, 2082: 60, 974: 60, 2889: 59, 2566: 59, 2081: 59, 2732: 59, 1745: 59, 2704: 59, 1625: 59, 2500: 59, 2787: 59, 3091: 59, 2227: 59, 1383: 59, 1899: 59, 1850: 59, 6097: 59, 2584: 59, 13215: 59, 3794: 59, 2838: 59, 3139: 59, 4101: 59, 1133: 59, 3304: 59, 3112: 59, 1857: 59, 5725: 59, 2112: 59, 4629: 59, 3092: 59, 5338: 59, 1653: 59, 13211: 59, 1431: 59, 696: 58, 3602: 58, 1859: 58, 6074: 58, 835: 58, 2579: 58, 989: 58, 1487: 58, 2095: 58, 2433: 58, 3471: 58, 1256: 58, 2002: 58, 3055: 58, 2076: 58, 3007: 58, 2742: 58, 13121: 58, 2709: 58, 4694: 58, 1697: 58, 14269: 58, 1224: 58, 2674: 58, 4822: 58, 8361: 58, 26869: 58, 14519: 58, 2255: 57, 7102: 57, 22655: 57, 3482: 57, 2589: 57, 2593: 57, 4202: 57, 2272: 57, 2758: 57, 1871: 57, 5048: 57, 4117: 57, 5269: 57, 21476: 57, 1777: 57, 2793: 57, 1627: 57, 2089: 57, 1806: 57, 1805: 57, 2345: 57, 1193: 57, 30411: 57, 2423: 57, 2972: 57, 2841: 57, 1851: 57, 14346: 57, 1618: 57, 2466: 57, 26722: 57, 4540: 56, 6006: 56, 1560: 56, 6324: 56, 2351: 56, 4049: 56, 3595: 56, 3429: 56, 3128: 56, 3381: 56, 1241: 56, 3680: 56, 10358: 56, 888: 56, 1091: 56, 2502: 56, 4991: 56, 1869: 56, 2954: 56, 2821: 56, 1842: 56, 3809: 56, 4569: 56, 2305: 56, 8080: 56, 3867: 56, 3584: 56, 3095: 56, 1906: 56, 1761: 56, 969: 56, 30281: 56, 3379: 56, 2725: 55, 2716: 55, 2536: 55, 2019: 55, 3040: 55, 2120: 55, 1300: 55, 2925: 55, 2173: 55, 4460: 55, 2054: 55, 4031: 55, 2047: 55, 2141: 55, 3920: 55, 2783: 55, 5893: 55, 2385: 55, 2101: 55, 4275: 55, 2938: 55, 1568: 55, 1647: 55, 1790: 55, 4407: 55, 4484: 55, 1926: 55, 1759: 55, 1690: 55, 2457: 55, 2170: 55, 3428: 55, 1527: 55, 27142: 55, 1910: 54, 2164: 54, 2198: 54, 177: 54, 2159: 54, 4093: 54, 2332: 54, 4094: 54, 1849: 54, 3075: 54, 3325: 54, 3356: 54, 2984: 54, 4235: 54, 2863: 54, 2154: 54, 5309: 54, 2679: 54, 4647: 54, 3424: 54, 2921: 54, 1920: 54, 1985: 54, 2526: 54, 2189: 54, 19992: 54, 3169: 54, 2845: 54, 3201: 54, 1349: 54, 7182: 54, 5284: 54, 2480: 54, 1974: 54, 1596: 54, 2088: 54, 1427: 54, 2153: 54, 2391: 54, 1425: 53, 3067: 53, 4618: 53, 3403: 53, 770: 53, 4530: 53, 2044: 53, 1962: 53, 8614: 53, 3931: 53, 2905: 53, 1367: 53, 3039: 53, 1995: 53, 1733: 53, 2677: 53, 2451: 53, 1710: 53, 2337: 53, 1393: 53, 2434: 53, 4036: 53, 4241: 53, 5930: 53, 3694: 53, 2309: 53, 1546: 53, 3242: 53, 2059: 53, 830: 53, 1645: 53, 3286: 53, 1432: 53, 2666: 53, 1791: 53, 3699: 53, 534: 53, 1846: 53, 2739: 53, 3375: 53, 5027: 53, 2200: 53, 3712: 53, 12450: 53, 4372: 52, 2340: 52, 8024: 52, 1283: 52, 2705: 52, 3037: 52, 3748: 52, 4323: 52, 2986: 52, 4582: 52, 2914: 52, 2413: 52, 2214: 52, 97: 52, 1517: 52, 4086: 52, 2092: 52, 3070: 52, 1793: 52, 6592: 52, 7238: 52, 19809: 52, 2895: 52, 1463: 52, 8112: 52, 1969: 52, 2586: 52, 3970: 52, 1121: 52, 3145: 52, 3196: 52, 4731: 52, 3709: 52, 1340: 52, 2483: 52, 2021: 52, 1970: 52, 2790: 52, 2015: 52, 2362: 52, 2773: 52, 9203: 52, 3344: 51, 4770: 51, 4067: 51, 3052: 51, 3158: 51, 3200: 51, 2151: 51, 2802: 51, 3785: 51, 1436: 51, 1335: 51, 1705: 51, 1484: 51, 4964: 51, 6193: 51, 3008: 51, 2389: 51, 3193: 51, 24905: 51, 4870: 51, 2448: 51, 2409: 51, 2012: 51, 811: 51, 1322: 51, 14618: 51, 3349: 51, 1270: 51, 1377: 51, 1855: 51, 1628: 51, 3243: 51, 3837: 51, 4613: 51, 2883: 50, 28446: 50, 2368: 50, 1666: 50, 4284: 50, 2980: 50, 3563: 50, 2077: 50, 3241: 50, 5959: 50, 1575: 50, 3300: 50, 3493: 50, 2298: 50, 39854: 50, 18651: 50, 4783: 50, 2849: 50, 5509: 50, 1709: 50, 2879: 50, 3380: 50, 2287: 50, 3672: 50, 2083: 50, 2965: 50, 3960: 50, 3609: 50, 2100: 50, 2494: 50, 1815: 50, 2544: 50, 2346: 50, 2601: 50, 1674: 50, 3771: 50, 1900: 50, 3097: 50, 2498: 50, 5018: 50, 2507: 50, 1004: 50, 2124: 50, 1333: 50, 6214: 50, 1708: 50, 2321: 49, 2393: 49, 1909: 49, 5783: 49, 5541: 49, 2156: 49, 2482: 49, 3649: 49, 8215: 49, 2517: 49, 1173: 49, 5135: 49, 3315: 49, 2311: 49, 2874: 49, 2013: 49, 1602: 49, 2854: 49, 2944: 49, 1271: 49, 2324: 49, 3240: 49, 10865: 49, 2499: 49, 2796: 49, 2250: 49, 6947: 49, 4316: 49, 4503: 49, 3312: 49, 2233: 49, 4227: 49, 3015: 49, 4125: 49, 6473: 49, 2572: 49, 3423: 49, 4090: 49, 2591: 49, 9067: 49, 2920: 49, 4536: 49, 2428: 49, 5681: 49, 2446: 49, 6714: 49, 2025: 49, 4267: 49, 3402: 49, 3054: 49, 2359: 49, 2462: 49, 10035: 49, 2085: 49, 2165: 48, 3113: 48, 3401: 48, 2549: 48, 5009: 48, 3795: 48, 3161: 48, 4798: 48, 3141: 48, 1680: 48, 1800: 48, 4129: 48, 3683: 48, 3502: 48, 3210: 48, 3955: 48, 2109: 48, 2700: 48, 2

In [ ]:
# tokenizer_name = "LGAI-EXAONE/K-EXAONE-236B-A23B"

data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/data.csv"
max_token_length = 512
batch_size_train = 64
num_workers = 4
batch_size_val = 64
batch_size_test = 64
val_num_workers = 4
start_idx = 1
end_idx = 53
padding_idx = 0
unk_idx = 3
seed = 42

In [ ]:
class LoadersLGEXA236():
    def __init__(
            self,
            data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/data.csv",
            max_token_length = 512,
            batch_size_train = 8,
            num_workers = 4,
            batch_size_val = 4,
            batch_size_test = 4,
            val_num_workers = 4,
            start_idx = 64100, 
            end_idx = 1, 
            padding_idx = 0, 
            unk_idx = 2,
            seed = 42,
    ):
        self.start_idx = start_idx
        self.end_idx = end_idx
        self.padding_idx = padding_idx
        self.unk_idx = unk_idx

        # 1) 데이터셋 로드
        dataset = load_dataset("csv", data_files=data_path)['train']
        # AI hub 한국어-영어 번역(병렬) 말뭉치 데이터셋
        # kor, en, cat 3개의 칼럼으로 구성

        # 2) 카테고리 컬럼의 고유 클래스 찾아서 ClassLabel 객체 생성
        unique_classes = dataset.unique('cat')  
        # 'cat' 열에 문장 분류 
        # 0: 구어체
        # 1: 대화체
        # 2: 문어체_뉴스
        # 3: 문어체_한국문화
        # 4: 문어체_조례
        # 5: 문어체_지자체웹사이트

        print(f"==>> unique_classes: {unique_classes}")
        class_label = ClassLabel(names=unique_classes)

        # 3) 기존 컬럼 타입 변경 (캐스팅)
        dataset = dataset.cast_column('cat', class_label)

        # 4) stratify_by_column으로 분할
        train_validtest = dataset.train_test_split(test_size=0.2, seed=seed, stratify_by_column='cat')
        valid_test = train_validtest['test'].train_test_split(test_size=0.1, seed=seed, stratify_by_column='cat')

        dataset_dict = DatasetDict({
            'train': train_validtest['train'],
            'validation': valid_test['train'],
            'test': valid_test['test']
        })

        # print(dataset_dict)

        NUM_CPU = multiprocessing.cpu_count()
        # print(f"==>> NUM_CPU: {NUM_CPU}")

        # self.tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-ko-en")
        # @@@ 점포, 만료 등의 단어가 <unk>인 문제 발견 => 다른 토크나이저 사용?
        self.tokenizer = AutoTokenizer.from_pretrained("LGAI-EXAONE/K-EXAONE-236B-A23B")

        print(self.tokenizer.all_special_ids)
        print(self.tokenizer.all_special_tokens)

        print(f"==>> self.tokenizer.model_max_length: {self.tokenizer.model_max_length}")

        print(f"==>> len(self.tokenizer): {len(self.tokenizer)}")

        self.max_token_length = min(max_token_length, self.tokenizer.model_max_length)
        print(f"==>> self.max_token_length: {self.max_token_length}")

        # partial을 이용해 tokenizer, max_token_length 인자 고정
        cetf = partial(convert_examples_to_features, tokenizer=self.tokenizer, max_token_length=self.max_token_length)
        # @@@ convert_examples_to_features함수에서 examples가 첫번쨰 인자가 아니면 
        # @@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서 
        # @@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러 발생

        self.datasets = dataset_dict.map(
                                cetf,
                                # lambda examples: convert_examples_to_features(examples, tokenizer=self.tokenizer, max_token_length=self.max_token_length),
                                batched=True,
                                # 원 데이터 'en', 'kor', 'cat' 등의 칼럼을 지우려면
                                # remove_columns 인자 사용
                                # remove_columns=dataset_dict["train"].column_names,
                                num_proc=NUM_CPU)

        print(f"==>> self.datasets: {self.datasets}")

        self.train_set = self.datasets['train']
        self.val_set = self.datasets['validation']
        self.test_set = self.datasets['test']

        c_fn = partial(collate_fn, start_idx=self.start_idx, end_idx=self.end_idx, padding_idx=self.padding_idx, unk_idx=self.unk_idx)

        self.loader_train = DataLoader(self.train_set, batch_size=batch_size_train, collate_fn=c_fn, shuffle=True, num_workers=num_workers, pin_memory=True)
        # 학습시에만 shuffle=True
        self.loader_val = DataLoader(self.val_set, batch_size=batch_size_val, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)
        self.loader_test = DataLoader(self.test_set, batch_size=batch_size_test, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)

# def convert_examples_to_features(tokenizer, max_token_length, examples):
# @@@@@@@@@ examples가 첫번쨰 인자가 아니면 
# @@@@@@@@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서
# @@@@@@@@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러가 발생한다
def convert_examples_to_features(examples, tokenizer, max_token_length):
    model_inputs = tokenizer(examples['kor'],
                             text_target=examples['en'],
                             max_length=max_token_length, truncation=True)
    # 여기서 첫번째 인자와 두번째 인자의 순서를 바꾸면 한영 번역 대신 영한 번역용으로 인풋과 타겟이 토큰화된다
    return model_inputs


def collate_fn(batch, start_idx, end_idx, padding_idx, unk_idx):
    # print('Original:\n', batch)
    # print("".center(50, "-"))
    # batch는 [{'kor':..., 'en':..., 'cat':숫자, 'input_ids':[...], 'attention_mask':[1, ...], 'labels': [...]}, ...] 형태
    
    # keys = batch[0].keys()
    keys = ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels']
    # print(f"==>> keys: {keys}")
    # print("".center(50, "-"))
    
    # new_batch = {k:[] for k in keys}
    # new_batch['decoder_inputs'] = []
    
    # for b in batch:
    #     for k,v in b.items():
    #         if k == 'input_ids' or k == 'attention_mask':
    #             new_batch[k].append(torch.LongTensor(v))
    #         elif k == 'labels':
    #             new_batch[k].append(torch.LongTensor(v))
    #             new_batch['decoder_inputs'].append(torch.LongTensor([65001] + v[:-1]))
    #         else:
    #             new_batch[k].append(v)

    # key값별로 value 다 모으기
    new_batch = {k:[b[k] for b in batch] for k in keys}

    # list들 LongTensor로 변환
    new_batch['decoder_inputs'] = [torch.LongTensor([start_idx] + label[:-1]) for label in new_batch['labels']]
    # print(f"==>> new_batch['decoder_inputs']: {new_batch['decoder_inputs']}")
    new_batch['input_ids'] = [torch.LongTensor(inp) for inp in new_batch['input_ids']]
    new_batch['labels'] = [torch.LongTensor(label) for label in new_batch['labels']]
    new_batch['attention_mask'] = [torch.LongTensor(mask) for mask in new_batch['attention_mask']]

    new_batch['ntokens'] = sum([l.numel() for l in new_batch['labels']])

    # decoder input의 attention mask 생성
    new_batch['decoder_mask'] = [torch.ones_like(d_inp, dtype=torch.long) for d_inp in new_batch['decoder_inputs']]


    # 각 input과 target 텐서를 패딩
    padded_inputs = pad_sequence(new_batch['input_ids'], batch_first=True, padding_value=padding_idx)
    new_batch['input_ids'] = padded_inputs
    padded_decoder_inputs = pad_sequence(new_batch['decoder_inputs'], batch_first=True, padding_value=padding_idx)
    new_batch['decoder_inputs'] = padded_decoder_inputs
    padded_targets = pad_sequence(new_batch['labels'], batch_first=True, padding_value=padding_idx)
    new_batch['labels'] = padded_targets

    # attention 마스크는 패딩(padding_idx) 대신 False(0)을 입력
    padded_masks = pad_sequence(new_batch['attention_mask'], batch_first=True, padding_value=0)
    new_batch['attention_mask'] = padded_masks

    padded_d_masks = pad_sequence(new_batch['decoder_mask'], batch_first=True, padding_value=0)
    new_batch['decoder_mask'] = padded_d_masks
    
    return new_batch

In [ ]:
loaders = LoadersLGEXA236(
    data_path=data_path,
    max_token_length=max_token_length,
    batch_size_train=batch_size_train,
    num_workers=num_workers,
    batch_size_val=batch_size_val,
    batch_size_test=batch_size_test,
    val_num_workers=val_num_workers,
    start_idx=start_idx,
    end_idx=end_idx,
    padding_idx=padding_idx,
    unk_idx=unk_idx,
    seed=seed,
)

==>> unique_classes: [2, 4, 1, 0, 3, 5]
[1, 53, 3, 0]
['[BOS]', '<|endofturn|>', '[UNK]', '[PAD]']
==>> self.tokenizer.model_max_length: 1000000000000000019884624838656
==>> len(self.tokenizer): 153600
==>> self.max_token_length: 512
==>> self.datasets: DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1281934
    })
    validation: Dataset({
        features: ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 288435
    })
    test: Dataset({
        features: ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 32049
    })
})

In [ ]:
print(f"==>> unk_idx: {unk_idx}")

input_total = Counter([])
target_total = Counter([])
# total

num_batches_train = len(loaders.loader_train)

for step, batch in tqdm(
    enumerate(loaders.loader_train),
    total=num_batches_train,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total += input_count
    target_total += target_count

    # if step == 10:
    #     break

print(f"==>> input_total: {input_total}")
print(f"==>> target_total: {target_total}")
print(f"==>> input_total[unk_idx]: {input_total[unk_idx]}")
print(f"==>> target_total[unk_idx]: {target_total[unk_idx]}")


input_total_val = Counter([])
target_total_val = Counter([])
# total

num_batches_val = len(loaders.loader_val)

for step, batch in tqdm(
    enumerate(loaders.loader_val),
    total=num_batches_val,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_val += input_count
    target_total_val += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_val: {input_total_val}")
print(f"==>> target_total_val: {target_total_val}")
print(f"==>> input_total_val[unk_idx]: {input_total_val[unk_idx]}")
print(f"==>> target_total_val[unk_idx]: {target_total_val[unk_idx]}")


input_total_test = Counter([])
target_total_test = Counter([])
# total

num_batches_test = len(loaders.loader_test)

for step, batch in tqdm(
    enumerate(loaders.loader_test),
    total=num_batches_test,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_test += input_count
    target_total_test += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_test: {input_total_test}")
print(f"==>> target_total_test: {target_total_test}")
print(f"==>> input_total_test[unk_idx]: {input_total_test[unk_idx]}")
print(f"==>> target_total_test[unk_idx]: {target_total_test[unk_idx]}")

==>> unk_idx: 3

100%|██████████| 20031/20031 [02:07<00:00, 157.36it/s]

==>> input_total: Counter({0: 44664829, 375: 1252651, 582: 607045, 373: 430630, 378: 321639, 377: 277422, 634: 271210, 379: 241685, 905: 193872, 730: 193758, 696: 164609, 2373: 149445, 657: 136885, 380: 133980, 732: 126080, 4605: 125672, 1548: 114237, 382: 111850, 1075: 106630, 41728: 101319, 2376: 98249, 381: 96139, 1488: 90088, 715: 87677, 2030: 83403, 17005: 82821, 13456: 81352, 720: 80183, 383: 77830, 386: 76196, 385: 72259, 384: 70902, 858: 70308, 999: 69766, 369: 68060, 392: 66040, 643: 64209, 125365: 63976, 798: 62055, 1222: 61104, 79694: 55140, 48199: 49766, 14178: 49346, 853: 49174, 370: 47453, 2171: 44923, 2751: 42929, 2425: 42511, 18420: 40687, 125371: 40361, 10348: 39303, 16524: 38431, 1043: 36100, 1058: 35534, 125373: 34281, 698: 32750, 40379: 31476, 954: 30146, 816: 30115, 125366: 29572, 2517: 29454, 942: 28800, 1050: 28759, 1823: 28528, 650: 27024, 125372: 26941, 125399: 26577, 1965: 25779, 987: 25468, 764: 24649, 722: 24383, 800: 23934, 125383: 23904, 765: 22872, 902: 22797, 1081: 22175, 125379: 22134, 1877: 21974, 712: 21852, 22226: 21848, 1126: 21607, 125625: 21407, 125515: 21121, 1522: 20909, 855: 20887, 125995: 20856, 1818: 20559, 1210: 20553, 9099: 20394, 823: 20358, 125438: 20351, 125445: 20266, 1042: 20264, 125497: 20107, 916: 20101, 721: 19700, 887: 19551, 125422: 19403, 838: 19173, 9583: 19154, 85080: 18501, 3157: 18266, 1255: 18263, 3321: 18111, 941: 18068, 125392: 18065, 1367: 18049, 125377: 17956, 129018: 17945, 125929: 17875, 799: 17775, 37891: 17669, 125387: 17667, 4560: 17643, 1416: 17583, 10996: 17303, 1029: 17064, 4978: 16763, 5623: 16656, 125745: 16488, 1146: 16473, 1080: 16457, 1600: 16369, 1094: 16267, 125402: 16193, 22773: 16104, 2870: 16092, 41281: 16002, 125391: 15804, 125400: 15784, 2878: 15691, 1979: 15686, 125368: 15601, 1490: 15466, 2597: 15260, 125594: 15084, 1437: 15047, 961: 15043, 15169: 14957, 4022: 14831, 1159: 14718, 1325: 14695, 27506: 14612, 977: 14431, 1810: 14406, 4264: 14361, 1332: 14335, 1018: 14314, 125512: 14203, 125382: 14182, 1023: 14177, 3051: 14102, 3376: 14086, 789: 13847, 366: 13833, 1495: 13808, 2736: 13691, 1856: 13674, 1053: 13655, 1002: 13625, 126270: 13469, 2879: 13447, 11326: 13412, 2888: 13390, 30885: 13325, 1286: 13279, 1452: 13219, 3401: 13136, 128877: 12972, 125412: 12965, 125448: 12907, 1060: 12747, 374: 12743, 16559: 12686, 5153: 12528, 1553: 12516, 2827: 12512, 760: 12505, 1430: 12497, 41655: 12479, 3637: 12453, 1595: 12452, 139505: 12439, 4385: 12399, 125369: 12266, 1280: 12242, 964: 12239, 50747: 12195, 834: 12120, 2626: 12105, 2424: 12067, 1326: 12003, 125413: 11858, 1254: 11835, 4415: 11806, 1271: 11798, 26111: 11794, 2318: 11782, 1645: 11723, 975: 11713, 53641: 11678, 125386: 11638, 6734: 11486, 6697: 11360, 125666: 11352, 28612: 11239, 125433: 11135, 955: 11124, 901: 11107, 1780: 11083, 1794: 11070, 1336: 11036, 1331: 11035, 1774: 10998, 740: 10900, 128614: 10881, 2126: 10870, 1597: 10858, 3216: 10826, 6015: 10735, 1617: 10664, 30761: 10651, 1369: 10599, 1084: 10591, 2491: 10500, 1031: 10431, 9768: 10430, 15913: 10393, 1420: 10351, 1225: 10329, 85390: 10299, 8052: 10290, 125537: 10278, 830: 10208, 1740: 10191, 125427: 10103, 3685: 10028, 28726: 10027, 2534: 10026, 1105: 9981, 1985: 9868, 962: 9845, 125451: 9828, 15585: 9821, 1216: 9788, 1047: 9782, 1658: 9775, 5457: 9756, 17324: 9733, 125471: 9705, 14010: 9685, 2645: 9639, 869: 9564, 4559: 9556, 7360: 9551, 126891: 9535, 43202: 9534, 1921: 9500, 125742: 9487, 125437: 9430, 2820: 9423, 4349: 9414, 5414: 9405, 54689: 9343, 1137: 9315, 2448: 9313, 844: 9310, 3428: 9295, 125468: 9254, 6332: 9250, 125376: 9223, 1413: 9219, 3172: 9180, 1881: 9156, 2781: 9144, 14708: 9067, 38045: 9043, 2927: 9037, 2252: 9000, 28498: 8957, 924: 8955, 10538: 8950, 125380: 8936, 1130: 8919, 1353: 8915, 1371: 8906, 691: 8883, 4373: 8881, 868: 8871, 125396: 8851, 4484: 8807, 769: 8801, 125493: 8793, 24040: 8789, 1698: 8735, 1235: 8659, 2022: 8648, 2329: 8636, 1647: 8572, 126119: 8569, 6487: 8564, 4806: 8526, 2575: 8482, 4490: 8357, 125457: 8353, 127123: 8284, 125397: 8270, 4169: 8269, 3163: 8256, 1546: 8251, 125415: 8243, 1629: 8242, 1052: 8237, 21212: 8236, 8454: 8216, 2733: 8181, 38069: 8175, 1092: 8168, 35604: 8164, 2886: 8154, 125425: 8147, 5086: 8132, 3903: 8115, 125406: 8109, 125577: 8052, 1323: 8023, 3974: 8019, 3718: 8006, 6327: 7991, 1682: 7962, 125375: 7962, 125384: 7952, 125398: 7925, 5275: 7918, 1644: 7911, 125385: 7881, 1113: 7866, 125446: 7863, 4854: 7845, 1615: 7844, 69893: 7811, 8291: 7802, 16519: 7787, 125467: 7757, 5299: 7750, 22692: 7746, 126934: 7708, 2299: 7700, 3596: 7699, 126171: 7669, 2437: 7662, 1821: 7658, 2092: 7654, 25082: 7650, 9429: 7641, 992: 7636, 126475: 7621, 31882: 7598, 5159: 7586, 1411: 7585, 4982: 7585, 2632: 7584, 125606: 7540, 21701: 7535, 4024: 7534, 3672: 7531, 1526: 7505, 733: 7501, 125430: 7499, 22610: 7497, 125654: 7494, 3788: 7494, 713: 7492, 2257: 7461, 1008: 7430, 8789: 7423, 1182: 7404, 1244: 7370, 7572: 7357, 30695: 7353, 1775: 7350, 2739: 7343, 8713: 7340, 125796: 7339, 4100: 7330, 1376: 7297, 4650: 7296, 25755: 7274, 125423: 7262, 125444: 7259, 775: 7245, 7257: 7244, 1811: 7241, 7087: 7235, 125747: 7234, 3235: 7217, 15536: 7215, 2618: 7196, 1509: 7194, 2799: 7183, 3950: 7163, 6589: 7157, 6026: 7155, 125404: 7148, 1175: 7148, 4003: 7106, 125481: 7104, 4504: 7091, 3492: 7084, 931: 7083, 6951: 7078, 1858: 7059, 1154: 7051, 126358: 7048, 1931: 7041, 5569: 7039, 125499: 7018, 1202: 7006, 3570: 6969, 56867: 6950, 125588: 6948, 125478: 6925, 704: 6869, 13147: 6844, 128160: 6837, 125611: 6815, 2705: 6801, 5985: 6795, 948: 6794, 1201: 6756, 3626: 6743, 5422: 6738, 125505: 6728, 13452: 6726, 3257: 6717, 694: 6717, 2175: 6704, 7858: 6703, 32918: 6693, 127062: 6685, 2588: 6675, 6296: 6675, 780: 6673, 125613: 6668, 126924: 6668, 1560: 6651, 3754: 6623, 5547: 6602, 6582: 6593, 1349: 6587, 7517: 6582, 2051: 6575, 1679: 6573, 8722: 6552, 1799: 6548, 125500: 6548, 129933: 6537, 125677: 6532, 1934: 6525, 129685: 6517, 2904: 6515, 5720: 6512, 2453: 6504, 127412: 6503, 125572: 6495, 134593: 6492, 12418: 6471, 1200: 6459, 3539: 6454, 1868: 6431, 10724: 6428, 125362: 6412, 2379: 6410, 125417: 6403, 12621: 6380, 1415: 6377, 3196: 6375, 15418: 6363, 3118: 6360, 8536: 6354, 125703: 6351, 1728: 6343, 125431: 6339, 2472: 6329, 4817: 6318, 6033: 6278, 125420: 6275, 1673: 6264, 125603: 6260, 3550: 6252, 125408: 6228, 1859: 6227, 1282: 6226, 8397: 6225, 1147: 6224, 1719: 6205, 125465: 6197, 2785: 6195, 2110: 6192, 10739: 6190, 2553: 6189, 125755: 6182, 4986: 6176, 2266: 6175, 125645: 6158, 2372: 6151, 1907: 6139, 3090: 6139, 3100: 6128, 3050: 6128, 22241: 6122, 125489: 6117, 3347: 6115, 1051: 6109, 4872: 6076, 1910: 6072, 5256: 6058, 125746: 6056, 2885: 6051, 4949: 6051, 7686: 6051, 125407: 6047, 125453: 6046, 1601: 6042, 3893: 6041, 125424: 6039, 8939: 6009, 47073: 5998, 1469: 5997, 125626: 5995, 125459: 5978, 3239: 5976, 4477: 5973, 125411: 5971, 5639: 5968, 915: 5967, 2211: 5966, 6747: 5957, 4880: 5951, 1360: 5951, 5837: 5941, 848: 5939, 125542: 5922, 7956: 5920, 6618: 5905, 6670: 5902, 125492: 5889, 6521: 5887, 125549: 5887, 1803: 5884, 9598: 5873, 2351: 5858, 1302: 5840, 4408: 5832, 127284: 5830, 14976: 5825, 2247: 5824, 1418: 5821, 1022: 5819, 2086: 5818, 5718: 5801, 6948: 5792, 1278: 5791, 3223: 5790, 4302: 5778, 5292: 5774, 125405: 5771, 3758: 5762, 15282: 5761, 125871: 5758, 5865: 5752, 4824: 5747, 10079: 5734, 5010: 5724, 1384: 5721, 3446: 5719, 6507: 5715, 126078: 5710, 1400: 5704, 3399: 5695, 125675: 5695, 125435: 5686, 1922: 5678, 3365: 5669, 126557: 5660, 5266: 5657, 125806: 5655, 3129: 5654, 2326: 5653, 4677: 5652, 125484: 5648, 33623: 5645, 125609: 5644, 1246: 5636, 7245: 5620, 14954: 5605, 3745: 5603, 1580: 5601, 4576: 5594, 3705: 5585, 125496: 5584, 11240: 5568, 1619: 5567, 1337: 5561, 8584: 5550, 896: 5534, 2042: 5532, 125507: 5522, 125410: 5516, 125426: 5515, 2502: 5514, 125960: 5513, 59985: 5513, 4463: 5510, 125501: 5507, 2628: 5506, 125460: 5500, 37728: 5496, 3885: 5496, 3336: 5491, 4308: 5491, 125393: 5488, 2431: 5485, 1015: 5476, 5304: 5455, 126422: 5454, 126023: 5446, 125760: 5444, 34593: 5436, 126724: 5435, 3713: 5431, 4762: 5426, 15220: 5415, 125557: 5396, 1710: 5396, 126007: 5378, 126745: 5366, 37817: 5357, 125615: 5347, 27574: 5344, 12730: 5343, 126042: 5342, 5930: 5340, 125418: 5330, 1562: 5316, 125464: 5314, 1229: 5312, 125726: 5305, 4767: 5304, 2419: 5301, 12230: 5300, 6138: 5295, 125463: 5294, 36090: 5292, 1124: 5284, 129808: 5284, 3755: 5282, 989: 5279, 126551: 5271, 3523: 5253, 2263: 5247, 1727: 5239, 125390: 5233, 1067: 5223, 773: 5220, 1451: 5219, 9504: 5209, 8023: 5200, 1466: 5191, 2802: 5189, 1590: 5186, 125638: 5180, 125551: 5178, 3387: 5175, 125709: 5171, 1694: 5154, 125416: 5151, 11175: 5148, 10503: 5148, 2843: 5147, 6893: 5143, 125363: 5141, 125547: 5139, 4232: 5130, 881: 5128, 3449: 5126, 6698: 5124, 1257: 5120, 125579: 5115, 2434: 5114, 20271: 5112, 135782: 5109, 6696: 5101, 1368: 5094, 10018: 5091, 3187: 5086, 1949: 5084, 18101: 5083, 3327: 5080, 125530: 5078, 125486: 5077, 3027: 5076, 3325: 5076, 9791: 5073, 125480: 5067, 846: 5066, 9808: 5066, 5833: 5064, 1541: 5054, 5135: 5043, 2469: 5024, 6453: 5021, 7215: 5007, 2264: 4995, 36427: 4991, 125832: 4976, 1744: 4971, 3778: 4964, 2401: 4948, 125652: 4940, 56415: 4939, 125470: 4933, 125586: 4931, 2447: 4928, 5359: 4919, 5149: 4908, 126125: 4900, 1352: 4897, 126383: 4887, 1299: 4884, 2583: 4883, 9858: 4878, 1212: 4874, 1976: 4864, 4648: 4862, 13908: 4860, 11703: 4856, 9234: 4852, 125619: 4844, 1990: 4838, 3930: 4833, 3460: 4824, 5336: 4821, 3053: 4815, 50294: 4813, 126080: 4813, 4850: 4811, 1465: 4811, 1956: 4806, 4996: 4804, 4532: 4799, 125636: 4799, 9177: 4774, 6245: 4768, 1264: 4762, 3670: 4762, 126196: 4759, 1030: 4756, 1157: 4755, 4840: 4753, 4954: 4749, 1142: 4746, 125454: 4742, 1634: 4741, 8851: 4739, 1938: 4719, 1987: 4710, 3231: 4708, 5445: 4690, 8292: 4688, 2718: 4676, 1951: 4672, 5954: 4667, 4289: 4667, 125707: 4664, 125531: 4663, 806: 4660, 3728: 4651, 10443: 4642, 10395: 4641, 6600: 4638, 12527: 4630, 126946: 4628, 17200: 4622, 7059: 4618, 1125: 4618, 3771: 4611, 125541: 4605, 970: 4605, 130809: 4600, 125916: 4599, 5838: 4596, 1763: 4592, 5506: 4590, 3519: 4589, 28675: 4582, 2131: 4582, 8254: 4578, 125370: 4573, 2662: 4568, 5371: 4562, 126974: 4561, 3916: 4561, 13076: 4559, 125409: 4550, 1588: 4547, 1841: 4544, 1139: 4537, 3576: 4535, 125564: 4535, 3971: 4532, 1523: 4531, 7135: 4529, 6797: 4527, 135006: 4523, 126345: 4515, 6912: 4515, 3358: 4514, 2041: 4512, 4177: 4511, 125842: 4505, 125429: 4502, 126970: 4495, 8760: 4495, 5876: 4477, 9496: 4475, 12367: 4474, 7084: 4469, 1618: 4468, 8923: 4466, 12100: 4463, 130402: 4462, 126527: 4461, 125364: 4458, 1531: 4458, 1952: 4454, 3696: 4452, 1955: 4451, 1736: 4450, 1822: 4449, 19890: 4447, 2210: 4440, 1208: 4434, 6610: 4426, 125629: 4417, 127124: 4417, 2088: 4415, 5443: 4413, 1556: 4411, 125529: 4409, 2134: 4409, 130102: 4408, 18093: 4404, 7457: 4403, 1862: 4403, 9384: 4395, 7952: 4389, 16596: 4388, 1565: 4385, 1172: 4383, 27390: 4383, 125644: 4383, 10313: 4381, 7773: 4374, 2939: 4366, 14547: 4365, 4400: 4362, 125401: 4357, 3481: 4351, 125502: 4349, 8235: 4340, 127378: 4334, 3764: 4332, 2540: 4332, 125434: 4328, 27484: 4320, 2690: 4315, 125543: 4303, 126088: 4298, 33377: 4298, 5675: 4297, 1667: 4297, 2876: 4289, 5601: 4287, 1983: 4285, 9853: 4284, 5717: 4282, 1387: 4281, 3063: 4281, 61419: 4280, 125516: 4276, 32784: 4272, 2625: 4267, 125443: 4266, 1578: 4264, 52132: 4262, 1846: 4261, 1726: 4261, 7751: 4258, 125736: 4257, 125534: 4256, 1654: 4254, 125639: 4253, 2289: 4249, 1898: 4246, 5577: 4241, 1587: 4240, 2793: 4233, 1151: 4229, 125987: 4227, 4125: 4224, 125646: 4218, 125367: 4213, 2710: 4210, 6031: 4208, 125839: 4206, 66582: 4203, 8792: 4202, 125436: 4194, 125562: 4193, 9350: 4192, 63535: 4192, 7924: 4190, 4649: 4184, 13311: 4181, 7660: 4180, 125698: 4174, 1106: 4172, 3701: 4171, 5780: 4170, 1504: 4169, 2775: 4167, 6318: 4165, 4533: 4163, 125540: 4161, 3656: 4160, 2158: 4157, 12080: 4145, 126228: 4142, 1296: 4141, 3830: 4139, 33861: 4135, 125394: 4132, 9997: 4123, 5480: 4123, 126214: 4119, 130110: 4108, 125498: 4107, 125447: 4101, 2129: 4092, 6738: 4091, 125907: 4086, 21715: 4081, 125526: 4081, 6105: 4080, 1582: 4080, 125601: 4073, 7626: 4069, 2613: 4063, 29015: 4055, 2430: 4051, 10572: 4044, 1873: 4043, 5568: 4036, 7639: 4035, 1899: 4029, 6329: 4028, 11989: 4022, 3083: 4020, 3252: 4020, 8990: 4017, 1061: 4016, 1813: 4015, 23356: 4013, 127585: 4013, 7369: 4006, 26331: 4004, 3008: 4002, 926: 3996, 5805: 3996, 137325: 3992, 10701: 3991, 4659: 3988, 6908: 3988, 3483: 3988, 125689: 3988, 3892: 3986, 5998: 3981, 8357: 3979, 126144: 3976, 127867: 3974, 3317: 3973, 125614: 3970, 7299: 3969, 3091: 3967, 5731: 3955, 3253: 3950, 125456: 3949, 34284: 3944, 11090: 3942, 1721: 3941, 1897: 3939, 7632: 3931, 9239: 3930, 126062: 3927, 5776: 3926, 2560: 3924, 125942: 3911, 27350: 3900, 9906: 3900, 2104: 3900, 125825: 3899, 72863: 3898, 3331: 3897, 2470: 3896, 125374: 3896, 2361: 3892, 5204: 3886, 4394: 3885, 126984: 3885, 1398: 3883, 126605: 3883, 11006: 3883, 1689: 3881, 31172: 3880, 126118: 3879, 4130: 3879, 9952: 3878, 6279: 3877, 125532: 3868, 125441: 3868, 3108: 3867, 5552: 3865, 6135: 3855, 53387: 3854, 5465: 3850, 126200: 3849, 1564: 3846, 125589: 3845, 4679: 3845, 6003: 3845, 4516: 3844, 125681: 3834, 6674: 3825, 13625: 3822, 126357: 3819, 126102: 3818, 1234: 3817, 6854: 3817, 125599: 3808, 2764: 3805, 11073: 3804, 9759: 3803, 9811: 3802, 2327: 3799, 42914: 3797, 1339: 3796, 7285: 3785, 5434: 3783, 1637: 3779, 11121: 3778, 19730: 3774, 44065: 3767, 125880: 3765, 6490: 3765, 125750: 3761, 1944: 3756, 1156: 3747, 20515: 3747, 6226: 3740, 2666: 3740, 54417: 3732, 3396: 3731, 11137: 3730, 6539: 3729, 2485: 3726, 4558: 3725, 3753: 3724, 126029: 3724, 125712: 3709, 9898: 3706, 1756: 3700, 125940: 3696, 126361: 3695, 8405: 3692, 2029: 3690, 1374: 3689, 6843: 3689, 125883: 3688, 6810: 3681, 1356: 3681, 38534: 3680, 1747: 3679, 5210: 3679, 125568: 3678, 3071: 3674, 8171: 3667, 125550: 3664, 7111: 3657, 9365: 3656, 10326: 3652, 6101: 3651, 125581: 3651, 5659: 3648, 126929: 3646, 7482: 3646, 5213: 3642, 125587: 3641, 6660: 3640, 2139: 3638, 4669: 3637, 130078: 3637, 125583: 3636, 12466: 3633, 125965: 3629, 5575: 3627, 1110: 3626, 5821: 3626, 6783: 3625, 4866: 3625, 17297: 3620, 127330: 3619, 3545: 3616, 125660: 3610, 126273: 3609, 2055: 3607, 127909: 3600, 125947: 3600, 13613: 3597, 15001: 3594, 1183: 3586, 4830: 3585, 10491: 3585, 4503: 3575, 21046: 3573, 7216: 3570, 3101: 3567, 5019: 3566, 125490: 3565, 8015: 3562, 1880: 3560, 125761: 3559, 8296: 3557, 10021: 3555, 7820: 3551, 4630: 3550, 1485: 3548, 9209: 3545, 4526: 3539, 27359: 3539, 126026: 3538, 8065: 3536, 126668: 3535, 1936: 3534, 1144: 3533, 26450: 3533, 17728: 3527, 4591: 3524, 1903: 3518, 33373: 3518, 129170: 3512, 7630: 3512, 125565: 3512, 125378: 3511, 5415: 3509, 4747: 3507, 4985: 3507, 9019: 3505, 126221: 3504, 4857: 3503, 8551: 3502, 126031: 3499, 9060: 3497, 4078: 3496, 3833: 3496, 126645: 3494, 9386: 3493, 3996: 3491, 6066: 3489, 125817: 3488, 13432: 3487, 8040: 3484, 11856: 3479, 7419: 3473, 11316: 3471, 18407: 3470, 125428: 3462, 11685: 3461, 1869: 3461, 6401: 3456, 54065: 3456, 5830: 3455, 4998: 3446, 126302: 3442, 9757: 3441, 7121: 3440, 4809: 3440, 32536: 3439, 127033: 3439, 1770: 3437, 34445: 3436, 125694: 3434, 29082: 3433, 27846: 3432, 1867: 3423, 77094: 3423, 132644: 3421, 12452: 3419, 14519: 3416, 7317: 3412, 125528: 3404, 126286: 3400, 826: 3398, 3164: 3396, 129706: 3395, 12072: 3394, 140298: 3390, 3644: 3390, 10084: 3387, 125683: 3382, 5653: 3381, 126074: 3379, 4703: 3379, 10921: 3377, 3924: 3371, 5610: 3368, 125816: 3364, 101: 3364, 9293: 3361, 128147: 3360, 37946: 3355, 8877: 3353, 125765: 3352, 6588: 3352, 2325: 3349, 125944: 3348, 9642: 3348, 4937: 3347, 4288: 3342, 3504: 3335, 125649: 3334, 125789: 3334, 127466: 3332, 128523: 3330, 13419: 3330, 125833: 3329, 126321: 3327, 12025: 3326, 6037: 3322, 11720: 3320, 4344: 3319, 125879: 3314, 14912: 3312, 3864: 3309, 125730: 3309, 4208: 3308, 7747: 3308, 5424: 3307, 5553: 3305, 3693: 3305, 29042: 3303, 1221: 3302, 132035: 3299, 5788: 3297, 125743: 3297, 3276: 3292, 32046: 3291, 31747: 3290, 135100: 3287, 5355: 3284, 13383: 3284, 2938: 3284, 2316: 3281, 138154: 3277, 1510: 3276, 4088: 3276, 126161: 3276, 876: 3275, 2068: 3274, 8726: 3272, 4510: 3272, 7374: 3272, 3093: 3271, 12103: 3271, 125474: 3269, 3882: 3265, 126932: 3265, 22356: 3263, 3117: 3263, 126610: 3262, 4084: 3261, 125627: 3261, 125682: 3260, 125807: 3255, 5757: 3254, 438: 3253, 10325: 3251, 2703: 3250, 6264: 3247, 6733: 3246, 893: 3244, 7489: 3239, 32607: 3237, 21231: 3236, 1572: 3236, 1107: 3231, 3867: 3231, 2207: 3227, 10112: 3227, 785: 3226, 13554: 3226, 21154: 3223, 6720: 3223, 18269: 3222, 126205: 3219, 9472: 3219, 3198: 3218, 3060: 3217, 125558: 3217, 125494: 3217, 125705: 3216, 28811: 3213, 15052: 3212, 1472: 3210, 8259: 3208, 125776: 3208, 42864: 3207, 2356: 3207, 125791: 3205, 2805: 3204, 126602: 3202, 8800: 3200, 4028: 3199, 10551: 3199, 2230: 3199, 5255: 3195, 5806: 3193, 64101: 3190, 125822: 3190, 6410: 3188, 125924: 3188, 126534: 3186, 3662: 3181, 125803: 3180, 6433: 3180, 6784: 3180, 6414: 3178, 125482: 3178, 9739: 3177, 3826: 3173, 8375: 3172, 125858: 3172, 2518: 3171, 125600: 3169, 3328: 3169, 2804: 3165, 22556: 3163, 9045: 3163, 2578: 3163, 34797: 3162, 2107: 3160, 67973: 3157, 126630: 3155, 1372: 3152, 5224: 3150, 1429: 3149, 26185: 3144, 3726: 3141, 4143: 3140, 5262: 3140, 128488: 3140, 7081: 3138, 126448: 3137, 1288: 3135, 125432: 3135, 8673: 3135, 6181: 3134, 125570: 3134, 688: 3133, 6297: 3129, 9782: 3129, 1481: 3128, 11783: 3127, 7739: 3126, 1888: 3121, 7967: 3120, 131179: 3116, 4038: 3116, 3184: 3115, 1471: 3114, 4668: 3114, 1928: 3111, 8590: 3111, 3173: 3110, 2109: 3110, 125655: 3107, 125665: 3105, 23581: 3098, 7082: 3095, 14110: 3094, 1035: 3093, 4907: 3091, 14022: 3090, 2479: 3087, 5005: 3082, 1696: 3080, 125721: 3078, 125899: 3074, 125522: 3072, 125574: 3072, 1162: 3071, 125647: 3071, 18106: 3070, 10145: 3070, 126523: 3069, 9134: 3067, 7157: 3064, 14767: 3057, 8038: 3056, 125536: 3054, 125479: 3052, 19800: 3052, 125713: 3051, 127065: 3049, 37103: 3048, 8337: 3047, 7300: 3045, 5241: 3045, 126199: 3045, 1606: 3043, 12869: 3042, 125592: 3041, 11347: 3036, 5616: 3027, 18610: 3026, 11366: 3024, 2048: 3023, 125695: 3021, 126889: 3019, 11864: 3015, 7404: 3013, 1566: 3011, 129457: 3010, 6744: 3009, 127852: 3009, 125819: 3009, 126441: 3008, 125838: 3008, 2102: 3008, 8493: 3008, 34619: 3006, 2599: 3006, 8369: 3005, 1627: 3003, 4214: 3003, 129163: 3002, 18893: 3002, 7887: 3000, 126674: 2999, 11172: 2995, 8625: 2992, 13072: 2990, 13018: 2988, 5630: 2984, 6389: 2983, 127069: 2983, 125575: 2980, 13942: 2979, 126002: 2979, 1766: 2971, 3311: 2971, 14053: 2971, 10505: 2971, 9048: 2970, 6440: 2967, 5106: 2965, 1461: 2962, 2024: 2962, 3323: 2960, 137435: 2956, 125628: 2955, 125861: 2955, 126460: 2952, 10224: 2950, 36744: 2949, 6930: 2947, 4694: 2944, 125642: 2944, 1989: 2937, 13905: 2935, 5222: 2931, 2353: 2930, 2833: 2929, 6850: 2928, 2222: 2928, 8179: 2927, 5372: 2926, 125509: 2925, 18580: 2925, 3585: 2924, 3675: 2924, 1048: 2924, 125487: 2923, 64358: 2922, 1577: 2921, 125607: 2919, 10368: 2918, 4732: 2915, 48737: 2915, 7794: 2914, 4885: 2913, 20180: 2909, 4186: 2908, 1738: 2906, 125511: 2906, 12127: 2903, 11795: 2903, 10595: 2901, 9971: 2901, 2113: 2898, 125718: 2898, 8224: 2897, 16068: 2894, 59646: 2893, 125848: 2889, 5259: 2889, 126809: 2888, 125597: 2888, 9423: 2888, 71444: 2887, 11252: 2886, 125388: 2885, 5647: 2883, 46040: 2882, 8151: 2882, 4512: 2881, 125521: 2879, 1432: 2878, 3613: 2876, 2605: 2875, 125952: 2875, 26143: 2873, 6396: 2869, 3329: 2867, 751: 2867, 6451: 2865, 125887: 2864, 30747: 2864, 125777: 2864, 34688: 2863, 1529: 2863, 126330: 2858, 368: 2857, 7319: 2854, 11859: 2853, 7608: 2853, 4536: 2851, 8771: 2848, 54598: 2844, 6693: 2844, 7524: 2840, 1963: 2839, 21592: 2837, 125782: 2836, 4045: 2833, 1484: 2832, 2319: 2831, 1173: 2830, 126488: 2

100%|██████████| 4507/4507 [00:25<00:00, 174.39it/s]

==>> input_total_val: Counter({0: 9971996, 375: 281878, 582: 136373, 373: 96778, 378: 72239, 377: 62027, 634: 60832, 379: 54812, 730: 43580, 905: 43526, 696: 37192, 2373: 34074, 657: 30958, 380: 30500, 732: 28406, 4605: 28089, 1548: 25645, 382: 25154, 1075: 23957, 41728: 22673, 2376: 22274, 381: 21308, 1488: 20217, 715: 19840, 17005: 18824, 2030: 18479, 13456: 18342, 720: 18080, 383: 17447, 386: 17169, 385: 16018, 858: 15925, 384: 15856, 999: 15802, 369: 15230, 392: 14787, 125365: 14485, 643: 14434, 1222: 14086, 798: 13843, 79694: 12345, 14178: 11209, 48199: 11034, 853: 10971, 370: 10704, 2171: 10184, 2425: 9737, 2751: 9617, 18420: 9230, 125371: 8964, 10348: 8872, 16524: 8662, 1043: 8032, 1058: 7892, 125373: 7730, 698: 7252, 40379: 7083, 954: 6734, 816: 6681, 125366: 6664, 2517: 6606, 1050: 6567, 942: 6527, 650: 6141, 125399: 6093, 1823: 6062, 125372: 5940, 1965: 5801, 987: 5740, 764: 5529, 125383: 5426, 722: 5419, 800: 5274, 765: 5133, 1081: 5080, 902: 4998, 125379: 4956, 712: 4942, 1877: 4925, 22226: 4896, 1126: 4808, 855: 4793, 125625: 4775, 125515: 4667, 1818: 4660, 1522: 4636, 125995: 4635, 125445: 4611, 1210: 4607, 125438: 4585, 1042: 4574, 125497: 4554, 9099: 4554, 721: 4549, 887: 4526, 916: 4512, 823: 4509, 125422: 4393, 838: 4345, 9583: 4336, 85080: 4327, 1255: 4233, 941: 4201, 1367: 4175, 3321: 4083, 3157: 4083, 799: 4076, 129018: 4021, 1416: 3963, 125929: 3958, 125387: 3923, 4560: 3905, 37891: 3904, 125377: 3894, 10996: 3892, 5623: 3884, 125392: 3875, 1029: 3786, 125745: 3704, 1146: 3687, 1080: 3668, 125368: 3654, 4978: 3651, 1600: 3648, 1094: 3643, 125402: 3580, 125391: 3565, 1490: 3551, 2870: 3531, 41281: 3526, 125400: 3500, 22773: 3496, 125594: 3492, 1979: 3450, 2878: 3426, 4022: 3407, 15169: 3403, 2597: 3383, 1159: 3373, 1437: 3349, 961: 3332, 1810: 3288, 1325: 3282, 366: 3247, 977: 3236, 3376: 3236, 1332: 3221, 126270: 3198, 27506: 3191, 1018: 3172, 4264: 3169, 1023: 3162, 789: 3154, 125512: 3134, 125382: 3131, 2736: 3131, 1002: 3117, 3051: 3107, 1053: 3065, 1856: 3059, 1495: 3055, 2879: 3023, 125412: 2997, 3401: 2984, 2888: 2981, 11326: 2965, 1452: 2927, 1286: 2926, 128877: 2901, 125448: 2879, 30885: 2878, 1553: 2878, 41655: 2869, 3637: 2859, 4385: 2853, 2827: 2843, 2424: 2828, 834: 2815, 1060: 2806, 760: 2805, 374: 2804, 1430: 2803, 16559: 2798, 964: 2794, 125369: 2782, 1280: 2765, 139505: 2761, 1595: 2747, 2626: 2732, 1326: 2720, 5153: 2713, 50747: 2701, 4415: 2687, 125413: 2678, 1271: 2675, 26111: 2675, 1794: 2663, 2318: 2655, 975: 2644, 1645: 2617, 1254: 2600, 53641: 2594, 28612: 2588, 6697: 2567, 125386: 2565, 1331: 2526, 955: 2517, 6734: 2515, 1774: 2503, 1369: 2500, 125666: 2475, 1597: 2470, 740: 2469, 1780: 2467, 3216: 2457, 125433: 2451, 901: 2429, 128614: 2428, 2126: 2423, 2534: 2395, 6015: 2391, 15913: 2384, 1420: 2364, 28726: 2344, 8052: 2341, 1740: 2333, 125427: 2330, 125537: 2325, 1084: 2322, 85390: 2310, 830: 2309, 1336: 2282, 2491: 2278, 125451: 2276, 9768: 2276, 1617: 2276, 962: 2273, 1031: 2273, 30761: 2262, 1105: 2253, 2645: 2246, 1225: 2242, 3685: 2235, 15585: 2210, 2927: 2201, 2820: 2196, 17324: 2196, 1047: 2195, 126891: 2195, 6332: 2177, 125437: 2176, 4349: 2169, 125742: 2165, 1216: 2162, 5414: 2150, 43202: 2146, 5457: 2145, 1985: 2141, 869: 2129, 125471: 2128, 1921: 2127, 4559: 2121, 1413: 2119, 3172: 2115, 2448: 2110, 14010: 2109, 1658: 2107, 1881: 2103, 7360: 2093, 3428: 2092, 924: 2081, 868: 2075, 844: 2070, 54689: 2067, 125493: 2054, 1130: 2050, 14708: 2050, 10538: 2034, 2781: 2034, 4373: 2026, 4484: 2025, 125468: 2025, 2252: 2019, 691: 2014, 1353: 2013, 1137: 2012, 125376: 2008, 38045: 2008, 2329: 2001, 125380: 1991, 24040: 1991, 769: 1977, 2022: 1959, 1235: 1957, 1647: 1944, 125396: 1942, 4169: 1937, 1371: 1936, 28498: 1933, 1698: 1928, 6487: 1920, 126119: 1919, 4806: 1918, 2886: 1897, 1546: 1892, 4490: 1890, 125415: 1885, 125406: 1885, 125457: 1878, 38069: 1876, 125425: 1872, 69893: 1871, 3903: 1868, 3974: 1863, 1323: 1858, 1052: 1858, 2733: 1856, 1092: 1848, 1629: 1843, 125385: 1836, 125397: 1836, 2575: 1835, 127123: 1833, 3163: 1823, 21212: 1807, 8454: 1804, 125375: 1788, 125446: 1787, 3718: 1786, 5086: 1784, 6327: 1782, 1113: 1771, 733: 1765, 125577: 1760, 1644: 1759, 2299: 1756, 2092: 1753, 4854: 1753, 1821: 1750, 8291: 1750, 126475: 1747, 125398: 1747, 992: 1746, 1682: 1742, 126934: 1740, 25082: 1736, 3596: 1736, 125384: 1736, 125467: 1733, 1244: 1732, 5275: 1730, 5299: 1726, 125430: 1726, 4982: 1712, 9429: 1708, 1411: 1708, 7572: 1707, 1182: 1706, 125796: 1706, 16519: 1705, 22692: 1700, 22610: 1699, 35604: 1697, 4024: 1695, 30695: 1694, 125606: 1690, 3672: 1684, 1526: 1682, 126171: 1679, 25755: 1674, 3235: 1671, 31882: 1671, 713: 1670, 2739: 1669, 2257: 1668, 4003: 1666, 125747: 1666, 1509: 1665, 15536: 1661, 56867: 1657, 5159: 1650, 8789: 1649, 2632: 1647, 4650: 1647, 2799: 1642, 7257: 1642, 1811: 1637, 6026: 1630, 3788: 1628, 6951: 1626, 1008: 1624, 4100: 1624, 6589: 1623, 1376: 1617, 125654: 1617, 1615: 1615, 3950: 1613, 2618: 1606, 1175: 1606, 2437: 1605, 125423: 1599, 125478: 1599, 1775: 1599, 21701: 1598, 8713: 1598, 4504: 1593, 125499: 1591, 13452: 1588, 1858: 1576, 126358: 1574, 128160: 1571, 7087: 1570, 2705: 1569, 125505: 1567, 125404: 1566, 775: 1566, 3492: 1564, 2904: 1563, 125613: 1562, 1154: 1558, 1201: 1553, 3570: 1552, 125481: 1551, 13147: 1546, 1679: 1546, 931: 1545, 134593: 1544, 129933: 1537, 7858: 1535, 948: 1535, 126924: 1531, 5569: 1531, 5422: 1527, 125444: 1527, 12621: 1523, 127062: 1523, 694: 1520, 125588: 1517, 125362: 1516, 7517: 1508, 1560: 1503, 704: 1503, 1931: 1501, 5985: 1499, 1202: 1495, 32918: 1492, 8536: 1491, 2588: 1490, 125431: 1490, 3626: 1489, 1051: 1485, 1934: 1481, 3550: 1480, 1147: 1479, 127412: 1477, 2175: 1471, 1868: 1470, 12418: 1470, 2379: 1469, 1799: 1464, 125603: 1461, 3257: 1460, 125420: 1459, 5720: 1458, 780: 1458, 129685: 1458, 125572: 1458, 6296: 1456, 1728: 1453, 2453: 1451, 4872: 1450, 3754: 1446, 3539: 1444, 125411: 1438, 3050: 1437, 125500: 1437, 2553: 1436, 2266: 1432, 10739: 1431, 3196: 1430, 6747: 1429, 125417: 1429, 4817: 1428, 5547: 1427, 8722: 1426, 1859: 1425, 125677: 1423, 7686: 1423, 125611: 1422, 3118: 1420, 4949: 1417, 6582: 1416, 1673: 1415, 2051: 1414, 1200: 1413, 1415: 1411, 10724: 1411, 1349: 1406, 2110: 1402, 1282: 1398, 6670: 1396, 3100: 1393, 3090: 1392, 125746: 1390, 22241: 1390, 1910: 1390, 2372: 1387, 1719: 1386, 47073: 1386, 125465: 1379, 3347: 1377, 2472: 1376, 2785: 1376, 125703: 1374, 6521: 1374, 9598: 1373, 125407: 1370, 125489: 1369, 3893: 1367, 125459: 1366, 125492: 1363, 125408: 1363, 8397: 1361, 4986: 1360, 125405: 1359, 5718: 1358, 5639: 1352, 6033: 1344, 14976: 1338, 125453: 1338, 1907: 1335, 1803: 1334, 6948: 1334, 915: 1332, 15418: 1332, 848: 1331, 15282: 1328, 1246: 1327, 5266: 1325, 3446: 1324, 125549: 1324, 5010: 1323, 125424: 1323, 4477: 1322, 1360: 1320, 1278: 1320, 1601: 1320, 2351: 1319, 5256: 1319, 2885: 1318, 125484: 1313, 8939: 1312, 14954: 1311, 5865: 1306, 1418: 1306, 3365: 1303, 1469: 1302, 1022: 1301, 125645: 1300, 5837: 1298, 2247: 1298, 4463: 1298, 3239: 1296, 10079: 1296, 4302: 1296, 125496: 1293, 125755: 1293, 3223: 1293, 125675: 1293, 7956: 1291, 2628: 1290, 2211: 1290, 127284: 1289, 4880: 1288, 4576: 1287, 3399: 1287, 1302: 1284, 125626: 1280, 2086: 1280, 126422: 1279, 7245: 1278, 125501: 1277, 3758: 1276, 11240: 1272, 4677: 1271, 8584: 1268, 3745: 1267, 6618: 1267, 1384: 1266, 1400: 1266, 125542: 1264, 4408: 1264, 126078: 1261, 896: 1258, 125609: 1257, 3129: 1254, 37817: 1253, 2434: 1252, 3705: 1251, 1619: 1249, 1337: 1248, 3755: 1248, 4824: 1247, 5304: 1247, 1710: 1244, 2042: 1243, 5292: 1242, 125806: 1242, 59985: 1237, 15220: 1234, 125426: 1233, 1015: 1231, 6507: 1230, 125615: 1229, 125393: 1229, 36090: 1229, 126557: 1228, 1580: 1228, 6698: 1225, 33623: 1225, 2326: 1222, 3336: 1220, 125460: 1218, 125435: 1218, 34593: 1217, 125871: 1216, 12730: 1215, 125557: 1214, 1257: 1214, 125410: 1214, 125507: 1213, 3449: 1212, 126724: 1212, 1124: 1206, 125760: 1203, 4308: 1203, 125463: 1202, 773: 1202, 2431: 1199, 125960: 1199, 125418: 1199, 125464: 1198, 129808: 1198, 10503: 1197, 125726: 1196, 1922: 1192, 4232: 1190, 2263: 1189, 846: 1189, 10018: 1189, 125579: 1187, 3713: 1185, 27574: 1184, 881: 1184, 1694: 1182, 3885: 1179, 5930: 1179, 3387: 1178, 125547: 1177, 3327: 1176, 126042: 1176, 126023: 1175, 4767: 1175, 2502: 1175, 12230: 1175, 6696: 1174, 5149: 1169, 2802: 1169, 1590: 1167, 2419: 1167, 1229: 1166, 125390: 1166, 7215: 1166, 1727: 1165, 4762: 1165, 1067: 1163, 125652: 1162, 37728: 1161, 6138: 1161, 135782: 1161, 8023: 1160, 125551: 1160, 9504: 1160, 3523: 1159, 18101: 1157, 20271: 1155, 125638: 1155, 989: 1150, 125486: 1149, 2401: 1145, 1352: 1145, 3027: 1142, 5336: 1142, 1451: 1141, 125363: 1141, 125530: 1136, 3187: 1135, 1976: 1134, 126745: 1133, 3325: 1133, 5833: 1132, 125470: 1132, 11175: 1131, 1368: 1128, 1466: 1124, 6893: 1123, 125709: 1123, 126383: 1122, 3778: 1120, 1465: 1118, 125416: 1116, 1949: 1113, 1744: 1112, 125586: 1111, 1299: 1110, 9808: 1110, 2469: 1108, 1562: 1104, 2843: 1103, 28675: 1100, 1125: 1097, 17200: 1096, 56415: 1095, 11703: 1093, 126007: 1093, 3930: 1093, 4850: 1092, 125480: 1092, 1938: 1090, 6453: 1089, 4996: 1089, 36427: 1087, 5135: 1087, 3771: 1085, 4532: 1085, 13908: 1085, 125916: 1084, 50294: 1083, 126551: 1083, 2718: 1081, 1387: 1081, 12367: 1081, 125454: 1080, 1541: 1079, 1523: 1079, 5359: 1079, 2264: 1078, 3053: 1077, 4840: 1077, 7059: 1075, 2447: 1075, 3971: 1074, 1990: 1073, 125531: 1073, 126125: 1070, 6912: 1070, 125370: 1070, 1987: 1069, 4954: 1068, 3576: 1067, 126080: 1067, 3460: 1067, 3670: 1066, 5876: 1063, 8254: 1063, 7952: 1062, 1142: 1061, 126196: 1061, 9791: 1061, 8292: 1059, 10395: 1059, 130809: 1057, 6245: 1057, 125429: 1057, 125636: 1055, 9858: 1053, 5838: 1053, 125832: 1052, 125629: 1051, 1956: 1051, 126946: 1050, 2583: 1050, 970: 1050, 125707: 1049, 3519: 1048, 12527: 1047, 1030: 1047, 1157: 1047, 125619: 1046, 12100: 1045, 1822: 1042, 18093: 1041, 2131: 1041, 1634: 1040, 13076: 1039, 1264: 1038, 5371: 1038, 9234: 1036, 3231: 1035, 8851: 1034, 10443: 1033, 125842: 1033, 135006: 1033, 6600: 1030, 4648: 1027, 9384: 1025, 125502: 1025, 4400: 1024, 1898: 1023, 125564: 1021, 4289: 1020, 7084: 1019, 7773: 1018, 9177: 1018, 130402: 1015, 2289: 1015, 14547: 1015, 1151: 1014, 126345: 1014, 125364: 1013, 130102: 1013, 7135: 1013, 8760: 1012, 1578: 1012, 2134: 1012, 63535: 1011, 126974: 1008, 33377: 1008, 3916: 1007, 1212: 1005, 126970: 1004, 125543: 1003, 2041: 1001, 3358: 1001, 5445: 1001, 1588: 999, 1951: 999, 4177: 999, 4125: 998, 6610: 997, 5954: 997, 3063: 997, 1763: 996, 2210: 995, 1139: 995, 1587: 994, 126088: 993, 125541: 993, 2662: 993, 125409: 991, 1955: 991, 1208: 990, 125644: 989, 1983: 988, 61419: 988, 125436: 988, 126527: 986, 27390: 986, 1565: 985, 125529: 985, 10313: 984, 806: 983, 3728: 983, 5717: 981, 19890: 980, 2939: 979, 2129: 979, 5577: 979, 3696: 976, 3656: 976, 20515: 972, 5601: 972, 8235: 972, 1667: 971, 7660: 971, 7457: 970, 16596: 970, 1556: 969, 33861: 969, 1862: 969, 1952: 968, 1841: 968, 5506: 968, 6797: 967, 2710: 966, 2793: 966, 27484: 964, 2088: 964, 6908: 963, 5443: 962, 1846: 961, 12080: 961, 125639: 960, 2430: 960, 3481: 958, 8923: 957, 7924: 954, 125516: 954, 125526: 954, 125698: 954, 13311: 953, 32784: 952, 125987: 952, 2540: 952, 6031: 952, 125434: 950, 1172: 950, 2625: 950, 1899: 949, 127124: 949, 9496: 949, 3701: 949, 125401: 948, 5480: 947, 66582: 946, 8990: 944, 9997: 943, 9239: 943, 125646: 942, 9853: 941, 3892: 941, 125540: 940, 4659: 938, 9350: 938, 125534: 938, 7299: 937, 1504: 937, 2470: 937, 125443: 936, 125447: 936, 1106: 934, 6318: 934, 1618: 933, 130110: 933, 9898: 933, 125394: 933, 125562: 931, 1531: 930, 2690: 929, 5780: 929, 5675: 928, 1296: 926, 34284: 925, 7751: 925, 1736: 925, 1726: 924, 125374: 922, 6738: 922, 1897: 921, 4533: 921, 2876: 920, 126102: 920, 125498: 919, 2775: 918, 52132: 917, 3483: 917, 3083: 916, 1873: 916, 3830: 913, 126228: 913, 9906: 912, 3253: 911, 125532: 911, 3317: 908, 7639: 908, 21715: 905, 125736: 904, 3108: 904, 5552: 904, 125601: 904, 125942: 903, 127378: 903, 3764: 903, 1689: 902, 1654: 901, 31172: 901, 7369: 900, 6105: 900, 1061: 900, 29015: 900, 4130: 900, 125441: 898, 2613: 896, 125880: 896, 127867: 896, 9952: 895, 5568: 895, 3252: 894, 125456: 894, 125599: 893, 3331: 892, 23356: 889, 6279: 887, 6101: 886, 127585: 885, 5731: 884, 125839: 884, 3008: 883, 11090: 882, 11989: 882, 6329: 881, 5204: 881, 10701: 881, 7111: 880, 6226: 880, 125907: 880, 8792: 879, 26331: 879, 137325: 878, 2560: 877, 125689: 876, 6674: 876, 4516: 875, 11137: 875, 2104: 875, 127330: 875, 125568: 874, 11121: 874, 72863: 873, 125940: 870, 125614: 870, 2485: 869, 125367: 868, 11006: 868, 7626: 867, 6135: 866, 8405: 866, 125750: 866, 126214: 865, 126118: 865, 126605: 864, 125825: 863, 125587: 862, 10572: 862, 126200: 861, 2666: 860, 125947: 860, 2361: 859, 126144: 859, 5805: 858, 9759: 857, 5776: 856, 8357: 856, 4649: 855, 926: 855, 7285: 855, 19730: 854, 10326: 854, 8065: 854, 5659: 852, 1813: 852, 1156: 851, 2158: 850, 4679: 850, 1756: 848, 9365: 848, 53387: 848, 2327: 848, 5575: 848, 38534: 848, 125681: 847, 130078: 847, 126357: 847, 27350: 845, 6783: 845, 5998: 844, 126361: 843, 1582: 841, 1880: 841, 1721: 841, 127033: 840, 126273: 840, 5821: 839, 4394: 839, 1944: 839, 125565: 838, 5434: 837, 125589: 837, 126062: 835, 5213: 835, 6490: 834, 6854: 833, 125583: 833, 54417: 830, 1110: 830, 1485: 830, 2139: 828, 44065: 827, 4703: 827, 5210: 825, 129170: 825, 125883: 825, 17728: 825, 4558: 824, 5019: 824, 4078: 824, 11073: 824, 1770: 823, 6003: 823, 18407: 822, 15001: 822, 9060: 822, 125761: 822, 4866: 822, 1339: 821, 2764: 821, 126029: 821, 3396: 821, 125660: 819, 7419: 819, 127909: 819, 5465: 818, 32536: 817, 1398: 817, 4526: 817, 6660: 816, 126984: 816, 3545: 815, 126286: 815, 3753: 814, 2055: 814, 29082: 814, 6066: 813, 4857: 813, 13625: 813, 10021: 813, 125581: 813, 1564: 812, 17297: 812, 42914: 812, 6539: 811, 3091: 811, 8015: 810, 4669: 810, 126302: 810, 1637: 810, 4344: 809, 826: 808, 126929: 808, 6843: 808, 126668: 807, 10491: 806, 9386: 805, 12466: 804, 4985: 804, 1356: 804, 11856: 802, 125528: 802, 5830: 802, 129706: 801, 7632: 801, 8171: 800, 7820: 799, 126031: 799, 13432: 799, 3864: 798, 4830: 798, 125378: 798, 5415: 798, 4809: 797, 125712: 797, 3071: 797, 4630: 796, 9757: 794, 125649: 794, 3164: 792, 8040: 788, 9472: 788, 126026: 787, 7216: 786, 125490: 785, 7121: 785, 7374: 785, 26450: 784, 125965: 784, 4503: 783, 3833: 783, 67973: 783, 11685: 782, 101: 781, 9811: 781, 125817: 781, 4937: 780, 3504: 780, 3276: 780, 1903: 779, 77094: 779, 8551: 779, 1183: 778, 8296: 778, 126448: 778, 7482: 778, 1867: 777, 1510: 777, 4088: 776, 1234: 776, 6037: 775, 7747: 775, 6720: 773, 125683: 772, 7489: 771, 11316: 771, 125694: 770, 9209: 770, 4747: 769, 5788: 769, 9019: 769, 126161: 769, 9642: 768, 125550: 768, 7630: 768, 125803: 768, 3693: 768, 2029: 768, 6588: 767, 12452: 766, 1572: 766, 125428: 766, 876: 766, 13613: 765, 3644: 764, 126074: 764, 3996: 764, 2805: 764, 1374: 763, 34445: 763, 21046: 763, 54065: 762, 1936: 762, 33373: 761, 127466: 761, 5424: 760, 126645: 759, 27846: 759, 4288: 759, 11720: 759, 1372: 758, 125705: 758, 125494: 757, 8877: 757, 128147: 756, 6401: 756, 125730: 755, 4143: 755, 4591: 754, 1144: 754, 2938: 754, 126932: 754, 125776: 753, 3867: 753, 10084: 753, 438: 753, 126534: 753, 1035: 752, 3826: 752, 10921: 752, 13383: 752, 125879: 749, 125833: 749, 13419: 748, 125665: 748, 2578: 748, 37946: 747, 125765: 746, 27359: 745, 4208: 743, 125816: 743, 125432: 742, 5610: 742, 8726: 742, 5653: 742, 23581: 741, 2325: 741, 13554: 741, 3924: 740, 140298: 740, 32607: 740, 126221: 740, 3093: 740, 126602: 739, 9045: 739, 1928: 737, 4038: 737, 21154: 736, 2703: 736, 3198: 736, 4998: 735, 7317: 734, 2207: 734, 131179: 734, 18269: 733, 3311: 733, 126205: 732, 3117: 732, 42864: 731, 126321: 730, 3662: 730, 6810: 729, 2479: 729, 5553: 729, 4510: 728, 3328: 728, 128523: 728, 125791: 727, 2107: 727, 5806: 727, 6733: 726, 125482: 725, 1472: 725, 125789: 724, 14912: 724, 1747: 724, 8259: 724, 2068: 723, 9782: 723, 11783: 723, 14110: 723, 10325: 722, 11864: 722, 13018: 722, 135100: 721, 138154: 720, 26185: 720, 8375: 720, 5262: 720, 34619: 719, 3726: 719, 125655: 719, 125682: 719, 37103: 719, 125474: 718, 5757: 717, 1221: 717, 1869: 716, 2356: 716, 3101: 716, 125479: 716, 1471: 716, 8224: 716, 12025: 714, 12072: 714, 11366: 713, 2804: 712, 132644: 712, 4907: 712, 126674: 711, 128488: 711, 64101: 710, 125944: 710, 126889: 710, 1606: 710, 125487: 709, 21231: 709, 126610: 708, 22556: 707, 125822: 707, 1888: 706, 14519: 706, 7082: 706, 6410: 706, 6440: 705, 2230: 705, 8590: 705, 5259: 705, 28811: 704, 5355: 704, 8800: 704, 14053: 704, 4084: 704, 7967: 704, 125861: 703, 2109: 703, 125628: 703, 29042: 702, 893: 702, 125536: 702, 12103: 701, 2102: 700, 1288: 700, 5005: 700, 32046: 700, 9739: 699, 34688: 699, 126523: 699, 10551: 699, 125924: 699, 3173: 699, 9293: 698, 3184: 697, 2518: 697, 10145: 696, 8179: 696, 8493: 696, 125743: 694, 10112: 694, 5146: 694, 5255: 694, 125600: 693, 2024: 693, 6264: 693, 132035: 693, 125558: 692, 125642: 692, 126630: 692, 10224: 692, 26143: 692, 126460: 692, 3882: 691, 4028: 691, 688: 691, 8369: 690, 34797: 689, 4668: 689, 18106: 689, 31747: 688, 11347: 688, 1481: 688, 125592: 687, 126002: 687, 64358: 687, 6784: 686, 125627: 686, 6433: 686, 125509: 686, 18610: 686, 12869: 685, 59646: 684, 7887: 684, 13072: 683, 3675: 683, 16068: 683, 4885: 682, 125695: 682, 1431: 682, 400: 682, 6414: 682, 5106: 682, 3060: 681, 125647: 680, 126199: 680, 1429: 679, 8673: 679, 127065: 678, 785: 678, 5241: 678, 125574: 678, 8337: 677, 4694: 677, 1738: 676, 22356: 676, 6693: 675, 8771: 675, 125511: 675, 7081: 673, 127069: 672, 4186: 672, 6581: 672, 125575: 672, 4214: 671, 7514: 671, 1484: 670, 8038: 670, 5224: 670, 9134: 670, 6850: 670, 15052: 669, 1766: 669, 125713: 669, 6389: 669, 7739: 668, 125570: 668, 2316: 667, 125807: 667, 1107: 667, 125718: 667, 12127: 667, 8151: 667, 6297: 666, 125858: 666, 1461: 666, 6930: 665, 11172: 665, 125539: 665, 4060: 665, 2833: 665, 129163: 665, 10368: 663, 125521: 663, 126330: 663, 1162: 662, 1048: 662, 125819: 662, 19885: 662, 125721: 662, 7157: 662, 4786: 661, 45022: 661, 7300: 661, 6181: 661, 14767: 661, 14022: 660, 10595: 660, 8625: 660, 3055: 659, 126809: 659, 2222: 659, 18580: 659, 2048: 659, 6744: 659, 125452: 658, 128115: 658, 15069: 658, 125838: 658, 125522: 657, 5616: 656, 1696: 656, 126441: 656, 126877: 655, 125899: 655, 11795: 655, 4512: 654, 2319: 654, 126552: 654, 7404: 654, 125782: 654, 1577: 654, 9125: 653, 3130: 653, 6451: 653, 2599: 652, 126592: 651, 10831: 651, 5647: 651, 9423: 651, 125671: 651, 1627: 650, 5763: 649, 127401: 649, 127888: 649, 46040: 648, 1995: 648, 125706: 647, 30747: 647, 9048: 647, 125983: 646, 4045: 646, 3329: 646, 5222: 646, 137435: 646, 10505: 646, 125848: 645, 18893: 645, 128885: 644, 5658: 644, 10733: 643, 48737: 643, 6086: 643, 368: 642, 1703: 642, 19417: 641, 3585: 641, 9860: 640, 4064: 640, 4930: 640, 7608: 639, 7524: 638, 127852: 638, 1529: 637, 7799: 636, 125887: 636, 36744: 636, 2015: 636, 126281: 635, 125952: 635, 129457: 634, 4071: 634, 1040: 634, 7936: 634, 2069: 634, 18305: 634, 2359: 634, 48413: 633, 19800: 633, 9971: 632, 4336: 631, 126059: 631, 2555: 631, 6675: 631, 1432: 630, 3011: 630, 20870: 630, 126908: 629, 7794: 629, 5630: 629, 2563: 629, 1989: 628, 1433: 628, 6577: 627, 3613: 627, 5363: 627, 13942: 627, 4160: 626, 62036: 626, 126472: 625, 54598: 624, 4268: 624, 1568: 624, 2957: 624, 4841: 623, 125777: 623, 125607: 623, 3323: 623, 11859: 623, 5184: 623, 1777: 622, 4536: 622, 29635: 622, 3827: 622, 125808: 621, 20180: 621, 5372: 621, 50173: 621, 1640: 620, 128936: 619, 125506: 619, 126926: 618, 126079: 618, 126488: 618, 18488: 618, 125612: 617, 21592: 617, 8434: 616, 8901: 616, 17635: 616, 5615: 616, 125510: 616, 5161: 616, 125597: 615, 126514: 615, 125477: 615, 11979: 615, 5376: 615, 1793: 615, 2113: 614, 125664: 614, 11252: 614, 15118: 614, 126615: 613, 52

100%|██████████| 501/501 [00:02<00:00, 202.66it/s]

==>> input_total_test: Counter({0: 1096801, 375: 31389, 582: 15071, 373: 10871, 378: 7886, 377: 7003, 634: 6871, 379: 6057, 905: 4810, 730: 4730, 696: 4170, 2373: 3720, 657: 3473, 380: 3349, 4605: 3228, 732: 3122, 1548: 2838, 382: 2779, 1075: 2627, 2376: 2555, 41728: 2495, 381: 2318, 715: 2232, 1488: 2223, 17005: 2114, 2030: 2077, 13456: 2052, 720: 2034, 383: 2002, 386: 1869, 385: 1824, 858: 1793, 384: 1736, 999: 1713, 369: 1679, 643: 1627, 392: 1616, 125365: 1603, 798: 1564, 1222: 1511, 79694: 1399, 48199: 1259, 14178: 1245, 370: 1201, 853: 1187, 2171: 1099, 18420: 1082, 2425: 1042, 125371: 1025, 2751: 1020, 10348: 1018, 16524: 935, 125373: 889, 1043: 870, 1058: 832, 40379: 792, 698: 787, 2517: 766, 954: 765, 1050: 752, 942: 743, 125366: 724, 650: 710, 1823: 691, 816: 688, 125399: 670, 125372: 649, 1965: 649, 125383: 618, 722: 603, 987: 597, 764: 591, 22226: 575, 1877: 566, 1081: 565, 1818: 557, 1522: 554, 765: 548, 823: 545, 1126: 542, 712: 542, 902: 540, 800: 539, 125995: 528, 125438: 524, 125445: 523, 125422: 517, 125497: 517, 125625: 514, 125379: 510, 9099: 506, 1210: 504, 855: 499, 9583: 498, 125515: 498, 916: 491, 1042: 489, 85080: 476, 125392: 473, 838: 471, 887: 468, 721: 466, 941: 460, 3157: 459, 799: 457, 129018: 451, 125377: 451, 1255: 448, 4560: 448, 1367: 447, 1416: 441, 37891: 441, 3321: 439, 1094: 432, 125745: 425, 125368: 423, 10996: 422, 125929: 421, 5623: 421, 1979: 412, 2878: 409, 41281: 407, 1029: 404, 125594: 402, 125391: 401, 1080: 398, 1146: 398, 22773: 396, 15169: 396, 1856: 394, 1490: 394, 125402: 392, 125400: 392, 4264: 391, 2870: 387, 961: 384, 125387: 384, 4022: 382, 4978: 380, 125382: 376, 126270: 375, 366: 375, 1023: 372, 1600: 368, 125512: 365, 2597: 364, 1159: 362, 789: 362, 1437: 362, 3376: 361, 1810: 361, 128877: 361, 1495: 353, 11326: 352, 27506: 352, 374: 348, 1452: 346, 1018: 344, 2888: 344, 125412: 342, 125448: 338, 3051: 337, 760: 337, 1286: 337, 3401: 335, 1332: 333, 977: 333, 125386: 330, 1553: 330, 2827: 329, 1325: 329, 1002: 329, 16559: 328, 1331: 327, 1280: 326, 1053: 326, 9768: 322, 1060: 319, 1271: 319, 834: 317, 125369: 316, 2318: 314, 3637: 312, 2879: 309, 50747: 309, 125413: 308, 41655: 308, 2736: 307, 2626: 306, 5153: 303, 1326: 301, 6734: 300, 30885: 296, 4385: 294, 53641: 293, 1254: 292, 1774: 292, 964: 290, 1645: 290, 26111: 286, 1430: 285, 1780: 283, 139505: 282, 30761: 280, 740: 280, 2424: 279, 975: 279, 901: 278, 125666: 274, 6697: 273, 1597: 273, 2645: 273, 2126: 272, 955: 271, 4415: 271, 868: 269, 17324: 268, 1225: 268, 3685: 266, 962: 265, 85390: 264, 3216: 264, 126891: 264, 1595: 264, 1216: 262, 15585: 262, 1084: 262, 15913: 262, 1617: 261, 6015: 261, 125537: 260, 125433: 259, 125427: 258, 1369: 258, 1137: 257, 1031: 255, 5414: 254, 28612: 254, 28726: 253, 1371: 252, 1105: 252, 1985: 252, 1336: 252, 2329: 249, 128614: 249, 2534: 248, 8052: 248, 125451: 248, 14708: 248, 7360: 248, 1353: 246, 830: 246, 1740: 246, 4559: 245, 1794: 243, 2491: 243, 1130: 242, 1921: 241, 1658: 241, 1881: 241, 924: 241, 125380: 240, 2448: 238, 3428: 238, 869: 237, 4349: 236, 3172: 234, 125396: 234, 5457: 234, 125493: 234, 1420: 234, 1629: 233, 6332: 232, 3974: 231, 28498: 231, 2022: 231, 3903: 231, 1047: 231, 1775: 229, 5159: 228, 1052: 228, 54689: 228, 3718: 227, 125437: 227, 2781: 227, 38045: 226, 125471: 226, 125742: 225, 126119: 224, 43202: 224, 844: 224, 6487: 224, 4484: 223, 24040: 223, 125415: 222, 2820: 222, 1235: 222, 125376: 221, 10538: 220, 1647: 219, 125468: 217, 2252: 216, 8454: 216, 2575: 215, 1413: 214, 4169: 214, 1698: 214, 3163: 213, 16519: 213, 125457: 213, 38069: 213, 125654: 213, 769: 212, 14010: 211, 4373: 210, 1113: 208, 125406: 208, 4490: 208, 691: 208, 2733: 207, 35604: 206, 1092: 206, 125577: 205, 127123: 204, 4806: 204, 125446: 204, 1811: 204, 733: 204, 125425: 203, 3492: 202, 2092: 202, 22610: 202, 1244: 201, 8713: 201, 125375: 200, 9429: 200, 992: 200, 3788: 199, 2927: 199, 3672: 199, 2299: 199, 1411: 198, 21212: 198, 3596: 198, 2886: 198, 125467: 198, 126475: 198, 125444: 197, 5086: 197, 7087: 195, 125385: 195, 126171: 194, 1546: 194, 1821: 194, 1934: 193, 7257: 193, 2739: 193, 31882: 192, 125384: 191, 13147: 191, 4650: 191, 4982: 191, 1615: 191, 7572: 190, 4504: 189, 125478: 189, 4024: 188, 2051: 188, 1323: 188, 6327: 187, 6951: 187, 8789: 187, 125423: 187, 126358: 186, 2618: 186, 1682: 186, 30695: 185, 1509: 184, 2799: 184, 4854: 184, 1154: 184, 125500: 184, 22692: 184, 126934: 184, 125505: 183, 5299: 183, 8291: 183, 125398: 183, 125499: 182, 1202: 182, 2257: 182, 5275: 181, 1008: 181, 1200: 181, 2437: 181, 1560: 181, 127412: 181, 1376: 180, 1644: 180, 69893: 180, 21701: 179, 3950: 179, 125796: 179, 25082: 179, 125430: 179, 5985: 178, 125417: 178, 1526: 177, 4100: 177, 125603: 177, 7858: 175, 3626: 175, 2785: 175, 780: 174, 3539: 174, 125424: 174, 125747: 174, 129685: 173, 1868: 173, 25755: 173, 3570: 173, 1858: 173, 5422: 173, 1931: 173, 6589: 173, 3235: 172, 127062: 172, 1051: 172, 775: 172, 7517: 172, 125397: 171, 3754: 171, 1384: 171, 931: 171, 125606: 170, 125407: 170, 2632: 170, 1415: 170, 2705: 169, 1679: 168, 8722: 168, 5837: 168, 10724: 168, 6296: 168, 5256: 167, 125404: 167, 713: 167, 5569: 167, 694: 167, 1175: 167, 1302: 167, 125645: 167, 2904: 167, 125611: 167, 704: 166, 128160: 166, 129933: 166, 4003: 166, 13452: 165, 125588: 165, 125411: 165, 47073: 165, 125481: 165, 6026: 165, 3257: 164, 5547: 164, 6521: 164, 3196: 164, 1182: 164, 1619: 163, 1719: 163, 2372: 163, 56867: 163, 8397: 163, 4408: 163, 948: 162, 12418: 162, 3347: 161, 1910: 161, 15536: 161, 1728: 161, 8536: 161, 6582: 160, 7956: 160, 3550: 160, 4824: 159, 125489: 159, 125572: 159, 1400: 159, 1418: 159, 1601: 159, 125453: 158, 1282: 158, 989: 157, 125410: 157, 4817: 157, 2110: 157, 1799: 157, 4949: 157, 1922: 156, 125613: 156, 4677: 156, 6618: 155, 2379: 155, 2175: 154, 125626: 154, 1907: 154, 1360: 154, 4302: 154, 125703: 154, 1201: 153, 8584: 153, 2326: 153, 125431: 153, 125393: 153, 2588: 153, 126422: 153, 5930: 153, 125408: 152, 3050: 152, 3090: 152, 2885: 152, 5833: 152, 12621: 152, 2553: 151, 2472: 151, 125459: 151, 4477: 151, 32918: 151, 125362: 150, 1803: 150, 2266: 150, 3365: 150, 1337: 150, 125755: 150, 848: 149, 2843: 149, 3399: 149, 5720: 149, 2431: 149, 4986: 149, 6948: 149, 3118: 148, 125542: 148, 1562: 148, 4872: 148, 3885: 148, 125677: 147, 915: 146, 14954: 146, 1349: 146, 2401: 146, 125426: 146, 1710: 146, 4648: 146, 126924: 146, 3239: 146, 10739: 146, 134593: 145, 4576: 145, 125464: 145, 4308: 145, 125675: 145, 14976: 144, 125470: 144, 3745: 144, 125484: 144, 5266: 144, 6670: 144, 896: 144, 2042: 144, 125435: 144, 7245: 144, 125549: 143, 9858: 143, 34593: 143, 9598: 143, 3713: 143, 3778: 143, 15282: 142, 125420: 142, 125960: 142, 5292: 142, 5718: 142, 11175: 142, 15418: 142, 5639: 142, 3336: 141, 8939: 141, 36090: 141, 126724: 141, 33623: 141, 1955: 141, 2211: 141, 125871: 141, 36427: 141, 2351: 140, 125416: 140, 5304: 140, 1257: 140, 1124: 140, 5865: 140, 125501: 140, 4762: 140, 125586: 140, 4767: 139, 3129: 139, 126551: 139, 1157: 139, 2502: 138, 1949: 138, 125405: 138, 2469: 138, 1956: 138, 7686: 138, 3893: 138, 3325: 138, 1015: 138, 3446: 138, 1022: 137, 10079: 137, 5135: 137, 1278: 137, 3705: 137, 2264: 137, 3223: 137, 125760: 137, 6747: 136, 2583: 136, 127284: 136, 2453: 136, 13908: 136, 6453: 136, 59985: 136, 125492: 136, 1246: 136, 8851: 135, 846: 135, 125615: 135, 5149: 135, 125465: 135, 4463: 135, 1147: 135, 1673: 135, 37817: 135, 4880: 134, 135782: 134, 1859: 133, 3053: 133, 2718: 133, 3449: 133, 2434: 133, 125418: 133, 2628: 133, 125463: 133, 125609: 133, 2086: 133, 125746: 133, 11240: 133, 12730: 132, 1744: 132, 125409: 132, 3755: 132, 129808: 132, 125579: 132, 3523: 132, 125652: 132, 5371: 131, 126078: 131, 1466: 131, 6033: 131, 126007: 131, 125806: 130, 1590: 130, 125496: 130, 125534: 130, 6610: 130, 125709: 129, 1212: 129, 126196: 129, 3100: 129, 125486: 128, 1694: 128, 63535: 128, 125557: 128, 126557: 128, 125619: 128, 126974: 128, 3758: 128, 3327: 128, 10018: 128, 125547: 127, 1469: 127, 3187: 126, 13311: 126, 7215: 126, 22241: 126, 1541: 126, 56415: 126, 1299: 126, 1976: 126, 50294: 126, 15220: 125, 773: 125, 6138: 125, 126745: 125, 13076: 125, 125436: 124, 6696: 124, 881: 124, 1067: 124, 16596: 124, 7084: 124, 27574: 124, 1952: 124, 6912: 123, 125726: 123, 125364: 123, 5359: 123, 4996: 123, 37728: 123, 125638: 123, 125507: 123, 5010: 123, 3519: 123, 125707: 122, 5954: 122, 1862: 122, 9808: 122, 126023: 122, 125601: 122, 1938: 122, 1987: 122, 1618: 122, 125987: 121, 6507: 121, 126042: 121, 1727: 121, 126527: 121, 125516: 121, 1368: 121, 3460: 121, 5552: 120, 2263: 120, 20271: 120, 10503: 120, 126946: 120, 1667: 120, 125832: 120, 127585: 120, 1229: 120, 5480: 120, 1451: 120, 9496: 120, 1580: 120, 2247: 119, 4840: 119, 125460: 119, 4232: 119, 130102: 119, 2447: 119, 7952: 119, 125480: 119, 18093: 119, 126125: 119, 1142: 118, 6329: 118, 125363: 118, 126214: 118, 7751: 118, 9853: 118, 125629: 118, 125644: 118, 6698: 118, 127378: 117, 125551: 117, 9504: 117, 5601: 117, 18101: 117, 1873: 117, 52132: 117, 1990: 117, 1841: 117, 4850: 117, 125390: 117, 6031: 117, 125636: 117, 127124: 116, 125394: 116, 8760: 116, 3253: 116, 2289: 116, 5876: 116, 54065: 116, 19890: 116, 125564: 116, 4532: 116, 8254: 116, 6279: 116, 14547: 115, 125880: 115, 4954: 115, 3387: 115, 10313: 115, 1387: 114, 125434: 114, 6893: 114, 11703: 114, 2802: 114, 8023: 114, 130110: 113, 4533: 113, 125530: 113, 9177: 113, 125839: 113, 7639: 113, 3481: 113, 126383: 113, 3027: 113, 61419: 112, 8235: 112, 2540: 112, 3231: 112, 2613: 112, 1531: 112, 125529: 112, 17200: 112, 10572: 112, 126345: 112, 3701: 112, 126080: 112, 8990: 111, 21715: 111, 11006: 111, 125907: 111, 2419: 111, 5776: 111, 9906: 111, 806: 111, 4177: 111, 3696: 111, 9898: 111, 126228: 111, 33861: 111, 3670: 111, 7482: 111, 125531: 111, 10395: 111, 125916: 111, 125842: 110, 8923: 110, 5838: 110, 1125: 110, 11989: 110, 7135: 110, 1352: 110, 1264: 110, 23356: 110, 126984: 110, 125543: 110, 2134: 110, 2131: 110, 9384: 109, 970: 109, 7820: 109, 125540: 109, 3916: 109, 1899: 109, 1880: 109, 1523: 109, 125429: 109, 5336: 109, 7626: 109, 1822: 108, 1030: 108, 12367: 108, 1578: 108, 10443: 108, 5568: 108, 1736: 108, 7059: 108, 125646: 108, 125454: 108, 8357: 108, 8292: 108, 5717: 108, 126088: 107, 1587: 107, 2088: 107, 3971: 107, 1588: 107, 125526: 107, 27390: 107, 3008: 107, 27484: 107, 125401: 107, 3108: 106, 1582: 106, 130809: 106, 5780: 106, 125502: 106, 7285: 106, 5506: 106, 7924: 106, 2690: 106, 125532: 106, 4400: 106, 2710: 106, 3656: 106, 6245: 106, 125443: 106, 8171: 106, 2041: 106, 2485: 105, 1898: 105, 5675: 105, 48413: 105, 126102: 105, 12230: 105, 7419: 105, 6797: 105, 3728: 105, 126605: 105, 126970: 105, 1634: 105, 7773: 104, 7111: 104, 12100: 104, 66582: 104, 1208: 104, 4289: 104, 2560: 104, 1756: 104, 6101: 104, 8040: 104, 1172: 104, 3317: 104, 4747: 104, 1139: 104, 2139: 103, 27350: 103, 5577: 103, 2666: 103, 3892: 103, 3063: 103, 5575: 103, 130402: 103, 125562: 103, 3930: 103, 9234: 103, 135006: 103, 9365: 103, 9791: 103, 6318: 103, 1897: 103, 5443: 103, 125498: 103, 125712: 102, 125942: 102, 5788: 102, 32784: 102, 2104: 102, 1565: 102, 4130: 102, 6908: 102, 400: 102, 5465: 102, 33377: 102, 7457: 101, 1654: 101, 125370: 101, 3830: 101, 1951: 101, 1696: 101, 17297: 101, 1556: 101, 125589: 101, 130078: 101, 6600: 101, 7660: 101, 126118: 100, 22356: 100, 6674: 100, 9920: 100, 4659: 100, 1763: 100, 9239: 100, 1465: 100, 1296: 100, 1504: 100, 6738: 100, 3576: 99, 8590: 99, 1747: 99, 9350: 99, 3396: 99, 1106: 99, 7299: 99, 2210: 99, 125441: 99, 7369: 99, 129170: 99, 4125: 99, 126645: 99, 3358: 99, 6105: 98, 5731: 98, 135100: 98, 3662: 98, 1061: 98, 11685: 98, 54417: 98, 6226: 98, 1983: 97, 4985: 97, 126026: 97, 125374: 97, 1689: 97, 2793: 97, 29082: 97, 6539: 97, 6854: 97, 13625: 97, 126062: 97, 2327: 97, 3504: 97, 6003: 97, 53387: 97, 5019: 97, 7747: 97, 8792: 97, 2662: 97, 125581: 97, 9060: 96, 72863: 96, 8800: 96, 1944: 96, 125528: 96, 12466: 96, 4558: 96, 3545: 96, 11121: 96, 27359: 96, 126448: 96, 5224: 96, 1110: 96, 2876: 96, 6440: 96, 29015: 95, 125568: 95, 3252: 95, 125743: 95, 4516: 95, 44065: 95, 3083: 95, 125681: 95, 26450: 95, 125649: 95, 18407: 95, 4394: 95, 2158: 95, 125822: 95, 5210: 95, 4998: 95, 125736: 94, 7630: 94, 2069: 94, 13432: 94, 126361: 94, 2938: 94, 125490: 94, 4630: 94, 129457: 94, 4344: 94, 12527: 94, 9811: 94, 3483: 94, 125825: 94, 9952: 94, 15001: 94, 125761: 94, 17728: 94, 3996: 94, 5204: 94, 1485: 94, 3764: 94, 11859: 94, 19730: 93, 125883: 93, 4526: 93, 125367: 93, 125587: 93, 5363: 93, 2775: 93, 126144: 93, 125750: 93, 2129: 93, 132644: 93, 125789: 93, 5213: 93, 1903: 93, 10701: 93, 3829: 93, 101: 93, 3833: 93, 2578: 93, 42914: 93, 126029: 92, 10491: 92, 126200: 92, 127330: 92, 125639: 92, 5434: 92, 5415: 92, 5424: 92, 125541: 92, 1564: 92, 9997: 92, 2109: 92, 3924: 92, 11090: 91, 3071: 91, 8015: 91, 34445: 91, 31172: 91, 33373: 91, 5630: 91, 2353: 91, 2430: 91, 77094: 91, 3644: 91, 1726: 91, 1867: 91, 125776: 91, 6181: 91, 6810: 91, 4830: 90, 8065: 90, 13419: 90, 2325: 90, 126302: 90, 126273: 90, 4649: 90, 7081: 90, 5255: 90, 10921: 90, 2764: 90, 6401: 90, 125614: 90, 926: 90, 10595: 90, 125627: 89, 126205: 89, 125550: 89, 34284: 89, 125456: 89, 12080: 89, 3616: 89, 126357: 89, 5553: 89, 9782: 89, 4809: 89, 125698: 89, 1888: 89, 5445: 89, 3771: 89, 6660: 89, 10084: 89, 5806: 89, 4679: 89, 11316: 89, 2361: 89, 5998: 89, 125791: 89, 10326: 89, 127852: 88, 1144: 88, 12099: 88, 8375: 88, 127909: 88, 132035: 88, 7374: 88, 4866: 88, 6451: 88, 125558: 88, 5805: 88, 1339: 88, 5259: 88, 6588: 88, 4503: 88, 1869: 88, 140298: 88, 28675: 88, 1936: 88, 3091: 88, 6490: 87, 2599: 87, 8726: 87, 2470: 87, 9759: 87, 2207: 87, 138154: 87, 20515: 87, 12072: 87, 1703: 87, 11073: 87, 1151: 87, 126221: 87, 5376: 87, 6135: 87, 125689: 87, 7632: 87, 2625: 87, 6264: 87, 3164: 87, 3331: 87, 2939: 87, 125509: 86, 26331: 86, 21231: 86, 2068: 86, 2055: 86, 22556: 86, 5355: 86, 18269: 86, 125565: 86, 5134: 86, 125721: 86, 131179: 86, 10021: 86, 125817: 86, 4857: 86, 2566: 86, 1183: 86, 21046: 86, 6843: 86, 5821: 86, 826: 86, 28811: 85, 125474: 85, 125947: 85, 785: 85, 13942: 85, 9642: 85, 48737: 85, 3093: 85, 19800: 85, 127867: 85, 3693: 85, 9472: 85, 32536: 85, 1156: 85, 4510: 85, 125838: 84, 125494: 84, 5610: 84, 125924: 84, 8224: 84, 2518: 84, 9209: 84, 34619: 84, 126534: 84, 126932: 84, 137325: 84, 126809: 84, 125522: 84, 13613: 84, 4214: 84, 1288: 84, 125575: 83, 3184: 83, 893: 83, 125556: 83, 125765: 83, 1846: 83, 64101: 83, 4937: 83, 125655: 83, 4143: 83, 125607: 83, 14022: 83, 11720: 83, 3977: 83, 11783: 83, 4088: 83, 15118: 82, 11172: 82, 6016: 82, 13018: 82, 7216: 82, 125600: 82, 126286: 82, 1398: 82, 12025: 82, 126523: 82, 7460: 82, 2805: 82, 5161: 82, 27846: 82, 1234: 82, 1356: 82, 126929: 82, 4668: 81, 32046: 81, 9386: 81, 125730: 81, 2015: 81, 2563: 81, 125965: 81, 2102: 81, 125682: 81, 6066: 81, 126558: 81, 5653: 81, 1107: 81, 438: 81, 125447: 81, 6783: 81, 125628: 81, 3826: 80, 3060: 80, 12149: 80, 126674: 80, 4591: 80, 16278: 80, 2703: 80, 127069: 80, 9739: 80, 125599: 80, 6577: 80, 30747: 80, 11795: 80, 125879: 80, 13072: 80, 7157: 80, 6410: 80, 125597: 80, 2316: 80, 1928: 80, 30284: 80, 4669: 80, 11821: 80, 128147: 80, 125432: 79, 8151: 79, 7121: 79, 6037: 79, 11864: 79, 32607: 79, 12232: 79, 14912: 79, 125665: 79, 126074: 79, 1432: 79, 368: 79, 34797: 79, 125642: 79, 2029: 79, 125428: 79, 3329: 79, 3328: 79, 1770: 79, 4208: 79, 130156: 79, 6733: 79, 1461: 79, 14767: 79, 126259: 79, 45958: 79, 5757: 79, 4269: 79, 126031: 78, 12103: 78, 126602: 78, 1180: 78, 125891: 78, 129706: 78, 3117: 78, 10970: 78, 10325: 78, 6414: 78, 2962: 78, 6433: 78, 67973: 78, 37946: 78, 126630: 78, 125777: 78, 3585: 78, 1606: 78, 7404: 78, 125983: 78, 3726: 78, 4288: 77, 125940: 77, 128523: 77, 19417: 77, 20180: 77, 137435: 77, 1995: 77, 4186: 77, 125378: 77, 126344: 77, 5659: 77, 125482: 77, 125944: 77, 4885: 77, 6720: 77, 11137: 77, 125592: 77, 14053: 77, 5647: 77, 3827: 77, 9293: 77, 125570: 77, 125899: 77, 8673: 77, 125694: 77, 10112: 77, 14519: 77, 10368: 77, 127401: 77, 6850: 77, 6930: 76, 16068: 76, 4038: 76, 3028: 76, 1471: 76, 7704: 76, 126610: 76, 4786: 76, 126079: 76, 8551: 76, 1813: 76, 9019: 76, 125803: 76, 126321: 76, 5830: 76, 11856: 76, 8877: 76, 2230: 76, 6675: 76, 1040: 76, 37103: 76, 1721: 76, 6784: 76, 42864: 76, 7524: 76, 21154: 76, 38534: 76, 8369: 76, 1221: 75, 125487: 75, 4355: 75, 9012: 75, 2804: 75, 8296: 75, 5106: 75, 134860: 75, 2479: 75, 125696: 75, 3867: 75, 10672: 75, 126637: 75, 125722: 75, 125660: 75, 15845: 75, 125819: 75, 126712: 75, 29042: 75, 12869: 75, 127305: 75, 1637: 75, 71444: 75, 127493: 75, 15069: 75, 23581: 75, 125582: 75, 125782: 74, 1766: 74, 18305: 74, 11366: 74, 2492: 74, 7794: 74, 1374: 74, 1963: 74, 12452: 74, 1104: 74, 3323: 74, 126460: 74, 3810: 74, 125821: 74, 14110: 74, 126550: 74, 688: 74, 126199: 74, 5283: 74, 1162: 73, 126161: 73, 59646: 73, 126488: 73, 127065: 73, 125816: 73, 2222: 73, 1566: 73, 4078: 73, 125452: 73, 2319: 73, 3198: 73, 125403: 73, 2229: 73, 18314: 73, 4536: 73, 1777: 73, 11979: 73, 6297: 73, 126519: 73, 1717: 73, 10714: 73, 3101: 73, 16976: 73, 4694: 73, 7489: 73, 125583: 72, 126059: 72, 1572: 72, 6396: 72, 12219: 72, 7730: 72, 34688: 72, 125887: 72, 18610: 72, 126002: 72, 54598: 72, 130112: 72, 8082: 72, 876: 72, 9425: 72, 126215: 72, 127812: 72, 65296: 72, 13140: 72, 8337: 72, 7879: 72, 4060: 72, 128115: 72, 126472: 72, 125727: 72, 6581: 72, 48295: 72, 958: 71, 11782: 71, 134554: 71, 8651: 71, 126552: 71, 125966: 71, 3753: 71, 125861: 71, 125714: 71, 15329: 71, 18488: 71, 8405: 71, 17939: 71, 2250: 71, 126185: 71, 7967: 71, 126668: 71, 125833: 71, 50280: 71, 8434: 71, 4950: 71, 5763: 71, 5831: 70, 1738: 70, 26361: 70, 8011: 70, 1173: 70, 1431: 70, 751: 70, 17228: 70, 126456: 70, 1484: 70, 126725: 70, 13508: 70, 125624: 70, 9125: 70, 129090: 70, 5616: 70, 10902: 70, 17635: 70, 125818: 70, 50173: 70, 41836: 70, 8038: 70, 10831: 70, 129163: 70, 1627: 70, 4399: 70, 6406: 70, 26185: 70, 3276: 70, 9971: 70, 10551: 70, 28839: 70, 125539: 70, 18580: 70, 7317: 70, 31747: 70, 5184: 70, 1472: 70, 125683: 70, 8580: 70, 16404: 69, 1640: 69, 125479: 69, 125521: 69, 8179: 69, 2960: 69, 11347: 69, 680: 69, 2833: 69, 5222: 69, 11932: 69, 2107: 69, 4907: 69, 125477: 69, 18893: 69, 125634: 69, 7082: 69, 10969: 69, 18386: 69, 125580: 69, 7625: 69, 72756: 69, 24911: 69, 125506: 68, 125671: 68, 2818: 68, 126087: 68, 4268: 68, 8510: 68, 125795: 68, 4703: 68, 3675: 68, 7300: 68, 126251: 68, 10733: 68, 125858: 68, 18106: 68, 1577: 68, 65573: 68, 125740: 68, 3102: 68, 5767: 68, 125848: 68, 2359: 68, 21817: 68, 5262: 68, 13554: 68, 2957: 68, 2024: 68, 2315: 67, 3613: 67, 126615: 67, 1035: 67, 12695: 67, 7806: 67, 125647: 67, 6389: 67, 4732: 67, 5241: 67, 9035: 67, 3130: 67, 125511: 67, 1481: 67, 46232: 67, 131624: 67, 4081: 67, 126014: 67, 1429: 67, 4071: 67, 8573: 67, 1510: 67, 52854: 67, 128936: 67, 4841: 67, 126441: 67, 8771: 67, 13383: 67, 6472: 66, 127466: 66, 4931: 66, 12786: 66, 125778: 66, 7076: 66, 125731: 66, 7298: 66, 5847: 66, 128488: 66, 40480: 66, 53696: 66, 5372: 66, 5146: 66, 9423: 66, 125705: 66, 5005: 66, 128260: 66, 10145: 66, 125711: 66, 21334: 66, 4666: 66, 125585: 66, 126690: 66, 7739: 66, 14504: 66, 8519: 66, 5458: 66, 3303: 65, 9860: 65, 128222: 65, 125807: 65, 4512: 65, 17172: 65, 23192: 65, 127307: 65, 25043: 65, 1543: 65, 1837: 65, 126653: 65, 1652: 65, 59553: 65, 127126: 65, 126618: 65, 32051: 65, 6086: 65, 4008: 65, 31746: 65, 3311: 65, 15052: 65, 126015: 65, 8695: 65, 1385: 65, 1529: 65, 125536: 65, 16076: 65, 126908: 65, 26143: 65, 12438: 65, 125664: 65, 18812: 65, 125640: 65, 18150: 65, 126926: 65, 125669: 65, 11126: 64, 3236: 64, 6744: 64, 126513: 64, 125718: 64, 5615: 64, 30518: 64, 7151: 64, 7243: 64, 129723: 64, 7741: 64, 125793: 64, 125952: 64, 125786: 64, 2356: 64, 5324: 64, 1793: 64, 19120: 64, 126139: 64, 5658: 64, 3055: 64, 10505: 64, 22548: 64, 8814: 64, 126982: 64, 36744: 64, 125510: 64, 11030: 64, 2555: 64, 6693: 64, 388

In [ ]:
# tokenizer_name = "Translation-EnKo/exaone3-instrucTrans-v2-enko-7.8b"

data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/data.csv"
max_token_length = 512
batch_size_train = 64
num_workers = 4
batch_size_val = 64
batch_size_test = 64
val_num_workers = 4
start_idx = 1
end_idx = 361
padding_idx = 0
unk_idx = 3
seed = 42

In [ ]:
class LoadersLGEXAENKO():
    def __init__(
            self,
            data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/data.csv",
            max_token_length = 512,
            batch_size_train = 8,
            num_workers = 4,
            batch_size_val = 4,
            batch_size_test = 4,
            val_num_workers = 4,
            start_idx = 64100, 
            end_idx = 1, 
            padding_idx = 0, 
            unk_idx = 2,
            seed = 42,
    ):
        self.start_idx = start_idx
        self.end_idx = end_idx
        self.padding_idx = padding_idx
        self.unk_idx = unk_idx

        # 1) 데이터셋 로드
        dataset = load_dataset("csv", data_files=data_path)['train']
        # AI hub 한국어-영어 번역(병렬) 말뭉치 데이터셋
        # kor, en, cat 3개의 칼럼으로 구성

        # 2) 카테고리 컬럼의 고유 클래스 찾아서 ClassLabel 객체 생성
        unique_classes = dataset.unique('cat')  
        # 'cat' 열에 문장 분류 
        # 0: 구어체
        # 1: 대화체
        # 2: 문어체_뉴스
        # 3: 문어체_한국문화
        # 4: 문어체_조례
        # 5: 문어체_지자체웹사이트

        print(f"==>> unique_classes: {unique_classes}")
        class_label = ClassLabel(names=unique_classes)

        # 3) 기존 컬럼 타입 변경 (캐스팅)
        dataset = dataset.cast_column('cat', class_label)

        # 4) stratify_by_column으로 분할
        train_validtest = dataset.train_test_split(test_size=0.2, seed=seed, stratify_by_column='cat')
        valid_test = train_validtest['test'].train_test_split(test_size=0.1, seed=seed, stratify_by_column='cat')

        dataset_dict = DatasetDict({
            'train': train_validtest['train'],
            'validation': valid_test['train'],
            'test': valid_test['test']
        })

        # print(dataset_dict)

        NUM_CPU = multiprocessing.cpu_count()
        # print(f"==>> NUM_CPU: {NUM_CPU}")

        # self.tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-ko-en")
        # @@@ 점포, 만료 등의 단어가 <unk>인 문제 발견 => 다른 토크나이저 사용?
        self.tokenizer = AutoTokenizer.from_pretrained("Translation-EnKo/exaone3-instrucTrans-v2-enko-7.8b")

        special_tokens_dict = {'pad_token': '[PAD]'}
        self.tokenizer.add_special_tokens(special_tokens_dict)
        
        print(self.tokenizer.all_special_ids)
        print(self.tokenizer.all_special_tokens)

        print(f"==>> self.tokenizer.model_max_length: {self.tokenizer.model_max_length}")

        print(f"==>> len(self.tokenizer): {len(self.tokenizer)}")

        self.max_token_length = min(max_token_length, self.tokenizer.model_max_length)

        # partial을 이용해 tokenizer, max_token_length 인자 고정
        cetf = partial(convert_examples_to_features, tokenizer=self.tokenizer, max_token_length=self.max_token_length)
        # @@@ convert_examples_to_features함수에서 examples가 첫번쨰 인자가 아니면 
        # @@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서 
        # @@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러 발생

        self.datasets = dataset_dict.map(
                                cetf,
                                # lambda examples: convert_examples_to_features(examples, tokenizer=self.tokenizer, max_token_length=self.max_token_length),
                                batched=True,
                                # 원 데이터 'en', 'kor', 'cat' 등의 칼럼을 지우려면
                                # remove_columns 인자 사용
                                # remove_columns=dataset_dict["train"].column_names,
                                num_proc=NUM_CPU)

        print(f"==>> self.datasets: {self.datasets}")

        self.train_set = self.datasets['train']
        self.val_set = self.datasets['validation']
        self.test_set = self.datasets['test']

        c_fn = partial(collate_fn, start_idx=self.start_idx, end_idx=self.end_idx, padding_idx=self.padding_idx, unk_idx=self.unk_idx)

        self.loader_train = DataLoader(self.train_set, batch_size=batch_size_train, collate_fn=c_fn, shuffle=True, num_workers=num_workers, pin_memory=True)
        # 학습시에만 shuffle=True
        self.loader_val = DataLoader(self.val_set, batch_size=batch_size_val, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)
        self.loader_test = DataLoader(self.test_set, batch_size=batch_size_test, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)

# def convert_examples_to_features(tokenizer, max_token_length, examples):
# @@@@@@@@@ examples가 첫번쨰 인자가 아니면 
# @@@@@@@@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서
# @@@@@@@@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러가 발생한다
def convert_examples_to_features(examples, tokenizer, max_token_length):
    model_inputs = tokenizer(examples['kor'],
                             text_target=examples['en'],
                             max_length=max_token_length, truncation=True)
    # 여기서 첫번째 인자와 두번째 인자의 순서를 바꾸면 한영 번역 대신 영한 번역용으로 인풋과 타겟이 토큰화된다
    return model_inputs


def collate_fn(batch, start_idx, end_idx, padding_idx, unk_idx):
    # print('Original:\n', batch)
    # print("".center(50, "-"))
    # batch는 [{'kor':..., 'en':..., 'cat':숫자, 'input_ids':[...], 'attention_mask':[1, ...], 'labels': [...]}, ...] 형태
    
    # keys = batch[0].keys()
    keys = ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels']
    # print(f"==>> keys: {keys}")
    # print("".center(50, "-"))
    
    # new_batch = {k:[] for k in keys}
    # new_batch['decoder_inputs'] = []
    
    # for b in batch:
    #     for k,v in b.items():
    #         if k == 'input_ids' or k == 'attention_mask':
    #             new_batch[k].append(torch.LongTensor(v))
    #         elif k == 'labels':
    #             new_batch[k].append(torch.LongTensor(v))
    #             new_batch['decoder_inputs'].append(torch.LongTensor([65001] + v[:-1]))
    #         else:
    #             new_batch[k].append(v)

    # key값별로 value 다 모으기
    new_batch = {k:[b[k] for b in batch] for k in keys}

    # list들 LongTensor로 변환
    new_batch['decoder_inputs'] = [torch.LongTensor([start_idx] + label[:-1]) for label in new_batch['labels']]
    # print(f"==>> new_batch['decoder_inputs']: {new_batch['decoder_inputs']}")
    new_batch['input_ids'] = [torch.LongTensor(inp) for inp in new_batch['input_ids']]
    new_batch['labels'] = [torch.LongTensor(label) for label in new_batch['labels']]
    new_batch['attention_mask'] = [torch.LongTensor(mask) for mask in new_batch['attention_mask']]

    new_batch['ntokens'] = sum([l.numel() for l in new_batch['labels']])

    # decoder input의 attention mask 생성
    new_batch['decoder_mask'] = [torch.ones_like(d_inp, dtype=torch.long) for d_inp in new_batch['decoder_inputs']]


    # 각 input과 target 텐서를 패딩
    padded_inputs = pad_sequence(new_batch['input_ids'], batch_first=True, padding_value=padding_idx)
    new_batch['input_ids'] = padded_inputs
    padded_decoder_inputs = pad_sequence(new_batch['decoder_inputs'], batch_first=True, padding_value=padding_idx)
    new_batch['decoder_inputs'] = padded_decoder_inputs
    padded_targets = pad_sequence(new_batch['labels'], batch_first=True, padding_value=padding_idx)
    new_batch['labels'] = padded_targets

    # attention 마스크는 패딩(padding_idx) 대신 False(0)을 입력
    padded_masks = pad_sequence(new_batch['attention_mask'], batch_first=True, padding_value=0)
    new_batch['attention_mask'] = padded_masks

    padded_d_masks = pad_sequence(new_batch['decoder_mask'], batch_first=True, padding_value=0)
    new_batch['decoder_mask'] = padded_d_masks
    
    return new_batch

In [ ]:
loaders = LoadersLGEXAENKO(
    data_path=data_path,
    max_token_length=max_token_length,
    batch_size_train=batch_size_train,
    num_workers=num_workers,
    batch_size_val=batch_size_val,
    batch_size_test=batch_size_test,
    val_num_workers=val_num_workers,
    start_idx=start_idx,
    end_idx=end_idx,
    padding_idx=padding_idx,
    unk_idx=unk_idx,
    seed=seed,
)

==>> unique_classes: [2, 4, 1, 0, 3, 5]
[1, 361, 3, 0]
['[BOS]', '[|endofturn|]', '[UNK]', '[PAD]']
==>> self.tokenizer.model_max_length: 1000000000000000019884624838656
==>> len(self.tokenizer): 102400
==>> self.datasets: DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1281934
    })
    validation: Dataset({
        features: ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 288435
    })
    test: Dataset({
        features: ['kor', 'en', 'cat', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 32049
    })
})

In [ ]:
print(f"==>> unk_idx: {unk_idx}")

input_total = Counter([])
target_total = Counter([])
# total

num_batches_train = len(loaders.loader_train)

for step, batch in tqdm(
    enumerate(loaders.loader_train),
    total=num_batches_train,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total += input_count
    target_total += target_count

    # if step == 10:
    #     break

print(f"==>> input_total: {input_total}")
print(f"==>> target_total: {target_total}")
print(f"==>> input_total[unk_idx]: {input_total[unk_idx]}")
print(f"==>> target_total[unk_idx]: {target_total[unk_idx]}")

input_total_val = Counter([])
target_total_val = Counter([])
# total

num_batches_val = len(loaders.loader_val)

for step, batch in tqdm(
    enumerate(loaders.loader_val),
    total=num_batches_val,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_val += input_count
    target_total_val += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_val: {input_total_val}")
print(f"==>> target_total_val: {target_total_val}")
print(f"==>> input_total_val[unk_idx]: {input_total_val[unk_idx]}")
print(f"==>> target_total_val[unk_idx]: {target_total_val[unk_idx]}")


input_total_test = Counter([])
target_total_test = Counter([])
# total

num_batches_test = len(loaders.loader_test)

for step, batch in tqdm(
    enumerate(loaders.loader_test),
    total=num_batches_test,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_test += input_count
    target_total_test += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_test: {input_total_test}")
print(f"==>> target_total_test: {target_total_test}")
print(f"==>> input_total_test[unk_idx]: {input_total_test[unk_idx]}")
print(f"==>> target_total_test[unk_idx]: {target_total_test[unk_idx]}")

==>> unk_idx: 3

100%|██████████| 20031/20031 [02:01<00:00, 164.78it/s]

==>> input_total: Counter({0: 51439188, 375: 1253775, 696: 932057, 657: 901982, 634: 880598, 2373: 712170, 643: 631781, 730: 626493, 582: 604052, 905: 525739, 732: 512419, 4605: 509293, 373: 436753, 773: 425953, 1130: 331095, 1075: 322202, 378: 321767, 853: 299924, 377: 277422, 41728: 265790, 13456: 265105, 379: 244175, 1548: 211102, 924: 205154, 715: 200305, 2662: 197434, 1060: 176567, 720: 158742, 868: 155171, 1371: 145086, 798: 143460, 698: 139901, 1222: 135246, 380: 134139, 2030: 133787, 999: 127507, 858: 125226, 2870: 124025, 48199: 118789, 369: 115016, 370: 114409, 382: 111850, 13452: 105417, 40379: 105183, 2957: 104931, 18420: 104661, 1965: 103937, 16524: 99859, 2376: 98248, 712: 98247, 17005: 97047, 381: 96140, 50747: 94665, 722: 91333, 838: 91316, 1488: 90088, 14178: 88100, 9583: 85093, 2171: 82365, 1145: 79854, 721: 77973, 383: 77831, 386: 76196, 1043: 75422, 1877: 73660, 385: 72259, 384: 70902, 942: 70664, 691: 69683, 4264: 69681, 97300: 69562, 392: 66071, 1107: 65758, 2751: 63164, 3401: 61277, 1367: 59827, 916: 59000, 5623: 57446, 1522: 56512, 650: 56461, 1216: 56366, 941: 56269, 10348: 53809, 76876: 52620, 764: 52328, 954: 51531, 855: 51229, 22226: 51112, 2425: 50705, 902: 50166, 1823: 49908, 2597: 49797, 1325: 48709, 4560: 47911, 1058: 47746, 816: 47697, 1137: 47610, 19850: 47306, 823: 45931, 740: 45861, 1050: 45622, 2042: 45306, 837: 44901, 1126: 44518, 2047: 43840, 2517: 43698, 1255: 42674, 1374: 42571, 3885: 42376, 1105: 42037, 41281: 41923, 1023: 40880, 600: 40611, 1042: 40539, 987: 40183, 1210: 40064, 1180: 39947, 970: 39309, 765: 39191, 2327: 38991, 15913: 38606, 6734: 38286, 799: 38186, 1081: 37933, 76766: 37406, 1119: 37206, 1902: 37016, 887: 36269, 366: 36084, 1416: 35988, 1466: 35855, 1774: 35515, 13910: 34731, 932: 33992, 800: 33678, 1668: 32476, 10996: 31730, 1047: 31220, 37728: 31173, 1995: 30595, 16559: 30514, 1595: 30356, 21212: 30162, 3157: 29952, 1490: 29941, 1051: 29906, 2414: 29789, 1080: 29321, 2878: 29042, 2364: 27477, 1094: 27432, 2110: 27345, 3478: 27031, 3051: 26866, 789: 26824, 1084: 26709, 955: 26699, 1271: 25851, 1280: 25536, 1104: 25384, 1437: 25132, 1159: 25055, 3379: 24872, 1856: 24717, 1810: 24565, 1818: 24551, 961: 24338, 1029: 24316, 2388: 23951, 1600: 23577, 3100: 23437, 4232: 23295, 2379: 23165, 5718: 23163, 846: 22789, 2888: 22772, 1418: 22590, 3050: 22475, 2329: 22280, 2372: 22252, 3125: 22238, 15169: 22204, 4022: 22057, 3376: 21890, 54689: 21750, 2424: 21689, 1821: 21650, 1740: 21598, 2736: 21164, 1579: 21068, 3718: 20825, 1452: 20725, 30885: 20721, 1430: 20516, 14010: 20437, 9099: 20394, 2472: 20034, 3163: 20031, 1002: 19991, 2104: 19966, 1332: 19916, 881: 19571, 3672: 19424, 1254: 19383, 2409: 19056, 1331: 19035, 1559: 18970, 96266: 18790, 1590: 18744, 3172: 18738, 1353: 18729, 1022: 18606, 2126: 18466, 2927: 18389, 22773: 18359, 2775: 18289, 37891: 18196, 901: 18064, 1495: 18055, 964: 18035, 19890: 18027, 21046: 18015, 5086: 17973, 2879: 17952, 1146: 17946, 1336: 17886, 3449: 17815, 3637: 17757, 41655: 17561, 374: 17517, 16519: 17507, 4978: 17431, 2491: 17397, 2626: 17378, 869: 17307, 2886: 17263, 28612: 17212, 5153: 17101, 1780: 17095, 2318: 17088, 80649: 17060, 1546: 17032, 3321: 16958, 2876: 16938, 8052: 16912, 2069: 16895, 1018: 16845, 1617: 16787, 6332: 16780, 1694: 16640, 5998: 16613, 9858: 16592, 2534: 16574, 1031: 16557, 3336: 16470, 35604: 16354, 8235: 16112, 1597: 16098, 1881: 15999, 2827: 15970, 3117: 15695, 1052: 15688, 844: 15658, 1799: 15634, 3864: 15619, 1360: 15570, 2841: 15525, 3347: 15521, 6015: 15504, 1286: 15467, 1053: 15429, 5847: 15350, 1225: 15201, 4415: 15125, 713: 15067, 3328: 15038, 2448: 14988, 4767: 14953, 5299: 14918, 69893: 14892, 24040: 14807, 1719: 14763, 2553: 14740, 760: 14731, 7408: 14659, 27506: 14612, 3428: 14590, 2572: 14586, 3216: 14495, 38045: 14465, 59985: 14462, 2618: 14441, 56415: 14375, 15585: 14355, 1413: 14346, 3950: 14160, 4385: 14142, 3539: 14088, 830: 14085, 6912: 13952, 3685: 13944, 1763: 13906, 1899: 13849, 975: 13832, 15536: 13794, 733: 13694, 4308: 13597, 3460: 13574, 977: 13514, 4463: 13414, 11326: 13411, 1979: 13366, 7059: 13342, 2015: 13341, 482: 13322, 4490: 13206, 5275: 13200, 5838: 13165, 4666: 13113, 8393: 13008, 4373: 12987, 2257: 12984, 3492: 12973, 4288: 12911, 1369: 12907, 2645: 12870, 1553: 12861, 1647: 12839, 1736: 12813, 2022: 12800, 8454: 12748, 3311: 12737, 1457: 12700, 4559: 12685, 4078: 12614, 1092: 12592, 6318: 12513, 10538: 12402, 3523: 12360, 25082: 12356, 834: 12294, 1794: 12274, 694: 12219, 1229: 12154, 53641: 12149, 4806: 12140, 26111: 12138, 5071: 12119, 11499: 12118, 46461: 12118, 1398: 12089, 2048: 12078, 6487: 12074, 1326: 12024, 2674: 12018, 17324: 11987, 30761: 11970, 3027: 11962, 7087: 11914, 78001: 11869, 3754: 11865, 1162: 11829, 1015: 11809, 1775: 11771, 5457: 11764, 4024: 11696, 2034: 11693, 5336: 11599, 363: 11577, 15282: 11486, 2710: 11484, 4484: 11466, 2785: 11439, 4504: 11434, 1420: 11416, 9768: 11412, 1645: 11403, 5414: 11368, 6697: 11360, 1113: 11343, 15418: 11334, 1400: 11315, 3070: 11296, 3540: 11131, 5985: 11092, 4349: 11049, 1673: 11047, 3903: 11046, 2453: 11038, 5159: 11022, 2963: 10978, 3325: 10913, 3231: 10909, 1523: 10904, 4003: 10902, 28498: 10854, 1629: 10838, 2781: 10825, 5292: 10808, 4169: 10808, 8726: 10787, 1008: 10772, 1658: 10753, 2820: 10722, 22610: 10711, 1996: 10691, 3570: 10642, 3788: 10594, 2904: 10526, 4933: 10525, 5256: 10513, 2102: 10507, 4996: 10465, 1682: 10460, 5780: 10453, 1921: 10442, 1147: 10383, 3755: 10352, 5422: 10341, 3670: 10341, 6138: 10278, 2718: 10276, 1840: 10221, 2885: 10211, 1858: 10205, 1244: 10191, 43202: 10146, 36090: 10133, 3083: 10114, 1867: 10106, 8939: 10088, 3071: 10087, 826: 10079, 1202: 10074, 3626: 10073, 7457: 10055, 5010: 10045, 28726: 10027, 2802: 10017, 2628: 10010, 1235: 10004, 1061: 9992, 30695: 9979, 4408: 9949, 3916: 9923, 4302: 9914, 8221: 9907, 22556: 9895, 1985: 9872, 1766: 9805, 3399: 9772, 2389: 9760, 1938: 9758, 3235: 9751, 1384: 9749, 10313: 9740, 5568: 9738, 25755: 9706, 38069: 9700, 21701: 9688, 2036: 9683, 19730: 9681, 6296: 9681, 6747: 9668, 3713: 9656, 6327: 9646, 1710: 9602, 3184: 9582, 80923: 9560, 22692: 9558, 4880: 9547, 7360: 9540, 7517: 9536, 4394: 9501, 2311: 9501, 1883: 9480, 1481: 9450, 3596: 9440, 6453: 9429, 1282: 9414, 2588: 9412, 8397: 9376, 4125: 9365, 5720: 9354, 931: 9349, 2560: 9349, 1562: 9319, 5088: 9294, 1644: 9286, 1411: 9268, 8713: 9227, 5210: 9184, 9429: 9163, 2575: 9146, 8291: 9092, 14708: 9078, 25058: 9070, 1698: 9063, 780: 9030, 5371: 8997, 3830: 8990, 3758: 8962, 2323: 8952, 4289: 8931, 2430: 8911, 4650: 8908, 2092: 8892, 1949: 8870, 1873: 8861, 896: 8839, 4100: 8809, 1212: 8785, 1376: 8781, 1578: 8773, 4703: 8724, 5837: 8712, 3365: 8704, 37817: 8688, 4982: 8673, 8789: 8660, 7215: 8650, 5696: 8643, 1859: 8636, 4824: 8616, 5659: 8604, 1110: 8591, 10079: 8583, 3090: 8580, 32918: 8566, 2805: 8530, 1415: 8525, 3223: 8523, 1862: 8518, 926: 8495, 47073: 8492, 3257: 8479, 2139: 8470, 1618: 8465, 1265: 8454, 2666: 8449, 1469: 8447, 6589: 8439, 2109: 8433, 7572: 8420, 6908: 8394, 2733: 8391, 4576: 8382, 7299: 8379, 3745: 8367, 7887: 8366, 10368: 8358, 4477: 8356, 368: 8332, 1349: 8312, 4857: 8297, 5282: 8280, 1637: 8268, 962: 8229, 1257: 8217, 4840: 8215, 5575: 8201, 3091: 8199, 3656: 8199, 5197: 8185, 1040: 8184, 7121: 8171, 5653: 8157, 6101: 8146, 4854: 8123, 7257: 8123, 6105: 8123, 2705: 8116, 3063: 8111, 1824: 8075, 5552: 8074, 3726: 8052, 8292: 8048, 7015: 8044, 2739: 8036, 33623: 8035, 2252: 8029, 3974: 8022, 6670: 8016, 1526: 8008, 4949: 8005, 4954: 7989, 3627: 7985, 2605: 7974, 2175: 7968, 4130: 7967, 7956: 7965, 2578: 7961, 1619: 7948, 1509: 7940, 2051: 7940, 3705: 7936, 1811: 7913, 8254: 7896, 5135: 7893, 775: 7844, 6582: 7835, 1983: 7829, 13147: 7814, 5149: 7798, 7587: 7778, 1679: 7774, 7243: 7741, 34593: 7725, 6389: 7714, 3004: 7692, 6707: 7686, 4872: 7685, 3118: 7679, 5106: 7660, 5569: 7658, 5480: 7640, 7245: 7616, 4986: 7613, 31882: 7598, 2764: 7592, 4536: 7556, 6696: 7549, 8722: 7529, 5876: 7526, 3728: 7521, 6033: 7477, 1175: 7469, 2220: 7468, 5930: 7463, 6801: 7456, 9384: 7426, 5954: 7417, 2131: 7414, 3550: 7403, 4532: 7377, 4762: 7369, 2690: 7344, 5865: 7343, 2818: 7335, 1580: 7335, 3562: 7330, 8296: 7309, 5547: 7307, 4641: 7306, 2431: 7301, 2485: 7256, 3164: 7255, 2469: 7229, 1156: 7216, 5213: 7196, 1931: 7195, 2703: 7192, 3504: 7191, 769: 7191, 2799: 7186, 4060: 7144, 27359: 7126, 1541: 7100, 6026: 7099, 5690: 7088, 6181: 7083, 6951: 7078, 6720: 7060, 5266: 7048, 7858: 7045, 1030: 7044, 2088: 7012, 3443: 7005, 4907: 6985, 7157: 6984, 2247: 6977, 2566: 6971, 3545: 6969, 6948: 6965, 1813: 6956, 4038: 6952, 56867: 6950, 1803: 6948, 5133: 6937, 1615: 6922, 1200: 6917, 915: 6908, 6037: 6895, 15220: 6881, 6581: 6878, 3303: 6873, 3971: 6845, 4516: 6839, 2180: 6831, 1728: 6827, 36309: 6814, 3930: 6802, 848: 6790, 2086: 6787, 3497: 6785, 2264: 6775, 4677: 6766, 1201: 6757, 3252: 6757, 3771: 6737, 69597: 6733, 1151: 6707, 6034: 6688, 2263: 6682, 90042: 6682, 10739: 6666, 3892: 6665, 9808: 6660, 12621: 6655, 5434: 6650, 94493: 6630, 4679: 6626, 5639: 6620, 5073: 6611, 5359: 6601, 2052: 6600, 1323: 6586, 5005: 6571, 6521: 6566, 1822: 6565, 4503: 6528, 6784: 6521, 2230: 6519, 2632: 6515, 5789: 6511, 13908: 6500, 17297: 6480, 1451: 6477, 10326: 6476, 11316: 6476, 12418: 6471, 2266: 6465, 1727: 6463, 2211: 6454, 1556: 6429, 1846: 6429, 10724: 6428, 1868: 6419, 4850: 6418, 1934: 6415, 7924: 6401, 8405: 6397, 4387: 6395, 33377: 6374, 3331: 6353, 8536: 6341, 3577: 6338, 3239: 6328, 12527: 6327, 4313: 6326, 6618: 6320, 2939: 6320, 5304: 6316, 34445: 6307, 4659: 6302, 4648: 6297, 9234: 6289, 2351: 6289, 12438: 6286, 7111: 6277, 5788: 6264, 5262: 6240, 4526: 6233, 1142: 6233, 3483: 6187, 6031: 6181, 9257: 6179, 1352: 6174, 3778: 6166, 36427: 6166, 78151: 6157, 4649: 6156, 8023: 6145, 7686: 6141, 4573: 6132, 22241: 6122, 3730: 6098, 3838: 6097, 438: 6083, 2447: 6082, 1744: 6077, 27574: 6063, 2068: 6061, 1144: 6060, 3196: 6035, 1944: 6031, 1910: 6012, 1990: 6012, 52132: 6005, 2540: 6004, 11422: 5982, 1599: 5982, 27484: 5975, 4817: 5975, 3897: 5954, 1154: 5951, 10018: 5933, 5833: 5931, 5717: 5922, 1936: 5921, 3358: 5892, 2610: 5890, 3481: 5885, 2299: 5884, 2419: 5879, 1777: 5871, 11240: 5867, 3028: 5861, 1952: 5859, 1067: 5844, 5675: 5843, 50294: 5840, 5184: 5833, 785: 5830, 8800: 5827, 9598: 5825, 11175: 5814, 4630: 5814, 17200: 5806, 5204: 5805, 10876: 5797, 1721: 5779, 5224: 5778, 9504: 5777, 7799: 5773, 9148: 5772, 4786: 5772, 1582: 5766, 8792: 5761, 6893: 5754, 11685: 5744, 5445: 5735, 5616: 5732, 1385: 5720, 9846: 5717, 3329: 5716, 33861: 5715, 4148: 5702, 2512: 5679, 3173: 5660, 6288: 5638, 6016: 5632, 6003: 5630, 3187: 5620, 2993: 5607, 74914: 5606, 14954: 5605, 6698: 5604, 1956: 5601, 8952: 5600, 5255: 5597, 6507: 5588, 5797: 5585, 7723: 5583, 14976: 5578, 3893: 5577, 10503: 5576, 71181: 5574, 4262: 5572, 2437: 5561, 1977: 5557, 1510: 5556, 7084: 5553, 18106: 5550, 9853: 5521, 4400: 5516, 3827: 5516, 16301: 5516, 2502: 5514, 3810: 5507, 2479: 5502, 1922: 5501, 3519: 5491, 97666: 5486, 9239: 5471, 1182: 5453, 5293: 5445, 4270: 5442, 5614: 5432, 3867: 5426, 2619: 5417, 3370: 5416, 3108: 5411, 29082: 5407, 26331: 5400, 2062: 5399, 1601: 5386, 3253: 5380, 48413: 5364, 2592: 5352, 2112: 5348, 12730: 5343, 7969: 5341, 5019: 5328, 2289: 5320, 10176: 5314, 1907: 5314, 6843: 5313, 9209: 5312, 2515: 5310, 1246: 5306, 11030: 5290, 3327: 5290, 8584: 5289, 1139: 5279, 1560: 5273, 4375: 5271, 6245: 5270, 5333: 5257, 8229: 5249, 10443: 5220, 6738: 5197, 11703: 5197, 1208: 5184, 29042: 5182, 9425: 5178, 6264: 5166, 2401: 5164, 1472: 5163, 3323: 5158, 6797: 5153, 5776: 5152, 10752: 5152, 4669: 5146, 5465: 5144, 79469: 5140, 4019: 5119, 3446: 5116, 75599: 5115, 20271: 5112, 8145: 5100, 12367: 5099, 2128: 5098, 5630: 5088, 18101: 5083, 6539: 5078, 2316: 5072, 5134: 5071, 2326: 5070, 1565: 5055, 10395: 5055, 3585: 5047, 8675: 5040, 9906: 5036, 31172: 5031, 1992: 5021, 2325: 5015, 4985: 5008, 8171: 4997, 7773: 4990, 5731: 4987, 4198: 4979, 1841: 4970, 3644: 4944, 32536: 4940, 7135: 4931, 5300: 4929, 3753: 4925, 7228: 4918, 10491: 4917, 11710: 4900, 948: 4893, 8901: 4892, 5506: 4883, 5415: 4877, 7952: 4875, 2843: 4872, 29547: 4857, 2664: 4856, 1756: 4850, 4083: 4847, 6001: 4834, 9791: 4823, 4208: 4819, 54598: 4806, 2960: 4801, 2420: 4799, 2833: 4793, 3696: 4791, 6410: 4790, 1898: 4785, 7632: 4775, 9472: 4773, 7820: 4764, 3101: 4761, 12099: 4758, 4919: 4758, 2817: 4749, 8224: 4745, 8851: 4739, 1662: 4731, 2029: 4727, 64101: 4719, 6066: 4698, 12104: 4698, 5999: 4669, 5821: 4659, 1747: 4655, 1465: 4653, 3053: 4642, 65347: 4636, 2500: 4635, 11137: 4629, 6588: 4616, 4344: 4616, 1387: 4615, 66582: 4613, 5309: 4607, 3675: 4607, 29015: 4604, 2613: 4598, 4186: 4594, 1124: 4577, 1667: 4576, 704: 4575, 9177: 4572, 38534: 4566, 44065: 4562, 13076: 4559, 1125: 4558, 1260: 4554, 2210: 4539, 6279: 4535, 5577: 4527, 10505: 4524, 9365: 4519, 8357: 4517, 1173: 4517, 6600: 4517, 9048: 4510, 2470: 4498, 8760: 4495, 7485: 4491, 4045: 4491, 9687: 4490, 14547: 4485, 8065: 4476, 9496: 4475, 6178: 4474, 1903: 4473, 8923: 4466, 5615: 4464, 12100: 4463, 9350: 4459, 8040: 4458, 20515: 4456, 8857: 4454, 10701: 4435, 7482: 4434, 2361: 4430, 6610: 4426, 7639: 4422, 3882: 4417, 3833: 4414, 5443: 4413, 63535: 4409, 3276: 4407, 9062: 4404, 18093: 4404, 11073: 4403, 1987: 4402, 3387: 4401, 4444: 4401, 992: 4399, 1226: 4399, 4843: 4393, 2434: 4392, 12025: 4391, 4550: 4390, 16596: 4388, 1299: 4386, 27390: 4383, 9441: 4379, 4311: 4378, 12230: 4372, 5429: 4368, 1264: 4367, 2625: 4367, 69237: 4365, 5372: 4339, 24932: 4336, 7770: 4322, 2134: 4315, 28675: 4307, 29230: 4306, 6226: 4302, 5957: 4301, 1955: 4288, 1976: 4288, 5601: 4287, 8771: 4286, 45514: 4286, 5810: 4283, 3093: 4280, 61419: 4280, 10572: 4280, 32784: 4272, 9023: 4266, 3129: 4262, 3576: 4260, 3008: 4257, 6888: 4241, 2024: 4216, 4694: 4213, 8673: 4212, 9811: 4211, 2374: 4211, 6115: 4206, 5806: 4204, 1302: 4200, 8937: 4197, 4701: 4196, 10112: 4182, 13311: 4181, 7660: 4180, 9759: 4173, 2256: 4172, 4214: 4172, 5355: 4170, 7259: 4166, 6313: 4164, 1337: 4155, 2129: 4155, 3055: 4148, 5424: 4147, 14737: 4145, 12080: 4145, 1696: 4139, 10325: 4138, 6329: 4135, 2158: 4127, 9997: 4123, 12452: 4121, 17663: 4119, 11795: 4116, 13613: 4116, 6405: 4114, 21715: 4081, 2574: 4081, 4436: 4078, 7626: 4074, 10464: 4070, 7109: 4069, 4830: 4064, 8651: 4060, 2873: 4058, 1564: 4047, 13332: 4046, 12072: 4045, 7751: 4045, 87460: 4037, 10847: 4037, 5905: 4035, 8898: 4031, 11989: 4022, 8990: 4017, 7630: 4014, 83310: 4013, 4591: 4013, 54065: 4010, 5830: 4007, 7369: 4006, 10916: 3999, 688: 3999, 1897: 3999, 8491: 3997, 4826: 3993, 2635: 3992, 6620: 3990, 6783: 3988, 1587: 3988, 37946: 3987, 2583: 3982, 4268: 3982, 2178: 3980, 4084: 3978, 10021: 3975, 9898: 3973, 3075: 3973, 1278: 3972, 6401: 3971, 9457: 3970, 5233: 3964, 4064: 3962, 7683: 3957, 10551: 3955, 6196: 3954, 86274: 3953, 6496: 3952, 1339: 3951, 6850: 3948, 34284: 3944, 5222: 3944, 11090: 3942, 2836: 3927, 6297: 3925, 35714: 3922, 13018: 3920, 7317: 3917, 6440: 3903, 5714: 3901, 27350: 3900, 1504: 3896, 2041: 3881, 10602: 3881, 9952: 3878, 3609: 3877, 29241: 3869, 5927: 3866, 3317: 3866, 7110: 3861, 3764: 3854, 53387: 3854, 4177: 3852, 1531: 3839, 31747: 3833, 4160: 3830, 6675: 3830, 8259: 3828, 6674: 3825, 13625: 3822, 4937: 3812, 3693: 3810, 4150: 3809, 2804: 3809, 6135: 3806, 5346: 3803, 42914: 3797, 9860: 3793, 11006: 3791, 7104: 3789, 12129: 3788, 3623: 3781, 6854: 3779, 11121: 3778, 65573: 3777, 8151: 3775, 2793: 3774, 7460: 3772, 7608: 3768, 2920: 3767, 9386: 3766, 4998: 3758, 4841: 3749, 6319: 3748, 5080: 3747, 18314: 3745, 6433: 3742, 8256: 3739, 8099: 3739, 54417: 3734, 11347: 3728, 16170: 3725, 7936: 3720, 9045: 3717, 6414: 3717, 3790: 3712, 29635: 3711, 4028: 3705, 8580: 3702, 42864: 3702, 4510: 3700, 7322: 3700, 15052: 3699, 6873: 3694, 23356: 3689, 6132: 3688, 62036: 3688, 9642: 3682, 16805: 3677, 6490: 3670, 5241: 3669, 1620: 3669, 1356: 3666, 7419: 3664, 22356: 3660, 6086: 3659, 1951: 3658, 9806: 3655, 1726: 3646, 2563: 3643, 1461: 3641, 3086: 3639, 30453: 3635, 19800: 3634, 12466: 3633, 7285: 3626, 1157: 3626, 7254: 3624, 18407: 3621, 8551: 3619, 11821: 3618, 1566: 3617, 5795: 3613, 1368: 3610, 7216: 3610, 7374: 3604, 7625: 3601, 11864: 3600, 15001: 3594, 5081: 3593, 400: 3588, 1310: 3587, 5290: 3584, 1529: 3580, 3701: 3575, 2313: 3575, 5553: 3571, 9988: 3569, 1654: 3565, 7081: 3562, 1738: 3558, 819: 3555, 5962: 3550, 12103: 3547, 7075: 3546, 3868: 3538, 4935: 3537, 6065: 3536, 6693: 3534, 26450: 3533, 17728: 3527, 7082: 3527, 6535: 3525, 65144: 3521, 989: 3513, 40480: 3512, 1588: 3508, 9019: 3505, 3981: 3505, 5198: 3502, 3996: 3491, 34619: 3488, 3405: 3488, 13432: 3487, 4269: 3485, 16278: 3484, 16976: 3483, 53696: 3481, 11856: 3479, 1770: 3478, 3016: 3478, 10921: 3472, 6810: 3472, 5002: 3466, 5763: 3464, 1888: 3463, 5376: 3463, 1689: 3462, 11962: 3460, 7794: 3458, 50280: 3458, 13508: 3455, 8434: 3450, 8038: 3444, 9739: 3443, 9757: 3441, 27846: 3432, 13554: 3428, 38835: 3417, 14519: 3416, 2272: 3415, 5767: 3406, 17396: 3404, 1485: 3402, 10198: 3398, 7860: 3396, 7154: 3395, 96565: 3395, 9523: 3394, 2353: 3394, 8015: 3392, 806: 3386, 95483: 3384, 7546: 3382, 9060: 3375, 5903: 3374, 8687: 3372, 13905: 3370, 8877: 3368, 5610: 3368, 46040: 3367, 46232: 3362, 5089: 3357, 1953: 3351, 2222: 3351, 2055: 3349, 5805: 3349, 13527: 3348, 2516: 3345, 6106: 3341, 3662: 3341, 16116: 3336, 13139: 3336, 7524: 3333, 5772: 3331, 10756: 3331, 13419: 3330, 1006: 3330, 13072: 3328, 32607: 3328, 11997: 3326, 9971: 3325, 28811: 3325, 1172: 3323, 3924: 3323, 15329: 3323, 5161: 3321, 11720: 3319, 10084: 3315, 7319: 3314, 8337: 3314, 9134: 3314, 14912: 3312, 14504: 3310, 2368: 3309, 66527: 3308, 7747: 3308, 4533: 3304, 4488: 3303, 11996: 3301, 3826: 3301, 1568: 3292, 7818: 3291, 32046: 3291, 2356: 3287, 6241: 3285, 13383: 3284, 3782: 3284, 21231: 3282, 6660: 3282, 9293: 3282, 1880: 3282, 11477: 3281, 96808: 3280, 876: 3280, 7739: 3279, 6667: 3276, 3102: 3274, 5769: 3269, 12869: 3267, 8502: 3261, 7704: 3256, 5757: 3254, 10015: 3253, 8697: 3253, 10902: 3253, 8574: 3252, 2107: 3250, 2938: 3247, 893: 3243, 8375: 3242, 12528: 3241, 18269: 3240, 7489: 3239, 6451: 3238, 11151: 3238, 7667: 3237, 10823: 3234, 33373: 3226, 21154: 3223, 11782: 3219, 6137: 3219, 18893: 3218, 3794: 3217, 98293: 3216, 2474: 3211, 4558: 3209, 8897: 3208, 6576: 3208, 13140: 3185, 8147: 3182, 26361: 3180, 8808: 3178, 4328: 3176, 8510: 3176, 1296: 3171, 5146: 3169, 6153: 3167, 4278: 3159, 34797: 3158, 67973: 3157, 8311: 3146, 7879: 3143, 2113: 3143, 88088: 3136, 3236: 3134, 6665: 3131, 5647: 3128, 11783: 3127, 25253: 3127, 9007: 3125, 14053: 3121, 5809: 3120, 7967: 3120, 3829: 3118, 32051: 3117, 1547: 3115, 16356: 3113, 7427: 3113, 5582: 3100, 13120: 3099, 4271: 3099, 23581: 3098, 8135: 3093, 7603: 3093, 3660: 3092, 14022: 3090, 5567: 3085, 8869: 3084, 8576: 3083, 1471: 3078, 9845: 3077, 10622: 3072, 10145: 3071, 1354: 3071, 5585: 3069, 8082: 3066, 14095: 3065, 6387: 3058, 14767: 3057, 8211: 3057, 1429: 3056, 3474: 3053, 7347: 3053, 5259: 3052, 11230: 3052, 23124: 3044, 3613: 3040, 4885: 3038, 1634: 3034, 30747: 3033, 52854: 3032, 4604: 3030, 11859: 3027, 18610: 3026, 9782: 3026, 5898: 3025, 11366: 3024, 24238: 3020, 72712: 3020, 9423: 3019, 18488: 3014, 43632: 3013, 10224: 3006, 10871: 3004, 1106: 3004, 26185: 3004, 2004: 3002, 3286: 3001, 10672: 2998, 11172: 2995, 18812: 2994, 5107: 2993, 8625: 2992, 7396: 2991, 4988: 2988, 10733: 2987, 1318: 2980, 13942: 2979, 34408: 2976, 37465: 2971, 44810: 2967, 2359: 2967, 7957: 2965, 7553: 2965, 13235: 2964, 4886: 2961, 4597: 2958, 8493: 2955, 391: 2953, 45958: 2950, 4044: 2950, 73229: 2949, 5857: 2947, 6930: 2947, 15697: 2946, 3960: 2943, 5269: 2942, 17172: 2937, 39176: 2936, 10831: 2930, 8179: 2927, 18580: 2926, 9277: 2925, 9125: 2923, 64358: 2922, 75449: 2919, 5955: 2917, 4747: 2917, 48737: 2915, 20180: 2909, 4561: 2909, 7404: 2905, 12127: 2903, 5753: 2896, 16068: 2894, 4027: 2893, 59646: 2893, 3723: 2889, 4668: 2889, 1432: 2888, 11252: 2886, 9012: 

100%|██████████| 4507/4507 [00:24<00:00, 184.62it/s]

==>> input_total_val: Counter({0: 11505133, 375: 282161, 696: 209656, 657: 202546, 634: 198235, 2373: 160972, 643: 142069, 730: 140801, 582: 135684, 905: 118611, 732: 115393, 4605: 114477, 373: 98158, 773: 95620, 1130: 74083, 378: 72266, 1075: 72007, 853: 67346, 377: 62027, 13456: 59774, 41728: 59489, 379: 55297, 1548: 47283, 924: 46322, 715: 44940, 2662: 44425, 1060: 39366, 720: 35616, 868: 34502, 1371: 32454, 798: 32189, 698: 31110, 1222: 30807, 380: 30532, 2030: 29962, 999: 28858, 858: 28284, 2870: 27415, 48199: 26661, 369: 25917, 370: 25816, 382: 25155, 40379: 23801, 18420: 23644, 13452: 23598, 1965: 23426, 2957: 23399, 16524: 22602, 2376: 22274, 712: 22191, 17005: 21938, 50747: 21317, 381: 21309, 722: 20325, 838: 20290, 1488: 20217, 14178: 19823, 9583: 19113, 2171: 18776, 1145: 17832, 721: 17682, 383: 17448, 386: 17169, 1043: 17020, 1877: 16356, 385: 16019, 384: 15857, 942: 15736, 4264: 15477, 691: 15463, 97300: 15315, 392: 14792, 1107: 14764, 2751: 14235, 3401: 13782, 1367: 13604, 916: 13238, 5623: 13131, 650: 12836, 1216: 12640, 941: 12513, 1522: 12429, 10348: 12095, 764: 11959, 855: 11613, 2425: 11578, 76876: 11539, 22226: 11539, 954: 11533, 2597: 11081, 902: 11065, 1325: 11062, 1823: 10984, 4560: 10880, 816: 10784, 1058: 10723, 19850: 10597, 1137: 10558, 1050: 10322, 823: 10284, 837: 10213, 740: 10189, 2042: 10088, 2047: 9961, 1126: 9930, 2517: 9786, 1255: 9698, 3885: 9568, 1374: 9546, 41281: 9521, 1105: 9517, 1042: 9239, 1023: 9233, 600: 9197, 1180: 9056, 987: 8998, 1210: 8984, 765: 8868, 970: 8861, 799: 8854, 15913: 8708, 1081: 8665, 6734: 8614, 2327: 8551, 76766: 8414, 1119: 8313, 1902: 8260, 887: 8241, 1416: 8239, 366: 8153, 1774: 8031, 1466: 8009, 13910: 7803, 932: 7636, 800: 7437, 1668: 7229, 10996: 7199, 1047: 6990, 1051: 6881, 1490: 6838, 1995: 6822, 37728: 6788, 16559: 6785, 21212: 6732, 1595: 6695, 3157: 6693, 2414: 6614, 1080: 6561, 2878: 6439, 2364: 6201, 955: 6130, 1094: 6116, 3051: 6079, 2110: 6063, 789: 6062, 3478: 6021, 1084: 5968, 1271: 5815, 1104: 5809, 1159: 5748, 1280: 5731, 1437: 5726, 3379: 5657, 1856: 5607, 1029: 5568, 961: 5561, 1818: 5545, 1810: 5529, 2388: 5451, 3100: 5379, 5718: 5248, 1418: 5219, 4232: 5214, 1600: 5203, 2379: 5176, 846: 5120, 2888: 5108, 2424: 5071, 2372: 5051, 2329: 5051, 3050: 5027, 15169: 5025, 1740: 4981, 3376: 4978, 4022: 4958, 3125: 4909, 1821: 4886, 54689: 4848, 2736: 4757, 1452: 4645, 1579: 4641, 3718: 4636, 30885: 4621, 1430: 4583, 1002: 4564, 9099: 4554, 3163: 4548, 14010: 4522, 1332: 4482, 881: 4459, 3672: 4433, 2472: 4359, 1331: 4346, 2104: 4333, 1254: 4300, 2927: 4287, 1353: 4258, 2409: 4255, 1559: 4254, 3172: 4240, 1590: 4181, 96266: 4170, 2775: 4161, 964: 4160, 2126: 4142, 3449: 4124, 3637: 4111, 1022: 4060, 41655: 4053, 19890: 4052, 21046: 4048, 1146: 4039, 5086: 4022, 2879: 4009, 37891: 4006, 1495: 3996, 22773: 3994, 901: 3968, 2534: 3949, 2886: 3948, 2318: 3912, 374: 3910, 28612: 3907, 16519: 3903, 2626: 3886, 6332: 3878, 869: 3860, 2069: 3854, 1780: 3850, 3321: 3846, 1336: 3843, 2491: 3839, 1546: 3832, 80649: 3832, 8052: 3819, 1694: 3813, 4978: 3808, 2876: 3771, 1018: 3762, 9858: 3726, 5153: 3724, 1031: 3721, 1617: 3700, 3336: 3677, 1597: 3674, 5998: 3622, 8235: 3602, 35604: 3576, 1881: 3576, 2827: 3569, 3864: 3569, 1052: 3503, 3347: 3488, 6015: 3487, 1360: 3485, 844: 3484, 1799: 3480, 5847: 3462, 3117: 3448, 1053: 3443, 69893: 3436, 2841: 3435, 4415: 3423, 3328: 3410, 713: 3408, 760: 3403, 2448: 3384, 1286: 3376, 5299: 3355, 7408: 3351, 1719: 3342, 1225: 3334, 3428: 3330, 4767: 3319, 3216: 3311, 24040: 3308, 2553: 3304, 2618: 3294, 59985: 3267, 4385: 3257, 56415: 3241, 1413: 3238, 15585: 3227, 3950: 3213, 27506: 3191, 38045: 3185, 975: 3158, 3539: 3148, 15536: 3145, 2572: 3138, 1899: 3132, 3685: 3129, 977: 3127, 830: 3120, 4463: 3115, 6912: 3104, 1763: 3083, 733: 3077, 4308: 3045, 3460: 3035, 2645: 3020, 1553: 3013, 1794: 3010, 7059: 3004, 4373: 3000, 1369: 2986, 4490: 2976, 5275: 2975, 5838: 2972, 11326: 2965, 2015: 2964, 482: 2963, 1979: 2952, 3311: 2946, 4078: 2943, 3492: 2924, 8393: 2910, 4666: 2904, 4288: 2900, 1647: 2899, 2257: 2898, 4559: 2870, 1736: 2869, 1457: 2864, 834: 2860, 2022: 2853, 6318: 2822, 1092: 2814, 8454: 2794, 25082: 2772, 1326: 2763, 4806: 2763, 10538: 2761, 11499: 2758, 46461: 2756, 694: 2749, 26111: 2746, 3523: 2737, 6487: 2732, 5071: 2719, 53641: 2712, 1229: 2711, 1398: 2708, 2674: 2697, 17324: 2682, 5336: 2679, 78001: 2674, 3754: 2659, 1015: 2649, 2034: 2646, 1775: 2640, 4024: 2639, 7087: 2636, 3070: 2622, 2048: 2616, 1420: 2609, 5457: 2607, 363: 2601, 1645: 2601, 5414: 2600, 2710: 2595, 4484: 2593, 15282: 2587, 3027: 2580, 30761: 2571, 6697: 2567, 4003: 2548, 1523: 2542, 4504: 2539, 1162: 2534, 3903: 2523, 4349: 2512, 9768: 2508, 3540: 2499, 2453: 2498, 1400: 2497, 1629: 2497, 4169: 2492, 2820: 2491, 2785: 2491, 5985: 2485, 3325: 2476, 2904: 2471, 2781: 2462, 3755: 2462, 5159: 2456, 1113: 2439, 1673: 2437, 8726: 2429, 3231: 2426, 2963: 2422, 1921: 2420, 15418: 2416, 1996: 2413, 5292: 2413, 1008: 2405, 3670: 2403, 4933: 2396, 2102: 2391, 3570: 2390, 22610: 2380, 5780: 2368, 28498: 2367, 1658: 2366, 1244: 2366, 5422: 2361, 5010: 2355, 2718: 2349, 1147: 2347, 28726: 2344, 3788: 2333, 6747: 2329, 1840: 2324, 4996: 2317, 5256: 2316, 8221: 2316, 3083: 2309, 3626: 2309, 1682: 2298, 2802: 2291, 2389: 2289, 43202: 2287, 1061: 2286, 1235: 2281, 30695: 2276, 1867: 2275, 826: 2273, 2628: 2273, 1858: 2271, 22556: 2268, 36090: 2268, 6138: 2255, 25755: 2247, 2885: 2242, 3071: 2239, 1202: 2236, 5568: 2233, 4302: 2229, 38069: 2228, 7457: 2221, 3235: 2213, 4408: 2212, 7517: 2200, 1938: 2200, 1384: 2190, 1766: 2187, 2036: 2182, 80923: 2181, 4394: 2177, 2560: 2170, 1710: 2169, 3399: 2161, 6327: 2154, 3184: 2151, 3713: 2149, 1282: 2148, 1985: 2146, 19730: 2141, 3916: 2139, 3596: 2131, 6296: 2129, 22692: 2128, 4880: 2125, 10313: 2123, 6453: 2122, 8939: 2119, 5088: 2118, 2311: 2107, 4125: 2101, 7360: 2092, 1873: 2091, 1481: 2091, 5371: 2087, 1883: 2084, 25058: 2082, 1411: 2075, 9429: 2072, 2323: 2069, 1578: 2068, 1110: 2068, 7215: 2064, 3758: 2056, 14708: 2053, 5720: 2048, 8397: 2045, 2092: 2045, 1562: 2044, 2430: 2037, 37817: 2036, 931: 2035, 1644: 2034, 8291: 2034, 5210: 2032, 21701: 2030, 2588: 2020, 8713: 2018, 3365: 2014, 4650: 2014, 3830: 2009, 4703: 2007, 896: 2001, 47073: 1992, 1859: 1992, 1376: 1988, 5659: 1983, 1698: 1979, 4982: 1977, 2575: 1972, 6908: 1970, 780: 1965, 4100: 1963, 4289: 1953, 10079: 1952, 10368: 1950, 7572: 1949, 1415: 1945, 2733: 1945, 3090: 1932, 8789: 1930, 962: 1930, 2139: 1925, 5696: 1919, 1949: 1914, 5282: 1913, 2805: 1911, 3745: 1908, 926: 1908, 6670: 1906, 1212: 1906, 7299: 1905, 5837: 1902, 4576: 1898, 7121: 1897, 6589: 1894, 3726: 1891, 3223: 1891, 6101: 1890, 4477: 1888, 8254: 1886, 5653: 1877, 2666: 1875, 1637: 1874, 32918: 1872, 368: 1871, 1824: 1868, 1040: 1868, 1257: 1866, 3974: 1863, 1862: 1860, 4824: 1860, 3257: 1859, 1265: 1858, 2705: 1849, 2109: 1847, 2578: 1847, 3656: 1846, 5197: 1845, 4949: 1845, 7257: 1840, 3063: 1840, 5575: 1837, 1469: 1834, 2739: 1833, 1349: 1827, 4857: 1825, 4130: 1824, 6105: 1821, 7887: 1817, 8292: 1815, 5149: 1814, 1618: 1811, 5552: 1811, 4854: 1810, 3627: 1804, 1811: 1804, 1983: 1803, 2252: 1803, 4954: 1802, 7015: 1802, 1509: 1801, 1526: 1796, 4840: 1795, 1679: 1788, 34593: 1781, 13147: 1779, 3004: 1771, 3091: 1769, 7956: 1767, 2175: 1764, 3705: 1764, 5480: 1759, 33623: 1753, 2605: 1752, 1619: 1739, 4872: 1738, 5876: 1733, 7587: 1733, 7245: 1730, 5106: 1728, 775: 1719, 3118: 1716, 5135: 1708, 2051: 1707, 3550: 1697, 9384: 1695, 6707: 1695, 6582: 1694, 6696: 1693, 5865: 1691, 4536: 1691, 4986: 1691, 6801: 1691, 5569: 1688, 2818: 1683, 1175: 1682, 2131: 1681, 5690: 1674, 31882: 1671, 5930: 1668, 4532: 1666, 3164: 1665, 8296: 1663, 56867: 1657, 5213: 1656, 8722: 1651, 3562: 1650, 6389: 1650, 2764: 1649, 2485: 1648, 2703: 1648, 1156: 1646, 7858: 1646, 2799: 1645, 2690: 1641, 7243: 1638, 4038: 1635, 5266: 1631, 3728: 1629, 6948: 1627, 6951: 1626, 4060: 1626, 6720: 1625, 2220: 1617, 1580: 1617, 6026: 1615, 2469: 1613, 4762: 1607, 6581: 1607, 5954: 1606, 6033: 1604, 3504: 1601, 5133: 1598, 3545: 1592, 12621: 1588, 769: 1587, 1931: 1584, 15220: 1578, 4641: 1577, 2566: 1576, 7157: 1574, 36309: 1574, 3971: 1571, 3443: 1570, 1803: 1569, 3771: 1568, 6037: 1567, 5547: 1564, 1541: 1561, 2180: 1560, 2431: 1558, 4907: 1558, 915: 1557, 1728: 1556, 848: 1556, 1030: 1555, 1201: 1555, 6034: 1554, 10739: 1553, 3930: 1551, 2247: 1549, 6521: 1538, 1151: 1538, 27359: 1536, 1323: 1534, 4516: 1530, 3497: 1523, 5639: 1522, 4677: 1522, 6181: 1521, 3892: 1519, 69597: 1519, 2088: 1518, 3252: 1511, 4503: 1511, 94493: 1510, 2266: 1508, 33377: 1505, 1813: 1501, 10326: 1501, 2263: 1499, 90042: 1499, 6784: 1498, 1200: 1492, 4659: 1491, 8536: 1489, 4850: 1483, 3303: 1479, 4679: 1478, 1934: 1477, 11316: 1477, 7924: 1471, 12418: 1470, 5789: 1467, 2086: 1467, 5788: 1463, 1822: 1461, 2052: 1461, 5359: 1459, 8405: 1457, 2230: 1454, 3331: 1454, 5005: 1454, 7111: 1451, 9808: 1450, 1846: 1450, 5434: 1446, 2264: 1446, 13908: 1446, 1615: 1440, 5304: 1440, 1142: 1435, 5073: 1433, 2939: 1430, 12527: 1429, 4387: 1429, 7686: 1427, 1910: 1425, 4573: 1424, 1868: 1420, 10018: 1420, 3483: 1420, 2211: 1418, 1727: 1411, 2351: 1411, 10724: 1411, 5262: 1409, 2632: 1408, 1556: 1407, 3778: 1403, 4526: 1400, 1352: 1396, 12438: 1396, 1451: 1395, 17297: 1395, 3838: 1393, 34445: 1393, 6031: 1392, 1599: 1391, 22241: 1390, 4313: 1390, 9257: 1384, 6618: 1384, 8023: 1382, 78151: 1382, 3730: 1374, 3577: 1373, 1744: 1372, 17200: 1367, 36427: 1367, 9598: 1365, 1144: 1365, 2540: 1364, 5717: 1361, 4817: 1360, 4648: 1359, 9234: 1357, 3239: 1349, 1777: 1347, 3196: 1345, 2447: 1344, 1936: 1343, 27574: 1342, 1990: 1338, 7799: 1337, 11240: 1336, 6288: 1333, 2299: 1332, 1944: 1332, 785: 1330, 5184: 1326, 50294: 1326, 6698: 1324, 3173: 1324, 4649: 1320, 52132: 1319, 5833: 1315, 33861: 1314, 4262: 1313, 2068: 1312, 3358: 1312, 14954: 1311, 438: 1311, 1154: 1309, 10876: 1306, 2419: 1306, 2512: 1306, 4630: 1301, 4786: 1298, 2610: 1298, 27484: 1296, 3897: 1296, 10503: 1295, 1067: 1294, 3370: 1292, 4148: 1290, 9504: 1290, 9846: 1289, 3481: 1289, 3867: 1289, 8800: 1288, 3187: 1287, 4400: 1285, 5614: 1282, 11175: 1282, 3028: 1279, 2993: 1277, 14976: 1276, 5204: 1276, 11685: 1274, 3893: 1272, 11422: 1272, 9239: 1272, 8952: 1271, 7084: 1270, 3519: 1270, 3329: 1268, 1182: 1266, 2062: 1264, 2289: 1264, 3827: 1264, 1952: 1261, 1246: 1260, 5616: 1258, 1385: 1257, 74914: 1257, 6893: 1250, 7969: 1248, 1977: 1247, 5797: 1246, 6016: 1246, 9148: 1244, 71181: 1244, 5224: 1242, 9853: 1240, 5255: 1240, 5675: 1239, 3327: 1239, 1510: 1235, 2112: 1235, 29082: 1232, 12367: 1231, 5445: 1231, 1560: 1230, 3108: 1229, 2515: 1222, 18106: 1221, 1922: 1220, 26331: 1220, 1956: 1220, 5019: 1219, 8792: 1218, 6003: 1218, 3253: 1217, 12730: 1215, 1582: 1214, 6507: 1214, 8584: 1213, 1208: 1210, 4270: 1209, 2479: 1209, 4375: 1208, 1721: 1208, 3810: 1208, 4198: 1202, 2592: 1199, 2619: 1199, 5293: 1197, 11030: 1194, 5333: 1190, 3446: 1189, 2401: 1187, 2437: 1187, 48413: 1183, 7723: 1182, 10176: 1182, 1601: 1179, 31172: 1176, 2502: 1175, 6245: 1174, 10443: 1172, 7952: 1170, 11703: 1168, 7228: 1166, 97666: 1163, 1139: 1162, 16301: 1161, 1565: 1161, 10395: 1161, 2664: 1161, 18101: 1157, 8229: 1156, 20271: 1155, 9425: 1155, 9209: 1153, 6843: 1152, 7773: 1149, 6738: 1148, 20515: 1147, 1898: 1145, 1992: 1142, 9472: 1142, 75599: 1140, 1907: 1139, 79469: 1137, 3644: 1137, 4985: 1136, 32536: 1133, 5134: 1132, 12104: 1131, 29042: 1131, 2960: 1129, 2316: 1127, 1756: 1126, 4669: 1126, 6001: 1125, 8675: 1125, 5776: 1124, 1472: 1124, 1387: 1124, 4344: 1123, 3585: 1120, 2326: 1119, 6264: 1119, 8145: 1119, 5300: 1118, 6539: 1116, 2128: 1115, 9906: 1115, 8224: 1115, 8901: 1114, 2420: 1114, 6797: 1112, 8171: 1110, 4019: 1110, 2470: 1106, 5731: 1103, 7135: 1102, 5309: 1102, 10491: 1101, 948: 1100, 1841: 1098, 2325: 1096, 6066: 1094, 4919: 1093, 3323: 1091, 11137: 1091, 5415: 1089, 1260: 1087, 5630: 1086, 5465: 1084, 54598: 1084, 11710: 1084, 5821: 1081, 1662: 1080, 64101: 1079, 3753: 1079, 1124: 1078, 4208: 1075, 4186: 1075, 2833: 1074, 63535: 1067, 10752: 1067, 9365: 1065, 6178: 1065, 6279: 1065, 6588: 1062, 4083: 1061, 2434: 1060, 7820: 1060, 38534: 1059, 8065: 1057, 1125: 1057, 1465: 1056, 3276: 1055, 29547: 1054, 3696: 1052, 2500: 1052, 2817: 1051, 3675: 1048, 6410: 1048, 12100: 1045, 5506: 1043, 5999: 1043, 18093: 1041, 28675: 1041, 2029: 1041, 13076: 1039, 14547: 1037, 8851: 1034, 66582: 1034, 4311: 1033, 5577: 1033, 2843: 1032, 4045: 1027, 704: 1027, 2613: 1026, 2210: 1024, 3833: 1023, 29015: 1022, 5615: 1018, 9441: 1016, 4550: 1016, 9062: 1016, 8040: 1015, 10505: 1014, 8760: 1012, 1976: 1010, 9898: 1009, 65347: 1009, 1667: 1007, 9687: 1007, 3576: 1005, 1903: 1004, 3101: 1004, 2024: 1004, 6600: 1000, 4843: 1000, 1226: 999, 3053: 999, 9350: 997, 6610: 997, 9791: 996, 3055: 995, 2134: 991, 61419: 988, 24932: 988, 44065: 988, 6226: 987, 5429: 987, 27390: 986, 10701: 986, 7639: 985, 8771: 983, 2361: 981, 6496: 980, 1987: 979, 6405: 979, 3387: 979, 8357: 978, 7632: 977, 5806: 976, 9177: 975, 11795: 974, 2625: 973, 5601: 972, 7660: 971, 8857: 970, 16596: 970, 69237: 968, 12099: 968, 992: 968, 3882: 967, 12025: 965, 13018: 964, 3008: 962, 7485: 962, 1173: 962, 5443: 962, 9759: 962, 45514: 962, 11073: 962, 12080: 961, 12230: 960, 9023: 959, 2129: 957, 8923: 957, 1299: 956, 2574: 954, 1955: 954, 13311: 953, 10464: 953, 6783: 952, 32784: 952, 3129: 952, 4268: 951, 3093: 951, 6888: 951, 5372: 950, 10847: 949, 8898: 949, 7259: 949, 9496: 949, 7482: 949, 9048: 946, 5424: 945, 5233: 945, 8990: 944, 9997: 943, 4444: 943, 6313: 942, 29230: 940, 17663: 939, 1264: 938, 4214: 938, 5957: 934, 10021: 934, 35714: 933, 1747: 933, 2256: 932, 10325: 931, 12452: 930, 4694: 929, 7770: 929, 34284: 925, 1337: 924, 1587: 924, 3075: 922, 5830: 921, 7104: 920, 2873: 920, 8937: 918, 10112: 917, 10572: 917, 5905: 916, 5810: 916, 6850: 916, 1897: 915, 4701: 913, 14737: 912, 2374: 911, 6329: 910, 2635: 907, 7109: 907, 6440: 907, 6115: 907, 21715: 905, 8673: 905, 688: 905, 7369: 900, 6196: 900, 8651: 898, 4591: 896, 9952: 895, 2178: 895, 6401: 894, 3623: 893, 9457: 892, 54065: 890, 3609: 890, 3693: 890, 9811: 889, 7460: 886, 4830: 886, 83310: 885, 7630: 883, 30453: 882, 29241: 882, 7683: 882, 11090: 882, 11989: 882, 10916: 880, 5714: 880, 7751: 880, 2793: 879, 1310: 878, 1302: 877, 9806: 877, 7110: 876, 2836: 876, 6674: 876, 5355: 875, 11121: 874, 3790: 874, 1696: 873, 8151: 872, 3317: 870, 6620: 870, 2158: 870, 4937: 869, 9386: 869, 4841: 868, 7626: 868, 7419: 868, 5222: 867, 37946: 866, 8259: 865, 4826: 865, 86274: 864, 7608: 863, 2804: 863, 13613: 862, 1504: 861, 10551: 861, 4064: 861, 6135: 859, 2041: 859, 7317: 858, 7374: 858, 5346: 858, 62036: 858, 6693: 857, 18407: 856, 3981: 854, 4084: 854, 400: 854, 1278: 853, 4150: 853, 6675: 853, 6319: 851, 9642: 851, 7936: 851, 87460: 850, 6873: 849, 6297: 849, 7322: 848, 53387: 848, 27350: 845, 1339: 844, 4160: 844, 1461: 844, 2583: 843, 29635: 843, 9045: 843, 3016: 841, 11006: 840, 9860: 839, 5962: 839, 4177: 839, 12072: 838, 5080: 837, 1564: 836, 3405: 833, 6433: 833, 11347: 831, 9988: 830, 54417: 830, 10602: 830, 11864: 829, 4436: 829, 8099: 828, 6854: 828, 6086: 828, 42864: 825, 17728: 825, 16976: 824, 2920: 823, 8256: 823, 4028: 822, 15001: 822, 23356: 821, 5763: 821, 2563: 821, 1770: 821, 2313: 821, 6490: 821, 8580: 820, 5927: 819, 1531: 819, 5146: 818, 8551: 818, 16805: 818, 3701: 817, 3086: 816, 5081: 816, 819: 816, 50280: 815, 1529: 814, 7216: 814, 65573: 813, 13625: 813, 7285: 813, 3764: 812, 42914: 812, 34619: 811, 1356: 811, 13332: 810, 5290: 809, 7082: 809, 12129: 809, 4510: 808, 31747: 808, 6535: 808, 4998: 807, 1689: 806, 6414: 806, 5795: 805, 5002: 804, 12466: 804, 3868: 803, 11856: 802, 1157: 802, 15052: 801, 6065: 801, 5241: 801, 16170: 801, 1654: 800, 13432: 799, 15329: 799, 8687: 798, 53696: 797, 8434: 797, 7075: 797, 1738: 796, 5161: 796, 9757: 794, 7254: 794, 9060: 793, 3826: 791, 1620: 790, 1588: 788, 1953: 787, 26450: 784, 6132: 784, 67973: 783, 3782: 781, 4269: 781, 876: 780, 5553: 779, 5767: 778, 1568: 777, 9739: 776, 13554: 776, 18314: 775, 7747: 775, 5198: 774, 1485: 774, 2222: 773, 1368: 773, 46232: 773, 989: 772, 5089: 772, 7489: 771, 8038: 771, 8491: 771, 2356: 770, 7794: 770, 7818: 769, 9019: 769, 5376: 769, 2272: 768, 1006: 768, 2368: 768, 11821: 768, 1880: 767, 4935: 767, 38835: 767, 13072: 766, 14504: 766, 12103: 766, 40480: 765, 3996: 764, 10921: 764, 2516: 764, 19800: 763, 1726: 762, 10902: 762, 9523: 761, 8877: 761, 3662: 761, 27846: 759, 7154: 758, 16278: 758, 11720: 758, 7081: 757, 1951: 757, 8311: 756, 8697: 756, 10198: 756, 32607: 755, 95483: 755, 8015: 754, 1888: 754, 8337: 754, 13383: 752, 1354: 750, 6660: 750, 11997: 750, 12528: 749, 13419: 748, 2938: 747, 7625: 746, 22356: 744, 2107: 744, 7546: 743, 2055: 742, 5610: 742, 23581: 741, 6576: 740, 6451: 739, 14053: 738, 46040: 737, 18269: 737, 5107: 737, 6106: 737, 4328: 736, 21154: 736, 10084: 736, 12869: 736, 5259: 736, 17396: 736, 7524: 736, 3924: 735, 6137: 734, 893: 734, 66527: 734, 5769: 733, 5585: 732, 13508: 732, 7860: 732, 28811: 732, 6241: 732, 2353: 732, 13527: 732, 8574: 731, 8375: 731, 1547: 730, 16116: 729, 8576: 728, 13905: 728, 65144: 727, 5903: 726, 5805: 725, 14912: 724, 7704: 724, 9134: 724, 7739: 724, 1429: 723, 11477: 723, 11783: 723, 13139: 723, 96808: 722, 11230: 720, 3474: 719, 9984: 719, 2359: 719, 11996: 718, 7319: 718, 5757: 717, 10015: 717, 11962: 717, 13120: 716, 9971: 716, 1318: 715, 10756: 715, 8147: 715, 9125: 713, 8808: 713, 11366: 713, 806: 712, 3829: 712, 96565: 711, 4533: 710, 394: 709, 21231: 708, 7879: 707, 6667: 707, 8211: 707, 8502: 707, 9007: 706, 14519: 706, 1172: 706, 3794: 706, 2113: 705, 9845: 704, 9782: 704, 7967: 704, 1566: 703, 4278: 703, 10224: 703, 2474: 702, 1471: 702, 1296: 702, 11151: 701, 26361: 700, 11782: 700, 32046: 700, 34688: 699, 8135: 699, 26185: 698, 10823: 698, 10145: 696, 10831: 696, 8179: 696, 4488: 696, 5582: 695, 397: 695, 4885: 694, 5567: 694, 7347: 693, 23124: 692, 26143: 692, 16356: 692, 18893: 692, 88088: 691, 30747: 691, 33373: 690, 5898: 690, 6810: 690, 10871: 690, 5647: 690, 34797: 689, 3236: 688, 64358: 687, 73229: 687, 9293: 686, 10849: 686, 18610: 686, 10733: 685, 3102: 685, 8493: 685, 9423: 685, 4558: 684, 3613: 684, 1572: 684, 7427: 684, 5799: 684, 6153: 684, 59646: 684, 18488: 684, 7603: 683, 10514: 683, 16068: 683, 5809: 682, 18812: 681, 8897: 680, 4886: 679, 10622: 678, 13140: 677, 24238: 676, 7667: 674, 6387: 674, 44810: 674, 4988: 672, 14095: 672, 7396: 671, 98293: 671, 75449: 669, 8510: 669, 3130: 667, 12127: 667, 3660: 667, 32051: 665, 6930: 665, 11172: 665, 4271: 665, 25253: 665, 1106: 663, 7514: 663, 3960: 662, 11333: 662, 19885: 662, 45022: 661, 2555: 661, 14767: 661, 6665: 660, 5989: 660, 14022: 660, 8082: 660, 11859: 660, 13235: 660, 8625: 660, 18580: 659, 52854: 659, 39176: 658, 10351: 658, 6536: 657, 43743: 657, 5772: 656, 8369: 655, 6779: 655, 5269: 655, 4866: 655, 4027: 654, 3500: 653, 48487: 653, 5857: 652, 1372: 651, 391: 651, 4088: 651, 4557: 650, 4668: 650, 9012: 650, 3011: 649, 8204: 649, 14110: 649, 31097: 648, 65296: 648, 16059: 648, 3441: 647, 34408: 646, 3286: 646, 4809: 645, 3835: 645, 26053: 644, 4950: 644, 36753: 644, 5950: 643, 1634: 643, 33242: 643, 37465: 643, 48737: 643, 8869: 643, 10300: 642, 7553: 642, 9222: 642, 6744: 642, 10595: 641, 404: 641, 19417: 641, 72712: 640, 22676: 640, 9652: 639, 43632: 639, 17172: 637, 5753: 637, 2004: 636, 4604: 635, 1432: 634, 18305: 634, 4597: 633, 15697: 633, 5658: 633, 7368: 633, 10672: 632, 1035: 631, 11126: 631, 4521: 631, 3198: 631, 4044: 631, 3723: 630, 20870: 630, 13834: 630, 10969: 629, 7806: 629, 3802: 629, 45958: 629, 4747: 628, 5124: 628, 6577: 627, 5363: 627, 13103: 627, 13942: 627, 43574: 626, 7404: 624, 11932: 624, 9359: 623, 5955: 623, 30518: 623, 15069: 623, 4896: 623, 10497: 623, 59229: 622, 2207: 622, 20180: 621, 50173: 621, 3396: 620, 4930: 620, 12454: 619, 8590: 618, 21592: 617, 7957: 617, 36365: 616, 7244: 616, 46515: 615, 12126: 

100%|██████████| 501/501 [00:02<00:00, 217.43it/s]

==>> input_total_test: Counter({0: 1267146, 375: 31426, 696: 23516, 657: 22589, 634: 22424, 2373: 17778, 643: 15780, 730: 15281, 582: 14985, 905: 12947, 732: 12901, 4605: 12628, 373: 11049, 773: 10772, 1130: 8525, 1075: 8041, 378: 7888, 853: 7499, 377: 7003, 41728: 6713, 13456: 6532, 379: 6103, 1548: 5298, 924: 5101, 715: 4993, 2662: 4935, 1060: 4519, 720: 4037, 868: 3949, 1371: 3697, 798: 3639, 698: 3536, 2030: 3357, 380: 3349, 1222: 3348, 999: 3178, 858: 3105, 2870: 3093, 48199: 2975, 369: 2867, 370: 2860, 382: 2779, 18420: 2734, 40379: 2648, 1965: 2605, 2957: 2574, 2376: 2555, 13452: 2552, 16524: 2515, 17005: 2493, 712: 2448, 50747: 2389, 838: 2364, 381: 2318, 722: 2302, 1488: 2223, 14178: 2184, 9583: 2123, 2171: 2070, 1145: 2036, 383: 2002, 386: 1869, 1877: 1832, 942: 1828, 721: 1826, 385: 1824, 4264: 1820, 1043: 1812, 384: 1736, 97300: 1730, 691: 1702, 392: 1618, 1107: 1587, 1367: 1489, 1522: 1485, 3401: 1482, 2751: 1477, 916: 1443, 650: 1430, 5623: 1391, 1216: 1387, 941: 1385, 10348: 1341, 22226: 1308, 954: 1298, 76876: 1283, 855: 1263, 764: 1262, 2425: 1262, 4560: 1233, 1137: 1211, 902: 1210, 2597: 1195, 19850: 1187, 1050: 1169, 1325: 1162, 1058: 1158, 1823: 1154, 837: 1147, 2517: 1140, 823: 1138, 2047: 1137, 740: 1134, 816: 1134, 2042: 1131, 1126: 1111, 3885: 1081, 1255: 1077, 1105: 1076, 1180: 1066, 41281: 1059, 1374: 1052, 600: 1043, 970: 1028, 1023: 1028, 1042: 1005, 799: 1005, 1210: 973, 2327: 960, 6734: 957, 1081: 957, 15913: 953, 76766: 952, 366: 949, 765: 946, 987: 943, 1119: 939, 1902: 921, 1466: 904, 1416: 883, 13910: 872, 887: 868, 1774: 844, 932: 824, 800: 814, 1668: 807, 1047: 796, 16559: 794, 10996: 792, 37728: 784, 1995: 771, 1490: 764, 2878: 754, 3157: 748, 21212: 745, 1051: 734, 1094: 725, 1080: 724, 1856: 720, 2414: 715, 1084: 708, 2110: 706, 3051: 681, 2364: 681, 1280: 673, 1104: 658, 955: 658, 789: 658, 1595: 657, 1159: 656, 1271: 655, 1818: 649, 3478: 641, 3379: 639, 1437: 619, 2388: 615, 1810: 613, 961: 596, 2329: 593, 15169: 581, 2379: 580, 1029: 577, 54689: 577, 846: 576, 1418: 574, 3050: 574, 3100: 572, 3718: 567, 2372: 564, 2888: 561, 5718: 559, 3125: 557, 4022: 550, 1821: 546, 3376: 538, 2424: 534, 1452: 533, 1579: 529, 1600: 528, 4232: 528, 1331: 522, 3163: 516, 1002: 515, 14010: 508, 9099: 506, 1353: 506, 2104: 503, 3672: 502, 1559: 495, 30885: 490, 19890: 487, 1740: 486, 2736: 484, 881: 481, 3172: 479, 2409: 478, 1590: 478, 901: 477, 1332: 475, 374: 474, 9858: 469, 1430: 469, 16519: 468, 3637: 466, 1022: 461, 2069: 456, 2927: 456, 1254: 455, 2126: 452, 2472: 451, 3449: 449, 1780: 448, 2626: 445, 22773: 445, 1495: 445, 37891: 443, 964: 440, 96266: 440, 5086: 435, 80649: 435, 21046: 435, 5153: 434, 2879: 433, 869: 432, 2886: 432, 1360: 427, 2318: 427, 1881: 426, 1617: 425, 35604: 424, 2876: 424, 41655: 423, 1018: 418, 8052: 417, 1694: 416, 1031: 415, 1336: 415, 1146: 415, 3321: 414, 2775: 414, 8235: 411, 3347: 410, 6332: 407, 2491: 401, 5998: 400, 3336: 400, 1052: 399, 5847: 398, 2827: 398, 2841: 396, 6015: 394, 4978: 394, 1286: 392, 2534: 388, 1597: 388, 1546: 385, 844: 384, 24040: 383, 7408: 382, 3428: 381, 28612: 381, 3864: 378, 1225: 377, 3328: 376, 2572: 376, 1413: 373, 2618: 371, 69893: 371, 1719: 370, 3539: 367, 482: 367, 3685: 365, 760: 365, 56415: 365, 59985: 364, 15585: 364, 3117: 363, 2645: 363, 1799: 362, 2448: 362, 4767: 362, 8393: 361, 3950: 360, 2553: 359, 1053: 359, 3216: 357, 2015: 356, 975: 355, 4308: 354, 1899: 353, 1979: 353, 733: 353, 11326: 352, 27506: 352, 3460: 352, 1775: 352, 3492: 351, 713: 350, 5299: 350, 6912: 349, 830: 349, 4385: 348, 9768: 347, 38045: 346, 4415: 345, 1553: 341, 1763: 340, 6318: 339, 7059: 337, 5838: 334, 2022: 331, 1647: 331, 3311: 330, 4288: 329, 8454: 327, 1092: 327, 1736: 326, 834: 325, 17324: 323, 1400: 322, 4666: 321, 30761: 321, 5159: 320, 4078: 319, 15536: 317, 25082: 316, 2785: 315, 4490: 313, 5414: 313, 5071: 312, 78001: 312, 10538: 310, 5275: 310, 977: 309, 3903: 308, 2034: 306, 4559: 305, 2257: 305, 1369: 305, 1326: 304, 7087: 304, 1113: 303, 3754: 302, 53641: 302, 1645: 301, 4504: 300, 2048: 299, 46461: 298, 4024: 298, 26111: 297, 1008: 296, 5336: 295, 4463: 295, 4373: 295, 1162: 294, 3788: 293, 6487: 293, 3325: 292, 4484: 291, 694: 290, 2710: 290, 4169: 290, 15282: 289, 3540: 289, 1398: 289, 1229: 289, 1457: 288, 22610: 286, 1673: 286, 3070: 286, 5985: 285, 3523: 285, 3027: 284, 2674: 283, 1658: 282, 8221: 282, 28498: 282, 4806: 282, 1015: 282, 5457: 282, 1629: 280, 1523: 280, 11499: 277, 1867: 277, 1420: 276, 3231: 276, 36090: 275, 2904: 275, 6697: 273, 4933: 273, 1921: 272, 1794: 272, 4349: 271, 8726: 269, 5256: 268, 2102: 268, 5292: 268, 1682: 268, 5422: 266, 363: 266, 1061: 264, 2963: 264, 2781: 264, 2718: 263, 1244: 262, 8713: 262, 1996: 262, 3399: 261, 8397: 261, 1883: 260, 4408: 260, 3570: 258, 30695: 258, 1710: 258, 1858: 258, 1384: 257, 3670: 257, 5371: 256, 1938: 256, 1840: 255, 2820: 254, 22556: 254, 1147: 254, 826: 254, 15418: 254, 28726: 253, 5780: 253, 3626: 252, 21701: 252, 2885: 251, 4996: 251, 1766: 250, 3713: 250, 4003: 250, 2453: 248, 14708: 248, 7360: 248, 7517: 248, 2036: 246, 4302: 245, 3083: 244, 6138: 244, 1235: 243, 6453: 243, 2389: 243, 2139: 242, 2051: 242, 1202: 242, 3755: 242, 1985: 242, 6296: 242, 2092: 241, 896: 241, 1282: 241, 5575: 241, 38069: 241, 1481: 240, 2311: 239, 8939: 238, 4880: 237, 5568: 237, 4125: 237, 2628: 237, 3184: 236, 10313: 236, 5837: 236, 1562: 235, 2109: 235, 43202: 235, 19730: 234, 3596: 234, 1411: 233, 3365: 233, 780: 233, 1949: 233, 47073: 233, 2802: 232, 22692: 232, 6747: 231, 3974: 231, 5552: 231, 2560: 231, 7215: 230, 2578: 229, 3916: 229, 80923: 229, 5210: 229, 4394: 228, 3235: 227, 2575: 226, 1862: 226, 1618: 226, 7457: 225, 2430: 225, 3090: 225, 6327: 225, 931: 225, 1619: 224, 5010: 224, 4982: 224, 4824: 223, 1110: 223, 9429: 223, 4650: 223, 1698: 223, 3071: 222, 2666: 222, 8789: 222, 2805: 221, 25755: 221, 3830: 221, 5480: 220, 1811: 220, 3745: 220, 1415: 220, 6181: 220, 7572: 219, 1212: 218, 5930: 217, 7956: 216, 8291: 216, 1265: 215, 13147: 215, 962: 215, 2739: 215, 2733: 215, 25058: 215, 2705: 214, 5088: 214, 1824: 213, 4100: 213, 2588: 213, 37817: 212, 4576: 212, 5720: 212, 3758: 212, 1376: 211, 7257: 210, 1578: 210, 5197: 210, 5135: 209, 1040: 209, 6101: 209, 4289: 207, 4477: 207, 1509: 206, 5106: 206, 3223: 206, 10368: 204, 2485: 203, 3257: 203, 5149: 203, 1469: 203, 1175: 203, 5659: 203, 4840: 202, 6589: 202, 1873: 202, 3004: 202, 4857: 202, 3656: 202, 7245: 201, 368: 201, 33623: 201, 8254: 201, 2323: 200, 7299: 200, 4949: 200, 3063: 199, 6707: 199, 7121: 198, 5696: 198, 8722: 197, 6105: 197, 6908: 197, 1257: 197, 4130: 196, 27359: 196, 926: 195, 10079: 195, 4854: 195, 6670: 195, 1644: 195, 5282: 195, 1679: 194, 2818: 194, 1349: 194, 5954: 194, 3627: 194, 3562: 194, 775: 194, 7587: 193, 3705: 193, 2469: 193, 7015: 192, 31882: 192, 1983: 191, 3550: 191, 4536: 191, 4986: 191, 1541: 191, 1637: 191, 1859: 190, 34593: 190, 2605: 190, 1934: 189, 4703: 189, 2131: 189, 32918: 189, 2175: 188, 4038: 188, 5876: 188, 4872: 188, 2566: 188, 8292: 188, 7887: 187, 6951: 187, 3164: 187, 2220: 186, 9384: 186, 5569: 186, 7243: 186, 6801: 186, 4907: 185, 3118: 185, 1803: 184, 2799: 184, 4641: 184, 4762: 184, 5653: 184, 3504: 184, 8800: 183, 5266: 183, 1580: 183, 5690: 182, 1526: 182, 6582: 182, 4954: 182, 2264: 182, 6581: 182, 3497: 181, 3892: 181, 3091: 181, 1200: 181, 7858: 181, 3726: 181, 6521: 180, 4648: 180, 1156: 179, 5213: 179, 36309: 179, 5865: 178, 769: 178, 4677: 178, 3028: 177, 5547: 177, 6389: 176, 4532: 176, 6720: 176, 1931: 175, 6696: 175, 1030: 174, 5788: 174, 6948: 174, 69597: 174, 4060: 173, 7924: 173, 6037: 172, 2252: 172, 3577: 172, 34445: 172, 2764: 172, 2431: 172, 3303: 171, 6031: 171, 5133: 171, 3252: 171, 5833: 171, 7157: 171, 6034: 170, 2263: 170, 4659: 170, 17297: 170, 1868: 169, 4516: 169, 11422: 169, 2703: 169, 2690: 169, 2610: 168, 2088: 168, 10724: 168, 3545: 168, 1615: 168, 36427: 168, 94493: 167, 1144: 167, 2351: 167, 3728: 167, 7111: 166, 11316: 166, 4503: 166, 915: 166, 848: 166, 4526: 165, 90042: 165, 1142: 164, 48413: 164, 1952: 164, 2230: 164, 2068: 163, 1910: 163, 10326: 163, 56867: 163, 1728: 163, 3778: 163, 6618: 162, 1956: 162, 12418: 162, 3897: 162, 6026: 162, 5434: 161, 2086: 161, 8536: 161, 2266: 160, 4850: 160, 3930: 160, 4630: 159, 5304: 159, 13908: 159, 8296: 159, 29082: 159, 33377: 159, 6033: 159, 1846: 159, 3443: 158, 52132: 158, 4679: 158, 10739: 158, 1201: 157, 2180: 157, 1944: 157, 5359: 157, 8952: 157, 3810: 157, 1323: 157, 16301: 156, 11685: 156, 1727: 156, 2632: 156, 9853: 156, 4148: 156, 12621: 156, 78151: 155, 15220: 155, 74914: 155, 9808: 155, 6016: 155, 11175: 155, 7723: 154, 1599: 154, 2299: 154, 6784: 153, 2993: 152, 2479: 152, 5639: 152, 12099: 152, 3196: 152, 1151: 152, 1154: 152, 33861: 152, 5255: 152, 3108: 151, 3253: 151, 3331: 151, 8405: 151, 3329: 151, 4387: 151, 5224: 151, 7084: 150, 1582: 150, 2289: 150, 3730: 150, 2062: 150, 4649: 150, 5262: 150, 10018: 150, 3187: 149, 5184: 149, 27574: 149, 12438: 149, 50294: 149, 1451: 148, 3239: 148, 5204: 148, 4313: 148, 8584: 147, 1744: 147, 2540: 147, 7820: 147, 5019: 147, 4817: 147, 97666: 147, 9234: 147, 1936: 147, 14954: 146, 75599: 146, 5614: 146, 5797: 146, 2052: 146, 2247: 145, 2401: 145, 3519: 145, 5005: 145, 3971: 145, 2447: 145, 1977: 145, 10752: 145, 6288: 144, 9906: 144, 6178: 144, 2211: 144, 3481: 144, 785: 143, 9239: 143, 71181: 143, 5134: 143, 3483: 143, 5789: 143, 8792: 143, 1822: 142, 2326: 142, 1907: 142, 9598: 142, 5717: 142, 9257: 142, 3771: 142, 7686: 142, 1777: 142, 5073: 142, 9846: 141, 4573: 141, 3827: 141, 3838: 140, 4198: 140, 14976: 140, 1560: 140, 1246: 140, 1601: 140, 2843: 139, 2664: 139, 1992: 139, 2502: 138, 8229: 138, 8040: 138, 2515: 137, 1990: 137, 3867: 137, 9425: 137, 1955: 137, 7952: 137, 6539: 137, 9209: 137, 2437: 137, 6264: 137, 12527: 136, 9504: 136, 4985: 136, 54065: 136, 11240: 136, 27484: 136, 1556: 136, 8851: 135, 9148: 135, 5776: 135, 8224: 135, 1813: 135, 2939: 135, 7482: 135, 3327: 135, 8023: 135, 3644: 135, 6893: 134, 5630: 134, 9365: 134, 3370: 134, 17200: 134, 1385: 134, 1472: 134, 1747: 133, 10876: 133, 1208: 133, 5675: 133, 11030: 133, 4400: 133, 438: 133, 6003: 133, 32536: 133, 12730: 132, 1922: 132, 5465: 132, 5445: 132, 8171: 132, 6738: 132, 10176: 131, 1756: 131, 1352: 131, 5731: 130, 2619: 130, 63535: 130, 6610: 130, 7969: 129, 1721: 129, 4786: 129, 1182: 129, 54598: 129, 4311: 129, 3585: 129, 4262: 129, 6279: 129, 1260: 128, 5616: 128, 6698: 128, 11710: 128, 7639: 128, 7228: 128, 3173: 127, 26331: 127, 4270: 127, 8145: 127, 2833: 127, 2512: 127, 1510: 127, 65347: 127, 6410: 126, 10503: 126, 13311: 126, 64101: 126, 22241: 126, 4344: 126, 7135: 126, 5957: 126, 3086: 126, 7770: 125, 8065: 125, 2419: 125, 2325: 125, 4669: 125, 3358: 125, 13076: 125, 1067: 124, 4444: 124, 16596: 124, 1667: 124, 3893: 124, 4083: 124, 1139: 124, 4375: 124, 7799: 124, 6888: 124, 18106: 124, 3053: 123, 2128: 123, 12367: 123, 1841: 123, 3675: 123, 6843: 123, 29547: 123, 1387: 122, 11703: 122, 8675: 122, 5309: 122, 3446: 122, 7109: 122, 5293: 121, 2613: 121, 5415: 121, 2960: 121, 3696: 121, 3323: 121, 9472: 121, 3833: 121, 10395: 121, 7773: 120, 6329: 120, 20271: 120, 948: 120, 1565: 120, 83310: 120, 9496: 120, 10491: 119, 10443: 119, 9898: 119, 5333: 119, 10572: 119, 7460: 119, 18093: 119, 8651: 118, 1987: 118, 5300: 118, 6797: 118, 16976: 118, 6588: 118, 12104: 118, 5601: 117, 66582: 117, 18101: 117, 6507: 117, 79469: 117, 5424: 117, 6066: 117, 4843: 117, 3093: 117, 7751: 117, 9687: 117, 6245: 117, 5806: 117, 6001: 116, 7254: 116, 8760: 116, 2112: 116, 1302: 116, 1903: 116, 1226: 116, 2500: 116, 1124: 116, 2316: 116, 6440: 116, 4919: 115, 8857: 115, 1125: 115, 6873: 115, 14547: 115, 2817: 115, 4019: 115, 7104: 114, 5506: 114, 5999: 114, 29042: 114, 400: 114, 2434: 113, 5355: 113, 8357: 113, 6226: 113, 5821: 112, 61419: 112, 1898: 112, 31172: 112, 29015: 111, 704: 111, 8990: 111, 5577: 111, 21715: 111, 989: 111, 2592: 111, 4268: 111, 44065: 111, 3693: 111, 86274: 111, 1299: 111, 6401: 111, 2134: 111, 7632: 110, 8923: 110, 11989: 110, 1157: 110, 3008: 110, 3129: 110, 3075: 110, 4826: 109, 4186: 109, 5372: 109, 9811: 109, 7259: 109, 11821: 109, 3101: 109, 7626: 109, 8151: 108, 4214: 108, 8673: 108, 1696: 108, 4208: 108, 992: 108, 3829: 108, 1976: 108, 11006: 107, 1173: 107, 9350: 107, 2256: 107, 27390: 107, 7630: 106, 22356: 106, 14737: 106, 7704: 106, 13018: 106, 1465: 106, 4550: 106, 4998: 106, 2374: 106, 20515: 105, 3753: 105, 5290: 105, 1461: 105, 11073: 105, 11795: 105, 9177: 105, 12025: 105, 1897: 105, 8771: 105, 5905: 105, 2583: 104, 12100: 104, 2420: 104, 38835: 104, 10325: 104, 6675: 104, 23356: 104, 16170: 104, 29230: 104, 9062: 103, 27350: 103, 7485: 103, 88088: 103, 7285: 103, 12072: 103, 16805: 103, 8898: 103, 10602: 103, 7081: 103, 5927: 103, 8901: 103, 10701: 103, 5443: 103, 2563: 102, 5346: 102, 6115: 102, 32784: 102, 5553: 102, 8937: 102, 6405: 102, 1662: 102, 2873: 102, 35714: 102, 6850: 102, 3576: 101, 8099: 101, 19800: 101, 15329: 101, 7419: 101, 7322: 101, 2178: 101, 38534: 101, 7660: 101, 10015: 100, 9023: 100, 6674: 100, 5714: 100, 9920: 100, 2210: 100, 10464: 100, 3662: 100, 2024: 100, 2353: 100, 3609: 100, 1880: 100, 9791: 100, 6600: 100, 4830: 99, 9759: 99, 4694: 99, 5222: 99, 1564: 99, 4701: 99, 7369: 99, 5233: 99, 9441: 98, 2029: 98, 16116: 98, 1531: 98, 6319: 98, 46232: 98, 1264: 98, 3055: 98, 11962: 98, 7879: 98, 54417: 98, 10847: 97, 10021: 97, 9642: 97, 1337: 97, 4269: 97, 8256: 97, 5376: 97, 18407: 97, 13625: 97, 688: 97, 53387: 97, 8491: 97, 7747: 97, 87460: 97, 4045: 96, 5429: 96, 5081: 96, 8590: 96, 16278: 96, 7374: 96, 12466: 96, 65573: 96, 3387: 96, 11121: 96, 5795: 96, 2129: 96, 6854: 96, 3981: 96, 37946: 96, 4436: 96, 9806: 96, 1504: 96, 1485: 96, 4510: 96, 8580: 96, 5830: 95, 1566: 95, 4937: 95, 26450: 95, 10916: 95, 10672: 95, 62036: 95, 10505: 95, 13613: 95, 10112: 95, 1888: 95, 6496: 95, 11859: 95, 3868: 94, 2470: 94, 13432: 94, 7546: 94, 6451: 94, 2313: 94, 9952: 94, 15001: 94, 2625: 94, 17728: 94, 9457: 94, 5161: 94, 5769: 94, 3276: 94, 2361: 94, 3764: 94, 3996: 94, 3317: 94, 11997: 93, 893: 93, 5363: 93, 4591: 93, 6881: 93, 2938: 93, 13508: 93, 6414: 93, 11137: 93, 10921: 93, 4177: 93, 42914: 93, 9860: 92, 4841: 92, 9060: 92, 1587: 92, 28811: 92, 12232: 92, 5615: 92, 5810: 92, 30453: 92, 3405: 92, 6132: 92, 3882: 92, 18314: 92, 7075: 92, 9997: 92, 1339: 92, 13120: 92, 6297: 92, 31747: 92, 3790: 92, 50280: 92, 1953: 92, 3924: 92, 2158: 92, 24932: 92, 1354: 91, 6196: 91, 11090: 91, 10551: 91, 4150: 91, 45514: 91, 6313: 91, 6086: 91, 96808: 91, 17663: 91, 5089: 91, 6693: 90, 11864: 90, 6667: 90, 8015: 90, 95483: 90, 13419: 90, 11347: 90, 69237: 90, 5080: 90, 53696: 90, 2635: 90, 5259: 90, 34619: 90, 4160: 90, 5763: 90, 2041: 90, 40480: 89, 26361: 89, 34284: 89, 12080: 89, 2804: 89, 29635: 89, 6433: 89, 1356: 89, 14504: 89, 6783: 89, 8434: 89, 5767: 89, 12129: 89, 4044: 89, 10595: 89, 1738: 88, 5582: 88, 12103: 88, 13527: 88, 6241: 88, 4064: 88, 2793: 88, 9782: 88, 5962: 88, 1654: 88, 6620: 88, 7683: 88, 6810: 88, 7625: 87, 14095: 87, 7794: 87, 5241: 87, 8687: 87, 10084: 87, 66527: 87, 7524: 87, 2920: 86, 11782: 86, 21231: 86, 4533: 86, 10622: 86, 18269: 86, 9739: 86, 3660: 86, 7608: 86, 24238: 86, 6135: 86, 13072: 86, 7936: 86, 28675: 86, 1620: 86, 7154: 86, 29241: 86, 6490: 85, 3826: 85, 8375: 85, 3623: 85, 2222: 85, 13332: 85, 13942: 85, 48737: 85, 1588: 85, 2836: 85, 3616: 85, 10970: 85, 7667: 85, 8897: 85, 18812: 85, 45958: 85, 819: 84, 5857: 84, 8147: 84, 5610: 84, 8510: 84, 10902: 84, 9359: 84, 12452: 84, 12230: 84, 8697: 84, 23124: 84, 8337: 84, 14053: 84, 12935: 84, 3236: 83, 9386: 83, 10756: 83, 2272: 83, 1318: 83, 30747: 83, 1770: 83, 14022: 83, 11720: 83, 3977: 83, 4935: 83, 11783: 83, 3782: 83, 9652: 82, 6106: 82, 32607: 82, 9012: 82, 11172: 82, 10198: 82, 6137: 82, 1172: 82, 4488: 82, 5002: 82, 5198: 82, 8576: 82, 6153: 82, 27846: 82, 7317: 82, 3835: 81, 32046: 81, 1006: 81, 1278: 81, 391: 81, 25253: 81, 42864: 81, 8068: 81, 9048: 81, 4557: 81, 13140: 81, 6660: 81, 33373: 81, 5903: 81, 3205: 81, 46040: 80, 12149: 80, 2574: 80, 4668: 80, 2207: 80, 1432: 80, 8551: 80, 6577: 80, 1368: 80, 32051: 80, 15956: 80, 7082: 80, 4747: 80, 5269: 80, 30284: 80, 5567: 80, 12253: 80, 8574: 80, 2113: 80, 7110: 79, 4271: 79, 14912: 79, 13139: 79, 1529: 79, 5809: 79, 34797: 79, 11996: 79, 5247: 79, 9523: 79, 5950: 79, 8082: 79, 11932: 79, 5107: 79, 65296: 79, 4558: 79, 1726: 79, 12869: 79, 1547: 79, 7404: 79, 8259: 79, 14767: 79, 5757: 79, 2055: 78, 7806: 78, 9971: 78, 7776: 78, 18488: 78, 8877: 78, 394: 78, 67973: 78, 4885: 78, 2368: 78, 1887: 78, 3102: 78, 3701: 78, 1951: 78, 6576: 78, 10186: 77, 10849: 77, 2599: 77, 2516: 77, 8011: 77, 16356: 77, 19417: 77, 17396: 77, 20180: 77, 2474: 77, 6065: 77, 59229: 77, 11151: 77, 5146: 77, 8038: 77, 9293: 77, 6535: 77, 4896: 77, 14519: 77, 7427: 77, 7553: 77, 6930: 76, 11126: 76, 8808: 76, 16068: 76, 8211: 76, 3016: 76, 1471: 76, 17172: 76, 9019: 76, 3441: 76, 9125: 76, 5805: 76, 11856: 76, 1689: 76, 39176: 76, 9988: 76, 7216: 76, 7603: 76, 12126: 76, 8135: 76, 21154: 76, 10116: 76, 15118: 75, 404: 75, 5647: 75, 10733: 75, 15845: 75, 15052: 75, 36753: 75, 15069: 75, 23581: 75, 18305: 74, 3396: 74, 11366: 74, 4476: 74, 3794: 74, 96565: 74, 806: 74, 22676: 74, 1310: 74, 5799: 74, 10831: 74, 10714: 74, 52854: 74, 2359: 74, 3723: 74, 4950: 74, 5283: 74, 7739: 74, 9007: 74, 2004: 74, 7860: 74, 4988: 74, 59646: 73, 751: 73, 4809: 73, 10823: 73, 11979: 73, 1288: 73, 4355: 73, 12454: 73, 4278: 73, 10871: 73, 7489: 73, 13554: 73, 6657: 72, 11333: 72, 12219: 72, 7730: 72, 34688: 72, 7859: 72, 18610: 72, 5772: 72, 1296: 72, 4328: 72, 10514: 72, 11230: 72, 38105: 72, 10969: 72, 7319: 72, 4886: 72, 9222: 72, 9875: 72, 3960: 71, 4597: 71, 3554: 71, 75449: 71, 6665: 71, 876: 71, 2107: 71, 12528: 71, 10846: 71, 7967: 71, 18893: 71, 21334: 71, 11477: 71, 11892: 71, 43632: 71, 7347: 71, 10497: 71, 2555: 71, 9045: 71, 34408: 71, 6536: 70, 13834: 70, 9196: 70, 2962: 70, 12518: 70, 17228: 70, 9428: 70, 8110: 70, 10300: 70, 2356: 70, 98293: 70, 9423: 70, 50173: 70, 41836: 70, 4399: 70, 13905: 70, 28839: 70, 15334: 70, 10742: 70, 12270: 70, 18580: 70, 8369: 70, 6472: 69, 23192: 69, 33242: 69, 6396: 69, 2518: 69, 1106: 69, 5585: 69, 8179: 69, 6220: 69, 7957: 69, 5989: 69, 72712: 69, 8573: 69, 4084: 69, 8814: 69, 4866: 69, 18386: 69, 9645: 69, 24911: 69, 9683: 68, 1568: 68, 10754: 68, 73229: 68, 4383: 68, 7076: 68, 1703: 68, 8838: 68, 3286: 68, 3613: 68, 5831: 67, 16404: 67, 43574: 67, 15386: 67, 12695: 67, 7911: 67, 3742: 67, 15173: 67, 10625: 67, 4121: 67, 8311: 67, 9845: 67, 2250: 67, 18292: 67, 13103: 67, 4028: 67, 1634: 67, 37465: 67, 8502: 67, 36365: 67, 9277: 67, 13383: 67, 81945: 67, 3006: 67, 5753: 67, 15697: 66, 12786: 66, 4492: 66, 44532: 66, 7741: 66, 46515: 66, 18128: 66, 59553: 66, 9984: 66, 9886: 66, 6727: 66, 2398: 66, 4892: 66, 5898: 66, 10145: 66, 6406: 66, 37103: 66, 5946: 66, 48487: 66, 3261: 66, 48295: 66, 7818: 65, 3815: 65, 4512: 65, 30518: 65, 3130: 65, 42911: 65, 6594: 65, 9945: 65, 5006: 65, 3474: 65, 2307: 65, 6829: 65, 4008: 65, 8695: 65, 5476: 65, 6733: 65, 16076: 65, 3500: 65, 49706: 65, 10830: 65, 14110: 65, 26143: 65, 2108: 65, 4112: 65, 1640: 64, 7151: 64, 2822: 64, 7535: 64, 7298: 64, 13968: 64, 5324: 64, 19120: 64, 1717: 64, 11429: 64, 4521: 64, 5945: 64, 22548: 64, 409: 64, 16167: 64, 26185: 64, 397: 64, 1183: 64, 7027: 64, 5940: 64, 4561: 64, 64358: 64, 8243: 64, 25256: 64, 1869: 64, 2291: 63, 42700: 63, 5960: 63, 5093: 63, 12380: 63, 10439: 63, 12545: 63, 2319: 63, 7396: 63, 6493: 63, 70476: 63, 2970: 63, 11743: 63, 3011: 63, 5658: 63, 10466: 63, 2236: 63, 26053: 63, 3114: 63, 5485: 63, 5691: 63, 10292: 63, 10351: 63, 43743: 63, 14688: 63, 4088: 63, 6387: 63, 3684: 63, 8066: 63, 6129: 62, 4931: 62, 56792: 62, 5078: 62, 7499: 62, 14322: 62, 8869: 62, 13235: 62, 11684: 62, 7332: 62, 15295: 62, 36561: 62, 4970: 62, 5432: 62, 7244: 62, 5722: 62, 8204: 62, 13730: 62, 9757: 62, 4027: 62, 1606: 62, 12421: 62, 10618: 62, 18065: 62, 9688: 62, 2221: 

# en_ko_12m 데이터셋

In [1]:
from datasets import load_dataset, load_from_disk, ClassLabel, DatasetDict

In [34]:
ds = load_from_disk("/home/paokimsiwoong/workspace/github.com/paokimsiwoong/transformer_experiments/eda/en_ko_12m")

In [35]:
ds

DatasetDict({
    train: Dataset({
        features: ['domain', 'subdomain', 'style', 'target', 'source', 'target_text', 'source_text'],
        num_rows: 11895711
    })
})

In [36]:
unique_classes = ds.unique('domain')  
print(unique_classes)

{'train': ['일상생활', '해외고객과의채팅', '해외영업', '경제', '기술과학', '기후', '세계', '정치', '교양', '다큐', '연예공연', '영화드라마', '예능오락', '인터뷰', '기타', '다큐교양', '01000', '02000', '03000', '10110', '10121', '10122', '10129', '10210', '10220', '10300', '10400', '10500', '10610', '10620', '10712', '10713', '10720', '10730', '10742', '10743', '10749', '10750', '10791', '10792', '10795', '10796', '10797', '10799', '10801', '10802', '11110', '11120', '11200', '12000', '13103', '13104', '13109', '13213', '13219', '13221', '13224', '13229', '13400', '13920', '13992', '13994', '13999', '14120', '14191', '14192', '14194', '14199', '14411', '14419', '14491', '14499', '15129', '15211', '15219', '15220', '16101', '16102', '16103', '16211', '16212', '16221', '16229', '16230', '16300', '17110', '17120', '17220', '17901', '17902', '17909', '18110', '18120', '18200', '19210', '19221', '19229', '20111', '20119', '20121', '20129', '20131', '20132', '20201', '20202', '20203', '20311', '20312', '20313', '20321', '20322', '20411', '20413', '20421', '20422', '20423', '20424', '20491', '20492', '20493', '20494', '20495', '20499', '20500', '21101', '21102', '21210', '21220', '21230', '21300', '22110', '22191', '22192', '22193', '22199', '22211', '22212', '22213', '22214', '22221', '22222', '22223', '22229', '22231', '22232', '22241', '22249', '22251', '22259', '22291', '22292', '22299', '23110', '23120', '23190', '23210', '23220', '23230', '23310', '23321', '23322', '23324', '23325', '23329', '23910', '23991', '23992', '23994', '23995', '23999', '24110', '24120', '24131', '24132', '24191', '24199', '24210', '24221', '24222', '24229', '24290', '24311', '24312', '24321', '24322', '24329', '25111', '25112', '25113', '25114', '25119', '25121', '25122', '25123', '25130', '25200', '25911', '25912', '25913', '25914', '25921', '25922', '25923', '25924', '25929', '25931', '25932', '25933', '25934', '25941', '25942', '25943', '25944', '25991', '25992', '25993', '25995', '25999', '26111', '26112', '26121', '26129', '26211', '26212', '26219', '26221', '26222', '26223', '26224', '26291', '26292', '26293', '26294', '26295', '26299', '26310', '26321', '26322', '26323', '26329', '26410', '26421', '26422', '26429', '26511', '26519', '26521', '26529', '26600', '27111', '27112', '27191', '27192', '27193', '27194', '27199', '27211', '27212', '27213', '27214', '27215', '27216', '27219', '27301', '27302', '27309', '27400', '28111', '28112', '28113', '28114', '28119', '28121', '28122', '28123', '28201', '28202', '28301', '28302', '28303', '28410', '28421', '28422', '28423', '28429', '28511', '28512', '28519', '28520', '28901', '28902', '28903', '28909', '29111', '29119', '29120', '29131', '29132', '29133', '29141', '29142', '29150', '29161', '29162', '29163', '29169', '29171', '29172', '29173', '29174', '29175', '29176', '29180', '29191', '29192', '29193', '29194', '29199', '29210', '29221', '29222', '29223', '29224', '29229', '29230', '29241', '29242', '29250', '29261', '29269', '29271', '29272', '29280', '29291', '29292', '29293', '29294', '29299', '30110', '30121', '30122', '30201', '30203', '30310', '30320', '30331', '30332', '30391', '30392', '30393', '30399', '30400', '31111', '31112', '31113', '31114', '31120', '31201', '31202', '31311', '31312', '31320', '31910', '31920', '31991', '31999', '32010', '32021', '32029', '32091', '32099', '33110', '33120', '33201', '33202', '33209', '33301', '33302', '33303', '33309', '33401', '33402', '33409', '33910', '33920', '33930', '33991', '33992', '33993', '33999', '34000', '35111', '35112', '35113', '35114', '35119', '35120', '35130', '35200', '36010', '36020', '37000', '38100', '38200', '38300', '39000', '41100', '41221', '41222', '41223', '41224', '41225', '41229', '42110', '42121', '42122', '42123', '42129', '42131', '42132', '42133', '42134', '42135', '42137', '42138', '42139', '42201', '42202', '42203', '42204', '42209', '42311', '42312', '42321', '42322', '42411', '42420', '42491', '42492', '42499', '42500', '42600', '45000', '46200', '46310', '46320', '46330', '46410', '46430', '46440', '46450', '46460', '46490', '46510', '46520', '46530', '46590', '46610', '46620', '46690', '46710', '46720', '46730', '46740', '46790', '46800', '47000', '58110', '58120', '58211', '58212', '58219', '58221', '58222', '59111', '59112', '59113', '59114', '59120', '60000', '61220', '61299', '62010', '62021', '62022', '62090', '63111', '63112', '63120', '63910', '71300', '71500', '72121', '72122', '72129', '72911', '72919', '72921', '72922', '72923', '72924', '73100', '73203', '73209', '73301', '73303', '73902', '73903', '73904', '74211', '74212', '74220', '75320', '75994', 'H', 'K', '글로벌동향정보', '연구평가정보', '위해식품정보', '공학', '구어체_대화체', '기계', '농림수산식품', '농학', '뉴스문어체', '문화문어체', '물리학', '미생물학', '보건의료', '사회', '사회과학', '생명과학', '생물학 생화학', '수학', '약리학 독성학', '의약학', '재료', '재료과학', '전문분야 문어체', '정보-통신', '조례문어체', '지자체웹사이트 문어체', '컴퓨터과학', '화학', '환경과 생태학', 'IT/기술', '가정통신문', '관광', '금융/증시', '대법원판례', '스포츠', '의료/보건', '향토문화/음식', 'ICT', '의학', '전기', '전자', '교육', '문화', '법률', '예술', 'None', '교통', '구비 전승·언어·문학', '문화·교육', '문화·교육/교육|문화·교육/문화·예술', '문화·교육/교육|문화·교육/문화·예술|성씨·인물/근현대', '문화·교육/교육|역사/근현대', '문화·교육/교육|역사/근현대|문화유산/유형 유산', '문화·교육/문화·예술', '문화·교육/문화·예술|문화·교육/교육', '문화·교육/문화·예술|문화유산/무형 유산', '문화·교육/문화·예술|문화유산/유형 유산', '문화·교육/문화·예술|성씨·인물/근현대 인물', '문화·교육/문화·예술|성씨·인물/근현대 인물|문화유산/', '문화·교육/문화·예술|역사/근현대', '문화·교육/문화·예술|역사/전통 시대', '문화·교육/문화·예술|정체·경제·사회/사회·복지', '문화·교육/문화·예술|정치·경제·사회/경제·산업', '문화·교육/문화·예술|정치·경제·사회/경제·산업|문화유', '문화·교육/문화·예술|정치·경제·사회/사회·복지', '문화·교육/문화·예술|종교/기독교|문화유산/유형 유산', '문화·교육/언론·출판|문화·교육/문화·예술', '문화·교육/언론·출판|역사/근현대', '문화·교육/언론·출판|역사/근현대|문화유산/기록 유산', '문화·교육/체육|문화·교육/예술|생활·민속/민속', '문화·교육/체육|생활·민속/민속|문화유산/무형유산', '문화·예술', '문화유산', '문화유산/기록 유산|역사/근현대', '문화재', '민속', '생활·민속', '생활·민속/민속', '생활·민속/민속|문화유산/무형 유산', '생활·민속/민속|문화유산/무형유산', '생활·민속/민속|문화유산/유형 유산', '생활·민속/민속|민간신앙|가정신앙', '생활·민속/생활|역사/근현대', '생활·민속/생활|역사/근현대|문화유산/유형 유산', '성씨·인물', '역사', '역사/근현대', '역사/근현대|구비 전승·언어·문학/문학', '역사/근현대|문화·교육/교육', '역사/근현대|문화·교육/교육|문화유산/기록 유산', '역사/근현대|문화·교육/교육|문화유산/유형 유산', '역사/근현대|문화·교육/문화·예술', '역사/근현대|문화·교육/문화·예술|성씨·인물/근현대 인', '역사/근현대|문화·교육/언론·출판', '역사/근현대|문화·교육/언론·출판|문화유산/기록 유산', '역사/근현대|문화·교육/언론·출판|정치·경제·사회/정치', '역사/근현대|문화유산/기록 유산', '역사/근현대|문화유산/기록유산', '역사/근현대|문화유산/유형 유산', '역사/근현대|문화유산/유형유산', '역사/근현대|문화유산/유형유산|생활·민속/생활', '역사/근현대|생활·민속/생활', '역사/근현대|생활·민속/생활|문화유산/유형 유산', '역사/근현대|성씨·인물/근현대 인물', '역사/근현대|성씨·인물/근현대 인물|종교/유교', '역사/근현대|성씨·인물/근현대인물', '역사/근현대|성씨·인물/근현대인물|문화·교육/문화·예술', '역사/근현대|성씨·인물/전통 시대 인물', '역사/근현대|인물/근현대 인물', '역사/근현대|정치·경제·사회/경제 산업', '역사/근현대|정치·경제·사회/경제·산업', '역사/근현대|정치·경제·사회/경제·산업|문화유산/기록', '역사/근현대|정치·경제·사회/경제·산업|문화유산/유형', '역사/근현대|정치·경제·사회/경제·산업|성씨·인물/근현', '역사/근현대|정치·경제·사회/사회·복지', '역사/근현대|정치·경제·사회/사회·복지|문화유산/기록', '역사/근현대|정치·경제·사회/사회·복지|성씨·인물/근현', '역사/근현대|정치·경제·사회/사회·복지|정치·경제·사회', '역사/근현대|정치·경제·사회/정치·행정', '역사/근현대|정치·경제·사회/정치·행정|문화유산/기록', '역사/근현대|종교/기독교', '역사/근현대|종교/기독교|문화유산/유형 유산', '역사/근현대|종교/기독교|성씨·인물/근현대인물', '역사/근현대|종교/불교', '역사/근현대|종교/불교|문화유산/기록 유산', '역사/근현대|종교/신종교', '역사/전통 시대|문화·교육/문화·예술|문화유산/유형 유', '역사/전통 시대|역사/근현대', '정치·경제·사회', '정치·경제·사회/경제·산업|문화·교육/문화·예술', '정치·경제·사회/경제·산업|역사/근현대', '정치·경제·사회/경제·산업|역사/근현대|문화유산/유형', '정치·경제·사회/사회·복지|문화·교육/문화·예술', '정치·경제·사회/사회·복지|역사/근현대', '정치·경제·사회/사회·복지|역사/근현대|성씨·인물/근현', '정치·경제·사회/정치·행정|역사/근현대', '정치·경제·산업/경제·산업|역사/근현대', '정치∙경제∙사회', '종교', '종교/기독교|역사/근현대', '종교/기독교|정치·경제·사회/사회·복지|역사/근현대', '종교/불교|역사/근현대', '종교/불교|역사/근현대|성씨·인물/근현대 인물', '종교/신종교|역사/근현대', '종교/유교|역사/근현대|문화유산/유형 유산', '지리', '지리/인문 지리|지리/자연 지리|생활·민속/민속', '한국국제문화교류진흥원']}

In [ ]:
count = 0

def map_domain(raw_domain: str) -> str:
    if raw_domain is None:
        return "기타"

    d = raw_domain

    # 1) 명시적인 매핑
    if d in ["일상생활", "구어체_대화체", "해외고객과의채팅", "해외영업"]:
        return "일상/대화"

    if d in ["뉴스문어체", "지자체웹사이트 문어체", "가정통신문", "스포츠"]:
        return "뉴스/시사"

    if d in ["교양", "다큐", "다큐교양", "연예공연", "영화드라마", "예능오락", "인터뷰", "기타", # 방송콘텐츠 데이터셋에 기타 분류가 있음
             "문화문어체", 
             "문화", "문화·예술", "문화·교육", "문화재", "민속", "생활·민속",
             "문화유산", "역사", "역사/근현대", "역사/전통 시대",
             "구비 전승·언어·문학", "성씨·인물",
             "관광", "예술", "향토문화/음식", "종교", "지리",
             "정치·경제·사회", "정치∙경제∙사회", # 종류가 두가지?
             "정치·경제·산업/경제·산업|역사/근현대", "한국국제문화교류진흥원"]:
        return "문화/예술/역사"
    

    if d in ["경제", "세계", "정치", "기후", "기술과학", # 기술과학 분야 한-영 번역 병렬 말뭉치 데이터
             "글로벌동향정보", "연구평가정보", "위해식품정보", "법제도정보", # 식품 전문 분야 데이터
             "IT/기술", "ICT", "컴퓨터과학", "정보-통신",
             "공학", "전기", "전자", "재료", "재료과학",
             "수학", "물리학", "미생물학", "화학", "생명과학", "생물학 생화학",
             "환경과 생태학", "농학", "농림수산식품", "기계",
             "사회", "사회과학", "전문분야 문어체", "교육"]:
        return "과학/기술/학술자료"

    if d in ["의료/보건", "보건의료", "의학", "의약학", "의약학", "약리학 독성학"]:
        return "의학/보건"

    if d in ["법률", "대법원판례", "조례문어체", "교통"]:
        return "법률/행정"

    if d in ["금융/증시"]:
        return "금융/경제"

    # 2) 패턴 기반 매핑 (복잡한 문자열들)
    if d.startswith("문화·교육") or d.startswith("문화유산") or d.startswith("생활·민속"):
        return "문화/예술/역사"
    if d.startswith("역사/"):
        return "문화/예술/역사"
    if d.startswith("종교/"):
        return "문화/예술/역사"
    if d.startswith("지리/"):
        return "문화/예술/역사"
    if d.startswith("정치·경제·사회"):
        return "문화/예술/역사"
    if "의료" in d or "의학" in d or "보건" in d:
        return "의학/보건"
    
    # 특허
    if d.isdigit():
        return "특허"
    
    if d in ["H", "K"]:
        return "특허"

    # 3) 그 밖의 코드/기타 값
    if d in ["None"]:
        return "기타"

    # 조건에서 벗어난 경우의 수 카운트
    global count 
    count += 1
    print(d)
    # 기본값
    return "기타"

In [38]:
def map_domain_batch(batch):
    batch["super_domain"] = [map_domain(d) for d in batch["domain"]]
    return batch

In [39]:
ds = ds.map(map_domain_batch, batched=True)

Map:   0%|          | 0/11895711 [00:00<?, ? examples/s]

In [40]:
print(f"==>> count: {count}")

==>> count: 0

In [45]:
ds

DatasetDict({
    train: Dataset({
        features: ['domain', 'subdomain', 'style', 'target', 'source', 'target_text', 'source_text', 'super_domain'],
        num_rows: 11895711
    })
})

In [43]:
ds["train"][11000000:11000005]

{'domain': ['None', 'None', 'None', 'None', 'None'],
 'subdomain': ['None', 'None', 'None', 'None', 'None'],
 'style': ['문어체', '문어체', '문어체', '문어체', '문어체'],
 'target': ['ko', 'ko', 'ko', 'ko', 'ko'],
 'source': ['en', 'en', 'en', 'en', 'en'],
 'target_text': ['원래 더 많은 인원으로 데뷔할 생각이 있었다.',
  '웰리힐리 리조트는 대대로 스노보더에게 인기가 많은 곳이다.',
  '위트가 가미된 절제된 톤으로 현실적인 이야기를 풀어냈다.',
  '유니클로 감사제가 많은 이들의 이목을 집중시키고 있다.',
  '유독 여성 연예인들에게는 엄격한 외모 잣대가 주어진다.'],
 'source_text': ['I originally planned to debut with more people.',
  'Wellihilli Resort is popular with snowboarders for generations.',
  'Witness adds a realistic story with modest tones.',
  'The special events of UNIQLO have attracted much attention.',
  'Female entertainers are given strict standards of appearance.'],
 'super_domain': ['기타', '기타', '기타', '기타', '기타']}

In [44]:
ds.save_to_disk("en_ko_12m_with_super_domain")

Saving the dataset (0/11 shards):   0%|          | 0/11895711 [00:00<?, ? examples/s]

### feature 정리

In [1]:
from datasets import load_dataset, load_from_disk, ClassLabel, DatasetDict, Dataset
import pandas as pd

In [2]:
ds = load_from_disk("/home/paokimsiwoong/workspace/github.com/paokimsiwoong/transformer_experiments/eda/en_ko_12m_with_super_domain")

In [3]:
ds

DatasetDict({
    train: Dataset({
        features: ['domain', 'subdomain', 'style', 'target', 'source', 'target_text', 'source_text', 'super_domain'],
        num_rows: 11895711
    })
})

In [8]:
print(f'==>> type(ds["train"]["super_domain"]): {type(ds["train"]["super_domain"])}')

==>> type(ds["train"]["super_domain"]): <class 'datasets.arrow_dataset.Column'>

In [5]:
ds_filtered  = ds.filter(lambda x: x["super_domain"] != "기타")
ds_filtered

DatasetDict({
    train: Dataset({
        features: ['domain', 'subdomain', 'style', 'target', 'source', 'target_text', 'source_text', 'super_domain'],
        num_rows: 10393939
    })
})

In [4]:
df = ds["train"].to_pandas()

In [11]:
df.head()

,domain,subdomain,style,target,source,target_text,source_text,super_domain
0,일상생활,구매,구어체,ko,en,>제가 이걸 보여드리겠습니다.,>Let me show you this.,일상/대화
1,일상생활,구매,구어체,ko,en,">지금도, 지금도 보면 다들 고개를 끄덕끄덕했잖아.","> Even now, everyone is nodding.",일상/대화
2,일상생활,구매,구어체,ko,en,>와우영미.,> WaWooYoungmi.,일상/대화
3,일상생활,구매,구어체,ko,en,>그래요.,> Okay.,일상/대화
4,일상생활,구매,구어체,ko,en,없어도 돼요.,I don't need it.,일상/대화

In [4]:
df["super_domain"].value_counts()

super_domain
과학/기술/학술자료    3822044
일상/대화         2719332
기타            1501772
문화/예술/역사      1346542
의학/보건          720037
법률/행정          626520
뉴스/시사          619465
특허             359999
금융/경제          180000
Name: count, dtype: int64

In [5]:
df_f = df[df["super_domain"] != "기타"]

In [6]:
df_f["super_domain"].value_counts()

super_domain
과학/기술/학술자료    3822044
일상/대화         2719332
문화/예술/역사      1346542
의학/보건          720037
법률/행정          626520
뉴스/시사          619465
특허             359999
금융/경제          180000
Name: count, dtype: int64

In [8]:
df_f.head()

,domain,subdomain,style,target,source,target_text,source_text,super_domain
0,일상생활,구매,구어체,ko,en,>제가 이걸 보여드리겠습니다.,>Let me show you this.,일상/대화
1,일상생활,구매,구어체,ko,en,">지금도, 지금도 보면 다들 고개를 끄덕끄덕했잖아.","> Even now, everyone is nodding.",일상/대화
2,일상생활,구매,구어체,ko,en,>와우영미.,> WaWooYoungmi.,일상/대화
3,일상생활,구매,구어체,ko,en,>그래요.,> Okay.,일상/대화
4,일상생활,구매,구어체,ko,en,없어도 돼요.,I don't need it.,일상/대화

In [9]:
df_f = df_f.rename(columns={'target_text': 'kor', 'source_text': 'en'})

In [8]:
df_f.head()

,domain,subdomain,style,target,source,kor,en,super_domain
0,일상생활,구매,구어체,ko,en,>제가 이걸 보여드리겠습니다.,>Let me show you this.,일상/대화
1,일상생활,구매,구어체,ko,en,">지금도, 지금도 보면 다들 고개를 끄덕끄덕했잖아.","> Even now, everyone is nodding.",일상/대화
2,일상생활,구매,구어체,ko,en,>와우영미.,> WaWooYoungmi.,일상/대화
3,일상생활,구매,구어체,ko,en,>그래요.,> Okay.,일상/대화
4,일상생활,구매,구어체,ko,en,없어도 돼요.,I don't need it.,일상/대화

In [31]:
dup_check = df.duplicated(subset="target_text")

In [32]:
dup_check.head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [33]:
dup_check.value_counts()

False    10740854
True      1154857
Name: count, dtype: int64

In [34]:
dup_check[dup_check == True]

58          True
72          True
101         True
111         True
112         True
            ...
11895690    True
11895692    True
11895698    True
11895701    True
11895703    True
Length: 1154857, dtype: bool

In [7]:
ds_filtered["train"]

Dataset({
    features: ['domain', 'subdomain', 'style', 'target', 'source', 'target_text', 'source_text', 'super_domain'],
    num_rows: 10393939
})

In [8]:
df_f = ds_filtered["train"].to_pandas()

:

In [ ]:
df_f["super_domain"].value_counts()

NameError: name 'ds_filtered' is not defined

In [13]:
etc = df[df["super_domain"] == "기타"]
etc.head()

,domain,subdomain,style,target,source,target_text,source_text,super_domain
10293293,None,None,구어체,ko,en,'Bible Coloring'은 성경의 아름다운 이야기를 체험 할 수 있는 컬러링 ...,Bible Coloring' is a coloring application that...,기타
10293294,None,None,구어체,ko,en,씨티은행에서 일하세요?,Do you work at a City bank?,기타
10293295,None,None,구어체,ko,en,푸리토의 베스트셀러는 해외에서 입소문만으로 4차 완판을 기록하였다.,"PURITO's bestseller, which recorded 4th rough ...",기타
10293296,None,None,구어체,ko,en,11장에서는 예수님이 이번엔 나사로를 무덤에서 불러내어 죽은 자 가운데서 살리셨습니다.,In Chapter 11 Jesus called Lazarus from the to...,기타
10293297,None,None,구어체,ko,en,"6.5, 7, 8 사이즈가 몇 개나 더 재입고 될지 제게 알려주시면 감사하겠습니다.",I would feel grateful to know how many stocks ...,기타

In [14]:
etc["style"].value_counts()

style
문어체    1001772
구어체     400000
대화체     100000
Name: count, dtype: int64

In [15]:
lit = etc[etc["style"] == "문어체"]
lit.head()

,domain,subdomain,style,target,source,target_text,source_text,super_domain
10793293,None,None,문어체,ko,en,스키너가 말한 보상은 대부분 눈으로 볼 수 있는 현물이다.,Skinner's reward is mostly eye-watering.,기타
10793294,None,None,문어체,ko,en,심지어 어떤 문제가 발생할 건지도 어느 정도 예측이 가능하다.,Even some problems can be predicted.,기타
10793295,None,None,문어체,ko,en,오직 하나님만이 그 이유를 제대로 알 수 있을 겁니다.,Only God will exactly know why.,기타
10793296,None,None,문어체,ko,en,중국의 논쟁을 보며 간과해선 안 될 게 기업들의 고충이다.,Businesses should not overlook China's dispute.,기타
10793297,None,None,문어체,ko,en,박자가 느린 노래는 오랜 시간이 지나 뜨는 경우가 있다.,Slow-beating songs often float over time.,기타

In [27]:
lit.sample(10)

,domain,subdomain,style,target,source,target_text,source_text,super_domain
11270382,None,None,문어체,ko,en,가민에 따르면 지난해 4월 가민 한국지사를 설립한 이후 올해 상반기 매출 성장이 지...,Since establishing its Korean branch in April ...,기타
11476363,None,None,문어체,ko,en,강원 강릉의 한 펜션에서 일산화탄소 중독으로 의식을 잃어 병원에서 치료를 받고 있는...,Students who are being treated at hospitals fo...,기타
11371189,None,None,문어체,ko,en,양 대표는 “솔직히 중소기업에서 안전을 고려해 상대적으로 비싼 장비를 구입하는 것은...,"CEO Yang said, ""To be honest, it is not easy f...",기타
11388112,None,None,문어체,ko,en,"귀화한 라틀리프를 보유한 현대모비스는 외국인 선수 2명이 뛸 수 있는 2,3쿼터에 ...","Hyundai Mobis, which owns the naturalized Ratl...",기타
10991833,None,None,문어체,ko,en,노조는 “권력을 감시하던 언론인이 하루 아침에 권력 핵심부의 공직자로 자리를 옮겼다...,"""A journalist who had been monitoring power mo...",기타
11208222,None,None,문어체,ko,en,폭스콘은 중국·동남아와 비교해 인건비가 비싼 일본에서 가전을 생산하는 것은 수지에 ...,Foxconn decided that producing household appli...,기타
11166881,None,None,문어체,ko,en,김용진 기획재정부 차관이 31일 서울시 서초구 반포대로 서울지방조달청에서 열린 제7...,Vice-minister Kim Yong-jin of the Ministry of ...,기타
11218964,None,None,문어체,ko,en,삼화페인트 컬러디자인센터(이하 삼화페인트)가 지난달26일 서울 삼성동 코엑스에서 열...,The Samhwa Paints Color Design Center (Samhwa ...,기타
10950960,None,None,문어체,ko,en,유럽 최대 경제강국인 독일이 미국이 제공하는 안보에 안주하면서 러시아와 천연가스 사...,The purpose is that the biggest economic power...,기타
11759927,None,None,문어체,ko,en,이것을 옮기라고 하면 한 번 옮기려면 이미 400억 이상이 투자된 것이 손실이다.,"If you ask to move it, you will lose the inves...",기타

In [16]:
aihub = load_dataset("csv", data_files="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/data.csv",)

In [17]:
aihub

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'cat'],
        num_rows: 1602418
    })
})

In [18]:
df_ai = aihub["train"].to_pandas()
df_ai.head()

,kor,en,cat
0,그 이후 그의 행방이 알려지지 않은 상황이다.,"Since then, his whereabouts are unknown.",2
1,그녀가 사라진 후 각종 의혹은 꼬리를 물었다.,Various doubts arose after she disappeared.,2
2,당연히 러시아인 승객이 제일 먼저 부름을 받았다.,"Naturally, Russian passengers were called first.",2
3,더 중요한 것은 고용이 대체적으로 안정됐다는 점이다.,"More importantly, employment is generally stable.",2
4,모세가 죽고 나서 이제 여호수아가 이스라엘을 이끌었습니다.,Joshua led Israel after Moses died.,2

In [20]:
df_ai[df_ai["cat"] == 0].head()

,kor,en,cat
400298,'Bible Coloring'은 성경의 아름다운 이야기를 체험 할 수 있는 컬러링 ...,Bible Coloring' is a coloring application that...,0
400299,씨티은행에서 일하세요?,Do you work at a City bank?,0
400300,푸리토의 베스트셀러는 해외에서 입소문만으로 4차 완판을 기록하였다.,"PURITO's bestseller, which recorded 4th rough ...",0
400301,11장에서는 예수님이 이번엔 나사로를 무덤에서 불러내어 죽은 자 가운데서 살리셨습니다.,In Chapter 11 Jesus called Lazarus from the to...,0
400302,"6.5, 7, 8 사이즈가 몇 개나 더 재입고 될지 제게 알려주시면 감사하겠습니다.",I would feel grateful to know how many stocks ...,0

In [21]:
df_ai[df_ai["cat"] == 1].head()

,kor,en,cat
300298,이번 신제품 출시에 대한 시장의 반응은 어떤가요?,How is the market's reaction to the newly rele...,1
300299,판매량이 지난번 제품보다 빠르게 늘고 있습니다.,The sales increase is faster than the previous...,1
300300,그렇다면 공장에 연락해서 주문량을 더 늘려야겠네요.,"Then, we'll have to call the manufacturer and ...",1
300301,"네, 제가 연락해서 주문량을 2배로 늘리겠습니다.","Sure, I'll make a call and double the volume o...",1
300302,지난 회의 마지막에 논의했던 안건을 다시 볼까요?,Shall we take a look at the issues we discusse...,1

In [22]:
df_ai[df_ai["cat"] == 2].head()

,kor,en,cat
0,그 이후 그의 행방이 알려지지 않은 상황이다.,"Since then, his whereabouts are unknown.",2
1,그녀가 사라진 후 각종 의혹은 꼬리를 물었다.,Various doubts arose after she disappeared.,2
2,당연히 러시아인 승객이 제일 먼저 부름을 받았다.,"Naturally, Russian passengers were called first.",2
3,더 중요한 것은 고용이 대체적으로 안정됐다는 점이다.,"More importantly, employment is generally stable.",2
4,모세가 죽고 나서 이제 여호수아가 이스라엘을 이끌었습니다.,Joshua led Israel after Moses died.,2

In [23]:
df_ai[df_ai["cat"] == 3].head()

,kor,en,cat
600298,강릉 기생 매화가 등장하는 판소리 열두마당의 하나인 「강릉매화전」은 판소리 특유의 ...,"<Gangneung Maehwajeon>, one of the twelve mada...",3
600299,"다양한 미술관련 전시회의 개최, 각종 교육프로그램과 새로운 미술 사업을 개발하고 운...",The purpose of the establishment was to hold v...,3
600300,간장은 가정에서 담구던 재래식 간장과 공장에서 양조된 개량식 간장으로 나뉜다.,There are two main types of soy sauce: home-br...,3
600301,그는 한국에 발을 내딛은 최조의 가톨릭 사제로 한국 역사에서 중요한 위치를 차지하고...,He occupies a significant position in Korean h...,3
600302,"덕사의 창건은 신라 말 고려 초라고 전해지나 문헌이 없어 상세히 알 길이 없고, 현...",It is unclear regarding the foundation of Deok...,3

In [24]:
df_ai[df_ai["cat"] == 4].head()

,kor,en,cat
200000,의원의 회의규칙 제47조제1항,Article 47(1) of the Members' Meeting Rules,4
200001,ⓛ비공개회의록은 원고로서 보관한다.,(1) The non-public meeting minutes shall be ke...,4
200002,o 보고지연 훈계 3일이상,– Delay in reporting results in discipline at ...,4
200003,건물면적은 33제곱미터(전용면적) 이상이어야 한다.,The building area shall be at least 33 m² (exc...,4
200004,이 경우 「행정대집행법」을 준용한다.,"In such cases, the Vicarious Administrative Ex...",4

In [25]:
df_ai[df_ai["cat"] == 5].head()

,kor,en,cat
901485,"""경기도가 말산업 육성을 위해 총예산 245,193천원으로 2013년 경기도 용인시...","""The Gyeonggi provincial government announced ...",5
901486,"""경기도가 주최하고 경기FTA활용지원센터와 코트라가 주관한 이번 시장개척단은 지난 ...","""Organized by Gyeonggi provincial government a...",5
901487,"""경기도가 주최하고 경기도비정규직지원센터가 주관한 이번 교육은 공공 부문이 직·간접...","""Organized by Gyeonggi provincial government a...",5
901488,"""경기도가 주최하고 사단법인 한국장애인복지시설협회 경기도협회(대표자:정권)에서 주관...","""Organized by Gyeonggi provincial government a...",5
901489,"""경기도가 주최하고 인구보건복지협회 경기지회, 아이낳기좋은세상 경기운동본부가 주관하...","""Hosted by Gyeonggi provincial government, org...",5

In [28]:
df_ai[df_ai["kor"] == "스키너가 말한 보상은 대부분 눈으로 볼 수 있는 현물이다."]

,kor,en,cat
1402407,스키너가 말한 보상은 대부분 눈으로 볼 수 있는 현물이다.,Skinner's reward is mostly eye-watering.,2

In [19]:
df_ai["cat"]

0          2
1          2
2          2
3          2
4          2
          ..
1602413    2
1602414    2
1602415    2
1602416    2
1602417    2
Name: cat, Length: 1602418, dtype: int64

In [ ]:
# cat_names = ["구어체", "대화체", "문어체_뉴스", "문어체_한국문화", "문어체_조례", "문어체_지자체웹사이트"]

# super_domain
# 과학/기술/학술자료    3822044
# 일상/대화         2719332
# 문화/예술/역사      1346542
# 의학/보건          720037
# 법률/행정          626520
# 뉴스/시사          619465
# 특허             359999
# 금융/경제          180000
# Name: count, dtype: int64

In [ ]:
# ds_ai = DatasetDict(
#     {
#         "train": Dataset.from_pandas(df_ai.reset_index(drop=True))
#     }
# )

In [ ]:
# ds_ai

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'cat'],
        num_rows: 1602418
    })
})

In [19]:
ds_ai = aihub

In [20]:
# cat_names = ["구어체", "대화체", "문어체_뉴스", "문어체_한국문화", "문어체_조례", "문어체_지자체웹사이트"]

def map_domain(raw_domain) -> str:
    if raw_domain == 0:
        return "일상/대화"
    
    if raw_domain == 1:
        return "일상/대화"
    
    if raw_domain == 2:
        return "뉴스/시사"
    
    if raw_domain == 3:
        return "문화/예술/역사"
    
    if raw_domain == 4:
        return "법률/행정"

    if raw_domain == 5:
        return "뉴스/시사"
    
    return "기타"

In [21]:
def map_domain_batch(batch):
    batch["super_domain"] = [map_domain(c) for c in batch["cat"]]
    return batch

In [22]:
ds_ai = ds_ai.map(map_domain_batch, batched=True)

Map:   0%|          | 0/1602418 [00:00<?, ? examples/s]

In [23]:
ds_ai

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'cat', 'super_domain'],
        num_rows: 1602418
    })
})

In [24]:
df_ai_new = ds_ai["train"].to_pandas()

In [25]:
df_ai_new.head()

,kor,en,cat,super_domain
0,그 이후 그의 행방이 알려지지 않은 상황이다.,"Since then, his whereabouts are unknown.",2,뉴스/시사
1,그녀가 사라진 후 각종 의혹은 꼬리를 물었다.,Various doubts arose after she disappeared.,2,뉴스/시사
2,당연히 러시아인 승객이 제일 먼저 부름을 받았다.,"Naturally, Russian passengers were called first.",2,뉴스/시사
3,더 중요한 것은 고용이 대체적으로 안정됐다는 점이다.,"More importantly, employment is generally stable.",2,뉴스/시사
4,모세가 죽고 나서 이제 여호수아가 이스라엘을 이끌었습니다.,Joshua led Israel after Moses died.,2,뉴스/시사

In [26]:
df_ai_new["super_domain"].value_counts()

super_domain
뉴스/시사       901474
일상/대화       500000
문화/예술/역사    100646
법률/행정       100298
Name: count, dtype: int64

In [27]:
df_ai_new_new = df_ai_new.drop('cat', axis=1)
df_ai_new_new.head()

,kor,en,super_domain
0,그 이후 그의 행방이 알려지지 않은 상황이다.,"Since then, his whereabouts are unknown.",뉴스/시사
1,그녀가 사라진 후 각종 의혹은 꼬리를 물었다.,Various doubts arose after she disappeared.,뉴스/시사
2,당연히 러시아인 승객이 제일 먼저 부름을 받았다.,"Naturally, Russian passengers were called first.",뉴스/시사
3,더 중요한 것은 고용이 대체적으로 안정됐다는 점이다.,"More importantly, employment is generally stable.",뉴스/시사
4,모세가 죽고 나서 이제 여호수아가 이스라엘을 이끌었습니다.,Joshua led Israel after Moses died.,뉴스/시사

In [28]:
df_ai_new_new.to_csv("data_aihub.csv", index=False)

In [14]:
df_f.head()

,domain,subdomain,style,target,source,kor,en,super_domain
0,일상생활,구매,구어체,ko,en,>제가 이걸 보여드리겠습니다.,>Let me show you this.,일상/대화
1,일상생활,구매,구어체,ko,en,">지금도, 지금도 보면 다들 고개를 끄덕끄덕했잖아.","> Even now, everyone is nodding.",일상/대화
2,일상생활,구매,구어체,ko,en,>와우영미.,> WaWooYoungmi.,일상/대화
3,일상생활,구매,구어체,ko,en,>그래요.,> Okay.,일상/대화
4,일상생활,구매,구어체,ko,en,없어도 돼요.,I don't need it.,일상/대화

In [10]:
df_f_new = df_f.drop(['domain', 'subdomain', 'style', 'target', 'source'], axis=1)
df_f_new.head()

                            kor                                en super_domain
0              >제가 이걸 보여드리겠습니다.            >Let me show you this.        일상/대화
1  >지금도, 지금도 보면 다들 고개를 끄덕끄덕했잖아.  > Even now, everyone is nodding.        일상/대화
2                        >와우영미.                   > WaWooYoungmi.        일상/대화
3                         >그래요.                           > Okay.        일상/대화
4                       없어도 돼요.                  I don't need it.        일상/대화

In [11]:
df_f_new["kor"] = df_f_new["kor"].str.lstrip(">")
df_f_new["en"] = df_f_new["en"].str.lstrip(">")

In [12]:
df_f_new["kor"] = df_f_new["kor"].str.lstrip()
df_f_new["en"] = df_f_new["en"].str.lstrip()

In [13]:
df_f_new.head()

                           kor                              en super_domain
0              제가 이걸 보여드리겠습니다.           Let me show you this.        일상/대화
1  지금도, 지금도 보면 다들 고개를 끄덕끄덕했잖아.  Even now, everyone is nodding.        일상/대화
2                        와우영미.                   WaWooYoungmi.        일상/대화
3                         그래요.                           Okay.        일상/대화
4                      없어도 돼요.                I don't need it.        일상/대화

In [14]:
df_f_new["super_domain"].value_counts()

super_domain
과학/기술/학술자료    3822044
일상/대화         2719332
문화/예술/역사      1346542
의학/보건          720037
법률/행정          626520
뉴스/시사          619465
특허             359999
금융/경제          180000
Name: count, dtype: int64

In [15]:
df_f_new.to_csv("data.csv", index=False)

In [ ]:
# ds_new = DatasetDict(
#     {
#         "train": Dataset.from_pandas(df_f_new.reset_index(drop=True))
#     }
# )

:

In [35]:
# df_result = pd.merge(df_f_new, df_ai_new_new, on="super_domain")

In [ ]:
# ds_ai_new = DatasetDict(
#     {
#         "train": Dataset.from_pandas(df_ai_new_new.reset_index(drop=True))
#     }
# )

:

### 데이터셋 합치기

In [31]:
from datasets import load_dataset, load_from_disk, ClassLabel, DatasetDict, Dataset, concatenate_datasets
import pandas as pd

In [29]:
data = load_dataset("csv", data_files="data.csv",)
data

Generating train split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'super_domain'],
        num_rows: 10393939
    })
})

In [30]:
aihub = load_dataset("csv", data_files="data_aihub.csv",)
aihub

Generating train split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'super_domain'],
        num_rows: 1602418
    })
})

In [32]:
data["train"] = concatenate_datasets([data["train"], aihub["train"]])

In [33]:
data

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'super_domain'],
        num_rows: 11996357
    })
})

In [34]:
data["train"] = data["train"].sort("super_domain")

In [35]:
data["train"] = data["train"].rename_column("super_domain", "domain")

In [36]:
data

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'domain'],
        num_rows: 11996357
    })
})

In [37]:
data["train"][0:10]

{'kor': ['특정 지역에서는 순위 변동이 크게 나타나고 있는 점에 주목해야 한다.',
  'Post-2020 체제에서는 매5년마다 이전 수준보다 개선된 온실가스 감축 목표를 유엔에 제출해야 하는 래칫 메커니즘이 적용되므로, 국내 최대 온실가스 배출 원인 발전 부문의 감축 부담도 크게 증가할 전망이다.',
  '회귀 모델은 모두 통계적으로 유의하였고, 분산 팽창 계수(VIF)도 모두 2 내외의 양호한 값을 보여 다중 공선성의 문제도 크지 않음을 확인하였다.',
  'OOF에 대한 연구는 그 중요성에도 불구하고 다른 개발 재원에 대한 연구에 비해 매우 부족한 실정이며, 다음의 측면에서 한계를 보이고 있다.',
  '이에 기대효용 이론에 기초하여 투자자들의 고차 적률 위험에 대한 선호를 반영할 수 있는 일반적 성과 지표를 개발할 필요성이 대두되었다.',
  '본 연구에서 통제 변수로 사용되는 나머지 변수들은 선행 연구들의 결과와 일치하게 모두 기업 설명회 개최 기업과 그렇지 않은 기업에 차이가 있는 것으로 나타났다.',
  '최근에는 이러한 문제에서 벗어나고자 국민 계정상 비법인 개인 기업의 영업 잉여를 자영업 소득으로 간주하고 이를 노동 소득과 자본 소득으로 적절히 분할하는 방법을 사용하고 있다.',
  '만약 2012년 한국 선박 금융 공사가 설립되어 운영되었다고 가정하면 해운 업계가 현재와 같은 위기 상황으로까지 내몰리지는 않았을 수도 있었을 것이다.',
  '자녀 양육을 지원하기 위한 다양한 공적이전소득에서 영유아 자녀에 대한 지원을 분리하여 산출할 필요가 있다.',
  '지금까지 시도된 참여형 정책 결정 과정들 대부분은 위로부터의 주어진 장에서, 초대받은 자들이 주어진 임무를 수행하는 것이다.'],
 'en': ['It should be noted that there are significant ranking fluctuations in certain regions.',
  "Under the Post-2020 system, the ratchet mechanism, which requires the U.N. to submit improved greenhouse gas reduction targets every five years, is expected to significantly increase the burden on the nation's largest greenhouse gas emission-causing power generation.",
  'All regression models were statistically significant, and the variance inflation coefficient (VIF) all showed good values around 2, confirming that the problem of multicollinearity was not significant.',
  'Despite its importance, research on OOF is insufficient compared to research on other development resources, and it has limitations in the following aspects.',
  "This led to the need to develop general performance indicators that could reflect investors' preferences for higher-order adequacy risks based on the theory of expected utility.",
  'Consistent with the results of previous studies, the remaining variables used as control variables in this study were all found to be different between the companies holding the company briefing session and the companies that did not.',
  'Recently, in order to escape from this problem, the operating surplus of unincorporated private companies in the national account is regarded as self-employment income and the method is appropriately divided into labor income and capital income.',
  'If it was assumed that the Korea Shipping Finance Corporation was established and operated in 2012, the shipping industry might not have been pushed to the current crisis.',
  "It's important to calculate the support for babies and toddlers separately from various public transfer incomes to support child rearing.",
  'Most of the participatory policy-making processes that have been attempted so far are that the invitees perform their assigned tasks in each field from above.'],
 'domain': ['과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료']}

In [38]:
data.save_to_disk("en_ko_12m_p")

Saving the dataset (0/10 shards):   0%|          | 0/11996357 [00:00<?, ? examples/s]

In [1]:
from datasets import load_dataset, load_from_disk, ClassLabel, DatasetDict, Dataset, concatenate_datasets
import pandas as pd

In [2]:
ds = load_from_disk("/home/paokimsiwoong/workspace/github.com/paokimsiwoong/transformer_experiments/eda/en_ko_12m")

In [3]:
ds

DatasetDict({
    train: Dataset({
        features: ['domain', 'subdomain', 'style', 'target', 'source', 'target_text', 'source_text'],
        num_rows: 11895711
    })
})

In [4]:
df = ds["train"].to_pandas()

In [5]:
df["style"].value_counts()

style
문어체     5923098
구어체     3119332
None    2393282
특허       359999
대화체      100000
Name: count, dtype: int64

In [6]:
df[df["style"] == "None"].sample(10)

,domain,subdomain,style,target,source,target_text,source_text
7263363,의료/보건,None,None,ko,en,사망자 중 60세 이상 노인층은 516명으로 49.8%에 달한다.,"Among the deaths, 516 elderly people aged 60 o..."
7372658,의료/보건,None,None,ko,en,"전염병 대응과 같은 긴급 상황에서는 일부 단계를 생략해 기간을 단축할 수 있지만, ...",In emergency situations such as a response to ...
6410470,IT/기술,None,None,ko,en,JW홀딩스는 자회사인 JW생명과학의 3체임버 종합영양수액제가 '현재 세계일류상품'에...,JW Holdings announced on the 22nd that its sub...
6476765,가정통신문,None,None,ko,en,"아울러, 유행하는 대부분의 감염병이 손을 통해 우리 몸으로 들어옵니다.","In addition, most of the prevalent infectious ..."
4267751,연예공연,연예가중계,None,ko,en,친구들은 제 광고를 보면 많이 놀려요.,My friends tease me a lot when they see my ads.
7412754,향토문화/음식,None,None,ko,en,"동쪽으로 이승골산과 짓당산, 남쪽으로 불무골, 북쪽으로 봉화산이 있으며, 서쪽으로 ...",It borders Iseunggolsan Mountain and Jidangsan...
5561257,생물학 생화학,None,None,ko,en,이를 위해 효과적인 모기 방역 기법을 도출하기 위해 모기 서식 환경을 분석하여 세종...,"To this end, in order to derive effective mosq..."
6201091,화학,화학,None,ko,en,뉴질랜드는 학교 단위 수준에서 교사들의 자율성과 전문성을 존중하고 학교별로 핵심 역...,New Zealand has a number of programs at the sc...
6585771,관광,None,None,ko,en,철근과 콘크리트의 열팽창 계수가 거의 같다는 것은 우리 인류에게 축복과 같은 일이었다.,It was a blessing for us humans to have almost...
6379244,IT/기술,None,None,ko,en,국토부는 신분증 미소지 승객의 불편을 해소하기 위해 정부가 발행하는 전자증명으로 신...,"The Ministry of Land, Infrastructure and Trans..."

In [6]:
df["domain"].value_counts()

domain
None                             1501772
해외영업                             1260367
일상생활                              899757
경제                                548114
해외고객과의채팅                          540221
                                  ...
역사/근현대|문화·교육/언론·출판|문화유산/기록 유산          1
역사/근현대|종교/기독교|성씨·인물/근현대인물              1
역사/근현대|정치·경제·사회/경제 산업                  1
역사/근현대|인물/근현대 인물                       1
정치·경제·사회/경제·산업|문화·교육/문화·예술             1
Name: count, Length: 664, dtype: int64

In [7]:
df[df["domain"] == "해외고객과의채팅"].sample(10)

,domain,subdomain,style,target,source,target_text,source_text
1952364,해외고객과의채팅,도소매유통,구어체,ko,en,"하지만 비용이 50,000달러가 넘습니다.","But it would cost you over 50,000 dollars."
498574,해외고객과의채팅,도소매유통,구어체,ko,en,하지만 점점 플랫폼도 많아지고 경쟁이 치열합니다.,"However, there are more and more platforms and..."
1813138,해외고객과의채팅,"금융,보험",구어체,ko,en,시간이 충분하지 않았습니다.,We did not have enough time.
1917104,해외고객과의채팅,도소매유통,구어체,ko,en,"네, 물론입니다, 기다릴 수 있습니다.","Yes, sure, I can wait."
577687,해외고객과의채팅,도소매유통,구어체,ko,en,기존의 제품을 사용해도 되는지의 여부를 판단해서 준비하시면 되겠습니다.,You can decide whether you can use the existin...
2043666,해외고객과의채팅,정보통신,구어체,ko,en,대체불가 토큰에 대해 여쭤보고 싶습니다.,I just want to ask something about non-fungibl...
1940557,해외고객과의채팅,도소매유통,구어체,ko,en,제가 곧 이메일로 위탁 내역을 보내드리겠습니다.,I will send the consignment details through em...
456657,해외고객과의채팅,"기계장비,의료정밀",구어체,ko,en,계약서 초안에 몇 가지 불합리한 조항이 있는것 같아서요.,I think there are some unreasonable provisions...
708553,해외고객과의채팅,정보통신,구어체,ko,en,그런데 1안과 2안의 차이가 너무 커서 고민이 됩니다.,But I'm worried because it has a large differe...
1886022,해외고객과의채팅,도소매유통,구어체,ko,en,웹사이트에서 주문할 때의 제품 및 라벨의 스크린샷과 제 이메일 주소로 발송된 인보이...,I have a screenshot of the product and the lab...

In [8]:
df[df["domain"] == "해외영업"].sample(10)

,domain,subdomain,style,target,source,target_text,source_text
2619839,해외영업,"연구개발,과학기술",구어체,ko,en,우리가 많은 정보와 지식을 가지고 새로운 세계를 탐험할 수 있게 해줍니다.,"It lets us explore a new world, with much info..."
2483955,해외영업,도소매유통,구어체,ko,en,판매하는 제품인가요?,Are they included in the sale?
1104331,해외영업,도소매유통,구어체,ko,en,"집, 사무실, 이동중 어디서든 걱정없이 통화 가능합니다.","You can make calls without worries at home, in..."
1263158,해외영업,"연구개발,과학기술",구어체,ko,en,농도는 매우 신중하게 고려되어야 한다.,The concentration should be very carefully con...
802931,해외영업,도소매유통,구어체,ko,en,그러나 저는 공지 된 시간 내에 제품을 받지 못했습니다.,But I didn't receive the product within the an...
852699,해외영업,도소매유통,구어체,ko,en,식사량을 조절하고 체중을 관리하는데 효과적입니다.,It is effective in controlling the amount of m...
779610,해외영업,도소매유통,구어체,ko,en,그러나 저희는 아직 귀하로부터 입금을 받지 못했습니다.,But we haven't received a deposit from you yet.
1269221,해외영업,"연구개발,과학기술",구어체,ko,en,"Mr. Willson 선생님, 저희 쪽에서 생산하는 탄산 칼슘의 재료를 그쪽에서 받...","Mr. Wilson, I'd like to receive the ingredient..."
2239717,해외영업,도소매유통,구어체,ko,en,팬데믹 기간 중 당사는 해외 수출을 시작했습니다.,"During the pandemic, we started exporting our ..."
886539,해외영업,도소매유통,구어체,ko,en,저희는 300개에 대한 금액을 모두 지불했습니다.,We paid for all 300 pieces.

In [9]:
df[df["domain"] == "일상생활"].sample(10)

,domain,subdomain,style,target,source,target_text,source_text
166737,일상생활,여행,구어체,ko,en,>준비 시작하면 시작돼요.,>It starts when we get ready.
1441689,일상생활,여행,구어체,ko,en,소백산은 지방의 동쪽에 위치하고 있어요.,Mount Sobaek is located in the east of the pro...
237779,일상생활,예약,구어체,ko,en,>그런데 그렇게 해야 들어가.,>But you have to do it like that to go in.
1581256,일상생활,예약,구어체,ko,en,"프라이드 치킨, 프라이드 프라이, 버거와 같은 음식들이요.","Such as fried chicken, fried fries, and burgers."
801,일상생활,구매,구어체,ko,en,">야, 양세형 잘하네 양세형.",">Hey, Yang Se-hyeong is good. >Hey, Yang Se-hy..."
1551921,일상생활,여행,구어체,ko,en,그럼 먼저 좋은 점을 알려주세요.,Tell me the good ones first then.
1636865,일상생활,예약,구어체,ko,en,"AAA1, 추모식에서 아빠 추모연설을 해줘.","AAA1, I want you to perform the eulogy for Dad..."
236095,일상생활,예약,구어체,ko,en,그리고 만약에 부위에 부딪히면 그 자리 서있어야.,"And if you hit a part, you have to stand there."
281546,일상생활,음식,구어체,ko,en,> 아 그럼요 송지효도 지금 저한테 빠져 있잖아요.,"> Oh, of course. Song Jihyo is also into me ri..."
441803,일상생활,음식,구어체,ko,en,>어유~,>Uh~

In [10]:
df[df["domain"] == "구어체_대화체"].sample(10)

,domain,subdomain,style,target,source,target_text,source_text
5020911,구어체_대화체,None,구어체,ko,en,연중무휴 아니었어? 갑자기 왜 쉬는 건지 모르겠네.,Isn't it open throughout the year? What happened?
5020521,구어체_대화체,None,구어체,ko,en,그렇군요. 4주 동안 머물 곳은 정하셨나요? 확인할 방법이 있을까요?,I see. Have you confirmed where to stay for 4 ...
5025310,구어체_대화체,None,구어체,ko,en,이제 본다는 생각과 그냥 좋아서 이러고 있어.,I'm just doing like this with the thought that...
5011237,구어체_대화체,None,구어체,ko,en,"나는 하정우가 먹는 방식, 입는 방식이 좋아.",I like the way Ha Jung Woo eats and wears.
5015997,구어체_대화체,None,구어체,ko,en,그는 30분 전에 기차를 타러 나갔습니다.,He took off about half an hour ago to catch th...
5018325,구어체_대화체,None,구어체,ko,en,오백 미터 정도 걸어가면 돼요.,You just need to walk about 500 meters.
5020701,구어체_대화체,None,구어체,ko,en,혹시 위치를 잘못 말한 거 아닐까요? 확인 전화해 보세요.,Maybe you misdirected it. Give a call to check...
5029166,구어체_대화체,None,구어체,ko,en,제 생각에 이 배송 상자는 멀쩡한데 제품만 손상된 것으로 보아 배송 중 생긴 문제는...,Judging by the fact that the product was damag...
5024096,구어체_대화체,None,구어체,ko,en,"이 치즈로 수없이 많은 요리를 할 수 있지만, 튀김과 조림 요리가 가장 선호되죠.",You can cook countless dishes with this cheese...
5011250,구어체_대화체,None,구어체,ko,en,"나의 롤모델은 나의 언니, AAA입니다.","My role model is my older sister, AAA."

In [ ]:
# TODO: cat 칼럼 추가하기
# TODO: 중복 지우기

In [1]:
from datasets import load_dataset, load_from_disk, ClassLabel, DatasetDict, Dataset, concatenate_datasets
import pandas as pd

In [2]:
ds = load_from_disk("/home/paokimsiwoong/workspace/github.com/paokimsiwoong/transformer_experiments/eda/en_ko_12m_p")

In [3]:
ds

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'domain'],
        num_rows: 11996357
    })
})

In [4]:
df = ds["train"].to_pandas()

In [5]:
df["domain"].value_counts()

domain
과학/기술/학술자료    3822044
일상/대화         3219332
뉴스/시사         1520939
문화/예술/역사      1447188
법률/행정          726818
의학/보건          720037
특허             359999
금융/경제          180000
Name: count, dtype: int64

In [8]:
# 과학/기술/학술자료 일상/대화 뉴스/시사 문화/예술/역사 법률/행정 의학/보건 특허 금융/경제
df[df["domain"] == "과학/기술/학술자료"].sample(10)

,kor,en,domain
2464871,"어떤 실시예에 따르면, 상기 시선 추적 모듈(391)은 시선추적을 위한 마이크로 카...","According to an embodiment, the eye tracking m...",과학/기술/학술자료
2393326,상기 명령어 생성부는 상기 요청동작 판단부의 판단에 따른 사용자의 요청동작에 대응하...,The command generation unit may generate a com...,과학/기술/학술자료
2374490,다른 부재중 전화의 발신측은 전화 번호가 1850으로 시작하는 휴대폰 사용자이다.,The calling party of the other missed call is ...,과학/기술/학술자료
1191170,미 국무부는 한국 대표단과 면담을 통해 공산주의의 위협과 한국 승인에 있어서 미국의...,Through an interview with the Korean delegatio...,과학/기술/학술자료
1542896,"수학 교과가 생각하는 방법을 익히는 과목임을 고려한다면, 다양한 분류 가능성이 있음...",Considering that mathematics is a subject in w...,과학/기술/학술자료
3163410,생성된 바이오 디젤은 국제 기준에 못 미치게 되면 디젤의 성능을 저하시키고 사용의 ...,If the produced biodiesel does not meet the in...,과학/기술/학술자료
205606,호주 최대 항공사인 콴타스의 여객기가 하루 동안 세 대나 비상 착륙하는 사태가 발생했다.,"Australia's largest flight, Qantas, made a cri...",과학/기술/학술자료
765746,"통일신보는 ""위성 발사 역사는 겨울철에 위성을 쏴올려 성공한 예가 매우 낮다는 것을...","The Unification Shinbo reported, ""The history ...",과학/기술/학술자료
2364034,수신된 디지털 컴포넌트는 데이터 처리 시스템(102)의 탐색 컴포넌트(118)에 의...,The received digital component may be rendered...,과학/기술/학술자료
861608,맨체스터에서 전날 밤 공연장 테러로 적어도 22명이 숨진 일로 파운드화 가치가 하락...,At least 22 people were killed in the previous...,과학/기술/학술자료

In [9]:
# 과학/기술/학술자료 일상/대화 뉴스/시사 문화/예술/역사 법률/행정 의학/보건 특허 금융/경제
df[df["domain"] == "일상/대화"].sample(10)

,kor,en,domain
10514542,처음에 투자로 구입했어요.,They were initially bought as investments.,일상/대화
8879564,스마트 온도/습도 자동 조절 기능이 있습니다.,It has a smart temperature/humidity automatic ...,일상/대화
11037338,이것은 이러한 로봇이 활동할 때 작업자의 감독이 거의 또는 전혀 없을 수 있음을 의...,This means that there could be little to no su...,일상/대화
11462590,"관세 지급 거부로 물건이 한국으로 반송되면 초기 출고 시 운임, 반송운임, 관세를 ...",If the product is returned to Korea due to rej...,일상/대화
8843209,어제?,Yesterday?,일상/대화
10205011,"아니, 불행히도 무제한 타코는 팔지 않아.","No, unfortunately, they don't serve unlimited ...",일상/대화
8873296,"환자가 끊이지 않고 있고, 특히 지금처럼 전염병이 도는 시기에는 특히 면역 검사 수...","The number of patients is constant, and the de...",일상/대화
10136270,"비건 다이어트를 할 수도 있고, 운동을 시작할 수도 있어요.","You can go on a vegan diet, or maybe start exe...",일상/대화
10650610,피부 톤이 고르지 않은 사람들에게 특히 효과적입니다.,It is especially useful for people with uneven...,일상/대화
10510359,또한 귀하의 비즈니스가 재정적 어려움을 겪을 때 대출을 제공합니다.,We also provide loans when your business exper...,일상/대화

In [10]:
# 과학/기술/학술자료 일상/대화 뉴스/시사 문화/예술/역사 법률/행정 의학/보건 특허 금융/경제
df[df["domain"] == "뉴스/시사"].sample(10)

,kor,en,domain
4406395,체조에 대한 관심 확대 및 우수 선수 발굴·육성을 위한 제12회 서울특별시교육감배 ...,The 12th Seoul Metropolitan Office of Educatio...,뉴스/시사
5066818,민간 기업에 특정인의 채용이나 보직변경을 요구하거나 공공이 개최하는 축제나 박람회 ...,Civil servants will be banned from soliciting ...,뉴스/시사
5323215,예상에 크게 못 미친 애플의 실적에 세계 금융시장이 요동쳤다.,The global financial market fluctuated by Appl...,뉴스/시사
4388899,'학교생활기록 작성 및 관리 지침'을 근거로 작성한 『2019학년도 학교생활기록부 ...,We inform you of changes to the rules related ...,뉴스/시사
5185296,다음달 중 시가 안을 제출하면 국토부는 검토에 착수하게 되며 이르면 올해 안에 승인...,If the city submits a market price within next...,뉴스/시사
4215816,경기 종료 후 신태용 감독이 이용과 기뻐하고 있다.,"After the game ends, Shin Tae-yong rejoices wi...",뉴스/시사
5413659,지난 1월 소망교회에서 은퇴한 김지철(70) 목사가 새로이 ‘미래목회와 말씀연구원(...,"That's why Rev. Kim Ji-cheol, 70, who retired ...",뉴스/시사
5349867,생선 등 수분이 있는 제품을 담는 합성수지 제품과 채소 등의 제품을 담는 속 비닐은...,Synthetic resin products containing moisture p...,뉴스/시사
4577640,양키스를 비롯해 빅마켓 구단들의 경쟁이 붙으며 계약 규모가 커졌다.,As Yankees and other big clubs get into the co...,뉴스/시사
4563020,전반 34분엔 앤드류 로버트슨의 패스를 받은 베이날둠이 페널티지역 왼쪽에서 달려들며...,"In the 34th minute of the first half, Beinaldu...",뉴스/시사

In [11]:
# 과학/기술/학술자료 일상/대화 뉴스/시사 문화/예술/역사 법률/행정 의학/보건 특허 금융/경제
df[df["domain"] == "문화/예술/역사"].sample(10)

,kor,en,domain
6727300,사회적 이슈에 대해 대중이 저마다 가진 다원적 의견들을 키치를 통해 소통할 수 있도...,This is because it allows the public to commun...,문화/예술/역사
6165038,서울 암사동유적의 유네스코(UNESCO) 세계문화유산 등재를 염원하며 화려한 막을 ...,"From the 11th of last month, when the festival...",문화/예술/역사
5784331,그리고 그 다음으로 비교할 제품은 이 두 가지 통심입니다.,And the next product to compare is these two m...,문화/예술/역사
6380516,"시도 19호선이 가송리의 중부를 동서 방향으로 지나고 있고, 기타 도로들이 가송리의...",City Road 19 runs east-west of the central par...,문화/예술/역사
6861041,"유리병으로 된 박카스는 다른 유리병과 부딪히는 과정에서 쉽게 깨지고, 종이로 된 라...","Bacchus, which was made up of a glass bottle, ...",문화/예술/역사
5767655,이제 같이 풀어야 하는 문제야.,Now it's a question we have to solve together.,문화/예술/역사
6113138,"이 밖에도 외국인들이 ‘코리안 범프’라고 하는 ‘어깨빵’, 폰딧불(스마트폰+반딧불이...","Newly coined words such as “Korean bump”, “sho...",문화/예술/역사
5841776,지금은 제가 메이크업까지 완성을 하고 왔습니다.,Now I have finished my makeup as well.,문화/예술/역사
6035241,그들은 이미 중력에 의해 방향 감각을 상실했다고 느낍니다.,They already feel disoriented by the force of ...,문화/예술/역사
6307077,그늘막은 햇볕을 가려주기도 하지만 때로는 어둠을 드리우는 위험한 상황을 만들기도 한다.,"The shade can cover the sun, but sometimes it ...",문화/예술/역사

In [12]:
# 과학/기술/학술자료 일상/대화 뉴스/시사 문화/예술/역사 법률/행정 의학/보건 특허 금융/경제
df[df["domain"] == "법률/행정"].sample(10)

,kor,en,domain
6992409,구청장은 평생교육 운영비 등을 지원받은 기관 및 단체에 대하여 그 운영비 등을 목적...,"The head of the Gu may confirm, instruct, and ...",법률/행정
7648610,"운영위원회에는 간사 1명을 두되, 간사는 담당 교육연구사로 하고 위원장의 명을 받아...",The Steering Committee shall have one executiv...,법률/행정
7102099,"피고인은 2009. 3. 일자불상경 2항과 같은 장소에서, 같은 방법으로 피해자의 ...","On March, 2009, the Defendant forced an indece...",법률/행정
7379035,"단 그 제한은 자유와 권리의 본질적인 내용을 훼손하여서는 아니되며 언론, 출판에 대...","However, the restriction shall not undermine t...",법률/행정
7158751,"소송 지휘에 관한 결정·명령이나 집행정지 결정, 비송 사건에 관한 결정에는 기판력이...",There is no judgment in decisions or orders co...,법률/행정
7124449,불법행위 당시 두 가지 이상의 수입원에 해당하는 영업활동에 종사하고 있던 피해자의 ...,Where the amount of lost income of each busine...,법률/행정
7675025,주민자치회 위원을 선정함에 있어 투명하고 공정한 추첨 방법 결정과 과정 관리를 위하...,In selecting members of the Residents' Self-Go...,법률/행정
7441761,"그 결과, 다양한 기업지배구조 평가점수(주주 권리보호, 이사회 특성, 공시(IR 실...","As a result, various corporate governance eval...",법률/행정
7441837,"다만, 좀 더 부언하다면 상대적으로 노령계층과 취약계층이 많은 군지역의 경우 국고보...","If I were to say more, the military area, whic...",법률/행정
7366808,판례법 국가가 아니며 권력구조도 다른 한국에서 사용하기에는 적당하지 않은 면이 있는...,It is an expression inappropriate to be used i...,법률/행정

In [13]:
# 과학/기술/학술자료 일상/대화 뉴스/시사 문화/예술/역사 법률/행정 의학/보건 특허 금융/경제
df[df["domain"] == "의학/보건"].sample(10)

,kor,en,domain
8311374,멕시코 추정치와 비교하여 시간 경과에 따른 변화를 평가하면 미국에서 사례 수와 발병...,"Compared to Mexican estimates, assessing chang...",의학/보건
8187872,하이드로 스캐폴드는 불수용성 겔 형성을 위해 가교를 하도록 자극하는 액체 폴리머이다.,Hydrogel scaffolds are liquid polymers that st...,의학/보건
7734268,"이들은 28개의 보명지주를 돕거나 강화하는 한약재를 비교 분석하여, 소음 체질 관련...",They compared and analyzed 28 herbal medicines...,의학/보건
7849381,뿌리 부분인 털망울이 위축되고 밑 부분이 탈색된 느낌표 모양의 모발도 흔히 관찰된다.,Exclamation mark-shaped hair with shrunk root ...,의학/보건
7900934,"입국할 때 발열 및 호흡기증상이 있다면 검역관에게 신고하여 역학조사에 협조하고, 메...",If you have any fever or respiratory symptoms ...,의학/보건
8078676,안전 사회를 위해 재난과 안전에 대한 법 체계가 중요하다.,The legal system for disaster and safety is im...,의학/보건
7747113,본 연구를 통해 선정된 11편의 문헌에서 7개의 허약 선별 평가 도구가 도출되었다.,Seven frailty screening evaluation tools were ...,의학/보건
8025708,이들에 대한 적절한 영양 공급차원의 경제적 지원제도 마련이 시급해 보인다.,There seems to be an urgent need to prepare an...,의학/보건
7798957,지난 29일 국내에서 코로나19 검사를 받고 있는 사람은 8634명이었다.,"On the 29th, 8,634 people were being tested fo...",의학/보건
8324176,악성 및 양성 상태를 별도로 진단하는 것은 임상 실습에서 빈번한 도전이다.,"Thus, separately diagnosing malignant and beni...",의학/보건

In [14]:
# 과학/기술/학술자료 일상/대화 뉴스/시사 문화/예술/역사 법률/행정 의학/보건 특허 금융/경제
df[df["domain"] == "특허"].sample(10)

,kor,en,domain
11792601,"터보 차저 과열 방지 장치 및 상기 장치의 제조 방법본 발명에 따라, 미네랄 절연 ...",Turbocharger overheating protection device and...,특허
11670799,트로폴론 유도체레티노이드 작용을 가지며 의약의 유효성분으로서 유용한 화학식 I로 표...,TROPOLONE DERIVATIVETropolone derivatives repr...,특허
11983908,보안 메시지 제공 방법 및 시스템보안 메시지 제공 방법 및 시스템을 제공한다.본 발...,METHOD AND SYSTEM FOR PROVIDING SECURE MESSAGE...,특허
11690430,경화성 조성물(A) 성분 g당 10 내지 40 mg의 KOH인 산가를 갖고 자유 카...,Curable compositionCurable compositions which ...,특허
11923059,디스크 브레이크디자인판의 진동을 감소시킬 수 있는 디스크 브레이크를 제공한다. 캘리...,DISC BRAKETo provide a disc brake capable of r...,특허
11900846,양말연질 발포 시트를 이용한 양말에서의 소재의 강도를 약하게 하지 않고 통기성을 개...,SOCKSTo provide socks which uses a sot foamed ...,특허
11652920,합성 섬유용 처리제고연신 배율 고속 제사 조건에서도 조업성 자주(잘) 보풀의 적은 ...,TREATMENT AGENT FOR SYNTHETIC FIBERTo provide ...,특허
11758315,"코발트기 합금 제조물본 발명은, 석출 강화 Ni기 합금재와 동등 이상의 기계적 특성...",COBALT-BASED ALLOY PRODUCTThere is provided a ...,특허
11804822,자산 추적기자산 추적기 디바이스는 자산 추적기 디바이스의 배터리에 전력을 공급하기 ...,ASSET TRACKERAn asset tracker device includes ...,특허
11705525,공간 등 탈취 살균 장치공간 등 내를 효율적으로 탈취하거나 살균하는 공간 등 탈취 ...,APPARATUS FOR DEODORIZING AND STERILIZING INSI...,특허

In [15]:
# 과학/기술/학술자료 일상/대화 뉴스/시사 문화/예술/역사 법률/행정 의학/보건 특허 금융/경제
df[df["domain"] == "금융/경제"].sample(10)

,kor,en,domain
3836256,주요 국제기구들은 중국의 성장세 하락이 내년에도 이어질 것으로 전망하고 있다.,Major international organizations predict that...,금융/경제
3900902,토스와 IMM PE 이외에도 국내 PG 업체와 글로벌 결제 서비스 업체 등이 도전장...,"In addition to Toss and IMM PE, domestic PG co...",금융/경제
3862367,손 회장 측이 법적 소송으로 가더라도 연임이 확정되는 것은 아니라는 지적도 나온다.,Some point out that even if Chairman Sohn goes...,금융/경제
3840685,시장에선 한은의 '10월 금리 인하' 전망이 대세론으로 굳어지는 분위기다.,"In the market, the outlook for the Bank of Kor...",금융/경제
3865618,이베이코리아가 운영하는 G9는 유료멤버십 '스마일클럽' 회원 전용관을 열었다고 14...,"G9, operated by eBay Korea, announced on the 1...",금융/경제
3909274,월별 주행거리는 보험 가입 시 캐롯손해보험이 제공하는 운행 데이터 측정 장치 '캐롯...,"Monthly mileage is measured by installing a ""C...",금융/경제
3869047,"아울러 공정위가 아시아나항공 기내식 공급과 관련, 박 전 회장과 전·현직 경영인을 ...","Moreover, in relation to the supply of Asiana ...",금융/경제
3893196,"장원귀 번개장터 대표는 ""번개장터에 차이를 도입함으로써 수수료 면제 혜택과 결제시간...","Jang Won-gwi, CEO of Bungaejangter, said, ""By ...",금융/경제
3946004,"한화생명보험, 한화손해보험, 교보라이프플래닛, DB손해보험, 메리츠화재 등 국내 대...",Eleven products have been prepared through par...,금융/경제
3859344,일반 사채보다 리스크가 높은 신종자본증권은 금리차가 더 벌어졌다.,"The interest gap of new capital securities, wh...",금융/경제

### 한 분야 안에 문어체, 구어체가 섞인 부분들도 보이고, 다른 분야인데도 비슷한 문장들이 보임 ==> 단순히 문어체, 구어체 2분류로?
- #### == 문어체, 구어체, 혼재 3분류
    - #### 문어체: 과학/기술/학술자료 뉴스/시사 법률/행정 의학/보건 특허 금융/경제
    - #### 구어체: 일상/대화
        - #### 일상/대화에 포함된 "해외고객과의채팅", "해외영업"의 경우 비교적 문체가 딱딱하지만 그래도 일단 구어체
    - #### 혼재: 문화/예술/역사

In [1]:
from datasets import load_dataset, load_from_disk, ClassLabel, DatasetDict, Dataset, concatenate_datasets
import pandas as pd

In [2]:
ds = load_from_disk("/home/paokimsiwoong/workspace/github.com/paokimsiwoong/transformer_experiments/eda/en_ko_12m_p")

In [3]:
# 과학/기술/학술자료 일상/대화 뉴스/시사 문화/예술/역사 법률/행정 의학/보건 특허 금융/경제
def map_domain(d: str) -> str:
    if d == "일상/대화":
        return "구어체"
    if d == "문화/예술/역사":
        return "혼재"
    
    return "문어체"

In [4]:
def map_domain_batch(batch):
    batch["super_domain"] = [map_domain(d) for d in batch["domain"]]
    return batch

In [5]:
ds = ds.map(map_domain_batch, batched=True)

In [6]:
ds

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'domain', 'super_domain'],
        num_rows: 11996357
    })
})

In [6]:
df = ds["train"].to_pandas()
df.head()

,kor,en,domain,super_domain
0,특정 지역에서는 순위 변동이 크게 나타나고 있는 점에 주목해야 한다.,It should be noted that there are significant ...,과학/기술/학술자료,문어체
1,Post-2020 체제에서는 매5년마다 이전 수준보다 개선된 온실가스 감축 목표를 ...,"Under the Post-2020 system, the ratchet mechan...",과학/기술/학술자료,문어체
2,"회귀 모델은 모두 통계적으로 유의하였고, 분산 팽창 계수(VIF)도 모두 2 내외의...",All regression models were statistically signi...,과학/기술/학술자료,문어체
3,OOF에 대한 연구는 그 중요성에도 불구하고 다른 개발 재원에 대한 연구에 비해 매...,"Despite its importance, research on OOF is ins...",과학/기술/학술자료,문어체
4,이에 기대효용 이론에 기초하여 투자자들의 고차 적률 위험에 대한 선호를 반영할 수 ...,This led to the need to develop general perfor...,과학/기술/학술자료,문어체

In [7]:
df["super_domain"].value_counts()

super_domain
문어체    7329837
구어체    3219332
혼재     1447188
Name: count, dtype: int64

In [7]:
ds["train"] = ds["train"].rename_column("super_domain", "style")

In [8]:
ds

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'domain', 'style'],
        num_rows: 11996357
    })
})

In [13]:
df = ds["train"].to_pandas()
df.head()

,kor,en,domain,style
0,특정 지역에서는 순위 변동이 크게 나타나고 있는 점에 주목해야 한다.,It should be noted that there are significant ...,과학/기술/학술자료,문어체
1,Post-2020 체제에서는 매5년마다 이전 수준보다 개선된 온실가스 감축 목표를 ...,"Under the Post-2020 system, the ratchet mechan...",과학/기술/학술자료,문어체
2,"회귀 모델은 모두 통계적으로 유의하였고, 분산 팽창 계수(VIF)도 모두 2 내외의...",All regression models were statistically signi...,과학/기술/학술자료,문어체
3,OOF에 대한 연구는 그 중요성에도 불구하고 다른 개발 재원에 대한 연구에 비해 매...,"Despite its importance, research on OOF is ins...",과학/기술/학술자료,문어체
4,이에 기대효용 이론에 기초하여 투자자들의 고차 적률 위험에 대한 선호를 반영할 수 ...,This led to the need to develop general perfor...,과학/기술/학술자료,문어체

In [14]:
df["style"].value_counts()

style
문어체    7329837
구어체    3219332
혼재     1447188
Name: count, dtype: int64

In [15]:
df["domain"].value_counts()

domain
과학/기술/학술자료    3822044
일상/대화         3219332
뉴스/시사         1520939
문화/예술/역사      1447188
법률/행정          726818
의학/보건          720037
특허             359999
금융/경제          180000
Name: count, dtype: int64

In [9]:
# 과학/기술/학술자료 일상/대화 뉴스/시사 문화/예술/역사 법률/행정 의학/보건 특허 금융/경제
def map_domain(d: str) -> int:
    if d == "과학/기술/학술자료":
        return 0
    if d == "일상/대화":
        return 1
    if d == "뉴스/시사":
        return 2
    if d == "문화/예술/역사":
        return 3
    if d == "법률/행정":
        return 4
    if d == "의학/보건":
        return 5
    if d == "특허":
        return 6
    if d == "금융/경제":
        return 7
    
    return 8

In [10]:
def map_domain_batch(batch):
    batch["cat"] = [map_domain(d) for d in batch["domain"]]
    return batch

In [11]:
ds = ds.map(map_domain_batch, batched=True)

Map:   0%|          | 0/11996357 [00:00<?, ? examples/s]

In [12]:
ds

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'domain', 'style', 'cat'],
        num_rows: 11996357
    })
})

In [13]:
ds.save_to_disk("en_ko_12m_pp")

Saving the dataset (0/10 shards):   0%|          | 0/11996357 [00:00<?, ? examples/s]

In [14]:
df = ds["train"].to_pandas()
df.head()

,kor,en,domain,style,cat
0,특정 지역에서는 순위 변동이 크게 나타나고 있는 점에 주목해야 한다.,It should be noted that there are significant ...,과학/기술/학술자료,문어체,0
1,Post-2020 체제에서는 매5년마다 이전 수준보다 개선된 온실가스 감축 목표를 ...,"Under the Post-2020 system, the ratchet mechan...",과학/기술/학술자료,문어체,0
2,"회귀 모델은 모두 통계적으로 유의하였고, 분산 팽창 계수(VIF)도 모두 2 내외의...",All regression models were statistically signi...,과학/기술/학술자료,문어체,0
3,OOF에 대한 연구는 그 중요성에도 불구하고 다른 개발 재원에 대한 연구에 비해 매...,"Despite its importance, research on OOF is ins...",과학/기술/학술자료,문어체,0
4,이에 기대효용 이론에 기초하여 투자자들의 고차 적률 위험에 대한 선호를 반영할 수 ...,This led to the need to develop general perfor...,과학/기술/학술자료,문어체,0

In [15]:
df["cat"].value_counts()

cat
0    3822044
1    3219332
2    1520939
3    1447188
4     726818
5     720037
6     359999
7     180000
Name: count, dtype: int64

In [16]:
df["domain"].value_counts()

domain
과학/기술/학술자료    3822044
일상/대화         3219332
뉴스/시사         1520939
문화/예술/역사      1447188
법률/행정          726818
의학/보건          720037
특허             359999
금융/경제          180000
Name: count, dtype: int64

In [17]:
df["style"].value_counts()

style
문어체    7329837
구어체    3219332
혼재     1447188
Name: count, dtype: int64

### 중복 제거 (한국어, 영어 문장 쌍이 같은 경우, 한국어 문장 같고 영어 번역 결과가 다른 경우(학습에 혼란) 제거)

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import numpy as np
import pandas as pd

from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

from transformers import AutoTokenizer

from datasets import load_dataset, load_from_disk, ClassLabel, DatasetDict, Dataset, concatenate_datasets

import multiprocessing

from functools import partial

from tqdm import tqdm
from collections import Counter

In [2]:
data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/transformer_experiments/eda/en_ko_12m_pp"

In [3]:
ds = load_from_disk(data_path)

In [4]:
dataset = ds['train']

In [5]:
df = dataset.to_pandas()

In [12]:
dup_check = df.duplicated(subset="kor")

In [13]:
dup_check.value_counts()

False    10726732
True      1269625
Name: count, dtype: int64

In [16]:
dup_check_en = df.duplicated(subset="en")

In [17]:
dup_check_en.value_counts()

False    10808345
True      1188012
Name: count, dtype: int64

In [18]:
dup_check_kor_en = df.duplicated(subset=["kor","en"])

In [19]:
dup_check_kor_en.value_counts()

False    10970107
True      1026250
Name: count, dtype: int64

In [14]:
dup_check_all = df.duplicated()

In [15]:
dup_check_all.value_counts()

False    11194068
True       802289
Name: count, dtype: int64

In [6]:
df_c = df.drop_duplicates(subset=["kor", "en"])

In [7]:
c_dup_check = df_c.duplicated(subset="kor")
c_dup_check.value_counts()

False    10726732
True       243375
Name: count, dtype: int64

In [23]:
c_dup_check_koren = df_c.duplicated(subset=["kor", "en"])
c_dup_check_koren.value_counts()

False    10970107
Name: count, dtype: int64

In [8]:
df_clean = df_c.drop_duplicates(subset="kor")

In [9]:
clean_dup_check = df_clean.duplicated(subset="kor")
clean_dup_check.value_counts()

False    10726732
Name: count, dtype: int64

In [26]:
clean_dup_check_en = df_clean.duplicated(subset="en")
clean_dup_check_en.value_counts()

False    10583646
True       143086
Name: count, dtype: int64

In [10]:
df_clean.to_csv("data_clean.csv", index=False)

In [11]:
df_clean_en = df_c.drop_duplicates(subset="en")

In [12]:
clean_dup_check_en = df_clean_en.duplicated(subset="en")
clean_dup_check_en.value_counts()

False    10808345
Name: count, dtype: int64

In [30]:
clean_dup_check = df_clean_en.duplicated(subset="kor")
clean_dup_check.value_counts()

False    10585376
True       222969
Name: count, dtype: int64

In [13]:
df_clean_en.to_csv("data_clean_en.csv", index=False)

In [32]:
# ds_clean = DatasetDict(
#     {
#         "train": Dataset.from_pandas(df_clean.reset_index(drop=True))
#     }
# )

:

### class label 추가

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import numpy as np
import pandas as pd

from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

from transformers import AutoTokenizer

from datasets import load_dataset, load_from_disk, ClassLabel, DatasetDict, Dataset, concatenate_datasets

import multiprocessing

from functools import partial

from tqdm import tqdm
from collections import Counter

In [2]:
ds = load_dataset("csv", data_files="data_clean.csv",)

In [3]:
ds

DatasetDict({
    train: Dataset({
        features: ['kor', 'en', 'domain', 'style', 'cat'],
        num_rows: 10726732
    })
})

In [4]:
dataset = ds["train"]

In [5]:
unique_classes = dataset.unique('style')  
# 문어체    7329837
# 구어체    3219332
# 혼재     1447188

print(f"==>> unique_classes: {unique_classes}")

==>> unique_classes: ['문어체', '혼재', '구어체']

In [6]:
print(f"==>> type(unique_classes): {type(unique_classes)}")

==>> type(unique_classes): <class 'list'>

In [7]:

class_label = ClassLabel(names=['문어체', '구어체', '혼재'])
print(f"==>> class_label: {class_label}")

==>> class_label: ClassLabel(names=['문어체', '구어체', '혼재'])

In [8]:
# def cast_style(example):
#     example["style_class"] = class_label.str2int(example["style"])
#     return example

# dataset = dataset.map(cast_style)

def cast_style(example):
    example["style_class"] = [class_label.str2int(s) for s in example["style"]]
    return example

dataset = dataset.map(cast_style, batched=True)

In [9]:
dataset[:5]

{'kor': ['특정 지역에서는 순위 변동이 크게 나타나고 있는 점에 주목해야 한다.',
  'Post-2020 체제에서는 매5년마다 이전 수준보다 개선된 온실가스 감축 목표를 유엔에 제출해야 하는 래칫 메커니즘이 적용되므로, 국내 최대 온실가스 배출 원인 발전 부문의 감축 부담도 크게 증가할 전망이다.',
  '회귀 모델은 모두 통계적으로 유의하였고, 분산 팽창 계수(VIF)도 모두 2 내외의 양호한 값을 보여 다중 공선성의 문제도 크지 않음을 확인하였다.',
  'OOF에 대한 연구는 그 중요성에도 불구하고 다른 개발 재원에 대한 연구에 비해 매우 부족한 실정이며, 다음의 측면에서 한계를 보이고 있다.',
  '이에 기대효용 이론에 기초하여 투자자들의 고차 적률 위험에 대한 선호를 반영할 수 있는 일반적 성과 지표를 개발할 필요성이 대두되었다.'],
 'en': ['It should be noted that there are significant ranking fluctuations in certain regions.',
  "Under the Post-2020 system, the ratchet mechanism, which requires the U.N. to submit improved greenhouse gas reduction targets every five years, is expected to significantly increase the burden on the nation's largest greenhouse gas emission-causing power generation.",
  'All regression models were statistically significant, and the variance inflation coefficient (VIF) all showed good values around 2, confirming that the problem of multicollinearity was not significant.',
  'Despite its importance, research on OOF is insufficient compared to research on other development resources, and it has limitations in the following aspects.',
  "This led to the need to develop general performance indicators that could reflect investors' preferences for higher-order adequacy risks based on the theory of expected utility."],
 'domain': ['과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료'],
 'style': ['문어체', '문어체', '문어체', '문어체', '문어체'],
 'cat': [0, 0, 0, 0, 0],
 'style_class': [0, 0, 0, 0, 0]}

In [10]:
ds["train"] = dataset

In [11]:
unique_classes = dataset.unique('style_class')
print(f"==>> unique_classes: {unique_classes}")

==>> unique_classes: [0, 2, 1]

In [12]:
class_label = ClassLabel(names=[0, 1, 2])

In [13]:
ds["train"] = ds["train"].cast_column('style_class', class_label)

Casting the dataset:   0%|          | 0/10726732 [00:00<?, ? examples/s]

In [14]:
ds["train"][:5]

{'kor': ['특정 지역에서는 순위 변동이 크게 나타나고 있는 점에 주목해야 한다.',
  'Post-2020 체제에서는 매5년마다 이전 수준보다 개선된 온실가스 감축 목표를 유엔에 제출해야 하는 래칫 메커니즘이 적용되므로, 국내 최대 온실가스 배출 원인 발전 부문의 감축 부담도 크게 증가할 전망이다.',
  '회귀 모델은 모두 통계적으로 유의하였고, 분산 팽창 계수(VIF)도 모두 2 내외의 양호한 값을 보여 다중 공선성의 문제도 크지 않음을 확인하였다.',
  'OOF에 대한 연구는 그 중요성에도 불구하고 다른 개발 재원에 대한 연구에 비해 매우 부족한 실정이며, 다음의 측면에서 한계를 보이고 있다.',
  '이에 기대효용 이론에 기초하여 투자자들의 고차 적률 위험에 대한 선호를 반영할 수 있는 일반적 성과 지표를 개발할 필요성이 대두되었다.'],
 'en': ['It should be noted that there are significant ranking fluctuations in certain regions.',
  "Under the Post-2020 system, the ratchet mechanism, which requires the U.N. to submit improved greenhouse gas reduction targets every five years, is expected to significantly increase the burden on the nation's largest greenhouse gas emission-causing power generation.",
  'All regression models were statistically significant, and the variance inflation coefficient (VIF) all showed good values around 2, confirming that the problem of multicollinearity was not significant.',
  'Despite its importance, research on OOF is insufficient compared to research on other development resources, and it has limitations in the following aspects.',
  "This led to the need to develop general performance indicators that could reflect investors' preferences for higher-order adequacy risks based on the theory of expected utility."],
 'domain': ['과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료',
  '과학/기술/학술자료'],
 'style': ['문어체', '문어체', '문어체', '문어체', '문어체'],
 'cat': [0, 0, 0, 0, 0],
 'style_class': [0, 0, 0, 0, 0]}

In [15]:
df = ds["train"].to_pandas()

In [16]:
df["style_class"].value_counts()

style_class
0    6541468
1    2923158
2    1262106
Name: count, dtype: int64

In [17]:
ds.save_to_disk("en_ko_12m_ppp")

Saving the dataset (0/9 shards):   0%|          | 0/10726732 [00:00<?, ? examples/s]

## 새 데이터셋에 토크나이저 unk 토큰 개수 확인

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import numpy as np
import pandas as pd

from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

from transformers import AutoTokenizer

from datasets import load_dataset, load_from_disk, ClassLabel, DatasetDict, Dataset, concatenate_datasets

import multiprocessing

from functools import partial

from tqdm import tqdm
from collections import Counter

In [2]:
data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/transformer_experiments/eda/en_ko_12m_ppp"
max_token_length = 512
batch_size_train = 64
num_workers = 4
batch_size_val = 64
batch_size_test = 64
val_num_workers = 4
start_idx = 64100
end_idx = 1
padding_idx = 0
unk_idx = 2
seed = 42

In [3]:
class Loaders():
    def __init__(
            self,
            data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/data.csv",
            max_token_length = 512,
            batch_size_train = 8,
            num_workers = 4,
            batch_size_val = 4,
            batch_size_test = 4,
            val_num_workers = 4,
            start_idx = 64100, 
            end_idx = 1, 
            padding_idx = 0, 
            unk_idx = 2,
            seed = 42,
    ):
        self.start_idx = start_idx
        self.end_idx = end_idx
        self.padding_idx = padding_idx
        self.unk_idx = unk_idx

        # 1) 데이터셋 로드
        dataset = load_from_disk(data_path)['train']

        # 4) stratify_by_column으로 분할
        # train_validtest = dataset.train_test_split(test_size=0.2, seed=seed, stratify_by_column='cat')
        # valid_test = train_validtest['test'].train_test_split(test_size=0.1, seed=seed, stratify_by_column='cat')
        train_validtest = dataset.train_test_split(test_size=0.2, seed=seed, stratify_by_column='style_class')
        valid_test = train_validtest['test'].train_test_split(test_size=0.1, seed=seed, stratify_by_column='style_class')

        dataset_dict = DatasetDict({
            'train': train_validtest['train'],
            'validation': valid_test['train'],
            'test': valid_test['test']
        })

        # print(dataset_dict)

        NUM_CPU = multiprocessing.cpu_count()
        # print(f"==>> NUM_CPU: {NUM_CPU}")

        # self.tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-ko-en")
        # @@@ 점포, 만료 등의 단어가 <unk>인 문제 발견 => 다른 토크나이저 사용?
        self.tokenizer = AutoTokenizer.from_pretrained("KETI-AIR/ke-t5-base")

        special_tokens_dict = {'bos_token': '<s>'}
        self.tokenizer.add_special_tokens(special_tokens_dict)

        print(self.tokenizer.all_special_ids)
        print(self.tokenizer.all_special_tokens)

        print(f"==>> self.tokenizer.model_max_length: {self.tokenizer.model_max_length}")

        print(f"==>> len(self.tokenizer): {len(self.tokenizer)}")

        self.max_token_length = min(max_token_length, self.tokenizer.model_max_length)

        # partial을 이용해 tokenizer, max_token_length 인자 고정
        cetf = partial(convert_examples_to_features, tokenizer=self.tokenizer, max_token_length=self.max_token_length)
        # @@@ convert_examples_to_features함수에서 examples가 첫번쨰 인자가 아니면 
        # @@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서 
        # @@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러 발생

        self.datasets = dataset_dict.map(
                                cetf,
                                # lambda examples: convert_examples_to_features(examples, tokenizer=self.tokenizer, max_token_length=self.max_token_length),
                                batched=True,
                                # 원 데이터 'en', 'kor', 'cat' 등의 칼럼을 지우려면
                                # remove_columns 인자 사용
                                # remove_columns=dataset_dict["train"].column_names,
                                num_proc=NUM_CPU)

        print(f"==>> self.datasets: {self.datasets}")

        self.train_set = self.datasets['train']
        self.val_set = self.datasets['validation']
        self.test_set = self.datasets['test']

        c_fn = partial(collate_fn, start_idx=self.start_idx, end_idx=self.end_idx, padding_idx=self.padding_idx, unk_idx=self.unk_idx)

        self.loader_train = DataLoader(self.train_set, batch_size=batch_size_train, collate_fn=c_fn, shuffle=True, num_workers=num_workers, pin_memory=True)
        # 학습시에만 shuffle=True
        self.loader_val = DataLoader(self.val_set, batch_size=batch_size_val, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)
        self.loader_test = DataLoader(self.test_set, batch_size=batch_size_test, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)

# def convert_examples_to_features(tokenizer, max_token_length, examples):
# @@@@@@@@@ examples가 첫번쨰 인자가 아니면 
# @@@@@@@@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서
# @@@@@@@@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러가 발생한다
def convert_examples_to_features(examples, tokenizer, max_token_length):
    # try:
    model_inputs = tokenizer(examples['kor'],
                            text_target=examples['en'],
                            max_length=max_token_length, truncation=True)
    # 여기서 첫번째 인자와 두번째 인자의 순서를 바꾸면 한영 번역 대신 영한 번역용으로 인풋과 타겟이 토큰화된다
    return model_inputs
    # except Exception as e:
    #     # print(f"==>> error examples: {examples}")
    #     raise e


def collate_fn(batch, start_idx, end_idx, padding_idx, unk_idx):
    print('Original:\n', batch)
    # print("".center(50, "-"))
    # batch는 [{'kor':..., 'en':..., 'cat':숫자, 'input_ids':[...], 'attention_mask':[1, ...], 'labels': [...]}, ...] 형태
    
    # keys = batch[0].keys()
    keys = ['kor', 'en', 'domain', 'cat', 'style', 'style_class', 'input_ids', 'attention_mask', 'labels']
    # print(f"==>> keys: {keys}")
    # print("".center(50, "-"))
    
    # new_batch = {k:[] for k in keys}
    # new_batch['decoder_inputs'] = []
    
    # for b in batch:
    #     for k,v in b.items():
    #         if k == 'input_ids' or k == 'attention_mask':
    #             new_batch[k].append(torch.LongTensor(v))
    #         elif k == 'labels':
    #             new_batch[k].append(torch.LongTensor(v))
    #             new_batch['decoder_inputs'].append(torch.LongTensor([65001] + v[:-1]))
    #         else:
    #             new_batch[k].append(v)

    # key값별로 value 다 모으기
    new_batch = {k:[b[k] for b in batch] for k in keys}

    # list들 LongTensor로 변환
    new_batch['decoder_inputs'] = [torch.LongTensor([start_idx] + label[:-1]) for label in new_batch['labels']]
    # print(f"==>> new_batch['decoder_inputs']: {new_batch['decoder_inputs']}")
    new_batch['input_ids'] = [torch.LongTensor(inp) for inp in new_batch['input_ids']]
    new_batch['labels'] = [torch.LongTensor(label) for label in new_batch['labels']]
    new_batch['attention_mask'] = [torch.LongTensor(mask) for mask in new_batch['attention_mask']]

    new_batch['ntokens'] = sum([l.numel() for l in new_batch['labels']])

    # decoder input의 attention mask 생성
    new_batch['decoder_mask'] = [torch.ones_like(d_inp, dtype=torch.long) for d_inp in new_batch['decoder_inputs']]


    # 각 input과 target 텐서를 패딩
    padded_inputs = pad_sequence(new_batch['input_ids'], batch_first=True, padding_value=padding_idx)
    new_batch['input_ids'] = padded_inputs
    padded_decoder_inputs = pad_sequence(new_batch['decoder_inputs'], batch_first=True, padding_value=padding_idx)
    new_batch['decoder_inputs'] = padded_decoder_inputs
    padded_targets = pad_sequence(new_batch['labels'], batch_first=True, padding_value=padding_idx)
    new_batch['labels'] = padded_targets

    # attention 마스크는 패딩(padding_idx) 대신 False(0)을 입력
    padded_masks = pad_sequence(new_batch['attention_mask'], batch_first=True, padding_value=0)
    new_batch['attention_mask'] = padded_masks

    padded_d_masks = pad_sequence(new_batch['decoder_mask'], batch_first=True, padding_value=0)
    new_batch['decoder_mask'] = padded_d_masks
    
    return new_batch

In [ ]:
loaders = Loaders(
    data_path=data_path,
    max_token_length=max_token_length,
    batch_size_train=batch_size_train,
    num_workers=num_workers,
    batch_size_val=batch_size_val,
    batch_size_test=batch_size_test,
    val_num_workers=val_num_workers,
    start_idx=start_idx,
    end_idx=end_idx,
    padding_idx=padding_idx,
    unk_idx=unk_idx,
    seed=seed,
)

In [ ]:
print(f"==>> unk_idx: {unk_idx}")

input_total = Counter([])
target_total = Counter([])
# total

num_batches_train = len(loaders.loader_train)

for step, batch in tqdm(
    enumerate(loaders.loader_train),
    total=num_batches_train,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total += input_count
    target_total += target_count

    # if step == 10:
    #     break

print(f"==>> input_total: {input_total}")
print(f"==>> target_total: {target_total}")

print(f"==>> input_total[unk_idx]: {input_total[unk_idx]}")
print(f"==>> target_total[unk_idx]: {target_total[unk_idx]}")

input_total_val = Counter([])
target_total_val = Counter([])
# total

num_batches_val = len(loaders.loader_val)

for step, batch in tqdm(
    enumerate(loaders.loader_val),
    total=num_batches_val,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_val += input_count
    target_total_val += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_val: {input_total_val}")
print(f"==>> target_total_val: {target_total_val}")
print(f"==>> input_total_val[unk_idx]: {input_total_val[unk_idx]}")
print(f"==>> target_total_val[unk_idx]: {target_total_val[unk_idx]}")

input_total_test = Counter([])
target_total_test = Counter([])
# total

num_batches_test = len(loaders.loader_test)

for step, batch in tqdm(
    enumerate(loaders.loader_test),
    total=num_batches_test,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_test += input_count
    target_total_test += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_test: {input_total_test}")
print(f"==>> target_total_test: {target_total_test}")
print(f"==>> input_total_test[unk_idx]: {input_total_test[unk_idx]}")
print(f"==>> target_total_test[unk_idx]: {target_total_test[unk_idx]}")

In [ ]:
# tokenizer_name = "LGAI-EXAONE/K-EXAONE-236B-A23B"

data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/transformer_experiments/eda/en_ko_12m_ppp"
max_token_length = 512
batch_size_train = 64
num_workers = 4
batch_size_val = 64
batch_size_test = 64
val_num_workers = 4
start_idx = 1
end_idx = 53
padding_idx = 0
unk_idx = 3
seed = 42

In [ ]:
class LoadersLGEXA236():
    def __init__(
            self,
            data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/data.csv",
            max_token_length = 512,
            batch_size_train = 8,
            num_workers = 4,
            batch_size_val = 4,
            batch_size_test = 4,
            val_num_workers = 4,
            start_idx = 64100, 
            end_idx = 1, 
            padding_idx = 0, 
            unk_idx = 2,
            seed = 42,
    ):
        self.start_idx = start_idx
        self.end_idx = end_idx
        self.padding_idx = padding_idx
        self.unk_idx = unk_idx

        # 1) 데이터셋 로드
        dataset = load_from_disk(data_path)['train']
        
        # 4) stratify_by_column으로 분할
        # train_validtest = dataset.train_test_split(test_size=0.2, seed=seed, stratify_by_column='cat')
        # valid_test = train_validtest['test'].train_test_split(test_size=0.1, seed=seed, stratify_by_column='cat')
        train_validtest = dataset.train_test_split(test_size=0.2, seed=seed, stratify_by_column='style_class')
        valid_test = train_validtest['test'].train_test_split(test_size=0.1, seed=seed, stratify_by_column='style_class')

        dataset_dict = DatasetDict({
            'train': train_validtest['train'],
            'validation': valid_test['train'],
            'test': valid_test['test']
        })

        # print(dataset_dict)

        NUM_CPU = multiprocessing.cpu_count()
        # print(f"==>> NUM_CPU: {NUM_CPU}")

        # self.tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-ko-en")
        # @@@ 점포, 만료 등의 단어가 <unk>인 문제 발견 => 다른 토크나이저 사용?
        self.tokenizer = AutoTokenizer.from_pretrained("LGAI-EXAONE/K-EXAONE-236B-A23B")

        print(self.tokenizer.all_special_ids)
        print(self.tokenizer.all_special_tokens)

        print(f"==>> self.tokenizer.model_max_length: {self.tokenizer.model_max_length}")

        print(f"==>> len(self.tokenizer): {len(self.tokenizer)}")

        self.max_token_length = min(max_token_length, self.tokenizer.model_max_length)
        print(f"==>> self.max_token_length: {self.max_token_length}")

        # partial을 이용해 tokenizer, max_token_length 인자 고정
        cetf = partial(convert_examples_to_features, tokenizer=self.tokenizer, max_token_length=self.max_token_length)
        # @@@ convert_examples_to_features함수에서 examples가 첫번쨰 인자가 아니면 
        # @@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서 
        # @@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러 발생

        self.datasets = dataset_dict.map(
                                cetf,
                                # lambda examples: convert_examples_to_features(examples, tokenizer=self.tokenizer, max_token_length=self.max_token_length),
                                batched=True,
                                # 원 데이터 'en', 'kor', 'cat' 등의 칼럼을 지우려면
                                # remove_columns 인자 사용
                                # remove_columns=dataset_dict["train"].column_names,
                                num_proc=NUM_CPU)

        print(f"==>> self.datasets: {self.datasets}")

        self.train_set = self.datasets['train']
        self.val_set = self.datasets['validation']
        self.test_set = self.datasets['test']

        c_fn = partial(collate_fn, start_idx=self.start_idx, end_idx=self.end_idx, padding_idx=self.padding_idx, unk_idx=self.unk_idx)

        self.loader_train = DataLoader(self.train_set, batch_size=batch_size_train, collate_fn=c_fn, shuffle=True, num_workers=num_workers, pin_memory=True)
        # 학습시에만 shuffle=True
        self.loader_val = DataLoader(self.val_set, batch_size=batch_size_val, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)
        self.loader_test = DataLoader(self.test_set, batch_size=batch_size_test, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)

# def convert_examples_to_features(tokenizer, max_token_length, examples):
# @@@@@@@@@ examples가 첫번쨰 인자가 아니면 
# @@@@@@@@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서
# @@@@@@@@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러가 발생한다
def convert_examples_to_features(examples, tokenizer, max_token_length):
    model_inputs = tokenizer(examples['kor'],
                             text_target=examples['en'],
                             max_length=max_token_length, truncation=True)
    # 여기서 첫번째 인자와 두번째 인자의 순서를 바꾸면 한영 번역 대신 영한 번역용으로 인풋과 타겟이 토큰화된다
    return model_inputs


def collate_fn(batch, start_idx, end_idx, padding_idx, unk_idx):
    # print('Original:\n', batch)
    # print("".center(50, "-"))
    # batch는 [{'kor':..., 'en':..., 'cat':숫자, 'input_ids':[...], 'attention_mask':[1, ...], 'labels': [...]}, ...] 형태
    
    # keys = batch[0].keys()
    keys = ['kor', 'en', 'domain', 'cat', 'style', 'style_class', 'input_ids', 'attention_mask', 'labels']
    # print(f"==>> keys: {keys}")
    # print("".center(50, "-"))
    
    # new_batch = {k:[] for k in keys}
    # new_batch['decoder_inputs'] = []
    
    # for b in batch:
    #     for k,v in b.items():
    #         if k == 'input_ids' or k == 'attention_mask':
    #             new_batch[k].append(torch.LongTensor(v))
    #         elif k == 'labels':
    #             new_batch[k].append(torch.LongTensor(v))
    #             new_batch['decoder_inputs'].append(torch.LongTensor([65001] + v[:-1]))
    #         else:
    #             new_batch[k].append(v)

    # key값별로 value 다 모으기
    new_batch = {k:[b[k] for b in batch] for k in keys}

    # list들 LongTensor로 변환
    new_batch['decoder_inputs'] = [torch.LongTensor([start_idx] + label[:-1]) for label in new_batch['labels']]
    # print(f"==>> new_batch['decoder_inputs']: {new_batch['decoder_inputs']}")
    new_batch['input_ids'] = [torch.LongTensor(inp) for inp in new_batch['input_ids']]
    new_batch['labels'] = [torch.LongTensor(label) for label in new_batch['labels']]
    new_batch['attention_mask'] = [torch.LongTensor(mask) for mask in new_batch['attention_mask']]

    new_batch['ntokens'] = sum([l.numel() for l in new_batch['labels']])

    # decoder input의 attention mask 생성
    new_batch['decoder_mask'] = [torch.ones_like(d_inp, dtype=torch.long) for d_inp in new_batch['decoder_inputs']]


    # 각 input과 target 텐서를 패딩
    padded_inputs = pad_sequence(new_batch['input_ids'], batch_first=True, padding_value=padding_idx)
    new_batch['input_ids'] = padded_inputs
    padded_decoder_inputs = pad_sequence(new_batch['decoder_inputs'], batch_first=True, padding_value=padding_idx)
    new_batch['decoder_inputs'] = padded_decoder_inputs
    padded_targets = pad_sequence(new_batch['labels'], batch_first=True, padding_value=padding_idx)
    new_batch['labels'] = padded_targets

    # attention 마스크는 패딩(padding_idx) 대신 False(0)을 입력
    padded_masks = pad_sequence(new_batch['attention_mask'], batch_first=True, padding_value=0)
    new_batch['attention_mask'] = padded_masks

    padded_d_masks = pad_sequence(new_batch['decoder_mask'], batch_first=True, padding_value=0)
    new_batch['decoder_mask'] = padded_d_masks
    
    return new_batch

In [ ]:
loaders = LoadersLGEXA236(
    data_path=data_path,
    max_token_length=max_token_length,
    batch_size_train=batch_size_train,
    num_workers=num_workers,
    batch_size_val=batch_size_val,
    batch_size_test=batch_size_test,
    val_num_workers=val_num_workers,
    start_idx=start_idx,
    end_idx=end_idx,
    padding_idx=padding_idx,
    unk_idx=unk_idx,
    seed=seed,
)

In [ ]:
print(f"==>> unk_idx: {unk_idx}")

input_total = Counter([])
target_total = Counter([])
# total

num_batches_train = len(loaders.loader_train)

for step, batch in tqdm(
    enumerate(loaders.loader_train),
    total=num_batches_train,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total += input_count
    target_total += target_count

    # if step == 10:
    #     break

print(f"==>> input_total: {input_total}")
print(f"==>> target_total: {target_total}")
print(f"==>> input_total[unk_idx]: {input_total[unk_idx]}")
print(f"==>> target_total[unk_idx]: {target_total[unk_idx]}")


input_total_val = Counter([])
target_total_val = Counter([])
# total

num_batches_val = len(loaders.loader_val)

for step, batch in tqdm(
    enumerate(loaders.loader_val),
    total=num_batches_val,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_val += input_count
    target_total_val += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_val: {input_total_val}")
print(f"==>> target_total_val: {target_total_val}")
print(f"==>> input_total_val[unk_idx]: {input_total_val[unk_idx]}")
print(f"==>> target_total_val[unk_idx]: {target_total_val[unk_idx]}")


input_total_test = Counter([])
target_total_test = Counter([])
# total

num_batches_test = len(loaders.loader_test)

for step, batch in tqdm(
    enumerate(loaders.loader_test),
    total=num_batches_test,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_test += input_count
    target_total_test += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_test: {input_total_test}")
print(f"==>> target_total_test: {target_total_test}")
print(f"==>> input_total_test[unk_idx]: {input_total_test[unk_idx]}")
print(f"==>> target_total_test[unk_idx]: {target_total_test[unk_idx]}")

In [ ]:
# tokenizer_name = "Translation-EnKo/exaone3-instrucTrans-v2-enko-7.8b"

data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/transformer_experiments/eda/en_ko_12m_ppp"
max_token_length = 512
batch_size_train = 64
num_workers = 4
batch_size_val = 64
batch_size_test = 64
val_num_workers = 4
start_idx = 1
end_idx = 361
padding_idx = 0
unk_idx = 3
seed = 42

In [ ]:
class LoadersLGEXAENKO():
    def __init__(
            self,
            data_path="/home/paokimsiwoong/workspace/github.com/paokimsiwoong/ml_practice/transformer/data.csv",
            max_token_length = 512,
            batch_size_train = 8,
            num_workers = 4,
            batch_size_val = 4,
            batch_size_test = 4,
            val_num_workers = 4,
            start_idx = 64100, 
            end_idx = 1, 
            padding_idx = 0, 
            unk_idx = 2,
            seed = 42,
    ):
        self.start_idx = start_idx
        self.end_idx = end_idx
        self.padding_idx = padding_idx
        self.unk_idx = unk_idx

        # 1) 데이터셋 로드
        dataset = load_from_disk(data_path)['train']
        

        # 4) stratify_by_column으로 분할
        # train_validtest = dataset.train_test_split(test_size=0.2, seed=seed, stratify_by_column='cat')
        # valid_test = train_validtest['test'].train_test_split(test_size=0.1, seed=seed, stratify_by_column='cat')
        train_validtest = dataset.train_test_split(test_size=0.2, seed=seed, stratify_by_column='style_class')
        valid_test = train_validtest['test'].train_test_split(test_size=0.1, seed=seed, stratify_by_column='style_class')

        dataset_dict = DatasetDict({
            'train': train_validtest['train'],
            'validation': valid_test['train'],
            'test': valid_test['test']
        })

        # print(dataset_dict)

        NUM_CPU = multiprocessing.cpu_count()
        # print(f"==>> NUM_CPU: {NUM_CPU}")

        # self.tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-ko-en")
        # @@@ 점포, 만료 등의 단어가 <unk>인 문제 발견 => 다른 토크나이저 사용?
        self.tokenizer = AutoTokenizer.from_pretrained("Translation-EnKo/exaone3-instrucTrans-v2-enko-7.8b")

        special_tokens_dict = {'pad_token': '[PAD]'}
        self.tokenizer.add_special_tokens(special_tokens_dict)
        
        print(self.tokenizer.all_special_ids)
        print(self.tokenizer.all_special_tokens)

        print(f"==>> self.tokenizer.model_max_length: {self.tokenizer.model_max_length}")

        print(f"==>> len(self.tokenizer): {len(self.tokenizer)}")

        self.max_token_length = min(max_token_length, self.tokenizer.model_max_length)

        # partial을 이용해 tokenizer, max_token_length 인자 고정
        cetf = partial(convert_examples_to_features, tokenizer=self.tokenizer, max_token_length=self.max_token_length)
        # @@@ convert_examples_to_features함수에서 examples가 첫번쨰 인자가 아니면 
        # @@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서 
        # @@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러 발생

        self.datasets = dataset_dict.map(
                                cetf,
                                # lambda examples: convert_examples_to_features(examples, tokenizer=self.tokenizer, max_token_length=self.max_token_length),
                                batched=True,
                                # 원 데이터 'en', 'kor', 'cat' 등의 칼럼을 지우려면
                                # remove_columns 인자 사용
                                # remove_columns=dataset_dict["train"].column_names,
                                num_proc=NUM_CPU)

        print(f"==>> self.datasets: {self.datasets}")

        self.train_set = self.datasets['train']
        self.val_set = self.datasets['validation']
        self.test_set = self.datasets['test']

        c_fn = partial(collate_fn, start_idx=self.start_idx, end_idx=self.end_idx, padding_idx=self.padding_idx, unk_idx=self.unk_idx)

        self.loader_train = DataLoader(self.train_set, batch_size=batch_size_train, collate_fn=c_fn, shuffle=True, num_workers=num_workers, pin_memory=True)
        # 학습시에만 shuffle=True
        self.loader_val = DataLoader(self.val_set, batch_size=batch_size_val, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)
        self.loader_test = DataLoader(self.test_set, batch_size=batch_size_test, collate_fn=c_fn, shuffle=False, num_workers=val_num_workers, pin_memory=True)

# def convert_examples_to_features(tokenizer, max_token_length, examples):
# @@@@@@@@@ examples가 첫번쨰 인자가 아니면 
# @@@@@@@@@ partial과 dataset_dict.map의 인자 전달 방식이 충돌해서
# @@@@@@@@@ TypeError: convert_examples_to_features() got multiple values for argument 'tokenizer' 에러가 발생한다
def convert_examples_to_features(examples, tokenizer, max_token_length):
    model_inputs = tokenizer(examples['kor'],
                             text_target=examples['en'],
                             max_length=max_token_length, truncation=True)
    # 여기서 첫번째 인자와 두번째 인자의 순서를 바꾸면 한영 번역 대신 영한 번역용으로 인풋과 타겟이 토큰화된다
    return model_inputs


def collate_fn(batch, start_idx, end_idx, padding_idx, unk_idx):
    # print('Original:\n', batch)
    # print("".center(50, "-"))
    # batch는 [{'kor':..., 'en':..., 'cat':숫자, 'input_ids':[...], 'attention_mask':[1, ...], 'labels': [...]}, ...] 형태
    
    # keys = batch[0].keys()
    keys = ['kor', 'en', 'domain', 'cat', 'style', "style_class", 'input_ids', 'attention_mask', 'labels']
    # print(f"==>> keys: {keys}")
    # print("".center(50, "-"))
    
    # new_batch = {k:[] for k in keys}
    # new_batch['decoder_inputs'] = []
    
    # for b in batch:
    #     for k,v in b.items():
    #         if k == 'input_ids' or k == 'attention_mask':
    #             new_batch[k].append(torch.LongTensor(v))
    #         elif k == 'labels':
    #             new_batch[k].append(torch.LongTensor(v))
    #             new_batch['decoder_inputs'].append(torch.LongTensor([65001] + v[:-1]))
    #         else:
    #             new_batch[k].append(v)

    # key값별로 value 다 모으기
    new_batch = {k:[b[k] for b in batch] for k in keys}

    # list들 LongTensor로 변환
    new_batch['decoder_inputs'] = [torch.LongTensor([start_idx] + label[:-1]) for label in new_batch['labels']]
    # print(f"==>> new_batch['decoder_inputs']: {new_batch['decoder_inputs']}")
    new_batch['input_ids'] = [torch.LongTensor(inp) for inp in new_batch['input_ids']]
    new_batch['labels'] = [torch.LongTensor(label) for label in new_batch['labels']]
    new_batch['attention_mask'] = [torch.LongTensor(mask) for mask in new_batch['attention_mask']]

    new_batch['ntokens'] = sum([l.numel() for l in new_batch['labels']])

    # decoder input의 attention mask 생성
    new_batch['decoder_mask'] = [torch.ones_like(d_inp, dtype=torch.long) for d_inp in new_batch['decoder_inputs']]


    # 각 input과 target 텐서를 패딩
    padded_inputs = pad_sequence(new_batch['input_ids'], batch_first=True, padding_value=padding_idx)
    new_batch['input_ids'] = padded_inputs
    padded_decoder_inputs = pad_sequence(new_batch['decoder_inputs'], batch_first=True, padding_value=padding_idx)
    new_batch['decoder_inputs'] = padded_decoder_inputs
    padded_targets = pad_sequence(new_batch['labels'], batch_first=True, padding_value=padding_idx)
    new_batch['labels'] = padded_targets

    # attention 마스크는 패딩(padding_idx) 대신 False(0)을 입력
    padded_masks = pad_sequence(new_batch['attention_mask'], batch_first=True, padding_value=0)
    new_batch['attention_mask'] = padded_masks

    padded_d_masks = pad_sequence(new_batch['decoder_mask'], batch_first=True, padding_value=0)
    new_batch['decoder_mask'] = padded_d_masks
    
    return new_batch

In [ ]:
loaders = LoadersLGEXAENKO(
    data_path=data_path,
    max_token_length=max_token_length,
    batch_size_train=batch_size_train,
    num_workers=num_workers,
    batch_size_val=batch_size_val,
    batch_size_test=batch_size_test,
    val_num_workers=val_num_workers,
    start_idx=start_idx,
    end_idx=end_idx,
    padding_idx=padding_idx,
    unk_idx=unk_idx,
    seed=seed,
)

In [ ]:
print(f"==>> unk_idx: {unk_idx}")

input_total = Counter([])
target_total = Counter([])
# total

num_batches_train = len(loaders.loader_train)

for step, batch in tqdm(
    enumerate(loaders.loader_train),
    total=num_batches_train,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total += input_count
    target_total += target_count

    # if step == 10:
    #     break

print(f"==>> input_total: {input_total}")
print(f"==>> target_total: {target_total}")
print(f"==>> input_total[unk_idx]: {input_total[unk_idx]}")
print(f"==>> target_total[unk_idx]: {target_total[unk_idx]}")

input_total_val = Counter([])
target_total_val = Counter([])
# total

num_batches_val = len(loaders.loader_val)

for step, batch in tqdm(
    enumerate(loaders.loader_val),
    total=num_batches_val,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_val += input_count
    target_total_val += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_val: {input_total_val}")
print(f"==>> target_total_val: {target_total_val}")
print(f"==>> input_total_val[unk_idx]: {input_total_val[unk_idx]}")
print(f"==>> target_total_val[unk_idx]: {target_total_val[unk_idx]}")


input_total_test = Counter([])
target_total_test = Counter([])
# total

num_batches_test = len(loaders.loader_test)

for step, batch in tqdm(
    enumerate(loaders.loader_test),
    total=num_batches_test,
):  
    input_count = Counter(batch['input_ids'].view(-1).tolist())
    # print(input_count)
    # print(batch['input_ids'].view(-1).tolist())

    target_count = Counter(batch["labels"].view(-1).tolist())

    input_total_test += input_count
    target_total_test += target_count

    # if step == 10:
    #     break

print(f"==>> input_total_test: {input_total_test}")
print(f"==>> target_total_test: {target_total_test}")
print(f"==>> input_total_test[unk_idx]: {input_total_test[unk_idx]}")
print(f"==>> target_total_test[unk_idx]: {target_total_test[unk_idx]}")

In [ ]:
### TODO: 중복데이터 확인하고 지우기, cat 칼럼 지우기

In [ ]:
# from datasets import load_dataset, load_from_disk, ClassLabel, DatasetDict, Dataset, concatenate_datasets
# import pandas as pd

In [ ]:
# dup_check = df.duplicated(subset="target_text")